In [1]:
import pandas as pd

In [2]:
file_path = r'time_dt_extract.csv.txt'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['销售时间']
)

df

                 销售时间 商品名称   销量    销售额  城市
0 2024-05-01 08:30:15   手机   20  59980  北京
1 2024-05-02 14:20:30   耳机   15   5985  上海
2 2024-05-03 09:10:45   卫衣   80  15920  广州
3 2024-05-10 16:40:00   水杯  100   5900  深圳
4 2024-05-15 11:20:10   键盘   30  26970  北京
5 2024-06-01 15:10:20   鼠标   60   5940  上海
6 2024-06-08 08:50:35   平板   25  49975  广州

In [3]:
df['年'] = df['销售时间'].dt.year
df['月'] = df['销售时间'].dt.month
df['日'] = df['销售时间'].dt.day
df

                 销售时间 商品名称   销量    销售额  城市     年  月   日
0 2024-05-01 08:30:15   手机   20  59980  北京  2024  5   1
1 2024-05-02 14:20:30   耳机   15   5985  上海  2024  5   2
2 2024-05-03 09:10:45   卫衣   80  15920  广州  2024  5   3
3 2024-05-10 16:40:00   水杯  100   5900  深圳  2024  5  10
4 2024-05-15 11:20:10   键盘   30  26970  北京  2024  5  15
5 2024-06-01 15:10:20   鼠标   60   5940  上海  2024  6   1
6 2024-06-08 08:50:35   平板   25  49975  广州  2024  6   8

In [4]:
df['小时'] = df['销售时间'].dt.hour
df['分钟'] = df['销售时间'].dt.minute
df['秒'] = df['销售时间'].dt.second

df

                 销售时间 商品名称   销量    销售额  城市     年  月   日  小时  分钟   秒
0 2024-05-01 08:30:15   手机   20  59980  北京  2024  5   1   8  30  15
1 2024-05-02 14:20:30   耳机   15   5985  上海  2024  5   2  14  20  30
2 2024-05-03 09:10:45   卫衣   80  15920  广州  2024  5   3   9  10  45
3 2024-05-10 16:40:00   水杯  100   5900  深圳  2024  5  10  16  40   0
4 2024-05-15 11:20:10   键盘   30  26970  北京  2024  5  15  11  20  10
5 2024-06-01 15:10:20   鼠标   60   5940  上海  2024  6   1  15  10  20
6 2024-06-08 08:50:35   平板   25  49975  广州  2024  6   8   8  50  35

In [5]:
df['星期数'] = df['销售时间'].dt.dayofweek
df['星期名称'] = df['销售时间'].dt.day_name()
df['星期名称_中文'] = df['星期数'].map({0:'周一',1:'周二',2:'周三',3:'周四',4:'周五',5:'周六',6:'周日'})

df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六

In [7]:
df['当月第几天'] = df['销售时间'].dt.day
df['当年第几天'] = df['销售时间'].dt.dayofyear

df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160

In [8]:
df['是否周末'] = df['星期数'] >= 5
df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True

In [9]:
df['仅日期'] = df['销售时间'].dt.date
df['仅时间'] = df['销售时间'].dt.time

df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35

In [10]:
df['月份名称'] = df['销售时间'].dt.month_name()
df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [11]:
df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [12]:
df_time_idx = df.set_index('销售时间')
df_time_idx

,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
销售时间,,,,,,,,,,,,,,,,,,,
2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [13]:
df_time_idx['索引小时'] = df_time_idx.index.hour
df_time_idx['索引星期'] = df_time_idx.index.dayofweek

df_time_idx

,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,...,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称,索引小时,索引星期
销售时间,,,,,,,,,,,,,,,,,,,,,
2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,...,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May,8,2
2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,...,Thursday,周四,2,123,False,2024-05-02,14:20:30,May,14,3
2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,...,Friday,周五,3,124,False,2024-05-03,09:10:45,May,9,4
2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,...,Friday,周五,10,131,False,2024-05-10,16:40:00,May,16,4
2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,...,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May,11,2
2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,...,Saturday,周六,1,153,True,2024-06-01,15:10:20,June,15,5
2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,...,Saturday,周六,8,160,True,2024-06-08,08:50:35,June,8,5

In [14]:
df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [15]:
df_may_morning = df[(df['月'] == 5) & (df['小时'].between(8, 12))]

df_may_morning

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May

In [16]:
df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [17]:
week_sales = df.groupby('星期名称_中文')['销量'].sum()

week_sales

星期名称_中文
周三     50
周五    180
周六     85
周四     15
Name: 销量, dtype: int64

In [18]:
df_weekend = df[df['是否周末']]
df_weekend

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [19]:
df

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [20]:
df_null = df.copy()
df_null

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2,2024-05-03 09:10:45,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [21]:
df_null.loc[2, '销售时间'] = None
df_null

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,秒,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,15,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,30,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May
2,NaT,卫衣,80,15920,广州,2024,5,3,9,10,45,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,0,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,10,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,20,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,35,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June

In [22]:
df_null['月_safe'] = df_null['销售时间'].dt.month.fillna('未知')

df_null

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,...,星期数,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称,月_safe
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,...,2,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May,5.0
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,...,3,Thursday,周四,2,123,False,2024-05-02,14:20:30,May,5.0
2,NaT,卫衣,80,15920,广州,2024,5,3,9,10,...,4,Friday,周五,3,124,False,2024-05-03,09:10:45,May,未知
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,...,4,Friday,周五,10,131,False,2024-05-10,16:40:00,May,5.0
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,...,2,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May,5.0
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,...,5,Saturday,周六,1,153,True,2024-06-01,15:10:20,June,6.0
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,...,5,Saturday,周六,8,160,True,2024-06-08,08:50:35,June,6.0

In [23]:
df_null['月_unsafe'] = df_null['销售时间'].dt.month

df_null

,销售时间,商品名称,销量,销售额,城市,年,月,日,小时,分钟,...,星期名称,星期名称_中文,当月第几天,当年第几天,是否周末,仅日期,仅时间,月份名称,月_safe,月_unsafe
0,2024-05-01 08:30:15,手机,20,59980,北京,2024,5,1,8,30,...,Wednesday,周三,1,122,False,2024-05-01,08:30:15,May,5.0,5.0
1,2024-05-02 14:20:30,耳机,15,5985,上海,2024,5,2,14,20,...,Thursday,周四,2,123,False,2024-05-02,14:20:30,May,5.0,5.0
2,NaT,卫衣,80,15920,广州,2024,5,3,9,10,...,Friday,周五,3,124,False,2024-05-03,09:10:45,May,未知,NaN
3,2024-05-10 16:40:00,水杯,100,5900,深圳,2024,5,10,16,40,...,Friday,周五,10,131,False,2024-05-10,16:40:00,May,5.0,5.0
4,2024-05-15 11:20:10,键盘,30,26970,北京,2024,5,15,11,20,...,Wednesday,周三,15,136,False,2024-05-15,11:20:10,May,5.0,5.0
5,2024-06-01 15:10:20,鼠标,60,5940,上海,2024,6,1,15,10,...,Saturday,周六,1,153,True,2024-06-01,15:10:20,June,6.0,6.0
6,2024-06-08 08:50:35,平板,25,49975,广州,2024,6,8,8,50,...,Saturday,周六,8,160,True,2024-06-08,08:50:35,June,6.0,6.0

In [24]:
month_sales = df.groupby('月')['销量'].sum()

month_sales

月
5    245
6     85
Name: 销量, dtype: int64