In [12]:
import pandas as pd
import numpy as np

In [13]:
file_path = r'transform_scene.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类
0  华北  北京   手机  2999   2  5998   数码
1  华北  北京   键盘   899   3  2697   数码
2  华东  上海   耳机   399   5  1995   数码
3  华南  广州   卫衣   199  10  1990   服饰
4  华南  深圳   水杯    59  20  1180  日用品
5  华东  上海   鼠标    99   8   792   数码
6  华南  广州   裤子   299   6  1794   服饰
7  华南  深圳   毛巾    19  15   285  日用品
8  华北  北京   平板  1999   4  7996   数码
9  华东  上海   音箱   299   7  2093   数码

In [14]:
print(len(df))

10

In [15]:
df['品类总价合计'] = df.groupby('品类')['总价'].transform('sum')
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计
0  华北  北京   手机  2999   2  5998   数码   21571
1  华北  北京   键盘   899   3  2697   数码   21571
2  华东  上海   耳机   399   5  1995   数码   21571
3  华南  广州   卫衣   199  10  1990   服饰    3784
4  华南  深圳   水杯    59  20  1180  日用品    1465
5  华东  上海   鼠标    99   8   792   数码   21571
6  华南  广州   裤子   299   6  1794   服饰    3784
7  华南  深圳   毛巾    19  15   285  日用品    1465
8  华北  北京   平板  1999   4  7996   数码   21571
9  华东  上海   音箱   299   7  2093   数码   21571

In [16]:
df['城市数量均值'] = df.groupby('城市')['数量'].transform('mean').round(2)
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计  城市数量均值
0  华北  北京   手机  2999   2  5998   数码   21571    3.00
1  华北  北京   键盘   899   3  2697   数码   21571    3.00
2  华东  上海   耳机   399   5  1995   数码   21571    6.67
3  华南  广州   卫衣   199  10  1990   服饰    3784    8.00
4  华南  深圳   水杯    59  20  1180  日用品    1465   17.50
5  华东  上海   鼠标    99   8   792   数码   21571    6.67
6  华南  广州   裤子   299   6  1794   服饰    3784    8.00
7  华南  深圳   毛巾    19  15   285  日用品    1465   17.50
8  华北  北京   平板  1999   4  7996   数码   21571    3.00
9  华东  上海   音箱   299   7  2093   数码   21571    6.67

In [17]:
def z_score(x):
    return (x - x.mean()) / x.std()

df['单价标准化'] = df.groupby('品类')['单价'].transform(z_score).round(2)
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计  城市数量均值  单价标准化
0  华北  北京   手机  2999   2  5998   数码   21571    3.00   1.64
1  华北  北京   键盘   899   3  2697   数码   21571    3.00  -0.19
2  华东  上海   耳机   399   5  1995   数码   21571    6.67  -0.62
3  华南  广州   卫衣   199  10  1990   服饰    3784    8.00  -0.71
4  华南  深圳   水杯    59  20  1180  日用品    1465   17.50   0.71
5  华东  上海   鼠标    99   8   792   数码   21571    6.67  -0.89
6  华南  广州   裤子   299   6  1794   服饰    3784    8.00   0.71
7  华南  深圳   毛巾    19  15   285  日用品    1465   17.50  -0.71
8  华北  北京   平板  1999   4  7996   数码   21571    3.00   0.77
9  华东  上海   音箱   299   7  2093   数码   21571    6.67  -0.71

In [18]:
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计  城市数量均值  单价标准化
0  华北  北京   手机  2999   2  5998   数码   21571    3.00   1.64
1  华北  北京   键盘   899   3  2697   数码   21571    3.00  -0.19
2  华东  上海   耳机   399   5  1995   数码   21571    6.67  -0.62
3  华南  广州   卫衣   199  10  1990   服饰    3784    8.00  -0.71
4  华南  深圳   水杯    59  20  1180  日用品    1465   17.50   0.71
5  华东  上海   鼠标    99   8   792   数码   21571    6.67  -0.89
6  华南  广州   裤子   299   6  1794   服饰    3784    8.00   0.71
7  华南  深圳   毛巾    19  15   285  日用品    1465   17.50  -0.71
8  华北  北京   平板  1999   4  7996   数码   21571    3.00   0.77
9  华东  上海   音箱   299   7  2093   数码   21571    6.67  -0.71

In [19]:
df.loc[df['商品名称'].isin(['毛巾']), '单价'] = np.nan
df

   大区  城市 商品名称      单价  数量    总价   品类  品类总价合计  城市数量均值  单价标准化
0  华北  北京   手机  2999.0   2  5998   数码   21571    3.00   1.64
1  华北  北京   键盘   899.0   3  2697   数码   21571    3.00  -0.19
2  华东  上海   耳机   399.0   5  1995   数码   21571    6.67  -0.62
3  华南  广州   卫衣   199.0  10  1990   服饰    3784    8.00  -0.71
4  华南  深圳   水杯    59.0  20  1180  日用品    1465   17.50   0.71
5  华东  上海   鼠标    99.0   8   792   数码   21571    6.67  -0.89
6  华南  广州   裤子   299.0   6  1794   服饰    3784    8.00   0.71
7  华南  深圳   毛巾     NaN  15   285  日用品    1465   17.50  -0.71
8  华北  北京   平板  1999.0   4  7996   数码   21571    3.00   0.77
9  华东  上海   音箱   299.0   7  2093   数码   21571    6.67  -0.71

In [20]:
df['单价填充'] = df.groupby('品类')['单价'].transform(lambda x: x.fillna(x.mean()))
df

   大区  城市 商品名称      单价  数量    总价   品类  品类总价合计  城市数量均值  单价标准化    单价填充
0  华北  北京   手机  2999.0   2  5998   数码   21571    3.00   1.64  2999.0
1  华北  北京   键盘   899.0   3  2697   数码   21571    3.00  -0.19   899.0
2  华东  上海   耳机   399.0   5  1995   数码   21571    6.67  -0.62   399.0
3  华南  广州   卫衣   199.0  10  1990   服饰    3784    8.00  -0.71   199.0
4  华南  深圳   水杯    59.0  20  1180  日用品    1465   17.50   0.71    59.0
5  华东  上海   鼠标    99.0   8   792   数码   21571    6.67  -0.89    99.0
6  华南  广州   裤子   299.0   6  1794   服饰    3784    8.00   0.71   299.0
7  华南  深圳   毛巾     NaN  15   285  日用品    1465   17.50  -0.71    59.0
8  华北  北京   平板  1999.0   4  7996   数码   21571    3.00   0.77  1999.0
9  华东  上海   音箱   299.0   7  2093   数码   21571    6.67  -0.71   299.0

In [21]:
df

   大区  城市 商品名称      单价  数量    总价   品类  品类总价合计  城市数量均值  单价标准化    单价填充
0  华北  北京   手机  2999.0   2  5998   数码   21571    3.00   1.64  2999.0
1  华北  北京   键盘   899.0   3  2697   数码   21571    3.00  -0.19   899.0
2  华东  上海   耳机   399.0   5  1995   数码   21571    6.67  -0.62   399.0
3  华南  广州   卫衣   199.0  10  1990   服饰    3784    8.00  -0.71   199.0
4  华南  深圳   水杯    59.0  20  1180  日用品    1465   17.50   0.71    59.0
5  华东  上海   鼠标    99.0   8   792   数码   21571    6.67  -0.89    99.0
6  华南  广州   裤子   299.0   6  1794   服饰    3784    8.00   0.71   299.0
7  华南  深圳   毛巾     NaN  15   285  日用品    1465   17.50  -0.71    59.0
8  华北  北京   平板  1999.0   4  7996   数码   21571    3.00   0.77  1999.0
9  华东  上海   音箱   299.0   7  2093   数码   21571    6.67  -0.71   299.0

In [22]:
df['城市总价排名'] = df.groupby('城市')['总价'].transform(lambda x: x.rank(ascending=False, method='min')).astype(int)
df

   大区  城市 商品名称      单价  数量    总价   品类  品类总价合计  城市数量均值  单价标准化    单价填充  城市总价排名
0  华北  北京   手机  2999.0   2  5998   数码   21571    3.00   1.64  2999.0       2
1  华北  北京   键盘   899.0   3  2697   数码   21571    3.00  -0.19   899.0       3
2  华东  上海   耳机   399.0   5  1995   数码   21571    6.67  -0.62   399.0       2
3  华南  广州   卫衣   199.0  10  1990   服饰    3784    8.00  -0.71   199.0       1
4  华南  深圳   水杯    59.0  20  1180  日用品    1465   17.50   0.71    59.0       1
5  华东  上海   鼠标    99.0   8   792   数码   21571    6.67  -0.89    99.0       3
6  华南  广州   裤子   299.0   6  1794   服饰    3784    8.00   0.71   299.0       2
7  华南  深圳   毛巾     NaN  15   285  日用品    1465   17.50  -0.71    59.0       2
8  华北  北京   平板  1999.0   4  7996   数码   21571    3.00   0.77  1999.0       1
9  华东  上海   音箱   299.0   7  2093   数码   21571    6.67  -0.71   299.0       1

In [23]:
df

   大区  城市 商品名称      单价  数量    总价   品类  品类总价合计  城市数量均值  单价标准化    单价填充  城市总价排名
0  华北  北京   手机  2999.0   2  5998   数码   21571    3.00   1.64  2999.0       2
1  华北  北京   键盘   899.0   3  2697   数码   21571    3.00  -0.19   899.0       3
2  华东  上海   耳机   399.0   5  1995   数码   21571    6.67  -0.62   399.0       2
3  华南  广州   卫衣   199.0  10  1990   服饰    3784    8.00  -0.71   199.0       1
4  华南  深圳   水杯    59.0  20  1180  日用品    1465   17.50   0.71    59.0       1
5  华东  上海   鼠标    99.0   8   792   数码   21571    6.67  -0.89    99.0       3
6  华南  广州   裤子   299.0   6  1794   服饰    3784    8.00   0.71   299.0       2
7  华南  深圳   毛巾     NaN  15   285  日用品    1465   17.50  -0.71    59.0       2
8  华北  北京   平板  1999.0   4  7996   数码   21571    3.00   0.77  1999.0       1
9  华东  上海   音箱   299.0   7  2093   数码   21571    6.67  -0.71   299.0       1

In [24]:
df['组数量合计'] = df.groupby(['大区', '品类'])['数量'].transform('sum')
df

,大区,城市,商品名称,单价,数量,总价,品类,品类总价合计,城市数量均值,单价标准化,单价填充,城市总价排名,组数量合计
0,华北,北京,手机,2999.0,2,5998,数码,21571,3.00,1.64,2999.0,2,9
1,华北,北京,键盘,899.0,3,2697,数码,21571,3.00,-0.19,899.0,3,9
2,华东,上海,耳机,399.0,5,1995,数码,21571,6.67,-0.62,399.0,2,20
3,华南,广州,卫衣,199.0,10,1990,服饰,3784,8.00,-0.71,199.0,1,16
4,华南,深圳,水杯,59.0,20,1180,日用品,1465,17.50,0.71,59.0,1,35
5,华东,上海,鼠标,99.0,8,792,数码,21571,6.67,-0.89,99.0,3,20
6,华南,广州,裤子,299.0,6,1794,服饰,3784,8.00,0.71,299.0,2,16
7,华南,深圳,毛巾,NaN,15,285,日用品,1465,17.50,-0.71,59.0,2,35
8,华北,北京,平板,1999.0,4,7996,数码,21571,3.00,0.77,1999.0,1,9
9,华东,上海,音箱,299.0,7,2093,数码,21571,6.67,-0.71,299.0,1,20

In [25]:
df['数量占比'] = (df['数量'] / df['组数量合计']).round(2)
df

,大区,城市,商品名称,单价,数量,总价,品类,品类总价合计,城市数量均值,单价标准化,单价填充,城市总价排名,组数量合计,数量占比
0,华北,北京,手机,2999.0,2,5998,数码,21571,3.00,1.64,2999.0,2,9,0.22
1,华北,北京,键盘,899.0,3,2697,数码,21571,3.00,-0.19,899.0,3,9,0.33
2,华东,上海,耳机,399.0,5,1995,数码,21571,6.67,-0.62,399.0,2,20,0.25
3,华南,广州,卫衣,199.0,10,1990,服饰,3784,8.00,-0.71,199.0,1,16,0.62
4,华南,深圳,水杯,59.0,20,1180,日用品,1465,17.50,0.71,59.0,1,35,0.57
5,华东,上海,鼠标,99.0,8,792,数码,21571,6.67,-0.89,99.0,3,20,0.40
6,华南,广州,裤子,299.0,6,1794,服饰,3784,8.00,0.71,299.0,2,16,0.38
7,华南,深圳,毛巾,NaN,15,285,日用品,1465,17.50,-0.71,59.0,2,35,0.43
8,华北,北京,平板,1999.0,4,7996,数码,21571,3.00,0.77,1999.0,1,9,0.44
9,华东,上海,音箱,299.0,7,2093,数码,21571,6.67,-0.71,299.0,1,20,0.35

In [26]:
agg_result = df.groupby('品类')['总价'].sum()
agg_result

品类
数码     21571
日用品     1465
服饰      3784
Name: 总价, dtype: int64

In [27]:
trans_result = df.groupby('品类')['总价'].transform('sum')
trans_result

0    21571
1    21571
2    21571
3     3784
4     1465
5    21571
6     3784
7     1465
8    21571
9    21571
Name: 总价, dtype: int64