In [1]:
import pandas as pd

In [2]:
file_path = r'transform_vs_agg.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类
0  华北  北京   手机  2999   2  5998   数码
1  华北  北京   键盘   899   3  2697   数码
2  华东  上海   耳机   399   5  1995   数码
3  华南  广州   卫衣   199  10  1990   服饰
4  华南  深圳   水杯    59  20  1180  日用品
5  华东  上海   鼠标    99   8   792   数码
6  华南  广州   裤子   299   6  1794   服饰
7  华南  深圳   毛巾    19  15   285  日用品
8  华北  北京   平板  1999   4  7996   数码
9  华东  上海   音箱   299   7  2093   数码

In [3]:
print(len(df))

10

In [4]:
group_cat = df.groupby('品类')
group_cat

In [5]:
agg_sum = group_cat['总价'].agg('sum')
agg_sum

品类
数码     21571
日用品     1465
服饰      3784
Name: 总价, dtype: int64

In [6]:
print(len(agg_sum))

3

In [9]:
df

   大区  城市 商品名称    单价  数量    总价   品类
0  华北  北京   手机  2999   2  5998   数码
1  华北  北京   键盘   899   3  2697   数码
2  华东  上海   耳机   399   5  1995   数码
3  华南  广州   卫衣   199  10  1990   服饰
4  华南  深圳   水杯    59  20  1180  日用品
5  华东  上海   鼠标    99   8   792   数码
6  华南  广州   裤子   299   6  1794   服饰
7  华南  深圳   毛巾    19  15   285  日用品
8  华北  北京   平板  1999   4  7996   数码
9  华东  上海   音箱   299   7  2093   数码

In [7]:
trans_sum = group_cat['总价'].transform('sum')
trans_sum

0    21571
1    21571
2    21571
3     3784
4     1465
5    21571
6     3784
7     1465
8    21571
9    21571
Name: 总价, dtype: int64

In [8]:
print(len(trans_sum))

10

In [10]:
df['品类总价合计（变换）'] = trans_sum
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计（变换）
0  华北  北京   手机  2999   2  5998   数码       21571
1  华北  北京   键盘   899   3  2697   数码       21571
2  华东  上海   耳机   399   5  1995   数码       21571
3  华南  广州   卫衣   199  10  1990   服饰        3784
4  华南  深圳   水杯    59  20  1180  日用品        1465
5  华东  上海   鼠标    99   8   792   数码       21571
6  华南  广州   裤子   299   6  1794   服饰        3784
7  华南  深圳   毛巾    19  15   285  日用品        1465
8  华北  北京   平板  1999   4  7996   数码       21571
9  华东  上海   音箱   299   7  2093   数码       21571

In [11]:
agg_mean = group_cat['单价'].agg('mean').round(2)
agg_mean

品类
数码     1115.67
日用品      39.00
服饰      249.00
Name: 单价, dtype: float64

In [12]:
trans_mean = group_cat['单价'].transform('mean').round(2)
trans_mean

0    1115.67
1    1115.67
2    1115.67
3     249.00
4      39.00
5    1115.67
6     249.00
7      39.00
8    1115.67
9    1115.67
Name: 单价, dtype: float64

In [13]:
df['品类单价均值（变换）'] = trans_mean
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计（变换）  品类单价均值（变换）
0  华北  北京   手机  2999   2  5998   数码       21571     1115.67
1  华北  北京   键盘   899   3  2697   数码       21571     1115.67
2  华东  上海   耳机   399   5  1995   数码       21571     1115.67
3  华南  广州   卫衣   199  10  1990   服饰        3784      249.00
4  华南  深圳   水杯    59  20  1180  日用品        1465       39.00
5  华东  上海   鼠标    99   8   792   数码       21571     1115.67
6  华南  广州   裤子   299   6  1794   服饰        3784      249.00
7  华南  深圳   毛巾    19  15   285  日用品        1465       39.00
8  华北  北京   平板  1999   4  7996   数码       21571     1115.67
9  华东  上海   音箱   299   7  2093   数码       21571     1115.67

In [14]:
df['品类内总价占比'] = (df['总价'] / df['品类总价合计（变换）']).round(4)
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计（变换）  品类单价均值（变换）  品类内总价占比
0  华北  北京   手机  2999   2  5998   数码       21571     1115.67   0.2781
1  华北  北京   键盘   899   3  2697   数码       21571     1115.67   0.1250
2  华东  上海   耳机   399   5  1995   数码       21571     1115.67   0.0925
3  华南  广州   卫衣   199  10  1990   服饰        3784      249.00   0.5259
4  华南  深圳   水杯    59  20  1180  日用品        1465       39.00   0.8055
5  华东  上海   鼠标    99   8   792   数码       21571     1115.67   0.0367
6  华南  广州   裤子   299   6  1794   服饰        3784      249.00   0.4741
7  华南  深圳   毛巾    19  15   285  日用品        1465       39.00   0.1945
8  华北  北京   平板  1999   4  7996   数码       21571     1115.67   0.3707
9  华东  上海   音箱   299   7  2093   数码       21571     1115.67   0.0970

In [15]:
df['单价标准化'] = group_cat['单价'].transform(lambda x: (x - x.mean()) / x.std()).round(4)
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计（变换）  品类单价均值（变换）  品类内总价占比   单价标准化
0  华北  北京   手机  2999   2  5998   数码       21571     1115.67   0.2781  1.6407
1  华北  北京   键盘   899   3  2697   数码       21571     1115.67   0.1250 -0.1888
2  华东  上海   耳机   399   5  1995   数码       21571     1115.67   0.0925 -0.6243
3  华南  广州   卫衣   199  10  1990   服饰        3784      249.00   0.5259 -0.7071
4  华南  深圳   水杯    59  20  1180  日用品        1465       39.00   0.8055  0.7071
5  华东  上海   鼠标    99   8   792   数码       21571     1115.67   0.0367 -0.8857
6  华南  广州   裤子   299   6  1794   服饰        3784      249.00   0.4741  0.7071
7  华南  深圳   毛巾    19  15   285  日用品        1465       39.00   0.1945 -0.7071
8  华北  北京   平板  1999   4  7996   数码       21571     1115.67   0.3707  0.7695
9  华东  上海   音箱   299   7  2093   数码       21571     1115.67   0.0970 -0.7114

In [16]:
df

   大区  城市 商品名称    单价  数量    总价   品类  品类总价合计（变换）  品类单价均值（变换）  品类内总价占比   单价标准化
0  华北  北京   手机  2999   2  5998   数码       21571     1115.67   0.2781  1.6407
1  华北  北京   键盘   899   3  2697   数码       21571     1115.67   0.1250 -0.1888
2  华东  上海   耳机   399   5  1995   数码       21571     1115.67   0.0925 -0.6243
3  华南  广州   卫衣   199  10  1990   服饰        3784      249.00   0.5259 -0.7071
4  华南  深圳   水杯    59  20  1180  日用品        1465       39.00   0.8055  0.7071
5  华东  上海   鼠标    99   8   792   数码       21571     1115.67   0.0367 -0.8857
6  华南  广州   裤子   299   6  1794   服饰        3784      249.00   0.4741  0.7071
7  华南  深圳   毛巾    19  15   285  日用品        1465       39.00   0.1945 -0.7071
8  华北  北京   平板  1999   4  7996   数码       21571     1115.67   0.3707  0.7695
9  华东  上海   音箱   299   7  2093   数码       21571     1115.67   0.0970 -0.7114

In [17]:
df[['品类单价最大值', '品类数量最大值']] = group_cat[['单价', '数量']].transform('max')
df

,大区,城市,商品名称,单价,数量,总价,品类,品类总价合计（变换）,品类单价均值（变换）,品类内总价占比,单价标准化,品类单价最大值,品类数量最大值
0,华北,北京,手机,2999,2,5998,数码,21571,1115.67,0.2781,1.6407,2999,8
1,华北,北京,键盘,899,3,2697,数码,21571,1115.67,0.1250,-0.1888,2999,8
2,华东,上海,耳机,399,5,1995,数码,21571,1115.67,0.0925,-0.6243,2999,8
3,华南,广州,卫衣,199,10,1990,服饰,3784,249.00,0.5259,-0.7071,299,10
4,华南,深圳,水杯,59,20,1180,日用品,1465,39.00,0.8055,0.7071,59,20
5,华东,上海,鼠标,99,8,792,数码,21571,1115.67,0.0367,-0.8857,2999,8
6,华南,广州,裤子,299,6,1794,服饰,3784,249.00,0.4741,0.7071,299,10
7,华南,深圳,毛巾,19,15,285,日用品,1465,39.00,0.1945,-0.7071,59,20
8,华北,北京,平板,1999,4,7996,数码,21571,1115.67,0.3707,0.7695,2999,8
9,华东,上海,音箱,299,7,2093,数码,21571,1115.67,0.0970,-0.7114,2999,8