In [1]:
import pandas as pd

In [2]:
file_path = r'regex_extract.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

,商品名称,订单信息,地址,备注,编码
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234

In [3]:
num_pattern = r'(\d+)'
df['商品数字'] = df['商品名称'].str.extract(num_pattern)

df

,商品名称,订单信息,地址,备注,编码,商品数字
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN

In [5]:
order_pattern = r'-(\d+)'

df['订单号'] = df['订单信息'].str.extract(order_pattern)
df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005

In [6]:
addr_pattern = r'(\d+号)'

df['门牌号'] = df['地址'].str.extract(addr_pattern)

df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号

In [7]:
date_pattern = r'(\d{4}[-/.]?\d{2}[-/.]?\d{2})'

df['备注日期'] = df['备注'].str.extract(date_pattern)

df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05

In [8]:
df['日期_规范'] = df['备注日期'].str.replace(r'[/.]', '-', regex=True)

df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05

In [9]:
code_pattern = r'SP-(\d{4})-(\d+)'

df[['编码年份', '编号序号']] = df['编码'].str.extract(code_pattern)

df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范,编码年份,编号序号
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01,2024,00123
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02,2024,00456
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03,2024,00789
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504,2024,01011
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05,2024,01234

In [10]:
df['备注所有数字'] = df['备注'].str.findall(r'\d+')

df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范,编码年份,编号序号,备注所有数字
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01,2024,00123,"[2024, 05, 01]"
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02,2024,00456,"[2024, 05, 02]"
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03,2024,00789,"[2024, 05, 03]"
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504,2024,01011,[20240504]
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05,2024,01234,"[2024, 05, 05]"

In [11]:
df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范,编码年份,编号序号,备注所有数字
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01,2024,00123,"[2024, 05, 01]"
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02,2024,00456,"[2024, 05, 02]"
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03,2024,00789,"[2024, 05, 03]"
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504,2024,01011,[20240504]
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05,2024,01234,"[2024, 05, 05]"

In [16]:
import re

df['北京门牌号'] = df['地址'].apply(
    lambda x: re.search(r'(\d+号)', x).group(1) if '北京' in x else None
)
df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范,编码年份,编号序号,备注所有数字,北京门牌号
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01,2024,00123,"[2024, 05, 01]",88号
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02,2024,00456,"[2024, 05, 02]",NaN
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03,2024,00789,"[2024, 05, 03]",NaN
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504,2024,01011,[20240504],NaN
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05,2024,01234,"[2024, 05, 05]",10号

In [17]:
df

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范,编码年份,编号序号,备注所有数字,北京门牌号
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01,2024,00123,"[2024, 05, 01]",88号
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02,2024,00456,"[2024, 05, 02]",NaN
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03,2024,00789,"[2024, 05, 03]",NaN
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504,2024,01011,[20240504],NaN
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05,2024,01234,"[2024, 05, 05]",10号

In [19]:
df_null = df.copy()
df_null

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范,编码年份,编号序号,备注所有数字,北京门牌号
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01,2024,00123,"[2024, 05, 01]",88号
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02,2024,00456,"[2024, 05, 02]",NaN
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03,2024,00789,"[2024, 05, 03]",NaN
3,膳魔师水杯500ml,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504,2024,01011,[20240504],NaN
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05,2024,01234,"[2024, 05, 05]",10号

In [20]:
df_null.loc[3, '商品名称'] = '膳魔师水杯'

df_null['商品数字_safe'] = df_null['商品名称'].str.extract(r'(\d+)').fillna('无')

In [22]:
df_null

,商品名称,订单信息,地址,备注,编码,商品数字,订单号,门牌号,备注日期,日期_规范,编码年份,编号序号,备注所有数字,北京门牌号,商品数字_safe
0,苹果手机128G,ORD20240501-1001,北京市朝阳区建国路88号,热销2024-05-01发货,SP-2024-00123,128,1001,88号,2024-05-01,2024-05-01,2024,00123,"[2024, 05, 01]",88号,128
1,华为耳机Pro,ORD20240502-1002,上海市浦东新区张江路123号,库存充足2024/05/02出库,SP-2024-00456,NaN,1002,123号,2024/05/02,2024-05-02,2024,00456,"[2024, 05, 02]",NaN,无
2,优衣库卫衣XL,ORD20240503-1003,广州市天河区天河路77号,断码2024.05.03退货,SP-2024-00789,NaN,1003,77号,2024.05.03,2024-05-03,2024,00789,"[2024, 05, 03]",NaN,无
3,膳魔师水杯,ORD20240504-1004,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,500,1004,99号,20240504,20240504,2024,01011,[20240504],NaN,无
4,雷柏键盘青轴,ORD20240505-1005,北京市海淀区中关村大街10号,促销2024-05-05活动,SP-2024-01234,NaN,1005,10号,2024-05-05,2024-05-05,2024,01234,"[2024, 05, 05]",10号,无