In [1]:
import pandas as pd

In [2]:
file_path = r'regex_replace.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

,商品名称,订单号,手机号,地址,备注,编码
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234

In [3]:
phone_pattern = r'(\d{3})\d{4}(\d{4})'
df['手机号_脱敏'] = df['手机号'].astype(str).str.replace(phone_pattern, r'\1****\2', regex=True)

df

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000

In [4]:
addr_pattern = r'(\d+号).*'
df['地址_简化'] = df['地址'].str.replace(addr_pattern, r'\1', regex=True)

df

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号

In [7]:
date_pattern = r'(\d{4})[./](\d{2})[./](\d{2})'

df['备注_日期规范'] = df['备注'].str.replace(date_pattern, r'\1-\2-\3', regex=True)

df

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价

In [8]:
code_pattern = r'_'

df['编码_规范'] = df['编码'].str.replace(code_pattern, '-', regex=True)

df

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234

In [9]:
df['备注_清洗'] = df['备注_日期规范'].str.replace(r'&', '、', regex=True)

df

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范,备注_清洗
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123,热销2024-05-01发货、新品
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456,库存充足2024-05-02出库
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789,断码2024-05-03退货、清仓
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,新品20240504上架
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234,促销2024-05-05活动、特价

In [10]:
status_pattern = r'(热销|库存充足|断码|新品|促销)'

df['备注_状态标注'] = df['备注_清洗'].str.replace(status_pattern, r'【状态: \1】', regex=True)

df

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范,备注_清洗,备注_状态标注
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123,热销2024-05-01发货、新品,【状态: 热销】2024-05-01发货、【状态: 新品】
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456,库存充足2024-05-02出库,【状态: 库存充足】2024-05-02出库
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789,断码2024-05-03退货、清仓,【状态: 断码】2024-05-03退货、清仓
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,新品20240504上架,【状态: 新品】20240504上架
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234,促销2024-05-05活动、特价,【状态: 促销】2024-05-05活动、特价

In [11]:
order_pattern = r'^ORD-\d{8}-'

df['订单号_简化'] = df['订单号'].str.replace(order_pattern, '', regex=True)

df

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范,备注_清洗,备注_状态标注,订单号_简化
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123,热销2024-05-01发货、新品,【状态: 热销】2024-05-01发货、【状态: 新品】,1001
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456,库存充足2024-05-02出库,【状态: 库存充足】2024-05-02出库,1002
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789,断码2024-05-03退货、清仓,【状态: 断码】2024-05-03退货、清仓,1003
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,新品20240504上架,【状态: 新品】20240504上架,1004
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234,促销2024-05-05活动、特价,【状态: 促销】2024-05-05活动、特价,1005

In [13]:
df_null = df.copy()

df_null

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范,备注_清洗,备注_状态标注,订单号_简化
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123,热销2024-05-01发货、新品,【状态: 热销】2024-05-01发货、【状态: 新品】,1001
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456,库存充足2024-05-02出库,【状态: 库存充足】2024-05-02出库,1002
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789,断码2024-05-03退货、清仓,【状态: 断码】2024-05-03退货、清仓,1003
3,膳魔师水杯500ml,ORD-20240504-1004,13600136000,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,新品20240504上架,【状态: 新品】20240504上架,1004
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234,促销2024-05-05活动、特价,【状态: 促销】2024-05-05活动、特价,1005

In [15]:
df_null.loc[3, '手机号'] = 123456

df_null

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范,备注_清洗,备注_状态标注,订单号_简化
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123,热销2024-05-01发货、新品,【状态: 热销】2024-05-01发货、【状态: 新品】,1001
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456,库存充足2024-05-02出库,【状态: 库存充足】2024-05-02出库,1002
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789,断码2024-05-03退货、清仓,【状态: 断码】2024-05-03退货、清仓,1003
3,膳魔师水杯500ml,ORD-20240504-1004,123456,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,新品20240504上架,【状态: 新品】20240504上架,1004
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234,促销2024-05-05活动、特价,【状态: 促销】2024-05-05活动、特价,1005

In [18]:
df_null['手机号_脱敏_safe'] = df_null['手机号'].astype(str).str.replace(r'(\d{3})\d{4}(\d{4})', r'\1****\2',
                                                                        regex=True,
                                                                        n=1  # 仅替换1次
                                                                        ).fillna('格式错误')

df_null

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范,备注_清洗,备注_状态标注,订单号_简化,手机号_脱敏_safe
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123,热销2024-05-01发货、新品,【状态: 热销】2024-05-01发货、【状态: 新品】,1001,138****8000
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456,库存充足2024-05-02出库,【状态: 库存充足】2024-05-02出库,1002,139****9000
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789,断码2024-05-03退货、清仓,【状态: 断码】2024-05-03退货、清仓,1003,137****7000
3,膳魔师水杯500ml,ORD-20240504-1004,123456,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,新品20240504上架,【状态: 新品】20240504上架,1004,123456
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234,促销2024-05-05活动、特价,【状态: 促销】2024-05-05活动、特价,1005,135****5000

In [19]:
import re


def desensitize_phone(phone):
    phone_str = str(phone).strip()

    # 严格匹配11位手机号
    if re.fullmatch(r'\d{11}', phone_str):
        return re.sub(r'(\d{3})\d{4}(\d{4})', r'\1****\2', phone_str)
    else:
        return '格式错误'


df_null['手机号_脱敏_safe2'] = df_null['手机号'].apply(desensitize_phone)

In [20]:
df_null

,商品名称,订单号,手机号,地址,备注,编码,手机号_脱敏,地址_简化,备注_日期规范,编码_规范,备注_清洗,备注_状态标注,订单号_简化,手机号_脱敏_safe,手机号_脱敏_safe2
0,苹果手机128G,ORD-20240501-1001,13800138000,北京市朝阳区建国路88号-1单元,热销2024.05.01发货&新品,SP_2024_00123,138****8000,北京市朝阳区建国路88号,热销2024-05-01发货&新品,SP-2024-00123,热销2024-05-01发货、新品,【状态: 热销】2024-05-01发货、【状态: 新品】,1001,138****8000,138****8000
1,华为耳机Pro,ORD-20240502-1002,13900139000,上海市浦东新区张江路123号-5层,库存充足2024/05/02出库,SP_2024_00456,139****9000,上海市浦东新区张江路123号,库存充足2024-05-02出库,SP-2024-00456,库存充足2024-05-02出库,【状态: 库存充足】2024-05-02出库,1002,139****9000,139****9000
2,优衣库卫衣XL,ORD-20240503-1003,13700137000,广州市天河区天河路77号-3栋,断码2024-05-03退货&清仓,SP_2024_00789,137****7000,广州市天河区天河路77号,断码2024-05-03退货&清仓,SP-2024-00789,断码2024-05-03退货、清仓,【状态: 断码】2024-05-03退货、清仓,1003,137****7000,137****7000
3,膳魔师水杯500ml,ORD-20240504-1004,123456,深圳市南山区深南大道99号-8室,新品20240504上架,SP_2024_01011,136****6000,深圳市南山区深南大道99号,新品20240504上架,SP-2024-01011,新品20240504上架,【状态: 新品】20240504上架,1004,123456,格式错误
4,雷柏键盘青轴,ORD-20240505-1005,13500135000,北京市海淀区中关村大街10号-2楼,促销2024.05.05活动&特价,SP_2024_01234,135****5000,北京市海淀区中关村大街10号,促销2024-05-05活动&特价,SP-2024-01234,促销2024-05-05活动、特价,【状态: 促销】2024-05-05活动、特价,1005,135****5000,135****5000