In [1]:
import pandas as pd

In [2]:
file_path = r'group_filter.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [3]:
print(len(df))

10

In [5]:
filter1 = df.groupby('品类').filter(lambda x: x['总价'].sum() > 2000)
filter1

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
3  华南  广州   卫衣   199  10  1990  服饰   True
5  华东  上海   鼠标    99   8   792  数码  False
6  华南  广州   裤子   299   6  1794  服饰   True
8  华北  北京   平板  1999   4  7996  数码   True
9  华东  上海   音箱   299   7  2093  数码  False

In [6]:
print(len(filter1))

8

In [7]:
filter2 = df.groupby('城市').filter(lambda x: x['单价'].mean() > 500)
filter2

   大区  城市 商品名称    单价  数量    总价  品类  是否包邮
0  华北  北京   手机  2999   2  5998  数码  True
1  华北  北京   键盘   899   3  2697  数码  True
8  华北  北京   平板  1999   4  7996  数码  True

In [8]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [9]:
filter3 = df.groupby('大区').filter(lambda x: len(x) >= 3 and x['总价'].mean() > 2000)
filter3

   大区  城市 商品名称    单价  数量    总价  品类  是否包邮
0  华北  北京   手机  2999   2  5998  数码  True
1  华北  北京   键盘   899   3  2697  数码  True
8  华北  北京   平板  1999   4  7996  数码  True

In [11]:
filter4 = df.groupby(['大区', '品类']).filter(lambda x: x['数量'].sum() > 10)
filter4

   大区  城市 商品名称   单价  数量    总价   品类   是否包邮
2  华东  上海   耳机  399   5  1995   数码  False
3  华南  广州   卫衣  199  10  1990   服饰   True
4  华南  深圳   水杯   59  20  1180  日用品  False
5  华东  上海   鼠标   99   8   792   数码  False
6  华南  广州   裤子  299   6  1794   服饰   True
7  华南  深圳   毛巾   19  15   285  日用品  False
9  华东  上海   音箱  299   7  2093   数码  False

In [12]:
filter1

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
3  华南  广州   卫衣   199  10  1990  服饰   True
5  华东  上海   鼠标    99   8   792  数码  False
6  华南  广州   裤子   299   6  1794  服饰   True
8  华北  北京   平板  1999   4  7996  数码   True
9  华东  上海   音箱   299   7  2093  数码  False

In [13]:
filter_reset = filter1.reset_index(drop=True)
filter_reset

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
3  华南  广州   卫衣   199  10  1990  服饰   True
4  华东  上海   鼠标    99   8   792  数码  False
5  华南  广州   裤子   299   6  1794  服饰   True
6  华北  北京   平板  1999   4  7996  数码   True
7  华东  上海   音箱   299   7  2093  数码  False

In [14]:
normal_filter = df[df['单价'] > 1000]
normal_filter

   大区  城市 商品名称    单价  数量    总价  品类  是否包邮
0  华北  北京   手机  2999   2  5998  数码  True
8  华北  北京   平板  1999   4  7996  数码  True

In [15]:
print(len(normal_filter))

2

In [16]:
filter1

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
3  华南  广州   卫衣   199  10  1990  服饰   True
5  华东  上海   鼠标    99   8   792  数码  False
6  华南  广州   裤子   299   6  1794  服饰   True
8  华北  北京   平板  1999   4  7996  数码   True
9  华东  上海   音箱   299   7  2093  数码  False

In [17]:
print(len(filter1))

8

In [18]:
cat_sum = df.groupby('品类')['总价'].sum()
cat_sum

品类
数码     21571
日用品     1465
服饰      3784
Name: 总价, dtype: int64

In [19]:
filter1

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
3  华南  广州   卫衣   199  10  1990  服饰   True
5  华东  上海   鼠标    99   8   792  数码  False
6  华南  广州   裤子   299   6  1794  服饰   True
8  华北  北京   平板  1999   4  7996  数码   True
9  华东  上海   音箱   299   7  2093  数码  False