In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = r'filter_empty_group.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华北  天津  NaN     0   0     0   服饰  False
7  华东  南京  NaN     0   0     0  日用品  False

In [3]:
df = df.replace('', np.nan)

In [4]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华北  天津  NaN     0   0     0   服饰  False
7  华东  南京  NaN     0   0     0  日用品  False

In [5]:
print(len(df))

8

In [6]:
print(df.groupby(['大区', '品类']).size())

大区  品类
华东  数码     2
    日用品    1
华北  数码     2
    服饰     1
华南  日用品    1
    服饰     1
dtype: int64

In [7]:
group_multi = df.groupby(['大区', '品类'])
group_multi

In [8]:
filter_min_rows = group_multi.filter(lambda x: len(x) >= 2)
filter_min_rows

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
5  华东  上海   鼠标    99   8   792  数码  False

In [9]:
filter_valid_data = group_multi.filter(lambda x: (x['单价'] > 0).all() and (x['数量'] > 0).all())

filter_valid_data

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False

In [10]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华北  天津  NaN     0   0     0   服饰  False
7  华东  南京  NaN     0   0     0  日用品  False

In [11]:
filter_no_nan = group_multi.filter(lambda x: x['商品名称'].notna().all())

filter_no_nan

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False

In [12]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华北  天津  NaN     0   0     0   服饰  False
7  华东  南京  NaN     0   0     0  日用品  False

In [13]:
agg_group = df.groupby(['大区', '品类'])['总价'].sum().reset_index()
agg_group

   大区   品类    总价
0  华东   数码  2787
1  华东  日用品     0
2  华北   数码  8695
3  华北   服饰     0
4  华南  日用品  1180
5  华南   服饰  1990

In [14]:
filter_agg_empty = agg_group[agg_group['总价'] > 1000]
filter_agg_empty

   大区   品类    总价
0  华东   数码  2787
2  华北   数码  8695
4  华南  日用品  1180
5  华南   服饰  1990

In [15]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华北  天津  NaN     0   0     0   服饰  False
7  华东  南京  NaN     0   0     0  日用品  False

In [16]:
def filter_empty_groups(df, group_cols, min_rows=2, min_total=1000):
    group_obj = df.groupby(group_cols)
    filtered = group_obj.filter(lambda x: len(x) >= min_rows
                                          and x['总价'].sum() >= min_total
                                          and x.notna().all(axis=1).any())
    return filtered

final_filter = filter_empty_groups(df, ['大区', '品类'])
final_filter

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
5  华东  上海   鼠标    99   8   792  数码  False