In [1]:
import pandas as pd

In [2]:
file_path = r'dtype_special.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品
1  1002   耳机   中端  上海   32   普通     数码|便携
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲
3  1004   水杯   低端  深圳   89   普通    日用品|便携
4  1005   键盘  中高端  北京   45  VIP     数码|办公

In [4]:
price_map = {'低端': 0, '中端': 1, '中高端': 2}
df['价格区间编码'] = df['价格区间'].map(price_map)

df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2
1  1002   耳机   中端  上海   32   普通     数码|便携       1
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2

In [5]:
df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2
1  1002   耳机   中端  上海   32   普通     数码|便携       1
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2

In [6]:
df['用户等级编码'] = df['用户等级'].astype('category').cat.codes
df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码  用户等级编码
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2       0
1  1002   耳机   中端  上海   32   普通     数码|便携       1       1
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0       0
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0       1
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2       0

In [7]:
df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码  用户等级编码
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2       0
1  1002   耳机   中端  上海   32   普通     数码|便携       1       1
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0       0
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0       1
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2       0

In [8]:
tag_split = df['标签'].str.split('|', expand=True)

tag_split.columns = [f'标签{i + 1}' for i in range(tag_split.shape[1])]
tag_split

   标签1 标签2  标签3
0   数码  热销   新品
1   数码  便携  NaN
2   服饰  休闲  NaN
3  日用品  便携  NaN
4   数码  办公  NaN

In [9]:
df = pd.concat([df, tag_split], axis=1)
df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码  用户等级编码  标签1 标签2  标签3
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2       0   数码  热销   新品
1  1002   耳机   中端  上海   32   普通     数码|便携       1       1   数码  便携  NaN
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0       0   服饰  休闲  NaN
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0       1  日用品  便携  NaN
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2       0   数码  办公  NaN

In [10]:
df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码  用户等级编码  标签1 标签2  标签3
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2       0   数码  热销   新品
1  1002   耳机   中端  上海   32   普通     数码|便携       1       1   数码  便携  NaN
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0       0   服饰  休闲  NaN
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0       1  日用品  便携  NaN
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2       0   数码  办公  NaN

In [11]:
bins = [0, 50, 100, float('inf')]
labels = ['低销量', '中销量', '高销量']

df['销量等级'] = pd.cut(df['销量'], bins=bins, labels=labels)

df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码  用户等级编码  标签1 标签2  标签3 销量等级
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2       0   数码  热销   新品  中销量
1  1002   耳机   中端  上海   32   普通     数码|便携       1       1   数码  便携  NaN  低销量
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0       0   服饰  休闲  NaN  高销量
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0       1  日用品  便携  NaN  中销量
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2       0   数码  办公  NaN  低销量

In [12]:
df

   订单ID 商品名称 价格区间  城市   销量 用户等级        标签  价格区间编码  用户等级编码  标签1 标签2  标签3 销量等级
0  1001   手机  中高端  北京   58  VIP  数码|热销|新品       2       0   数码  热销   新品  中销量
1  1002   耳机   中端  上海   32   普通     数码|便携       1       1   数码  便携  NaN  低销量
2  1003   卫衣   低端  广州  105  VIP     服饰|休闲       0       0   服饰  休闲  NaN  高销量
3  1004   水杯   低端  深圳   89   普通    日用品|便携       0       1  日用品  便携  NaN  中销量
4  1005   键盘  中高端  北京   45  VIP     数码|办公       2       0   数码  办公  NaN  低销量

In [13]:
df['是否高价值'] = (df['价格区间编码'] >= 1) & (df['销量'] > 50)
df['是否高价值_描述'] = df['是否高价值'].map({True: '是', False: '否'})

df

,订单ID,商品名称,价格区间,城市,销量,用户等级,标签,价格区间编码,用户等级编码,标签1,标签2,标签3,销量等级,是否高价值,是否高价值_描述
0,1001,手机,中高端,北京,58,VIP,数码|热销|新品,2,0,数码,热销,新品,中销量,True,是
1,1002,耳机,中端,上海,32,普通,数码|便携,1,1,数码,便携,NaN,低销量,False,否
2,1003,卫衣,低端,广州,105,VIP,服饰|休闲,0,0,服饰,休闲,NaN,高销量,False,否
3,1004,水杯,低端,深圳,89,普通,日用品|便携,0,1,日用品,便携,NaN,中销量,False,否
4,1005,键盘,中高端,北京,45,VIP,数码|办公,2,0,数码,办公,NaN,低销量,False,否