In [1]:
import pandas as pd

In [2]:
file_path = r'dtype_check.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价        下单时间   是否包邮   折扣率
0  1001   手机  2999   2  北京  5998  2024-01-01   True  0.90
1  1002   耳机   399   5  上海  1995  2024-01-02  False  1.00
2  1003   卫衣   199  10  广州  1990  2024-01-03   True  0.85
3  1004   水杯    59  20  深圳  1180  2024-01-04  False  1.00
4  1005   键盘   899   3  北京  2697  2024-01-05   True  0.95

In [3]:
dtype_overall = df.dtypes

In [4]:
dtype_overall

订单ID      int64
商品名称        str
单价        int64
数量        int64
城市          str
总价        int64
下单时间        str
是否包邮       bool
折扣率     float64
dtype: object

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单ID    5 non-null      int64
 1   商品名称    5 non-null      str
 2   单价      5 non-null      int64
 3   数量      5 non-null      int64
 4   城市      5 non-null      str
 5   总价      5 non-null      int64
 6   下单时间    5 non-null      str
 7   是否包邮    5 non-null      bool
 8   折扣率     5 non-null      float64
dtypes: bool(1), float64(1), int64(4), str(3)
memory usage: 457.0 bytes

In [6]:
df

   订单ID 商品名称    单价  数量  城市    总价        下单时间   是否包邮   折扣率
0  1001   手机  2999   2  北京  5998  2024-01-01   True  0.90
1  1002   耳机   399   5  上海  1995  2024-01-02  False  1.00
2  1003   卫衣   199  10  广州  1990  2024-01-03   True  0.85
3  1004   水杯    59  20  深圳  1180  2024-01-04  False  1.00
4  1005   键盘   899   3  北京  2697  2024-01-05   True  0.95

In [7]:
col_dtype = df['单价'].dtype
col_dtype

dtype('int64')

In [8]:
multi_col_dtype = df[['订单ID', '下单时间', '是否包邮']].dtypes
multi_col_dtype

订单ID    int64
下单时间      str
是否包邮     bool
dtype: object

In [9]:
cell_type = type(df.loc[0, '是否包邮'])
print(cell_type)

<class 'numpy.bool'>

In [10]:
dtype_count = df.dtypes.value_counts()
print(dtype_count)

int64      4
str        3
bool       1
float64    1
Name: count, dtype: int64