In [1]:
import pandas as pd

In [2]:
file_path = r'dtype_convert.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价        下单时间   是否包邮   折扣率
0  1001   手机  2999   2  北京  5998  2024-01-01   True  0.90
1  1002   耳机   399   5  上海  1995  2024-01-02  False  1.00
2  1003   卫衣   199  10  广州  1990  2024-01-03   True  0.85
3  1004   水杯    59  20  深圳  1180  2024-01-04  False  1.00
4  1005   键盘   899   3  北京  2697  2024-01-05   True  0.95

In [3]:
df.dtypes

订单ID      int64
商品名称        str
单价        int64
数量        int64
城市          str
总价        int64
下单时间        str
是否包邮       bool
折扣率     float64
dtype: object

In [4]:
df['订单ID'] = df['订单ID'].astype(str)
df

   订单ID 商品名称    单价  数量  城市    总价        下单时间   是否包邮   折扣率
0  1001   手机  2999   2  北京  5998  2024-01-01   True  0.90
1  1002   耳机   399   5  上海  1995  2024-01-02  False  1.00
2  1003   卫衣   199  10  广州  1990  2024-01-03   True  0.85
3  1004   水杯    59  20  深圳  1180  2024-01-04  False  1.00
4  1005   键盘   899   3  北京  2697  2024-01-05   True  0.95

In [5]:
df.dtypes

订单ID        str
商品名称        str
单价        int64
数量        int64
城市          str
总价        int64
下单时间        str
是否包邮       bool
折扣率     float64
dtype: object

In [6]:
df['是否包邮'] = df['是否包邮'].astype(int)
df

   订单ID 商品名称    单价  数量  城市    总价        下单时间  是否包邮   折扣率
0  1001   手机  2999   2  北京  5998  2024-01-01     1  0.90
1  1002   耳机   399   5  上海  1995  2024-01-02     0  1.00
2  1003   卫衣   199  10  广州  1990  2024-01-03     1  0.85
3  1004   水杯    59  20  深圳  1180  2024-01-04     0  1.00
4  1005   键盘   899   3  北京  2697  2024-01-05     1  0.95

In [7]:
df.dtypes

订单ID        str
商品名称        str
单价        int64
数量        int64
城市          str
总价        int64
下单时间        str
是否包邮      int64
折扣率     float64
dtype: object

In [8]:
df['折扣率'] = (df['折扣率'] * 100).astype(int)
df

   订单ID 商品名称    单价  数量  城市    总价        下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998  2024-01-01     1   90
1  1002   耳机   399   5  上海  1995  2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990  2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180  2024-01-04     0  100
4  1005   键盘   899   3  北京  2697  2024-01-05     1   95

In [9]:
df.dtypes

订单ID      str
商品名称      str
单价      int64
数量      int64
城市        str
总价      int64
下单时间      str
是否包邮    int64
折扣率     int64
dtype: object

In [10]:
df['下单时间'] = pd.to_datetime(df['下单时间'], format='%Y-%m-%d')

df

   订单ID 商品名称    单价  数量  城市    总价       下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998 2024-01-01     1   90
1  1002   耳机   399   5  上海  1995 2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990 2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180 2024-01-04     0  100
4  1005   键盘   899   3  北京  2697 2024-01-05     1   95

In [11]:
df.dtypes

订单ID               str
商品名称               str
单价               int64
数量               int64
城市                 str
总价               int64
下单时间    datetime64[us]
是否包邮             int64
折扣率              int64
dtype: object

In [12]:
print(df.loc[0, '下单时间'])

2024-01-01 00:00:00

In [13]:
df

   订单ID 商品名称    单价  数量  城市    总价       下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998 2024-01-01     1   90
1  1002   耳机   399   5  上海  1995 2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990 2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180 2024-01-04     0  100
4  1005   键盘   899   3  北京  2697 2024-01-05     1   95

In [14]:
df['单价'] = df['单价'].astype(str)

df

   订单ID 商品名称    单价  数量  城市    总价       下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998 2024-01-01     1   90
1  1002   耳机   399   5  上海  1995 2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990 2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180 2024-01-04     0  100
4  1005   键盘   899   3  北京  2697 2024-01-05     1   95

In [15]:
df['单价'] = df['单价'].infer_objects()
df

   订单ID 商品名称    单价  数量  城市    总价       下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998 2024-01-01     1   90
1  1002   耳机   399   5  上海  1995 2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990 2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180 2024-01-04     0  100
4  1005   键盘   899   3  北京  2697 2024-01-05     1   95

In [16]:
df.dtypes

订单ID               str
商品名称               str
单价                 str
数量               int64
城市                 str
总价               int64
下单时间    datetime64[us]
是否包邮             int64
折扣率              int64
dtype: object

In [17]:
df

   订单ID 商品名称    单价  数量  城市    总价       下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998 2024-01-01     1   90
1  1002   耳机   399   5  上海  1995 2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990 2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180 2024-01-04     0  100
4  1005   键盘   899   3  北京  2697 2024-01-05     1   95

In [18]:
df['单价'] = df['单价'].astype(int)
df

   订单ID 商品名称    单价  数量  城市    总价       下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998 2024-01-01     1   90
1  1002   耳机   399   5  上海  1995 2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990 2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180 2024-01-04     0  100
4  1005   键盘   899   3  北京  2697 2024-01-05     1   95

In [19]:
df.dtypes

订单ID               str
商品名称               str
单价               int64
数量               int64
城市                 str
总价               int64
下单时间    datetime64[us]
是否包邮             int64
折扣率              int64
dtype: object

In [20]:
df_convert = df.astype(
    {
        '总价': float,
        '城市': 'category'

    }
)
df_convert

   订单ID 商品名称    单价  数量  城市      总价       下单时间  是否包邮  折扣率
0  1001   手机  2999   2  北京  5998.0 2024-01-01     1   90
1  1002   耳机   399   5  上海  1995.0 2024-01-02     0  100
2  1003   卫衣   199  10  广州  1990.0 2024-01-03     1   85
3  1004   水杯    59  20  深圳  1180.0 2024-01-04     0  100
4  1005   键盘   899   3  北京  2697.0 2024-01-05     1   95

In [21]:
df_convert.dtypes

订单ID               str
商品名称               str
单价               int64
数量               int64
城市            category
总价             float64
下单时间    datetime64[us]
是否包邮             int64
折扣率              int64
dtype: object