In [1]:
import pandas as pd

In [2]:
file_path = r'duplicate_data.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8'
)

df

   订单ID 商品名称   销售额  城市        下单时间
0  1001   手机  2999  北京  2024-01-01
1  1002   耳机   399  上海  2024-01-01
2  1001   手机  2999  北京  2024-01-01
3  1003   卫衣   199  广州  2024-01-02
4  1004   手机  2999  深圳  2024-01-02
5  1002   耳机   399  上海  2024-01-01
6  1005   水杯    59  北京  2024-01-03

In [3]:
duplicate_flag = df.duplicated()
duplicate_flag

0    False
1    False
2     True
3    False
4    False
5     True
6    False
dtype: bool

In [4]:
duplicate_count = duplicate_flag.sum()
print(duplicate_count)

2

In [5]:
duplicate_rows = df[duplicate_flag]
duplicate_rows

   订单ID 商品名称   销售额  城市        下单时间
2  1001   手机  2999  北京  2024-01-01
5  1002   耳机   399  上海  2024-01-01

In [7]:
print(len(df))

7

In [8]:
print(f"重复行占比: {(duplicate_count / len(df) * 100):.2f}%")

重复行占比: 28.57%

In [9]:
col_duplicate_flag = df.duplicated(subset=['商品名称', '销售额'], keep=False)
col_duplicate_flag

0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool

In [10]:
col_duplicate_rows = df[col_duplicate_flag]
col_duplicate_rows

   订单ID 商品名称   销售额  城市        下单时间
0  1001   手机  2999  北京  2024-01-01
1  1002   耳机   399  上海  2024-01-01
2  1001   手机  2999  北京  2024-01-01
4  1004   手机  2999  深圳  2024-01-02
5  1002   耳机   399  上海  2024-01-01

In [11]:
print(col_duplicate_flag.sum())

5

In [12]:
unique_rows = df.drop_duplicates()
unique_rows

   订单ID 商品名称   销售额  城市        下单时间
0  1001   手机  2999  北京  2024-01-01
1  1002   耳机   399  上海  2024-01-01
3  1003   卫衣   199  广州  2024-01-02
4  1004   手机  2999  深圳  2024-01-02
6  1005   水杯    59  北京  2024-01-03

In [13]:
print(len(unique_rows))

5

In [14]:
col_duplicate_flag = df.duplicated(subset=['商品名称', '销售额'], keep='first')
col_duplicate_flag

0    False
1    False
2     True
3    False
4     True
5     True
6    False
dtype: bool