In [1]:
import pandas as pd

In [2]:
file_path = r'sales_stats.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8'
)

df

   商品ID 商品名称    销售额   销量      单价  城市
0   101   手机  29990   10  2999.0  北京
1   102   耳机   3990   10   399.0  上海
2   103   卫衣  19900  100   199.0  广州
3   104   水杯   5900  100    59.0  深圳
4   105   键盘   8990   10   899.0  北京
5   106   鼠标   2990   10   299.0  上海
6   107   背包   4990   50    99.8  广州
7   108   雨伞   1990  100    19.9  深圳

In [3]:
stats_basic = df.describe()
stats_basic

            商品ID           销售额          销量           单价
count    8.00000      8.000000    8.000000     8.000000
mean   104.50000   9842.500000   48.750000   621.712500
std      2.44949   9926.603145   44.541313  1000.858959
min    101.00000   1990.000000   10.000000    19.900000
25%    102.75000   3740.000000   10.000000    89.600000
50%    104.50000   5445.000000   30.000000   249.000000
75%    106.25000  11717.500000  100.000000   524.000000
max    108.00000  29990.000000  100.000000  2999.000000

In [4]:
stats_spec = df[['销售额', '销量']].describe()

stats_spec

                销售额          销量
count      8.000000    8.000000
mean    9842.500000   48.750000
std     9926.603145   44.541313
min     1990.000000   10.000000
25%     3740.000000   10.000000
50%     5445.000000   30.000000
75%    11717.500000  100.000000
max    29990.000000  100.000000

In [5]:
print(f"{df['销售额'].sum():.2f}")

78740.00

In [6]:
print(f"{df['销量'].mean():.2f}")

48.75

In [7]:
df

   商品ID 商品名称    销售额   销量      单价  城市
0   101   手机  29990   10  2999.0  北京
1   102   耳机   3990   10   399.0  上海
2   103   卫衣  19900  100   199.0  广州
3   104   水杯   5900  100    59.0  深圳
4   105   键盘   8990   10   899.0  北京
5   106   鼠标   2990   10   299.0  上海
6   107   背包   4990   50    99.8  广州
7   108   雨伞   1990  100    19.9  深圳

In [8]:
df['单价'].max()

np.float64(2999.0)

In [9]:
df['单价'].min()

np.float64(19.9)

In [10]:
df['销量'].median()

np.float64(30.0)

In [11]:
print(f"{df['销售额'].std():.2f}")

9926.60

In [12]:
stats_group = df.groupby('城市')['销售额'].agg(['sum', 'mean', 'max']).reset_index()
stats_group

   城市    sum     mean    max
0  上海   6980   3490.0   3990
1  北京  38980  19490.0  29990
2  广州  24890  12445.0  19900
3  深圳   7890   3945.0   5900