In [1]:
import pandas as pd

In [2]:
file_path = r'missing_data.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['注册时间'],
    na_values=['']
)

df

   用户ID  姓名    年龄   城市       注册时间    消费金额 会员等级
0   101  张三  25.0   北京 2024-01-01   899.5  VIP
1   102  李四   NaN   上海 2024-01-02     NaN   普通
2   103  王五  30.0  NaN 2024-01-03  1299.0  VIP
3   104  赵六  35.0   深圳        NaT   799.8  NaN
4   105  钱七   NaN   广州 2024-01-05     NaN  VIP

In [3]:
missing_count = df.isnull().sum()
missing_count

用户ID    0
姓名      0
年龄      2
城市      1
注册时间    1
消费金额    2
会员等级    1
dtype: int64

In [4]:
missing_ratio = (df.isnull().sum() / len(df)) * 100
missing_ratio

用户ID     0.0
姓名       0.0
年龄      40.0
城市      20.0
注册时间    20.0
消费金额    40.0
会员等级    20.0
dtype: float64

In [5]:
missing_analysis = pd.DataFrame(
    {'缺失值数量': missing_count,
     '缺失比例(%)': missing_ratio.round(2)}
)

missing_analysis

      缺失值数量  缺失比例(%)
用户ID      0      0.0
姓名        0      0.0
年龄        2     40.0
城市        1     20.0
注册时间      1     20.0
消费金额      2     40.0
会员等级      1     20.0

In [6]:
df

   用户ID  姓名    年龄   城市       注册时间    消费金额 会员等级
0   101  张三  25.0   北京 2024-01-01   899.5  VIP
1   102  李四   NaN   上海 2024-01-02     NaN   普通
2   103  王五  30.0  NaN 2024-01-03  1299.0  VIP
3   104  赵六  35.0   深圳        NaT   799.8  NaN
4   105  钱七   NaN   广州 2024-01-05     NaN  VIP

In [7]:
rows_with_missing = df[df.isnull().any(axis=1)]
rows_with_missing

   用户ID  姓名    年龄   城市       注册时间    消费金额 会员等级
1   102  李四   NaN   上海 2024-01-02     NaN   普通
2   103  王五  30.0  NaN 2024-01-03  1299.0  VIP
3   104  赵六  35.0   深圳        NaT   799.8  NaN
4   105  钱七   NaN   广州 2024-01-05     NaN  VIP

In [9]:
print(df.isnull().sum().sum())

7

In [10]:
print(len(rows_with_missing))

4

In [11]:
print(len(df))

5