In [1]:
import pandas as pd

In [2]:
file_path = r'unique_data.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8'
)

df

   用户ID  姓名  城市   会员等级 消费品类  下单次数
0   101  张三  北京    VIP   数码     3
1   102  李四  上海     普通   服饰     2
2   103  王五  北京    VIP   数码     5
3   104  赵六  深圳    VIP  日用品     1
4   105  钱七  广州     普通   服饰     4
5   106  孙八  上海     普通   数码     2
6   107  周九  北京  高级VIP  日用品     3
7   108  吴十  深圳    VIP   服饰     1

In [5]:
city_unique = df['城市'].unique()
print(city_unique)

<StringArray>
['北京', '上海', '深圳', '广州']
Length: 4, dtype: str

In [6]:
level_unique = df['会员等级'].unique()
level_unique

<StringArray>
['VIP', '普通', '高级VIP']
Length: 3, dtype: str

In [7]:
city_nunique = df['城市'].nunique()
city_nunique

4

In [8]:
category_nunique = df['消费品类'].nunique()
category_nunique

3

In [10]:
df

   用户ID  姓名  城市   会员等级 消费品类  下单次数
0   101  张三  北京    VIP   数码     3
1   102  李四  上海     普通   服饰     2
2   103  王五  北京    VIP   数码     5
3   104  赵六  深圳    VIP  日用品     1
4   105  钱七  广州     普通   服饰     4
5   106  孙八  上海     普通   数码     2
6   107  周九  北京  高级VIP  日用品     3
7   108  吴十  深圳    VIP   服饰     1

In [11]:
level_count = df['会员等级'].value_counts()
level_count

会员等级
VIP      4
普通       3
高级VIP    1
Name: count, dtype: int64

In [12]:
city_count = df['城市'].value_counts()
city_count

城市
北京    3
上海    2
深圳    2
广州    1
Name: count, dtype: int64

In [13]:
city_group = df.groupby('城市')['下单次数'].mean().reset_index()

city_group

   城市      下单次数
0  上海  2.000000
1  北京  3.666667
2  广州  4.000000
3  深圳  1.000000