In [1]:
import pandas as pd

In [2]:
file_path = r'str_split_join.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

  商品名称             规格信息          标签  城市_大区            用户反馈
0   手机    128G|黑色|国行|4G  热销|2024|新品  北京_华北  电池耐用|系统流畅|价格偏高
1   耳机     无线|蓝牙|白色|入耳式     库存充足|热销  上海_华东         音质好|续航短
2   卫衣      XL|纯棉|红色|宽松    断码|降价|清仓  广州_华南       面料舒适|尺码偏大
3   水杯  500ml|不锈钢|蓝色|保温       新品|包邮  深圳_华南       保温效果好|无异味
4   键盘      机械|青轴|黑色|有线       促销|爆款  北京_华北        按键舒服|噪音大
5   鼠标     无线|静音|白色|充电款       特价|清仓  上海_华东         握感好|响应快

In [3]:
df['规格列表'] = df['规格信息'].str.split('|')
df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]"
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]"
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]"
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]"
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]"
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]"

In [4]:
spec_split = df['规格信息'].str.split('|', expand=True)
spec_split

       0    1   2    3
0   128G   黑色  国行   4G
1     无线   蓝牙  白色  入耳式
2     XL   纯棉  红色   宽松
3  500ml  不锈钢  蓝色   保温
4     机械   青轴  黑色   有线
5     无线   静音  白色  充电款

In [5]:
spec_split.columns = ['规格1', '规格2', '规格3', '规格4']

df = pd.concat([df, spec_split], axis=1)

df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款

In [7]:
df[['城市', '大区']] = df['城市_大区'].str.split('_', n=1, expand=True)

df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东

In [8]:
df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东

In [9]:
df['标签_拼接'] = df['标签'].str.split('|').str.join('、')
df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓

In [10]:
df['商品_规格'] = df['商品名称'] + '(' + df['规格1'] + '-' + df['规格2'] + ')'

df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色)
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙)
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉)
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢)
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴)
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音)

In [11]:
df['主规格'] = df['规格列表'].str[0]

df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格,主规格
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色),128G
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙),无线
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉),XL
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢),500ml
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴),机械
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音),无线

In [12]:
df['最后标签'] = df['标签'].str.split('|').str[-1]

df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格,主规格,最后标签
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色),128G,新品
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙),无线,热销
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉),XL,清仓
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢),500ml,包邮
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴),机械,爆款
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音),无线,清仓

In [13]:
def process_feedback(feedback):
    return '；'.join([x.strip() for x in feedback.split('|') if x])


df['反馈_清洗'] = df['用户反馈'].apply(process_feedback)

df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格,主规格,最后标签,反馈_清洗
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色),128G,新品,电池耐用；系统流畅；价格偏高
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙),无线,热销,音质好；续航短
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉),XL,清仓,面料舒适；尺码偏大
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢),500ml,包邮,保温效果好；无异味
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴),机械,爆款,按键舒服；噪音大
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音),无线,清仓,握感好；响应快

In [14]:
df['是否无线'] = df['规格列表'].apply(lambda x: '无线' in x)

df

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格,主规格,最后标签,反馈_清洗,是否无线
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色),128G,新品,电池耐用；系统流畅；价格偏高,False
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙),无线,热销,音质好；续航短,True
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉),XL,清仓,面料舒适；尺码偏大,False
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢),500ml,包邮,保温效果好；无异味,False
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴),机械,爆款,按键舒服；噪音大,False
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音),无线,清仓,握感好；响应快,True

In [15]:
df_null = df.copy()

df_null

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格,主规格,最后标签,反馈_清洗,是否无线
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色),128G,新品,电池耐用；系统流畅；价格偏高,False
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙),无线,热销,音质好；续航短,True
2,卫衣,XL|纯棉|红色|宽松,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉),XL,清仓,面料舒适；尺码偏大,False
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢),500ml,包邮,保温效果好；无异味,False
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴),机械,爆款,按键舒服；噪音大,False
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音),无线,清仓,握感好；响应快,True

In [16]:
df_null.loc[2, '规格信息'] = None
df_null

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格,主规格,最后标签,反馈_清洗,是否无线
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色),128G,新品,电池耐用；系统流畅；价格偏高,False
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙),无线,热销,音质好；续航短,True
2,卫衣,NaN,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉),XL,清仓,面料舒适；尺码偏大,False
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢),500ml,包邮,保温效果好；无异味,False
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴),机械,爆款,按键舒服；噪音大,False
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音),无线,清仓,握感好；响应快,True

In [18]:
df_null['规格_split_safe'] = df_null['规格信息'].str.split('|', na=False)
df_null

TypeError: StringMethods.split() got an unexpected keyword argument 'na'. Did you mean 'n'?

In [19]:
df_null['规格_split_safe'] = df_null['规格信息'].str.split('|').fillna('')
df_null

,商品名称,规格信息,标签,城市_大区,用户反馈,规格列表,规格1,规格2,规格3,规格4,城市,大区,标签_拼接,商品_规格,主规格,最后标签,反馈_清洗,是否无线,规格_split_safe
0,手机,128G|黑色|国行|4G,热销|2024|新品,北京_华北,电池耐用|系统流畅|价格偏高,"[128G, 黑色, 国行, 4G]",128G,黑色,国行,4G,北京,华北,热销、2024、新品,手机(128G-黑色),128G,新品,电池耐用；系统流畅；价格偏高,False,"[128G, 黑色, 国行, 4G]"
1,耳机,无线|蓝牙|白色|入耳式,库存充足|热销,上海_华东,音质好|续航短,"[无线, 蓝牙, 白色, 入耳式]",无线,蓝牙,白色,入耳式,上海,华东,库存充足、热销,耳机(无线-蓝牙),无线,热销,音质好；续航短,True,"[无线, 蓝牙, 白色, 入耳式]"
2,卫衣,NaN,断码|降价|清仓,广州_华南,面料舒适|尺码偏大,"[XL, 纯棉, 红色, 宽松]",XL,纯棉,红色,宽松,广州,华南,断码、降价、清仓,卫衣(XL-纯棉),XL,清仓,面料舒适；尺码偏大,False,
3,水杯,500ml|不锈钢|蓝色|保温,新品|包邮,深圳_华南,保温效果好|无异味,"[500ml, 不锈钢, 蓝色, 保温]",500ml,不锈钢,蓝色,保温,深圳,华南,新品、包邮,水杯(500ml-不锈钢),500ml,包邮,保温效果好；无异味,False,"[500ml, 不锈钢, 蓝色, 保温]"
4,键盘,机械|青轴|黑色|有线,促销|爆款,北京_华北,按键舒服|噪音大,"[机械, 青轴, 黑色, 有线]",机械,青轴,黑色,有线,北京,华北,促销、爆款,键盘(机械-青轴),机械,爆款,按键舒服；噪音大,False,"[机械, 青轴, 黑色, 有线]"
5,鼠标,无线|静音|白色|充电款,特价|清仓,上海_华东,握感好|响应快,"[无线, 静音, 白色, 充电款]",无线,静音,白色,充电款,上海,华东,特价、清仓,鼠标(无线-静音),无线,清仓,握感好；响应快,True,"[无线, 静音, 白色, 充电款]"

In [20]:
df_final = df[['商品名称', '城市', '大区', '主规格', '标签_拼接', '反馈_清洗']]

df_final

  商品名称  城市  大区    主规格       标签_拼接           反馈_清洗
0   手机  北京  华北   128G  热销、2024、新品  电池耐用；系统流畅；价格偏高
1   耳机  上海  华东     无线     库存充足、热销         音质好；续航短
2   卫衣  广州  华南     XL    断码、降价、清仓       面料舒适；尺码偏大
3   水杯  深圳  华南  500ml       新品、包邮       保温效果好；无异味
4   键盘  北京  华北     机械       促销、爆款        按键舒服；噪音大
5   鼠标  上海  华东     无线       特价、清仓         握感好；响应快