In [1]:
import pandas as pd

In [2]:
file_path = r'str_slice_replace.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

       商品编码        商品名称             订单号          手机号          地址          备注
0  SP001234    苹果手机128G  ORD20240501001  13800138000  北京市朝阳区XX街道  热销#新品#2024
1  SP005678     华为耳机无线版  ORD20240501002  13900139000  上海市浦东新区XX路     库存充足#热销
2  SP009012     优衣库卫衣XL  ORD20240501003  13700137000   广州市天河区XX巷    断码#降价#清仓
3  SP003456  膳魔师水杯500ml  ORD20240501004  13600136000  深圳市南山区XX大道       新品#包邮
4  SP007890     雷柏键盘机械轴  ORD20240501005  13500135000   北京市海淀区XX街    促销#爆款#特价

In [4]:
df['编码后四位'] = df['商品编码'].str[4:]
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890

In [5]:
df['订单日期'] = df['订单号'].str[3:11]
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501

In [7]:
df['手机号后4位'] = df['手机号'].astype(str).str[-4:]
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000

In [8]:
df['编码奇数位'] = df['商品编码'].str[::2]
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079

In [9]:
df['备注_替换分隔符'] = df['备注'].str.replace('#', '、', regex=False)

df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价

In [10]:
df['地址_替换'] = df['地址'].str.replace('市', '省', regex=False)
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街

In [11]:
df['备注_清洗'] = df['备注'].str.replace('#', '、').str.replace('热销', '畅销')
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价

In [12]:
df['手机号_脱敏'] = df['手机号'].astype(str).str.replace(r'(\d{3})\d{4}(\d{4})', r'\1****\2', regex=True)

df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000

In [13]:
df['商品名称_数字'] = df['商品名称'].str.replace(r'\D', '', regex=True)

df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,

In [16]:
replace_map = {'热销': '畅销', '断码': '缺货', '新品': '新品上市'}
df['备注_批量替换'] = df['备注_替换分隔符'].str.replace(replace_map, regex=False)

df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价

In [17]:
df['省份'] = df['地址'].str[:2]
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京

In [18]:
df['省份_规范'] = (
    df['省份'].str.replace('京', '北京市').str.replace('沪', '上海市').str.replace('广', '广东省').str.replace('深',
                                                                                                               '广东省'))

df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份,省份_规范
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京,北北京市
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海,上海
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州,广东省州
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳,广东省圳
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京,北北京市

In [19]:
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份,省份_规范
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京,北北京市
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海,上海
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州,广东省州
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳,广东省圳
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京,北北京市

In [20]:
df['备注_条件替换'] = df['备注_清洗'].apply(lambda x: x.replace('降价', '折扣') if '降价' in x else x)
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份,省份_规范,备注_条件替换
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京,北北京市,畅销、新品、2024
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海,上海,库存充足、畅销
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州,广东省州,断码、折扣、清仓
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳,广东省圳,新品、包邮
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京,北北京市,促销、爆款、特价

In [21]:
df

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份,省份_规范,备注_条件替换
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京,北北京市,畅销、新品、2024
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海,上海,库存充足、畅销
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州,广东省州,断码、折扣、清仓
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳,广东省圳,新品、包邮
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京,北北京市,促销、爆款、特价

In [22]:
df_null = df.copy()
df_null

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份,省份_规范,备注_条件替换
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京,北北京市,畅销、新品、2024
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海,上海,库存充足、畅销
2,SP009012,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州,广东省州,断码、折扣、清仓
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳,广东省圳,新品、包邮
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京,北北京市,促销、爆款、特价

In [23]:
df_null.loc[2, '商品编码'] = None
df_null

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份,省份_规范,备注_条件替换
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京,北北京市,畅销、新品、2024
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海,上海,库存充足、畅销
2,NaN,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州,广东省州,断码、折扣、清仓
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳,广东省圳,新品、包邮
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京,北北京市,促销、爆款、特价

In [30]:
df_null['编码后四位_safe'] = df_null['商品编码'].str.slice(3, None)
df_null

,商品编码,商品名称,订单号,手机号,地址,备注,编码后四位,订单日期,手机号后4位,编码奇数位,备注_替换分隔符,地址_替换,备注_清洗,手机号_脱敏,商品名称_数字,备注_批量替换,省份,省份_规范,备注_条件替换,编码后四位_safe
0,SP001234,苹果手机128G,ORD20240501001,13800138000,北京市朝阳区XX街道,热销#新品#2024,1234,20240501,8000,S013,热销、新品、2024,北京省朝阳区XX街道,畅销、新品、2024,138****8000,128,畅销、新品上市、2024,北京,北北京市,畅销、新品、2024,01234
1,SP005678,华为耳机无线版,ORD20240501002,13900139000,上海市浦东新区XX路,库存充足#热销,5678,20240501,9000,S057,库存充足、热销,上海省浦东新区XX路,库存充足、畅销,139****9000,,库存充足、畅销,上海,上海,库存充足、畅销,05678
2,NaN,优衣库卫衣XL,ORD20240501003,13700137000,广州市天河区XX巷,断码#降价#清仓,9012,20240501,7000,S091,断码、降价、清仓,广州省天河区XX巷,断码、降价、清仓,137****7000,,缺货、降价、清仓,广州,广东省州,断码、折扣、清仓,NaN
3,SP003456,膳魔师水杯500ml,ORD20240501004,13600136000,深圳市南山区XX大道,新品#包邮,3456,20240501,6000,S035,新品、包邮,深圳省南山区XX大道,新品、包邮,136****6000,500,新品上市、包邮,深圳,广东省圳,新品、包邮,03456
4,SP007890,雷柏键盘机械轴,ORD20240501005,13500135000,北京市海淀区XX街,促销#爆款#特价,7890,20240501,5000,S079,促销、爆款、特价,北京省海淀区XX街,促销、爆款、特价,135****5000,,促销、爆款、特价,北京,北北京市,促销、爆款、特价,07890