In [1]:
import pandas as pd

In [2]:
file_path = r'str_match.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

    商品名称        规格       品牌          手机号        备注  城市
0   苹果手机  128G黑色国行  A123456  13800138000  热销2024新品  北京
1   华为耳机    无线蓝牙白色   HW7890  13900139000      库存充足  上海
2  优衣库卫衣    XL纯棉红色    YK123  13700137000      断码降价  广州
3  膳魔师水杯  500ml不锈钢   SM5678  13600136000      新品包邮  深圳
4   雷柏键盘    机械青轴黑色   LP9012  13500135000      促销爆款  北京
5   罗技鼠标    无线静音白色   LJ4567  13400134000      特价清仓  上海
6   小米平板    256G银色    XM789  18800188000      新品上市  广州
7   美的水壶   1.8L不锈钢   MD1234  13200132000      清仓处理  深圳

In [3]:
df['含数码'] = df['商品名称'].str.contains('手机|耳机', na=False)

df

    商品名称        规格       品牌          手机号        备注  城市    含数码
0   苹果手机  128G黑色国行  A123456  13800138000  热销2024新品  北京   True
1   华为耳机    无线蓝牙白色   HW7890  13900139000      库存充足  上海   True
2  优衣库卫衣    XL纯棉红色    YK123  13700137000      断码降价  广州  False
3  膳魔师水杯  500ml不锈钢   SM5678  13600136000      新品包邮  深圳  False
4   雷柏键盘    机械青轴黑色   LP9012  13500135000      促销爆款  北京  False
5   罗技鼠标    无线静音白色   LJ4567  13400134000      特价清仓  上海  False
6   小米平板    256G银色    XM789  18800188000      新品上市  广州  False
7   美的水壶   1.8L不锈钢   MD1234  13200132000      清仓处理  深圳  False

In [4]:
digital_goods = df[df['含数码']]
digital_goods

   商品名称        规格       品牌          手机号        备注  城市   含数码
0  苹果手机  128G黑色国行  A123456  13800138000  热销2024新品  北京  True
1  华为耳机    无线蓝牙白色   HW7890  13900139000      库存充足  上海  True

In [5]:
df['品牌含A'] = df['品牌'].str.contains('a', case=False, na=False)

df

    商品名称        规格       品牌          手机号        备注  城市    含数码   品牌含A
0   苹果手机  128G黑色国行  A123456  13800138000  热销2024新品  北京   True   True
1   华为耳机    无线蓝牙白色   HW7890  13900139000      库存充足  上海   True  False
2  优衣库卫衣    XL纯棉红色    YK123  13700137000      断码降价  广州  False  False
3  膳魔师水杯  500ml不锈钢   SM5678  13600136000      新品包邮  深圳  False  False
4   雷柏键盘    机械青轴黑色   LP9012  13500135000      促销爆款  北京  False  False
5   罗技鼠标    无线静音白色   LJ4567  13400134000      特价清仓  上海  False  False
6   小米平板    256G银色    XM789  18800188000      新品上市  广州  False  False
7   美的水壶   1.8L不锈钢   MD1234  13200132000      清仓处理  深圳  False  False

In [6]:
df['品牌以A开头'] = df['品牌'].str.match('^A', na=False)

df

    商品名称        规格       品牌          手机号        备注  城市    含数码   品牌含A  品牌以A开头
0   苹果手机  128G黑色国行  A123456  13800138000  热销2024新品  北京   True   True    True
1   华为耳机    无线蓝牙白色   HW7890  13900139000      库存充足  上海   True  False   False
2  优衣库卫衣    XL纯棉红色    YK123  13700137000      断码降价  广州  False  False   False
3  膳魔师水杯  500ml不锈钢   SM5678  13600136000      新品包邮  深圳  False  False   False
4   雷柏键盘    机械青轴黑色   LP9012  13500135000      促销爆款  北京  False  False   False
5   罗技鼠标    无线静音白色   LJ4567  13400134000      特价清仓  上海  False  False   False
6   小米平板    256G银色    XM789  18800188000      新品上市  广州  False  False   False
7   美的水壶   1.8L不锈钢   MD1234  13200132000      清仓处理  深圳  False  False   False

In [8]:
df['规格以钢结尾'] = df['规格'].str.endswith('钢', na=False)

df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True

In [12]:
phone_pattern = r'^1[38]\d{9}$'

df['手机号格式正确'] = df['手机号'].astype(str).str.match(phone_pattern, na=False)

df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True

In [13]:
df['备注含新品'] = df['备注'].str.contains('新品', na=False)

df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True,False
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False

In [14]:
df['一线城市'] = df['城市'].str.contains('北京|上海', na=False)

df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True,False,False
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False

In [16]:
df['无线+华为'] = df['规格'].str.contains('无线', na=False) & df['品牌'].str.contains('HW', na=False)

df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True,False,False,False
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False,False
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True,False
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True,False
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False,False
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False,False

In [17]:
df['备注_替换'] = df['备注'].str.replace('新品', 'NEW', regex=False)

df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为,备注_替换
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False,热销2024NEW
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True,库存充足
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True,False,False,False,断码降价
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False,False,NEW包邮
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True,False,促销爆款
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True,False,特价清仓
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False,False,NEW上市
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False,False,清仓处理

In [18]:
df['手机号_打码'] = df['手机号'].astype(str).str.replace(r'(\d{3})\d{4}(\d{4})', r'\1****\2', regex=True)
df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为,备注_替换,手机号_打码
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False,热销2024NEW,138****8000
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True,库存充足,139****9000
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True,False,False,False,断码降价,137****7000
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False,False,NEW包邮,136****6000
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True,False,促销爆款,135****5000
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True,False,特价清仓,134****4000
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False,False,NEW上市,188****8000
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False,False,清仓处理,132****2000

In [19]:
df

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为,备注_替换,手机号_打码
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False,热销2024NEW,138****8000
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True,库存充足,139****9000
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True,False,False,False,断码降价,137****7000
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False,False,NEW包邮,136****6000
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True,False,促销爆款,135****5000
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True,False,特价清仓,134****4000
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False,False,NEW上市,188****8000
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False,False,清仓处理,132****2000

In [20]:
df_null = df.copy()

df_null

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为,备注_替换,手机号_打码
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False,热销2024NEW,138****8000
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True,库存充足,139****9000
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,断码降价,广州,False,False,False,False,True,False,False,False,断码降价,137****7000
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False,False,NEW包邮,136****6000
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True,False,促销爆款,135****5000
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True,False,特价清仓,134****4000
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False,False,NEW上市,188****8000
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False,False,清仓处理,132****2000

In [21]:
df_null.loc[2, '备注'] = None
df_null

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为,备注_替换,手机号_打码
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False,热销2024NEW,138****8000
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True,库存充足,139****9000
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,NaN,广州,False,False,False,False,True,False,False,False,断码降价,137****7000
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False,False,NEW包邮,136****6000
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True,False,促销爆款,135****5000
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True,False,特价清仓,134****4000
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False,False,NEW上市,188****8000
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False,False,清仓处理,132****2000

In [22]:
df_null['备注含降价'] = df_null['备注'].str.contains('降价', na=False)

df_null

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为,备注_替换,手机号_打码,备注含降价
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False,热销2024NEW,138****8000,False
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True,库存充足,139****9000,False
2,优衣库卫衣,XL纯棉红色,YK123,13700137000,NaN,广州,False,False,False,False,True,False,False,False,断码降价,137****7000,False
3,膳魔师水杯,500ml不锈钢,SM5678,13600136000,新品包邮,深圳,False,False,False,True,True,True,False,False,NEW包邮,136****6000,False
4,雷柏键盘,机械青轴黑色,LP9012,13500135000,促销爆款,北京,False,False,False,False,True,False,True,False,促销爆款,135****5000,False
5,罗技鼠标,无线静音白色,LJ4567,13400134000,特价清仓,上海,False,False,False,False,True,False,True,False,特价清仓,134****4000,False
6,小米平板,256G银色,XM789,18800188000,新品上市,广州,False,False,False,False,True,True,False,False,NEW上市,188****8000,False
7,美的水壶,1.8L不锈钢,MD1234,13200132000,清仓处理,深圳,False,False,False,True,True,False,False,False,清仓处理,132****2000,False

In [23]:
df_final = df[
    (df['一线城市']) &
    (df['含数码']) &
    (df['手机号格式正确'])
]

df_final

,商品名称,规格,品牌,手机号,备注,城市,含数码,品牌含A,品牌以A开头,规格以钢结尾,手机号格式正确,备注含新品,一线城市,无线+华为,备注_替换,手机号_打码
0,苹果手机,128G黑色国行,A123456,13800138000,热销2024新品,北京,True,True,True,False,True,True,True,False,热销2024NEW,138****8000
1,华为耳机,无线蓝牙白色,HW7890,13900139000,库存充足,上海,True,False,False,False,True,False,True,True,库存充足,139****9000