In [1]:
import pandas as pd

In [2]:
file_path = r'str_basic.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   商品名称          规格描述    品牌        备注  城市
0  手机      128G 黑色 国行  苹果    热销  2024  北京
1  耳机        无线蓝牙 白色   华为        库存充足  上海
2  卫衣       XL码 纯棉 红色   优衣库    断码  降价  广州
3  水杯    500ml 不锈钢 蓝色   膳魔师      新品上架  深圳
4  键盘       机械轴 青轴 黑色  雷柏       促销中    北京
5  鼠标        无线静音 白色   罗技           无  上海
6  裤子      32码 牛仔 蓝色    李维斯      清仓处理  广州
7  毛巾        纯棉 加厚 白色   洁丽雅      常规售卖  深圳

In [3]:
print(df)

   商品名称          规格描述    品牌        备注  城市
0  手机      128G 黑色 国行  苹果    热销  2024  北京
1  耳机        无线蓝牙 白色   华为        库存充足  上海
2  卫衣       XL码 纯棉 红色   优衣库    断码  降价  广州
3  水杯    500ml 不锈钢 蓝色   膳魔师      新品上架  深圳
4  键盘       机械轴 青轴 黑色  雷柏       促销中    北京
5  鼠标        无线静音 白色   罗技           无  上海
6  裤子      32码 牛仔 蓝色    李维斯      清仓处理  广州
7  毛巾        纯棉 加厚 白色   洁丽雅      常规售卖  深圳

In [4]:
df['商品名称_清洗'] = df['商品名称'].str.strip()

df

   商品名称          规格描述    品牌        备注  城市 商品名称_清洗
0  手机      128G 黑色 国行  苹果    热销  2024  北京      手机
1  耳机        无线蓝牙 白色   华为        库存充足  上海      耳机
2  卫衣       XL码 纯棉 红色   优衣库    断码  降价  广州      卫衣
3  水杯    500ml 不锈钢 蓝色   膳魔师      新品上架  深圳      水杯
4  键盘       机械轴 青轴 黑色  雷柏       促销中    北京      键盘
5  鼠标        无线静音 白色   罗技           无  上海      鼠标
6  裤子      32码 牛仔 蓝色    李维斯      清仓处理  广州      裤子
7  毛巾        纯棉 加厚 白色   洁丽雅      常规售卖  深圳      毛巾

In [5]:
print(df)

   商品名称          规格描述    品牌        备注  城市 商品名称_清洗
0  手机      128G 黑色 国行  苹果    热销  2024  北京      手机
1  耳机        无线蓝牙 白色   华为        库存充足  上海      耳机
2  卫衣       XL码 纯棉 红色   优衣库    断码  降价  广州      卫衣
3  水杯    500ml 不锈钢 蓝色   膳魔师      新品上架  深圳      水杯
4  键盘       机械轴 青轴 黑色  雷柏       促销中    北京      键盘
5  鼠标        无线静音 白色   罗技           无  上海      鼠标
6  裤子      32码 牛仔 蓝色    李维斯      清仓处理  广州      裤子
7  毛巾        纯棉 加厚 白色   洁丽雅      常规售卖  深圳      毛巾

In [6]:
df.to_csv('str_basic_1csv', encoding='utf-8', index=False)

In [7]:
df

   商品名称          规格描述    品牌        备注  城市 商品名称_清洗
0  手机      128G 黑色 国行  苹果    热销  2024  北京      手机
1  耳机        无线蓝牙 白色   华为        库存充足  上海      耳机
2  卫衣       XL码 纯棉 红色   优衣库    断码  降价  广州      卫衣
3  水杯    500ml 不锈钢 蓝色   膳魔师      新品上架  深圳      水杯
4  键盘       机械轴 青轴 黑色  雷柏       促销中    北京      键盘
5  鼠标        无线静音 白色   罗技           无  上海      鼠标
6  裤子      32码 牛仔 蓝色    李维斯      清仓处理  广州      裤子
7  毛巾        纯棉 加厚 白色   洁丽雅      常规售卖  深圳      毛巾

In [8]:
df['品牌_清洗'] = df['品牌'].str.strip()

df

   商品名称          规格描述    品牌        备注  城市 商品名称_清洗 品牌_清洗
0  手机      128G 黑色 国行  苹果    热销  2024  北京      手机    苹果
1  耳机        无线蓝牙 白色   华为        库存充足  上海      耳机    华为
2  卫衣       XL码 纯棉 红色   优衣库    断码  降价  广州      卫衣   优衣库
3  水杯    500ml 不锈钢 蓝色   膳魔师      新品上架  深圳      水杯   膳魔师
4  键盘       机械轴 青轴 黑色  雷柏       促销中    北京      键盘    雷柏
5  鼠标        无线静音 白色   罗技           无  上海      鼠标    罗技
6  裤子      32码 牛仔 蓝色    李维斯      清仓处理  广州      裤子   李维斯
7  毛巾        纯棉 加厚 白色   洁丽雅      常规售卖  深圳      毛巾   洁丽雅

In [9]:
df['规格描述_无空格'] = df['规格描述'].str.replace(' ', '')

df

   商品名称          规格描述    品牌        备注  城市 商品名称_清洗 品牌_清洗    规格描述_无空格
0  手机      128G 黑色 国行  苹果    热销  2024  北京      手机    苹果    128G黑色国行
1  耳机        无线蓝牙 白色   华为        库存充足  上海      耳机    华为      无线蓝牙白色
2  卫衣       XL码 纯棉 红色   优衣库    断码  降价  广州      卫衣   优衣库     XL码纯棉红色
3  水杯    500ml 不锈钢 蓝色   膳魔师      新品上架  深圳      水杯   膳魔师  500ml不锈钢蓝色
4  键盘       机械轴 青轴 黑色  雷柏       促销中    北京      键盘    雷柏     机械轴青轴黑色
5  鼠标        无线静音 白色   罗技           无  上海      鼠标    罗技      无线静音白色
6  裤子      32码 牛仔 蓝色    李维斯      清仓处理  广州      裤子   李维斯     32码牛仔蓝色
7  毛巾        纯棉 加厚 白色   洁丽雅      常规售卖  深圳      毛巾   洁丽雅      纯棉加厚白色

In [10]:
df['商品全称'] = df['商品名称_清洗'] + '-' + df['规格描述'].str.strip()

df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色

In [11]:
df['备注_标注'] = '状态: ' + df['备注'].str.strip()

df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖

In [12]:
df['品牌_en'] = ['Apple', 'Huawei', 'UNIQLO', 'Thermos', 'Rapoo', 'Logitech', 'Levi\'s', 'Grace']
df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace

In [13]:
df['品牌_大写'] = df['品牌_en'].str.upper()
df['品牌_小写'] = df['品牌_en'].str.lower()

df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en,品牌_大写,品牌_小写
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple,APPLE,apple
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei,HUAWEI,huawei
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO,UNIQLO,uniqlo
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos,THERMOS,thermos
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo,RAPOO,rapoo
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech,LOGITECH,logitech
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's,LEVI'S,levi's
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace,GRACE,grace

In [14]:
df['备注长度'] = df['备注'].str.strip().str.len()

df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en,品牌_大写,品牌_小写,备注长度
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple,APPLE,apple,8
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei,HUAWEI,huawei,4
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO,UNIQLO,uniqlo,6
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos,THERMOS,thermos,4
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo,RAPOO,rapoo,3
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech,LOGITECH,logitech,1
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's,LEVI'S,levi's,4
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace,GRACE,grace,4

In [15]:
df['规格前缀'] = df['规格描述'].str.strip().str[:5]
df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en,品牌_大写,品牌_小写,备注长度,规格前缀
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple,APPLE,apple,8,128G
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei,HUAWEI,huawei,4,无线蓝牙
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO,UNIQLO,uniqlo,6,XL码 纯
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos,THERMOS,thermos,4,500ml
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo,RAPOO,rapoo,3,机械轴 青
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech,LOGITECH,logitech,1,无线静音
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's,LEVI'S,levi's,4,32码 牛
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace,GRACE,grace,4,纯棉 加厚

In [16]:
df['备注_清洗'] = df['备注'].str.replace('  ', '、').str.strip()

df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en,品牌_大写,品牌_小写,备注长度,规格前缀,备注_清洗
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple,APPLE,apple,8,128G,热销、2024
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei,HUAWEI,huawei,4,无线蓝牙,库存充足
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO,UNIQLO,uniqlo,6,XL码 纯,断码、降价
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos,THERMOS,thermos,4,500ml,新品上架
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo,RAPOO,rapoo,3,机械轴 青,促销中、
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech,LOGITECH,logitech,1,无线静音,无
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's,LEVI'S,levi's,4,32码 牛,清仓处理
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace,GRACE,grace,4,纯棉 加厚,常规售卖

In [17]:
replace_map = {'热销': '畅销', '库存充足': '有货', '断码': '缺货'}

df['备注_替换'] = df['备注_清洗'].replace(replace_map)

df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en,品牌_大写,品牌_小写,备注长度,规格前缀,备注_清洗,备注_替换
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple,APPLE,apple,8,128G,热销、2024,热销、2024
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei,HUAWEI,huawei,4,无线蓝牙,库存充足,有货
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO,UNIQLO,uniqlo,6,XL码 纯,断码、降价,断码、降价
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos,THERMOS,thermos,4,500ml,新品上架,新品上架
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo,RAPOO,rapoo,3,机械轴 青,促销中、,促销中、
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech,LOGITECH,logitech,1,无线静音,无,无
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's,LEVI'S,levi's,4,32码 牛,清仓处理,清仓处理
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace,GRACE,grace,4,纯棉 加厚,常规售卖,常规售卖

In [18]:
df['备注_final'] = df['备注_清洗'].replace('无', '暂无备注').fillna('暂无备注')
df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en,品牌_大写,品牌_小写,备注长度,规格前缀,备注_清洗,备注_替换,备注_final
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple,APPLE,apple,8,128G,热销、2024,热销、2024,热销、2024
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei,HUAWEI,huawei,4,无线蓝牙,库存充足,有货,库存充足
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO,UNIQLO,uniqlo,6,XL码 纯,断码、降价,断码、降价,断码、降价
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos,THERMOS,thermos,4,500ml,新品上架,新品上架,新品上架
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo,RAPOO,rapoo,3,机械轴 青,促销中、,促销中、,促销中、
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech,LOGITECH,logitech,1,无线静音,无,无,暂无备注
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's,LEVI'S,levi's,4,32码 牛,清仓处理,清仓处理,清仓处理
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace,GRACE,grace,4,纯棉 加厚,常规售卖,常规售卖,常规售卖

In [19]:
df

,商品名称,规格描述,品牌,备注,城市,商品名称_清洗,品牌_清洗,规格描述_无空格,商品全称,备注_标注,品牌_en,品牌_大写,品牌_小写,备注长度,规格前缀,备注_清洗,备注_替换,备注_final
0,手机,128G 黑色 国行,苹果,热销 2024,北京,手机,苹果,128G黑色国行,手机-128G 黑色 国行,状态: 热销 2024,Apple,APPLE,apple,8,128G,热销、2024,热销、2024,热销、2024
1,耳机,无线蓝牙 白色,华为,库存充足,上海,耳机,华为,无线蓝牙白色,耳机-无线蓝牙 白色,状态: 库存充足,Huawei,HUAWEI,huawei,4,无线蓝牙,库存充足,有货,库存充足
2,卫衣,XL码 纯棉 红色,优衣库,断码 降价,广州,卫衣,优衣库,XL码纯棉红色,卫衣-XL码 纯棉 红色,状态: 断码 降价,UNIQLO,UNIQLO,uniqlo,6,XL码 纯,断码、降价,断码、降价,断码、降价
3,水杯,500ml 不锈钢 蓝色,膳魔师,新品上架,深圳,水杯,膳魔师,500ml不锈钢蓝色,水杯-500ml 不锈钢 蓝色,状态: 新品上架,Thermos,THERMOS,thermos,4,500ml,新品上架,新品上架,新品上架
4,键盘,机械轴 青轴 黑色,雷柏,促销中,北京,键盘,雷柏,机械轴青轴黑色,键盘-机械轴 青轴 黑色,状态: 促销中,Rapoo,RAPOO,rapoo,3,机械轴 青,促销中、,促销中、,促销中、
5,鼠标,无线静音 白色,罗技,无,上海,鼠标,罗技,无线静音白色,鼠标-无线静音 白色,状态: 无,Logitech,LOGITECH,logitech,1,无线静音,无,无,暂无备注
6,裤子,32码 牛仔 蓝色,李维斯,清仓处理,广州,裤子,李维斯,32码牛仔蓝色,裤子-32码 牛仔 蓝色,状态: 清仓处理,Levi's,LEVI'S,levi's,4,32码 牛,清仓处理,清仓处理,清仓处理
7,毛巾,纯棉 加厚 白色,洁丽雅,常规售卖,深圳,毛巾,洁丽雅,纯棉加厚白色,毛巾-纯棉 加厚 白色,状态: 常规售卖,Grace,GRACE,grace,4,纯棉 加厚,常规售卖,常规售卖,常规售卖

In [20]:
df_clean = df[['商品名称_清洗', '品牌_清洗', '规格描述_无空格', '商品全称', '备注_final', '城市']].rename(
    columns={'商品名称_清洗': '商品名称', '品牌_清洗': '品牌'})


df_clean

  商品名称   品牌    规格描述_无空格             商品全称 备注_final  城市
0   手机   苹果    128G黑色国行    手机-128G 黑色 国行  热销、2024  北京
1   耳机   华为      无线蓝牙白色       耳机-无线蓝牙 白色     库存充足  上海
2   卫衣  优衣库     XL码纯棉红色     卫衣-XL码 纯棉 红色    断码、降价  广州
3   水杯  膳魔师  500ml不锈钢蓝色  水杯-500ml 不锈钢 蓝色     新品上架  深圳
4   键盘   雷柏     机械轴青轴黑色     键盘-机械轴 青轴 黑色     促销中、  北京
5   鼠标   罗技      无线静音白色       鼠标-无线静音 白色     暂无备注  上海
6   裤子  李维斯     32码牛仔蓝色     裤子-32码 牛仔 蓝色     清仓处理  广州
7   毛巾  洁丽雅      纯棉加厚白色      毛巾-纯棉 加厚 白色     常规售卖  深圳