In [1]:
import pandas as pd

In [2]:
file_path = r'time_resample_up.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['销售日期'],
    index_col='销售日期'
)

df

             销量    销售额  城市
销售日期
2024-05-01   43  67957  北京
2024-05-03  130  32870  广州
2024-05-05   60   5940  深圳
2024-05-08   25  49975  深圳
2024-05-10   18   8998  北京

In [4]:
df_hourly = df.resample('h').asfreq()

df_hourly

                       销量      销售额   城市
销售日期
2024-05-01 00:00:00  43.0  67957.0   北京
2024-05-01 01:00:00   NaN      NaN  NaN
2024-05-01 02:00:00   NaN      NaN  NaN
2024-05-01 03:00:00   NaN      NaN  NaN
2024-05-01 04:00:00   NaN      NaN  NaN
...                   ...      ...  ...
2024-05-09 20:00:00   NaN      NaN  NaN
2024-05-09 21:00:00   NaN      NaN  NaN
2024-05-09 22:00:00   NaN      NaN  NaN
2024-05-09 23:00:00   NaN      NaN  NaN
2024-05-10 00:00:00  18.0   8998.0   北京

[217 rows x 3 columns]

In [5]:
df_12h = df.resample('12h').asfreq()

df_12h

                        销量      销售额   城市
销售日期
2024-05-01 00:00:00   43.0  67957.0   北京
2024-05-01 12:00:00    NaN      NaN  NaN
2024-05-02 00:00:00    NaN      NaN  NaN
2024-05-02 12:00:00    NaN      NaN  NaN
2024-05-03 00:00:00  130.0  32870.0   广州
2024-05-03 12:00:00    NaN      NaN  NaN
2024-05-04 00:00:00    NaN      NaN  NaN
2024-05-04 12:00:00    NaN      NaN  NaN
2024-05-05 00:00:00   60.0   5940.0   深圳
2024-05-05 12:00:00    NaN      NaN  NaN
2024-05-06 00:00:00    NaN      NaN  NaN
2024-05-06 12:00:00    NaN      NaN  NaN
2024-05-07 00:00:00    NaN      NaN  NaN
2024-05-07 12:00:00    NaN      NaN  NaN
2024-05-08 00:00:00   25.0  49975.0   深圳
2024-05-08 12:00:00    NaN      NaN  NaN
2024-05-09 00:00:00    NaN      NaN  NaN
2024-05-09 12:00:00    NaN      NaN  NaN
2024-05-10 00:00:00   18.0   8998.0   北京

In [6]:
df_hourly

                       销量      销售额   城市
销售日期
2024-05-01 00:00:00  43.0  67957.0   北京
2024-05-01 01:00:00   NaN      NaN  NaN
2024-05-01 02:00:00   NaN      NaN  NaN
2024-05-01 03:00:00   NaN      NaN  NaN
2024-05-01 04:00:00   NaN      NaN  NaN
...                   ...      ...  ...
2024-05-09 20:00:00   NaN      NaN  NaN
2024-05-09 21:00:00   NaN      NaN  NaN
2024-05-09 22:00:00   NaN      NaN  NaN
2024-05-09 23:00:00   NaN      NaN  NaN
2024-05-10 00:00:00  18.0   8998.0   北京

[217 rows x 3 columns]

In [8]:
df_hourly_fill0 = df.resample('h').last().fillna(0)

df_hourly_fill0

                       销量      销售额  城市
销售日期
2024-05-01 00:00:00  43.0  67957.0  北京
2024-05-01 01:00:00   0.0      0.0   0
2024-05-01 02:00:00   0.0      0.0   0
2024-05-01 03:00:00   0.0      0.0   0
2024-05-01 04:00:00   0.0      0.0   0
...                   ...      ...  ..
2024-05-09 20:00:00   0.0      0.0   0
2024-05-09 21:00:00   0.0      0.0   0
2024-05-09 22:00:00   0.0      0.0   0
2024-05-09 23:00:00   0.0      0.0   0
2024-05-10 00:00:00  18.0   8998.0  北京

[217 rows x 3 columns]

In [10]:
df

             销量    销售额  城市
销售日期
2024-05-01   43  67957  北京
2024-05-03  130  32870  广州
2024-05-05   60   5940  深圳
2024-05-08   25  49975  深圳
2024-05-10   18   8998  北京

In [9]:
df_hourly_ffill = df.resample('h').ffill()

df_hourly_ffill

                     销量    销售额  城市
销售日期
2024-05-01 00:00:00  43  67957  北京
2024-05-01 01:00:00  43  67957  北京
2024-05-01 02:00:00  43  67957  北京
2024-05-01 03:00:00  43  67957  北京
2024-05-01 04:00:00  43  67957  北京
...                  ..    ...  ..
2024-05-09 20:00:00  25  49975  深圳
2024-05-09 21:00:00  25  49975  深圳
2024-05-09 22:00:00  25  49975  深圳
2024-05-09 23:00:00  25  49975  深圳
2024-05-10 00:00:00  18   8998  北京

[217 rows x 3 columns]

In [12]:
df

             销量    销售额  城市
销售日期
2024-05-01   43  67957  北京
2024-05-03  130  32870  广州
2024-05-05   60   5940  深圳
2024-05-08   25  49975  深圳
2024-05-10   18   8998  北京

In [11]:
df_hourly_bfill = df.resample('h').bfill()

df_hourly_bfill

                      销量    销售额  城市
销售日期
2024-05-01 00:00:00   43  67957  北京
2024-05-01 01:00:00  130  32870  广州
2024-05-01 02:00:00  130  32870  广州
2024-05-01 03:00:00  130  32870  广州
2024-05-01 04:00:00  130  32870  广州
...                  ...    ...  ..
2024-05-09 20:00:00   18   8998  北京
2024-05-09 21:00:00   18   8998  北京
2024-05-09 22:00:00   18   8998  北京
2024-05-09 23:00:00   18   8998  北京
2024-05-10 00:00:00   18   8998  北京

[217 rows x 3 columns]

In [13]:
df

             销量    销售额  城市
销售日期
2024-05-01   43  67957  北京
2024-05-03  130  32870  广州
2024-05-05   60   5940  深圳
2024-05-08   25  49975  深圳
2024-05-10   18   8998  北京

In [14]:
df_hourly

                       销量      销售额   城市
销售日期
2024-05-01 00:00:00  43.0  67957.0   北京
2024-05-01 01:00:00   NaN      NaN  NaN
2024-05-01 02:00:00   NaN      NaN  NaN
2024-05-01 03:00:00   NaN      NaN  NaN
2024-05-01 04:00:00   NaN      NaN  NaN
...                   ...      ...  ...
2024-05-09 20:00:00   NaN      NaN  NaN
2024-05-09 21:00:00   NaN      NaN  NaN
2024-05-09 22:00:00   NaN      NaN  NaN
2024-05-09 23:00:00   NaN      NaN  NaN
2024-05-10 00:00:00  18.0   8998.0   北京

[217 rows x 3 columns]

In [18]:
df_hourly_interp = df.select_dtypes(include=['number']).resample('h').interpolate(method='linear')

df_hourly_interp

                            销量           销售额
销售日期
2024-05-01 00:00:00  43.000000  67957.000000
2024-05-01 01:00:00  44.812500  67226.020833
2024-05-01 02:00:00  46.625000  66495.041667
2024-05-01 03:00:00  48.437500  65764.062500
2024-05-01 04:00:00  50.250000  65033.083333
...                        ...           ...
2024-05-09 20:00:00  18.583333  12412.750000
2024-05-09 21:00:00  18.437500  11559.062500
2024-05-09 22:00:00  18.291667  10705.375000
2024-05-09 23:00:00  18.145833   9851.687500
2024-05-10 00:00:00  18.000000   8998.000000

[217 rows x 2 columns]

In [19]:
df_city_hourly = df.groupby('城市').resample('h').ffill()

df_city_hourly

                        销量    销售额
城市 销售日期
北京 2024-05-01 00:00:00  43  67957
   2024-05-01 01:00:00  43  67957
   2024-05-01 02:00:00  43  67957
   2024-05-01 03:00:00  43  67957
   2024-05-01 04:00:00  43  67957
...                     ..    ...
深圳 2024-05-07 20:00:00  60   5940
   2024-05-07 21:00:00  60   5940
   2024-05-07 22:00:00  60   5940
   2024-05-07 23:00:00  60   5940
   2024-05-08 00:00:00  25  49975

[291 rows x 2 columns]

In [21]:
df

             销量    销售额  城市
销售日期
2024-05-01   43  67957  北京
2024-05-03  130  32870  广州
2024-05-05   60   5940  深圳
2024-05-08   25  49975  深圳
2024-05-10   18   8998  北京

In [20]:
df_city_hourly = df_city_hourly.reset_index()

df_city_hourly

     城市                销售日期  销量    销售额
0    北京 2024-05-01 00:00:00  43  67957
1    北京 2024-05-01 01:00:00  43  67957
2    北京 2024-05-01 02:00:00  43  67957
3    北京 2024-05-01 03:00:00  43  67957
4    北京 2024-05-01 04:00:00  43  67957
..   ..                 ...  ..    ...
286  深圳 2024-05-07 20:00:00  60   5940
287  深圳 2024-05-07 21:00:00  60   5940
288  深圳 2024-05-07 22:00:00  60   5940
289  深圳 2024-05-07 23:00:00  60   5940
290  深圳 2024-05-08 00:00:00  25  49975

[291 rows x 4 columns]

In [24]:
df_15min = df.select_dtypes(include=['number']).resample('15min').interpolate(method='linear')

df_15min

                            销量           销售额
销售日期
2024-05-01 00:00:00  43.000000  67957.000000
2024-05-01 00:15:00  43.453125  67774.255208
2024-05-01 00:30:00  43.906250  67591.510417
2024-05-01 00:45:00  44.359375  67408.765625
2024-05-01 01:00:00  44.812500  67226.020833
...                        ...           ...
2024-05-09 23:00:00  18.145833   9851.687500
2024-05-09 23:15:00  18.109375   9638.265625
2024-05-09 23:30:00  18.072917   9424.843750
2024-05-09 23:45:00  18.036458   9211.421875
2024-05-10 00:00:00  18.000000   8998.000000

[865 rows x 2 columns]

In [26]:
df

             销量    销售额  城市
销售日期
2024-05-01   43  67957  北京
2024-05-03  130  32870  广州
2024-05-05   60   5940  深圳
2024-05-08   25  49975  深圳
2024-05-10   18   8998  北京

In [25]:
df_hourly

                       销量      销售额   城市
销售日期
2024-05-01 00:00:00  43.0  67957.0   北京
2024-05-01 01:00:00   NaN      NaN  NaN
2024-05-01 02:00:00   NaN      NaN  NaN
2024-05-01 03:00:00   NaN      NaN  NaN
2024-05-01 04:00:00   NaN      NaN  NaN
...                   ...      ...  ...
2024-05-09 20:00:00   NaN      NaN  NaN
2024-05-09 21:00:00   NaN      NaN  NaN
2024-05-09 22:00:00   NaN      NaN  NaN
2024-05-09 23:00:00   NaN      NaN  NaN
2024-05-10 00:00:00  18.0   8998.0   北京

[217 rows x 3 columns]

In [31]:
df

             销量    销售额  城市
销售日期
2024-05-01   43  67957  北京
2024-05-03  130  32870  广州
2024-05-05   60   5940  深圳
2024-05-08   25  49975  深圳
2024-05-10   18   8998  北京

In [30]:
df_safe_fill = df.resample('h').ffill(limit=48)

df_safe_fill

                       销量      销售额  城市
销售日期
2024-05-01 00:00:00  43.0  67957.0  北京
2024-05-01 01:00:00  43.0  67957.0  北京
2024-05-01 02:00:00  43.0  67957.0  北京
2024-05-01 03:00:00  43.0  67957.0  北京
2024-05-01 04:00:00  43.0  67957.0  北京
...                   ...      ...  ..
2024-05-09 20:00:00  25.0  49975.0  深圳
2024-05-09 21:00:00  25.0  49975.0  深圳
2024-05-09 22:00:00  25.0  49975.0  深圳
2024-05-09 23:00:00  25.0  49975.0  深圳
2024-05-10 00:00:00  18.0   8998.0  北京

[217 rows x 3 columns]

In [32]:
df_safe_fill['销量'] = df_safe_fill['销量'].clip(lower=0)

df_safe_fill

                       销量      销售额  城市
销售日期
2024-05-01 00:00:00  43.0  67957.0  北京
2024-05-01 01:00:00  43.0  67957.0  北京
2024-05-01 02:00:00  43.0  67957.0  北京
2024-05-01 03:00:00  43.0  67957.0  北京
2024-05-01 04:00:00  43.0  67957.0  北京
...                   ...      ...  ..
2024-05-09 20:00:00  25.0  49975.0  深圳
2024-05-09 21:00:00  25.0  49975.0  深圳
2024-05-09 22:00:00  25.0  49975.0  深圳
2024-05-09 23:00:00  25.0  49975.0  深圳
2024-05-10 00:00:00  18.0   8998.0  北京

[217 rows x 3 columns]

In [33]:
df_hourly_interp

                            销量           销售额
销售日期
2024-05-01 00:00:00  43.000000  67957.000000
2024-05-01 01:00:00  44.812500  67226.020833
2024-05-01 02:00:00  46.625000  66495.041667
2024-05-01 03:00:00  48.437500  65764.062500
2024-05-01 04:00:00  50.250000  65033.083333
...                        ...           ...
2024-05-09 20:00:00  18.583333  12412.750000
2024-05-09 21:00:00  18.437500  11559.062500
2024-05-09 22:00:00  18.291667  10705.375000
2024-05-09 23:00:00  18.145833   9851.687500
2024-05-10 00:00:00  18.000000   8998.000000

[217 rows x 2 columns]

In [34]:
df_hourly_interp['小时'] = df_hourly_interp.index.hour

df_hourly_interp

                            销量           销售额  小时
销售日期
2024-05-01 00:00:00  43.000000  67957.000000   0
2024-05-01 01:00:00  44.812500  67226.020833   1
2024-05-01 02:00:00  46.625000  66495.041667   2
2024-05-01 03:00:00  48.437500  65764.062500   3
2024-05-01 04:00:00  50.250000  65033.083333   4
...                        ...           ...  ..
2024-05-09 20:00:00  18.583333  12412.750000  20
2024-05-09 21:00:00  18.437500  11559.062500  21
2024-05-09 22:00:00  18.291667  10705.375000  22
2024-05-09 23:00:00  18.145833   9851.687500  23
2024-05-10 00:00:00  18.000000   8998.000000   0

[217 rows x 3 columns]

In [35]:
hourly_avg = df_hourly_interp.groupby('小时')['销量'].mean().round(1)

hourly_avg

小时
0     56.4
1     60.6
2     60.4
3     60.3
4     60.2
5     60.1
6     60.0
7     59.9
8     59.7
9     59.6
10    59.5
11    59.4
12    59.3
13    59.2
14    59.0
15    58.9
16    58.8
17    58.7
18    58.6
19    58.5
20    58.4
21    58.2
22    58.1
23    58.0
Name: 销量, dtype: float64