In [1]:
import numpy as np
import pandas as pd

In [2]:
file_path = r'time_resample_down.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['销售时间'],
    index_col='销售时间'
)

df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-01 18:10:00   音箱    8   3992  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-02 15:30:00   裤子   50   9950  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-05 11:20:00   鼠标   60   5940  深圳
2024-05-08 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   手表   18   8998  北京

In [3]:
df_daily = df.resample('D')['销量'].sum()

df_daily

销售时间
2024-05-01     43
2024-05-02    130
2024-05-03    130
2024-05-04      0
2024-05-05     60
2024-05-06      0
2024-05-07      0
2024-05-08     25
2024-05-09      0
2024-05-10     18
Freq: D, Name: 销量, dtype: int64

In [4]:
df_weekly = df.resample('W-MON')['销量'].sum()

df_weekly

销售时间
2024-05-06    363
2024-05-13     43
Freq: W-MON, Name: 销量, dtype: int64

In [8]:
df_monthly = df.resample('ME').agg({'销量': 'sum', '销售额': 'mean'})

df_monthly

             销量      销售额
销售时间
2024-05-31  406  19361.0

In [9]:
df_3days = df.resample('3D')['销量'].sum()

df_3days

销售时间
2024-05-01    303
2024-05-04     60
2024-05-07     25
2024-05-10     18
Freq: 3D, Name: 销量, dtype: int64

In [10]:
df_daily

销售时间
2024-05-01     43
2024-05-02    130
2024-05-03    130
2024-05-04      0
2024-05-05     60
2024-05-06      0
2024-05-07      0
2024-05-08     25
2024-05-09      0
2024-05-10     18
Freq: D, Name: 销量, dtype: int64

In [11]:
df_daily_fill = df.resample('D')['销量'].sum().dffillna(0)

df_daily_fill

销售时间
2024-05-01     43
2024-05-02    130
2024-05-03    130
2024-05-04      0
2024-05-05     60
2024-05-06      0
2024-05-07      0
2024-05-08     25
2024-05-09      0
2024-05-10     18
Freq: D, Name: 销量, dtype: int64

In [12]:
df_daily_fill = df_daily_fill.reset_index().rename(columns={'销售时间': '日期'})

df_daily_fill

          日期   销量
0 2024-05-01   43
1 2024-05-02  130
2 2024-05-03  130
3 2024-05-04    0
4 2024-05-05   60
5 2024-05-06    0
6 2024-05-07    0
7 2024-05-08   25
8 2024-05-09    0
9 2024-05-10   18

In [13]:
df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-01 18:10:00   音箱    8   3992  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-02 15:30:00   裤子   50   9950  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-05 11:20:00   鼠标   60   5940  深圳
2024-05-08 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   手表   18   8998  北京

In [15]:
df_city_daily = df.groupby('城市').resample('D')['销量'].sum()

df_city_daily

城市  销售时间
上海  2024-05-02    130
北京  2024-05-01     43
    2024-05-02      0
    2024-05-03      0
    2024-05-04      0
    2024-05-05      0
    2024-05-06      0
    2024-05-07      0
    2024-05-08      0
    2024-05-09      0
    2024-05-10     18
广州  2024-05-03    130
深圳  2024-05-05     60
    2024-05-06      0
    2024-05-07      0
    2024-05-08     25
Name: 销量, dtype: int64

In [16]:
df_city_daily = df_city_daily.reset_index()

df_city_daily

    城市       销售时间   销量
0   上海 2024-05-02  130
1   北京 2024-05-01   43
2   北京 2024-05-02    0
3   北京 2024-05-03    0
4   北京 2024-05-04    0
5   北京 2024-05-05    0
6   北京 2024-05-06    0
7   北京 2024-05-07    0
8   北京 2024-05-08    0
9   北京 2024-05-09    0
10  北京 2024-05-10   18
11  广州 2024-05-03  130
12  深圳 2024-05-05   60
13  深圳 2024-05-06    0
14  深圳 2024-05-07    0
15  深圳 2024-05-08   25

In [17]:
df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-01 18:10:00   音箱    8   3992  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-02 15:30:00   裤子   50   9950  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-05 11:20:00   鼠标   60   5940  深圳
2024-05-08 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   手表   18   8998  北京

In [18]:
df_daily_stats = df.resample('D')['销量'].agg(['max', 'min', 'mean']).round(1)

df_daily_stats

              max   min  mean
销售时间
2024-05-01   20.0   8.0  14.3
2024-05-02   80.0  50.0  65.0
2024-05-03  100.0  30.0  65.0
2024-05-04    NaN   NaN   NaN
2024-05-05   60.0  60.0  60.0
2024-05-06    NaN   NaN   NaN
2024-05-07    NaN   NaN   NaN
2024-05-08   25.0  25.0  25.0
2024-05-09    NaN   NaN   NaN
2024-05-10   18.0  18.0  18.0

In [19]:
df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-01 18:10:00   音箱    8   3992  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-02 15:30:00   裤子   50   9950  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-05 11:20:00   鼠标   60   5940  深圳
2024-05-08 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   手表   18   8998  北京

In [20]:
df_resample_safe = df.resample('D').agg({'销量': lambda x: x.sum() if not x.empty else 0, '销售额': 'sum'}).fillna(0)

df_resample_safe

             销量    销售额
销售时间
2024-05-01   43  69957
2024-05-02  130  25870
2024-05-03  130  32870
2024-05-04    0      0
2024-05-05   60   5940
2024-05-06    0      0
2024-05-07    0      0
2024-05-08   25  49975
2024-05-09    0      0
2024-05-10   18   8998

In [21]:
df_resample_safe = df.resample('D').agg({'销量': lambda x: x.sum() if not x.empty else 0, '销售额': 'sum'})

df_resample_safe

             销量    销售额
销售时间
2024-05-01   43  69957
2024-05-02  130  25870
2024-05-03  130  32870
2024-05-04    0      0
2024-05-05   60   5940
2024-05-06    0      0
2024-05-07    0      0
2024-05-08   25  49975
2024-05-09    0      0
2024-05-10   18   8998

In [22]:
daily_sales = df.resample('D')['销量'].sum()

daily_sales

销售时间
2024-05-01     43
2024-05-02    130
2024-05-03    130
2024-05-04      0
2024-05-05     60
2024-05-06      0
2024-05-07      0
2024-05-08     25
2024-05-09      0
2024-05-10     18
Freq: D, Name: 销量, dtype: int64