In [1]:
import pandas as pd

In [2]:
file_path = r"student_scores.xlsx"

In [9]:
df_sheet1 = pd.read_excel(
    file_path,
    sheet_name='Sheet1',
    na_values=['--', ''],
    usecols=['姓名', '班级', '语文', '数学', '英语']
)

print(df_sheet1)

   姓名  班级  语文    数学    英语
0  张三  一班  85  92.0  78.0
1  李四  一班  90  88.0   NaN
2  王五  二班  76   NaN  89.0
3  赵六  二班  88  95.0  90.0

In [10]:
df_sheet1

   姓名  班级  语文    数学    英语
0  张三  一班  85  92.0  78.0
1  李四  一班  90  88.0   NaN
2  王五  二班  76   NaN  89.0
3  赵六  二班  88  95.0  90.0

In [11]:
df_all = pd.read_excel(file_path, sheet_name=None)
print(df_all)

{'Sheet1':    姓名  班级  语文    数学  英语  备注
0  张三  一班  85  92.0  78  正常
1  李四  一班  90  88.0  --  缺考
2  王五  二班  76   NaN  89  正常
3  赵六  二班  88  95.0  90  优秀, 'class_info':    班级  班主任  人数
0  一班  李老师  30
1  二班  王老师  28}

In [12]:
df_all

{'Sheet1':    姓名  班级  语文    数学  英语  备注
 0  张三  一班  85  92.0  78  正常
 1  李四  一班  90  88.0  --  缺考
 2  王五  二班  76   NaN  89  正常
 3  赵六  二班  88  95.0  90  优秀,
 'class_info':    班级  班主任  人数
 0  一班  李老师  30
 1  二班  王老师  28}

In [13]:
print(list(df_all.keys()))

['Sheet1', 'class_info']

In [14]:
print(df_all['class_info'])

   班级  班主任  人数
0  一班  李老师  30
1  二班  王老师  28

In [15]:
df_all['class_info']

   班级  班主任  人数
0  一班  李老师  30
1  二班  王老师  28

In [16]:
df_custom = pd.read_excel(
    file_path,
    sheet_name='Sheet1',
    header=0,
    index_col='姓名'
)

print(df_custom)

    班级  语文    数学  英语  备注
姓名
张三  一班  85  92.0  78  正常
李四  一班  90  88.0  --  缺考
王五  二班  76   NaN  89  正常
赵六  二班  88  95.0  90  优秀

In [17]:
df_custom

    班级  语文    数学  英语  备注
姓名
张三  一班  85  92.0  78  正常
李四  一班  90  88.0  --  缺考
王五  二班  76   NaN  89  正常
赵六  二班  88  95.0  90  优秀