In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales.csv")
print(df)

   姓名    年龄  城市      销售额  备注
0  张三  25.0  北京  10000.0  正常
1  李四  30.0  上海  15000.0  --
2  王五   NaN  广州   8000.0  未知
3  赵六  28.0  深圳      NaN  正常
4  钱七  35.0  杭州  20000.0  异常

In [3]:
df

   姓名    年龄  城市      销售额  备注
0  张三  25.0  北京  10000.0  正常
1  李四  30.0  上海  15000.0  --
2  王五   NaN  广州   8000.0  未知
3  赵六  28.0  深圳      NaN  正常
4  钱七  35.0  杭州  20000.0  异常

In [4]:
df.head(3)

   姓名    年龄  城市      销售额  备注
0  张三  25.0  北京  10000.0  正常
1  李四  30.0  上海  15000.0  --
2  王五   NaN  广州   8000.0  未知

In [7]:
df_opt = pd.read_csv("sales.csv",
                     encoding="utf-8",
                     na_values=["--", '未知'],
                     usecols=['姓名', '城市', '销售额', '备注'],
                     index_col='姓名')
print(df_opt)

    城市      销售额   备注
姓名
张三  北京  10000.0   正常
李四  上海  15000.0  NaN
王五  广州   8000.0  NaN
赵六  深圳      NaN   正常
钱七  杭州  20000.0   异常

In [8]:
df_opt

    城市      销售额   备注
姓名
张三  北京  10000.0   正常
李四  上海  15000.0  NaN
王五  广州   8000.0  NaN
赵六  深圳      NaN   正常
钱七  杭州  20000.0   异常

In [9]:
print(df_opt.isnull().sum())

城市     0
销售额    1
备注     2
dtype: int64

In [10]:
print(df_opt.dtypes)

城市         str
销售额    float64
备注         str
dtype: object