In [1]:
import pandas as pd

In [2]:
file_path = r"product_data.json"

In [3]:
df_basic = pd.read_json(
    file_path,
    encoding="utf-8",
    dtype={"商品ID": int}
)

print(df_basic)

   商品ID 商品名称    价格   分类   库存
0   101   手机  2999   数码   50
1   102   卫衣   199   服饰  200
2   103   耳机   399   数码   --
3   104   水杯    59  日用品  150

In [4]:
df_basic

   商品ID 商品名称    价格   分类   库存
0   101   手机  2999   数码   50
1   102   卫衣   199   服饰  200
2   103   耳机   399   数码   --
3   104   水杯    59  日用品  150

In [7]:
df_opt = pd.read_json(file_path, encoding="utf-8")
df_opt['库存'] = pd.to_numeric(df_opt['库存'], errors='coerce')
df_opt = df_opt[['商品ID', '商品名称', '价格', '分类', '库存']]

print(df_opt)

   商品ID 商品名称    价格   分类     库存
0   101   手机  2999   数码   50.0
1   102   卫衣   199   服饰  200.0
2   103   耳机   399   数码    NaN
3   104   水杯    59  日用品  150.0

In [8]:
df_opt

   商品ID 商品名称    价格   分类     库存
0   101   手机  2999   数码   50.0
1   102   卫衣   199   服饰  200.0
2   103   耳机   399   数码    NaN
3   104   水杯    59  日用品  150.0

In [18]:
df_dict = pd.read_json("dict_data.json", encoding="utf-8", orient='records')
print(df_dict)

                          数码                        服饰
0  {'商品ID': 101, '价格': 2999}  {'商品ID': 102, '价格': 199}
1   {'商品ID': 103, '价格': 399}  {'商品ID': 104, '价格': 199}

In [10]:
df_dict

                            0                         1
数码  {'商品ID': 101, '价格': 2999}  {'商品ID': 103, '价格': 399}
服饰   {'商品ID': 102, '价格': 199}                      None

In [11]:
import json

with open("dict_data.json", encoding="utf-8") as f:
    data = json.load(f)

# 遍历每个分类，用json_normalize拆解列表，再拼接
df = pd.concat(
    [pd.json_normalize(data[category]).assign(分类=category) for category in data.keys()],
    ignore_index=True
)[["分类", "商品ID", "价格"]]

In [12]:
df

   分类  商品ID    价格
0  数码   101  2999
1  数码   103   399
2  服饰   102   199

In [13]:
print(df_basic.dtypes)

商品ID     int64
商品名称       str
价格       int64
分类         str
库存      object
dtype: object

In [14]:
df_basic

   商品ID 商品名称    价格   分类   库存
0   101   手机  2999   数码   50
1   102   卫衣   199   服饰  200
2   103   耳机   399   数码   --
3   104   水杯    59  日用品  150

In [15]:
df_opt

   商品ID 商品名称    价格   分类     库存
0   101   手机  2999   数码   50.0
1   102   卫衣   199   服饰  200.0
2   103   耳机   399   数码    NaN
3   104   水杯    59  日用品  150.0

In [16]:
print(df_opt.isnull().sum())

商品ID    0
商品名称    0
价格      0
分类      0
库存      1
dtype: int64