In [1]:
import pandas as pd
from IPython.testing.decorators import skip

In [2]:
file_path = r"D:\Projects\AiStudy\Python数据分析\\Pandas\二数据读取与写入\2_1本地文件读取\user_log.txt"

In [4]:
df_basic = pd.read_table(
    file_path,
    sep="|",
    encoding='utf-8',
    skip_blank_lines=True
)

print(df_basic)

   用户ID 用户名              登录时间         登录IP 设备类型
0  1001  张三  2024-01-01 08:30  192.168.1.1   手机
1  1002  李四  2024-01-01 09:15  192.168.1.2   电脑
2  1003  王五  2024-01-01 10:20  192.168.1.3   平板
3  1004  赵六  2024-01-01 11:00  192.168.1.4   --

In [5]:
df_basic

   用户ID 用户名              登录时间         登录IP 设备类型
0  1001  张三  2024-01-01 08:30  192.168.1.1   手机
1  1002  李四  2024-01-01 09:15  192.168.1.2   电脑
2  1003  王五  2024-01-01 10:20  192.168.1.3   平板
3  1004  赵六  2024-01-01 11:00  192.168.1.4   --

In [6]:
df_opt = pd.read_table(
    file_path,
    sep="|",
    encoding='utf-8',
    na_values=["--"],
    usecols=['用户ID', '用户名', '登录时间', '登录IP', '设备类型'],
    index_col='用户ID'
)

print(df_opt)

     用户名              登录时间         登录IP 设备类型
用户ID
1001  张三  2024-01-01 08:30  192.168.1.1   手机
1002  李四  2024-01-01 09:15  192.168.1.2   电脑
1003  王五  2024-01-01 10:20  192.168.1.3   平板
1004  赵六  2024-01-01 11:00  192.168.1.4  NaN

In [7]:
df_opt

     用户名              登录时间         登录IP 设备类型
用户ID
1001  张三  2024-01-01 08:30  192.168.1.1   手机
1002  李四  2024-01-01 09:15  192.168.1.2   电脑
1003  王五  2024-01-01 10:20  192.168.1.3   平板
1004  赵六  2024-01-01 11:00  192.168.1.4  NaN

In [11]:
df_csv = pd.read_csv(
    file_path,
    sep="|",
    encoding='utf-8',
    skiprows=0
)

print(df_csv)

   用户ID 用户名              登录时间         登录IP 设备类型
0  1001  张三  2024-01-01 08:30  192.168.1.1   手机
1  1002  李四  2024-01-01 09:15  192.168.1.2   电脑
2  1003  王五  2024-01-01 10:20  192.168.1.3   平板
3  1004  赵六  2024-01-01 11:00  192.168.1.4   --

In [12]:
df_csv

   用户ID 用户名              登录时间         登录IP 设备类型
0  1001  张三  2024-01-01 08:30  192.168.1.1   手机
1  1002  李四  2024-01-01 09:15  192.168.1.2   电脑
2  1003  王五  2024-01-01 10:20  192.168.1.3   平板
3  1004  赵六  2024-01-01 11:00  192.168.1.4   --