In [1]:
import pandas as pd

In [2]:
file_path = r'row_select.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    index_col='订单ID'
)

df

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697

In [3]:
row_0 = df.iloc[0]
row_0

商品名称      手机
单价      2999
数量         2
城市        北京
总价      5998
Name: 1001, dtype: object

In [4]:
print(type(row_0))

<class 'pandas.Series'>

In [8]:
rows_1_3 = df.iloc[1: 4]
rows_1_3

     商品名称   单价  数量  城市    总价
订单ID
1002   耳机  399   5  上海  1995
1003   卫衣  199  10  广州  1990
1004   水杯   59  20  深圳  1180

In [9]:
print(type(rows_1_3))

<class 'pandas.DataFrame'>

In [7]:
df

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697

In [10]:
rows_spec = df.iloc[[0, 2, 4]]
rows_spec

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1003   卫衣   199  10  广州  1990
1005   键盘   899   3  北京  2697

In [11]:
row_1002 = df.loc[1002]
row_1002

商品名称      耳机
单价       399
数量         5
城市        上海
总价      1995
Name: 1002, dtype: object

In [13]:
rows_1001_1004 = df.loc[1001: 1004]
rows_1001_1004

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180

In [14]:
df

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697

In [15]:
rows_label_spec = df.loc[[1001, 1005]]
rows_label_spec

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1005   键盘   899   3  北京  2697

In [16]:
df

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697

In [17]:
rows_amt_2000 = df[df['总价'] > 2000]
rows_amt_2000

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1005   键盘   899   3  北京  2697

In [18]:
rows_beijing_2000 = df[(df['城市'] == '北京') & (df['总价'] > 2000)]
rows_beijing_2000

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1005   键盘   899   3  北京  2697

In [19]:
df.head(3)

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990

In [20]:
df.tail(3)

     商品名称   单价  数量  城市    总价
订单ID
1003   卫衣  199  10  广州  1990
1004   水杯   59  20  深圳  1180
1005   键盘  899   3  北京  2697