In [1]:
import pandas as pd

In [2]:
file_path = r'row_add.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990

In [3]:
print(len(df))

3

In [5]:
new_row1 = {'订单ID': 1004, '商品名称': '水杯', '单价': 59, '数量': 20, '城市': '深圳', '总价': 1180}
new_df = pd.DataFrame([new_row1])

df = pd.concat([df, new_df], ignore_index=True)

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180

In [6]:
new_row2 = [1005, '键盘', 899, 3, '北京', 2697]
df.loc[len(df)] = new_row2

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697

In [7]:
print(len(df))

5

In [8]:
new_rows_df = pd.DataFrame(
    [
        [1006, '鼠标', 99, 8, '上海', 792],
        [1007, '背包', 199, 5, '广州', 995]
    ],
    columns=df.columns
)

df = pd.concat([df, new_rows_df], ignore_index=True)
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1007   背包   199   5  广州   995

In [9]:
print(len(df))

7