In [1]:
import pandas as pd

In [2]:
file_path = r'row_drop.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    index_col='订单ID'
)

df

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697
1006   鼠标    99   8  上海   792
1007   背包   199   5  广州   995

In [3]:
print(len(df))

7

In [4]:
df = df.drop(df.iloc[0].name)
df

     商品名称   单价  数量  城市    总价
订单ID
1002   耳机  399   5  上海  1995
1003   卫衣  199  10  广州  1990
1004   水杯   59  20  深圳  1180
1005   键盘  899   3  北京  2697
1006   鼠标   99   8  上海   792
1007   背包  199   5  广州   995

In [5]:
df = df.drop(df.iloc[[1, 2]].index)
df

     商品名称   单价  数量  城市    总价
订单ID
1002   耳机  399   5  上海  1995
1005   键盘  899   3  北京  2697
1006   鼠标   99   8  上海   792
1007   背包  199   5  广州   995

In [6]:
print(len(df))

4

In [7]:
df.drop(1006, inplace=True)
df

     商品名称   单价  数量  城市    总价
订单ID
1002   耳机  399   5  上海  1995
1005   键盘  899   3  北京  2697
1007   背包  199   5  广州   995

In [8]:
df.drop([1007], inplace=True)
df

     商品名称   单价  数量  城市    总价
订单ID
1002   耳机  399   5  上海  1995
1005   键盘  899   3  北京  2697

In [9]:
print(len(df))

2

In [10]:
df_reset = df.reset_index(drop=False)

In [11]:
df_reset

   订单ID 商品名称   单价  数量  城市    总价
0  1002   耳机  399   5  上海  1995
1  1005   键盘  899   3  北京  2697

In [12]:
df_reset = df_reset[df_reset['总价'] >= 2000]
df_reset

   订单ID 商品名称   单价  数量  城市    总价
1  1005   键盘  899   3  北京  2697

In [13]:
df = pd.read_csv(
    file_path,
    encoding='utf-8'
)

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1007   背包   199   5  广州   995

In [14]:
df_final = df[(df['城市'] == '北京') & (df['总价'] > 2000)]
df_final

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
4  1005   键盘   899   3  北京  2697