In [36]:
import pandas as pd

In [37]:
file_path = r'data_shift.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['日期'],
    index_col='日期'
)

df

            商品  日销量   日销售额  城市
日期
2024-05-01  手机   20  59980  北京
2024-05-02  手机   25  74975  北京
2024-05-03  手机   18  53982  北京
2024-05-04  手机   30  89970  北京
2024-05-05  手机   22  65978  北京
2024-05-06  手机   19  56981  北京
2024-05-07  手机   28  83972  北京

In [38]:
df['昨日销量'] = df['日销量'].shift(1)
df

            商品  日销量   日销售额  城市  昨日销量
日期
2024-05-01  手机   20  59980  北京   NaN
2024-05-02  手机   25  74975  北京  20.0
2024-05-03  手机   18  53982  北京  25.0
2024-05-04  手机   30  89970  北京  18.0
2024-05-05  手机   22  65978  北京  30.0
2024-05-06  手机   19  56981  北京  22.0
2024-05-07  手机   28  83972  北京  19.0

In [39]:
df['明日销量'] = df['日销量'].shift(-1)

df

            商品  日销量   日销售额  城市  昨日销量  明日销量
日期
2024-05-01  手机   20  59980  北京   NaN  25.0
2024-05-02  手机   25  74975  北京  20.0  18.0
2024-05-03  手机   18  53982  北京  25.0  30.0
2024-05-04  手机   30  89970  北京  18.0  22.0
2024-05-05  手机   22  65978  北京  30.0  19.0
2024-05-06  手机   19  56981  北京  22.0  28.0
2024-05-07  手机   28  83972  北京  19.0   NaN

In [40]:
df['2日前销量'] = df['日销量'].shift(2)

df

            商品  日销量   日销售额  城市  昨日销量  明日销量  2日前销量
日期
2024-05-01  手机   20  59980  北京   NaN  25.0    NaN
2024-05-02  手机   25  74975  北京  20.0  18.0    NaN
2024-05-03  手机   18  53982  北京  25.0  30.0   20.0
2024-05-04  手机   30  89970  北京  18.0  22.0   25.0
2024-05-05  手机   22  65978  北京  30.0  19.0   18.0
2024-05-06  手机   19  56981  北京  22.0  28.0   30.0
2024-05-07  手机   28  83972  北京  19.0   NaN   22.0

In [41]:
df

            商品  日销量   日销售额  城市  昨日销量  明日销量  2日前销量
日期
2024-05-01  手机   20  59980  北京   NaN  25.0    NaN
2024-05-02  手机   25  74975  北京  20.0  18.0    NaN
2024-05-03  手机   18  53982  北京  25.0  30.0   20.0
2024-05-04  手机   30  89970  北京  18.0  22.0   25.0
2024-05-05  手机   22  65978  北京  30.0  19.0   18.0
2024-05-06  手机   19  56981  北京  22.0  28.0   30.0
2024-05-07  手机   28  83972  北京  19.0   NaN   22.0

In [42]:
df['销量环比增长率(%)'] = ((df['日销量'] - df['昨日销量']) / df['昨日销量'] * 100).round(2)

df

            商品  日销量   日销售额  城市  昨日销量  明日销量  2日前销量  销量环比增长率(%)
日期
2024-05-01  手机   20  59980  北京   NaN  25.0    NaN         NaN
2024-05-02  手机   25  74975  北京  20.0  18.0    NaN       25.00
2024-05-03  手机   18  53982  北京  25.0  30.0   20.0      -28.00
2024-05-04  手机   30  89970  北京  18.0  22.0   25.0       66.67
2024-05-05  手机   22  65978  北京  30.0  19.0   18.0      -26.67
2024-05-06  手机   19  56981  北京  22.0  28.0   30.0      -13.64
2024-05-07  手机   28  83972  北京  19.0   NaN   22.0       47.37

In [43]:
df['销售额环比差值'] = df['日销售额'] - df['日销售额'].shift(1)

df

            商品  日销量   日销售额  城市  昨日销量  明日销量  2日前销量  销量环比增长率(%)  销售额环比差值
日期
2024-05-01  手机   20  59980  北京   NaN  25.0    NaN         NaN      NaN
2024-05-02  手机   25  74975  北京  20.0  18.0    NaN       25.00  14995.0
2024-05-03  手机   18  53982  北京  25.0  30.0   20.0      -28.00 -20993.0
2024-05-04  手机   30  89970  北京  18.0  22.0   25.0       66.67  35988.0
2024-05-05  手机   22  65978  北京  30.0  19.0   18.0      -26.67 -23992.0
2024-05-06  手机   19  56981  北京  22.0  28.0   30.0      -13.64  -8997.0
2024-05-07  手机   28  83972  北京  19.0   NaN   22.0       47.37  26991.0

In [44]:
# df['上月同期销量'] = df['日销量'].shift(freq='ME')
#
# df

In [45]:
df['3日销量均值'] = df['日销量'].rolling(window=3).mean().round(1)

df

            商品  日销量   日销售额  城市  昨日销量  明日销量  2日前销量  销量环比增长率(%)  销售额环比差值  3日销量均值
日期
2024-05-01  手机   20  59980  北京   NaN  25.0    NaN         NaN      NaN     NaN
2024-05-02  手机   25  74975  北京  20.0  18.0    NaN       25.00  14995.0     NaN
2024-05-03  手机   18  53982  北京  25.0  30.0   20.0      -28.00 -20993.0    21.0
2024-05-04  手机   30  89970  北京  18.0  22.0   25.0       66.67  35988.0    24.3
2024-05-05  手机   22  65978  北京  30.0  19.0   18.0      -26.67 -23992.0    23.3
2024-05-06  手机   19  56981  北京  22.0  28.0   30.0      -13.64  -8997.0    23.7
2024-05-07  手机   28  83972  北京  19.0   NaN   22.0       47.37  26991.0    23.0

In [46]:
df['5日销量最大值'] = df['日销量'].rolling(window=5).max()

df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值
日期,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0

In [47]:
df['3日销量总和'] = df['日销量'].rolling(window=3).sum()

df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和
日期,,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0

In [48]:
df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和
日期,,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0

In [49]:
df_multi = df.reset_index()

df_multi

,日期,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和
0,2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN
2,2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0
3,2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0
4,2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0
5,2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0
6,2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0

In [50]:
df_multi.loc[7:13, '商品'] = '耳机'

df_multi

,日期,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和
0,2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN
2,2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0
3,2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0
4,2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0
5,2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0
6,2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0

In [51]:
import pandas as pd

file_path = r'data_shift2.csv'

df_multi = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['日期']
)

df_multi

           日期  商品  日销量   日销售额  城市
0  2024-05-01  手机   20  59980  北京
1  2024-05-02  手机   25  74975  北京
2  2024-05-03  手机   18  53982  北京
3  2024-05-04  手机   30  89970  北京
4  2024-05-05  手机   22  65978  北京
5  2024-05-06  手机   19  56981  北京
6  2024-05-07  手机   28  83972  北京
7  2024-05-01  手机   20  59980  北京
8  2024-05-02  手机   25  74975  北京
9  2024-05-03  手机   18  53982  北京
10 2024-05-04  手机   30  89970  北京
11 2024-05-05  手机   22  65978  北京
12 2024-05-06  手机   19  56981  北京
13 2024-05-07  手机   28  83972  北京

In [52]:
df_multi.loc[7:13, '商品'] = '耳机'

df_multi

           日期  商品  日销量   日销售额  城市
0  2024-05-01  手机   20  59980  北京
1  2024-05-02  手机   25  74975  北京
2  2024-05-03  手机   18  53982  北京
3  2024-05-04  手机   30  89970  北京
4  2024-05-05  手机   22  65978  北京
5  2024-05-06  手机   19  56981  北京
6  2024-05-07  手机   28  83972  北京
7  2024-05-01  耳机   20  59980  北京
8  2024-05-02  耳机   25  74975  北京
9  2024-05-03  耳机   18  53982  北京
10 2024-05-04  耳机   30  89970  北京
11 2024-05-05  耳机   22  65978  北京
12 2024-05-06  耳机   19  56981  北京
13 2024-05-07  耳机   28  83972  北京

In [53]:
df_multi.loc[7:13, '日销量'] = [15,18,12,20,16,14,19]

df_multi

           日期  商品  日销量   日销售额  城市
0  2024-05-01  手机   20  59980  北京
1  2024-05-02  手机   25  74975  北京
2  2024-05-03  手机   18  53982  北京
3  2024-05-04  手机   30  89970  北京
4  2024-05-05  手机   22  65978  北京
5  2024-05-06  手机   19  56981  北京
6  2024-05-07  手机   28  83972  北京
7  2024-05-01  耳机   15  59980  北京
8  2024-05-02  耳机   18  74975  北京
9  2024-05-03  耳机   12  53982  北京
10 2024-05-04  耳机   20  89970  北京
11 2024-05-05  耳机   16  65978  北京
12 2024-05-06  耳机   14  56981  北京
13 2024-05-07  耳机   19  83972  北京

In [54]:
df_multi['分组_昨日销量'] = df_multi.groupby('商品')['日销量'].shift(1)

df_multi

           日期  商品  日销量   日销售额  城市  分组_昨日销量
0  2024-05-01  手机   20  59980  北京      NaN
1  2024-05-02  手机   25  74975  北京     20.0
2  2024-05-03  手机   18  53982  北京     25.0
3  2024-05-04  手机   30  89970  北京     18.0
4  2024-05-05  手机   22  65978  北京     30.0
5  2024-05-06  手机   19  56981  北京     22.0
6  2024-05-07  手机   28  83972  北京     19.0
7  2024-05-01  耳机   15  59980  北京      NaN
8  2024-05-02  耳机   18  74975  北京     15.0
9  2024-05-03  耳机   12  53982  北京     18.0
10 2024-05-04  耳机   20  89970  北京     12.0
11 2024-05-05  耳机   16  65978  北京     20.0
12 2024-05-06  耳机   14  56981  北京     16.0
13 2024-05-07  耳机   19  83972  北京     14.0

In [55]:
df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和
日期,,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0

In [56]:
df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和
日期,,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0

In [57]:
df['昨日销量_safe'] = df['昨日销量'].fillna(0)

df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和,昨日销量_safe
日期,,,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN,20.0
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0,25.0
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0,18.0
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0,30.0
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0,22.0
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0,19.0

In [58]:
import numpy as np

df['销量环比增长率_safe(%)'] = df['销量环比增长率(%)'].fillna(0).replace([np.inf, -np.inf], 0)

df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和,昨日销量_safe,销量环比增长率_safe(%)
日期,,,,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN,20.0,25.00
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0,25.0,-28.00
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0,18.0,66.67
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0,30.0,-26.67
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0,22.0,-13.64
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0,19.0,47.37

In [59]:
df

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和,昨日销量_safe,销量环比增长率_safe(%)
日期,,,,,,,,,,,,,,
2024-05-01,手机,20,59980,北京,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN,20.0,25.00
2024-05-03,手机,18,53982,北京,25.0,30.0,20.0,-28.00,-20993.0,21.0,NaN,63.0,25.0,-28.00
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0,18.0,66.67
2024-05-05,手机,22,65978,北京,30.0,19.0,18.0,-26.67,-23992.0,23.3,30.0,70.0,30.0,-26.67
2024-05-06,手机,19,56981,北京,22.0,28.0,30.0,-13.64,-8997.0,23.7,30.0,71.0,22.0,-13.64
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0,19.0,47.37

In [60]:
df_growth = df[df['销量环比增长率(%)'] > 10]

df_growth

,商品,日销量,日销售额,城市,昨日销量,明日销量,2日前销量,销量环比增长率(%),销售额环比差值,3日销量均值,5日销量最大值,3日销量总和,昨日销量_safe,销量环比增长率_safe(%)
日期,,,,,,,,,,,,,,
2024-05-02,手机,25,74975,北京,20.0,18.0,NaN,25.00,14995.0,NaN,NaN,NaN,20.0,25.00
2024-05-04,手机,30,89970,北京,18.0,22.0,25.0,66.67,35988.0,24.3,NaN,73.0,18.0,66.67
2024-05-07,手机,28,83972,北京,19.0,NaN,22.0,47.37,26991.0,23.0,30.0,69.0,19.0,47.37