In [1]:
import pandas as pd

In [3]:
file_path = r'time_delta_calc.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['下单时间', '支付时间', '发货时间', '签收时间']
)

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京

In [5]:
df['支付时长_分钟'] = (df['支付时间'] - df['下单时间']).dt.total_seconds() / 60

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0

In [6]:
df['发货时长_小时'] = (df['发货时间'] - df['支付时间']).dt.total_seconds() / 3600

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000

In [7]:
df['物流总时长'] = df['签收时间'] - df['发货时间']

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00

In [8]:
df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00

In [9]:
df['物流时长_天'] = df['物流总时长'].dt.days
df['物流时长_小时'] = df['物流总时长'].dt.components.hours
df['物流时长_分钟'] = df['物流总时长'].dt.components.minutes

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30

In [10]:
df['订单全周期_天'] = (df['签收时间'] - df['下单时间']).dt.total_seconds() / (24 * 3600)

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722

In [13]:
df_long_logistics = df[df['物流时长_天'] >= 2]

df_long_logistics

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722

In [14]:
city_avg_logistics = df.groupby('城市')['订单全周期_天'].mean().round(2)

city_avg_logistics

城市
上海    1.96
北京    2.06
广州    2.06
深圳    3.16
Name: 订单全周期_天, dtype: float64

In [15]:
df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722

In [16]:
max_pay_time = df['支付时长_分钟'].max()
min_logistics_time = df['物流总时长'].min()

max_pay_time

np.float64(8.0)

In [17]:
min_logistics_time

Timedelta('1 days 16:45:00')

In [18]:
df['发货时长_延迟2h'] = df['发货时长_小时'] + 2

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000

In [19]:
df['预计签收时间'] = df['发货时间'] + pd.Timedelta(days=2)

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h,预计签收时间
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667,2024-05-03 14:00:00
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000,2024-05-04 15:30:00
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333,2024-05-05 16:40:00
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333,2024-05-08 09:00:00
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000,2024-05-12 14:20:00

In [20]:
df['是否超时'] = df['签收时间'] > df['预计签收时间']

df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h,预计签收时间,是否超时
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667,2024-05-03 14:00:00,False
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000,2024-05-04 15:30:00,False
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333,2024-05-05 16:40:00,False
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333,2024-05-08 09:00:00,True
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000,2024-05-12 14:20:00,False

In [21]:
df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h,预计签收时间,是否超时
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667,2024-05-03 14:00:00,False
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000,2024-05-04 15:30:00,False
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333,2024-05-05 16:40:00,False
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333,2024-05-08 09:00:00,True
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000,2024-05-12 14:20:00,False

In [22]:
df_null = df.copy()

df_null

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h,预计签收时间,是否超时
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667,2024-05-03 14:00:00,False
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000,2024-05-04 15:30:00,False
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333,2024-05-05 16:40:00,False
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333,2024-05-08 09:00:00,True
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000,2024-05-12 14:20:00,False

In [23]:
df_null.loc[3, '签收时间'] = None
df_null

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h,预计签收时间,是否超时
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667,2024-05-03 14:00:00,False
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000,2024-05-04 15:30:00,False
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333,2024-05-05 16:40:00,False
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,NaT,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333,2024-05-08 09:00:00,True
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000,2024-05-12 14:20:00,False

In [24]:
df_null['物流总时长_safe'] = (df_null['签收时间'] - df_null['发货时间']).dt.total_seconds().fillna(0) / 3600

df_null

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h,预计签收时间,是否超时,物流总时长_safe
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667,2024-05-03 14:00:00,False,44.333333
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000,2024-05-04 15:30:00,False,40.750000
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333,2024-05-05 16:40:00,False,42.833333
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,NaT,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333,2024-05-08 09:00:00,True,0.000000
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000,2024-05-12 14:20:00,False,43.500000

In [25]:
df

,订单号,下单时间,支付时间,发货时间,签收时间,城市,支付时长_分钟,发货时长_小时,物流总时长,物流时长_天,物流时长_小时,物流时长_分钟,订单全周期_天,发货时长_延迟2h,预计签收时间,是否超时
0,ORD001,2024-05-01 08:30:00,2024-05-01 08:35:00,2024-05-01 14:00:00,2024-05-03 10:20:00,北京,5.0,5.416667,1 days 20:20:00,1,20,20,2.076389,7.416667,2024-05-03 14:00:00,False
1,ORD002,2024-05-02 09:10:00,2024-05-02 09:12:00,2024-05-02 15:30:00,2024-05-04 08:15:00,上海,2.0,6.300000,1 days 16:45:00,1,16,45,1.961806,8.300000,2024-05-04 15:30:00,False
2,ORD003,2024-05-03 10:00:00,2024-05-03 10:05:00,2024-05-03 16:40:00,2024-05-05 11:30:00,广州,5.0,6.583333,1 days 18:50:00,1,18,50,2.062500,8.583333,2024-05-05 16:40:00,False
3,ORD004,2024-05-05 11:20:00,2024-05-05 11:25:00,2024-05-06 09:00:00,2024-05-08 15:10:00,深圳,5.0,21.583333,2 days 06:10:00,2,6,10,3.159722,23.583333,2024-05-08 09:00:00,True
4,ORD005,2024-05-10 09:00:00,2024-05-10 09:08:00,2024-05-10 14:20:00,2024-05-12 09:50:00,北京,8.0,5.200000,1 days 19:30:00,1,19,30,2.034722,7.200000,2024-05-12 14:20:00,False

In [26]:
df_summary = df[['订单号', '城市', '订单全周期_天', '是否超时']]

df_summary

      订单号  城市   订单全周期_天   是否超时
0  ORD001  北京  2.076389  False
1  ORD002  上海  1.961806  False
2  ORD003  广州  2.062500  False
3  ORD004  深圳  3.159722   True
4  ORD005  北京  2.034722  False