In [1]:
import pandas as pd

In [2]:
file_path = r'time_offset.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['下单日期']
)

df

      订单号       下单日期   付款金额  城市
0  ORD001 2024-05-01  59980  北京
1  ORD002 2024-05-02  15920  上海
2  ORD003 2024-05-03  32870  广州
3  ORD004 2024-05-04   5940  深圳
4  ORD005 2024-05-31  49975  北京
5  ORD006 2024-06-01   8998  上海
6  ORD007 2024-06-08  26970  广州

In [12]:
from pandas.tseries.offsets import Day, BusinessDay, MonthEnd, MonthBegin, Week, CustomBusinessDay

In [4]:
df['下单+3天'] = df['下单日期'] + Day(3)

df

      订单号       下单日期   付款金额  城市      下单+3天
0  ORD001 2024-05-01  59980  北京 2024-05-04
1  ORD002 2024-05-02  15920  上海 2024-05-05
2  ORD003 2024-05-03  32870  广州 2024-05-06
3  ORD004 2024-05-04   5940  深圳 2024-05-07
4  ORD005 2024-05-31  49975  北京 2024-06-03
5  ORD006 2024-06-01   8998  上海 2024-06-04
6  ORD007 2024-06-08  26970  广州 2024-06-11

In [5]:
df['下单+2工作日'] = df['下单日期'] + BusinessDay(2)

df

      订单号       下单日期   付款金额  城市      下单+3天    下单+2工作日
0  ORD001 2024-05-01  59980  北京 2024-05-04 2024-05-03
1  ORD002 2024-05-02  15920  上海 2024-05-05 2024-05-06
2  ORD003 2024-05-03  32870  广州 2024-05-06 2024-05-07
3  ORD004 2024-05-04   5940  深圳 2024-05-07 2024-05-07
4  ORD005 2024-05-31  49975  北京 2024-06-03 2024-06-04
5  ORD006 2024-06-01   8998  上海 2024-06-04 2024-06-04
6  ORD007 2024-06-08  26970  广州 2024-06-11 2024-06-11

In [6]:
df['下单-1周'] = df['下单日期'] - Week(1)

df

      订单号       下单日期   付款金额  城市      下单+3天    下单+2工作日      下单-1周
0  ORD001 2024-05-01  59980  北京 2024-05-04 2024-05-03 2024-04-24
1  ORD002 2024-05-02  15920  上海 2024-05-05 2024-05-06 2024-04-25
2  ORD003 2024-05-03  32870  广州 2024-05-06 2024-05-07 2024-04-26
3  ORD004 2024-05-04   5940  深圳 2024-05-07 2024-05-07 2024-04-27
4  ORD005 2024-05-31  49975  北京 2024-06-03 2024-06-04 2024-05-24
5  ORD006 2024-06-01   8998  上海 2024-06-04 2024-06-04 2024-05-25
6  ORD007 2024-06-08  26970  广州 2024-06-11 2024-06-11 2024-06-01

In [7]:
df['当月月末'] = df['下单日期'] + MonthEnd(0)
df

      订单号       下单日期   付款金额  城市      下单+3天    下单+2工作日      下单-1周       当月月末
0  ORD001 2024-05-01  59980  北京 2024-05-04 2024-05-03 2024-04-24 2024-05-31
1  ORD002 2024-05-02  15920  上海 2024-05-05 2024-05-06 2024-04-25 2024-05-31
2  ORD003 2024-05-03  32870  广州 2024-05-06 2024-05-07 2024-04-26 2024-05-31
3  ORD004 2024-05-04   5940  深圳 2024-05-07 2024-05-07 2024-04-27 2024-05-31
4  ORD005 2024-05-31  49975  北京 2024-06-03 2024-06-04 2024-05-24 2024-05-31
5  ORD006 2024-06-01   8998  上海 2024-06-04 2024-06-04 2024-05-25 2024-06-30
6  ORD007 2024-06-08  26970  广州 2024-06-11 2024-06-11 2024-06-01 2024-06-30

In [8]:
df['下月月初'] = df['下单日期'] + MonthBegin(1)

df

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初
0,ORD001,2024-05-01,59980,北京,2024-05-04,2024-05-03,2024-04-24,2024-05-31,2024-06-01
1,ORD002,2024-05-02,15920,上海,2024-05-05,2024-05-06,2024-04-25,2024-05-31,2024-06-01
2,ORD003,2024-05-03,32870,广州,2024-05-06,2024-05-07,2024-04-26,2024-05-31,2024-06-01
3,ORD004,2024-05-04,5940,深圳,2024-05-07,2024-05-07,2024-04-27,2024-05-31,2024-06-01
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01
5,ORD006,2024-06-01,8998,上海,2024-06-04,2024-06-04,2024-05-25,2024-06-30,2024-07-01
6,ORD007,2024-06-08,26970,广州,2024-06-11,2024-06-11,2024-06-01,2024-06-30,2024-07-01

In [10]:
df['本周周一'] = df['下单日期'] - pd.to_timedelta(df['下单日期'].dt.dayofweek, unit='d')

df

C:\Users\LocalHost\AppData\Local\Temp\ipykernel_53236\2532879627.py:1: Pandas4Warning: 'd' is deprecated and will be removed in a future version. Please use 'D' instead of 'd'.
  df['本周周一'] = df['下单日期'] - pd.to_timedelta(df['下单日期'].dt.dayofweek, unit='d')

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初,本周周一
0,ORD001,2024-05-01,59980,北京,2024-05-04,2024-05-03,2024-04-24,2024-05-31,2024-06-01,2024-04-29
1,ORD002,2024-05-02,15920,上海,2024-05-05,2024-05-06,2024-04-25,2024-05-31,2024-06-01,2024-04-29
2,ORD003,2024-05-03,32870,广州,2024-05-06,2024-05-07,2024-04-26,2024-05-31,2024-06-01,2024-04-29
3,ORD004,2024-05-04,5940,深圳,2024-05-07,2024-05-07,2024-04-27,2024-05-31,2024-06-01,2024-04-29
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01,2024-05-27
5,ORD006,2024-06-01,8998,上海,2024-06-04,2024-06-04,2024-05-25,2024-06-30,2024-07-01,2024-05-27
6,ORD007,2024-06-08,26970,广州,2024-06-11,2024-06-11,2024-06-01,2024-06-30,2024-07-01,2024-06-03

In [13]:
holidays = [pd.Timestamp('2024-05-01')]

df['下单+2工作日_含节假日'] = df['下单日期'] + CustomBusinessDay(2, holidays=holidays)

df

C:\Users\LocalHost\AppData\Local\Temp\ipykernel_53236\3587530149.py:3: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex.
  df['下单+2工作日_含节假日'] = df['下单日期'] + CustomBusinessDay(2, holidays=holidays)

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初,本周周一,下单+2工作日_含节假日
0,ORD001,2024-05-01,59980,北京,2024-05-04,2024-05-03,2024-04-24,2024-05-31,2024-06-01,2024-04-29,2024-05-03
1,ORD002,2024-05-02,15920,上海,2024-05-05,2024-05-06,2024-04-25,2024-05-31,2024-06-01,2024-04-29,2024-05-06
2,ORD003,2024-05-03,32870,广州,2024-05-06,2024-05-07,2024-04-26,2024-05-31,2024-06-01,2024-04-29,2024-05-07
3,ORD004,2024-05-04,5940,深圳,2024-05-07,2024-05-07,2024-04-27,2024-05-31,2024-06-01,2024-04-29,2024-05-07
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01,2024-05-27,2024-06-04
5,ORD006,2024-06-01,8998,上海,2024-06-04,2024-06-04,2024-05-25,2024-06-30,2024-07-01,2024-05-27,2024-06-04
6,ORD007,2024-06-08,26970,广州,2024-06-11,2024-06-11,2024-06-01,2024-06-30,2024-07-01,2024-06-03,2024-06-11

In [14]:
df['下单+2工作日_是否周末'] = df['下单+2工作日'].dt.dayofweek >= 5
df

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初,本周周一,下单+2工作日_含节假日,下单+2工作日_是否周末
0,ORD001,2024-05-01,59980,北京,2024-05-04,2024-05-03,2024-04-24,2024-05-31,2024-06-01,2024-04-29,2024-05-03,False
1,ORD002,2024-05-02,15920,上海,2024-05-05,2024-05-06,2024-04-25,2024-05-31,2024-06-01,2024-04-29,2024-05-06,False
2,ORD003,2024-05-03,32870,广州,2024-05-06,2024-05-07,2024-04-26,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False
3,ORD004,2024-05-04,5940,深圳,2024-05-07,2024-05-07,2024-04-27,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01,2024-05-27,2024-06-04,False
5,ORD006,2024-06-01,8998,上海,2024-06-04,2024-06-04,2024-05-25,2024-06-30,2024-07-01,2024-05-27,2024-06-04,False
6,ORD007,2024-06-08,26970,广州,2024-06-11,2024-06-11,2024-06-01,2024-06-30,2024-07-01,2024-06-03,2024-06-11,False

In [15]:
df_may_end = df[(df['下单日期'] >= (df['当月月末'] - Day(3))) & (df['下单日期'].dt.month == 5)]

df_may_end

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初,本周周一,下单+2工作日_含节假日,下单+2工作日_是否周末
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01,2024-05-27,2024-06-04,False

In [17]:
df['周一对齐'] = df['本周周一']

In [18]:
week_amount = df.groupby('周一对齐')['付款金额'].sum()

week_amount

周一对齐
2024-04-29    114710
2024-05-27     58973
2024-06-03     26970
Name: 付款金额, dtype: int64

In [19]:
df['5月31+1天'] = pd.Timestamp('2024-05-31') + Day(1)

df

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初,本周周一,下单+2工作日_含节假日,下单+2工作日_是否周末,周一对齐,5月31+1天
0,ORD001,2024-05-01,59980,北京,2024-05-04,2024-05-03,2024-04-24,2024-05-31,2024-06-01,2024-04-29,2024-05-03,False,2024-04-29,2024-06-01
1,ORD002,2024-05-02,15920,上海,2024-05-05,2024-05-06,2024-04-25,2024-05-31,2024-06-01,2024-04-29,2024-05-06,False,2024-04-29,2024-06-01
2,ORD003,2024-05-03,32870,广州,2024-05-06,2024-05-07,2024-04-26,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False,2024-04-29,2024-06-01
3,ORD004,2024-05-04,5940,深圳,2024-05-07,2024-05-07,2024-04-27,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False,2024-04-29,2024-06-01
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01,2024-05-27,2024-06-04,False,2024-05-27,2024-06-01
5,ORD006,2024-06-01,8998,上海,2024-06-04,2024-06-04,2024-05-25,2024-06-30,2024-07-01,2024-05-27,2024-06-04,False,2024-05-27,2024-06-01
6,ORD007,2024-06-08,26970,广州,2024-06-11,2024-06-11,2024-06-01,2024-06-30,2024-07-01,2024-06-03,2024-06-11,False,2024-06-03,2024-06-01

In [20]:
df['日期有效'] = df['下单+2工作日'].notna()

df

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初,本周周一,下单+2工作日_含节假日,下单+2工作日_是否周末,周一对齐,5月31+1天,日期有效
0,ORD001,2024-05-01,59980,北京,2024-05-04,2024-05-03,2024-04-24,2024-05-31,2024-06-01,2024-04-29,2024-05-03,False,2024-04-29,2024-06-01,True
1,ORD002,2024-05-02,15920,上海,2024-05-05,2024-05-06,2024-04-25,2024-05-31,2024-06-01,2024-04-29,2024-05-06,False,2024-04-29,2024-06-01,True
2,ORD003,2024-05-03,32870,广州,2024-05-06,2024-05-07,2024-04-26,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False,2024-04-29,2024-06-01,True
3,ORD004,2024-05-04,5940,深圳,2024-05-07,2024-05-07,2024-04-27,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False,2024-04-29,2024-06-01,True
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01,2024-05-27,2024-06-04,False,2024-05-27,2024-06-01,True
5,ORD006,2024-06-01,8998,上海,2024-06-04,2024-06-04,2024-05-25,2024-06-30,2024-07-01,2024-05-27,2024-06-04,False,2024-05-27,2024-06-01,True
6,ORD007,2024-06-08,26970,广州,2024-06-11,2024-06-11,2024-06-01,2024-06-30,2024-07-01,2024-06-03,2024-06-11,False,2024-06-03,2024-06-01,True

In [21]:
df['工作日间隔'] = (df['下单+2工作日'] - df['下单日期']).dt.days

df

,订单号,下单日期,付款金额,城市,下单+3天,下单+2工作日,下单-1周,当月月末,下月月初,本周周一,下单+2工作日_含节假日,下单+2工作日_是否周末,周一对齐,5月31+1天,日期有效,工作日间隔
0,ORD001,2024-05-01,59980,北京,2024-05-04,2024-05-03,2024-04-24,2024-05-31,2024-06-01,2024-04-29,2024-05-03,False,2024-04-29,2024-06-01,True,2
1,ORD002,2024-05-02,15920,上海,2024-05-05,2024-05-06,2024-04-25,2024-05-31,2024-06-01,2024-04-29,2024-05-06,False,2024-04-29,2024-06-01,True,4
2,ORD003,2024-05-03,32870,广州,2024-05-06,2024-05-07,2024-04-26,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False,2024-04-29,2024-06-01,True,4
3,ORD004,2024-05-04,5940,深圳,2024-05-07,2024-05-07,2024-04-27,2024-05-31,2024-06-01,2024-04-29,2024-05-07,False,2024-04-29,2024-06-01,True,3
4,ORD005,2024-05-31,49975,北京,2024-06-03,2024-06-04,2024-05-24,2024-05-31,2024-06-01,2024-05-27,2024-06-04,False,2024-05-27,2024-06-01,True,4
5,ORD006,2024-06-01,8998,上海,2024-06-04,2024-06-04,2024-05-25,2024-06-30,2024-07-01,2024-05-27,2024-06-04,False,2024-05-27,2024-06-01,True,3
6,ORD007,2024-06-08,26970,广州,2024-06-11,2024-06-11,2024-06-01,2024-06-30,2024-07-01,2024-06-03,2024-06-11,False,2024-06-03,2024-06-01,True,3