In [1]:
import pandas as pd

In [2]:
file_path = r'column_drop.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价    商品信息  折扣率    折后总价      利润
0  1001   手机  2999   2  北京  已完成   微信  5998  手机（北京）  0.9  5398.2  1199.6
1  1002   耳机   399   5  上海  已完成  支付宝  1995  耳机（上海）  0.9  1795.5   399.0
2  1003   卫衣   199  10  广州  已完成   微信  1990  卫衣（广州）  0.9  1791.0   398.0
3  1004   水杯    59  20  深圳  已完成  支付宝  1180  水杯（深圳）  0.9  1062.0   236.0
4  1005   键盘   899   3  北京  已完成   微信  2697  键盘（北京）  0.9  2427.3   539.4

In [3]:
print(df.columns.tolist())

['订单ID', '商品名称', '单价', '数量', '城市', '订单状态', '支付方式', '总价', '商品信息', '折扣率', '折后总价', '利润']

In [4]:
print(len(df.columns))

12

In [5]:
df.drop('商品信息', axis=1, inplace=True)
df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价  折扣率    折后总价      利润
0  1001   手机  2999   2  北京  已完成   微信  5998  0.9  5398.2  1199.6
1  1002   耳机   399   5  上海  已完成  支付宝  1995  0.9  1795.5   399.0
2  1003   卫衣   199  10  广州  已完成   微信  1990  0.9  1791.0   398.0
3  1004   水杯    59  20  深圳  已完成  支付宝  1180  0.9  1062.0   236.0
4  1005   键盘   899   3  北京  已完成   微信  2697  0.9  2427.3   539.4

In [7]:
print(df.columns.tolist())

['订单ID', '商品名称', '单价', '数量', '城市', '订单状态', '支付方式', '总价', '折扣率', '折后总价', '利润']

In [8]:
print(len(df.columns))

11

In [9]:
del df['折扣率']
df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价    折后总价      利润
0  1001   手机  2999   2  北京  已完成   微信  5998  5398.2  1199.6
1  1002   耳机   399   5  上海  已完成  支付宝  1995  1795.5   399.0
2  1003   卫衣   199  10  广州  已完成   微信  1990  1791.0   398.0
3  1004   水杯    59  20  深圳  已完成  支付宝  1180  1062.0   236.0
4  1005   键盘   899   3  北京  已完成   微信  2697  2427.3   539.4

In [10]:
print(df.columns.tolist())

['订单ID', '商品名称', '单价', '数量', '城市', '订单状态', '支付方式', '总价', '折后总价', '利润']

In [11]:
print(len(df.columns))

10

In [12]:
df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价    折后总价      利润
0  1001   手机  2999   2  北京  已完成   微信  5998  5398.2  1199.6
1  1002   耳机   399   5  上海  已完成  支付宝  1995  1795.5   399.0
2  1003   卫衣   199  10  广州  已完成   微信  1990  1791.0   398.0
3  1004   水杯    59  20  深圳  已完成  支付宝  1180  1062.0   236.0
4  1005   键盘   899   3  北京  已完成   微信  2697  2427.3   539.4

In [13]:
df.drop(
    columns=['支付方式', '订单状态'],
    inplace=True
)

df

   订单ID 商品名称    单价  数量  城市    总价    折后总价      利润
0  1001   手机  2999   2  北京  5998  5398.2  1199.6
1  1002   耳机   399   5  上海  1995  1795.5   399.0
2  1003   卫衣   199  10  广州  1990  1791.0   398.0
3  1004   水杯    59  20  深圳  1180  1062.0   236.0
4  1005   键盘   899   3  北京  2697  2427.3   539.4

In [14]:
print(df.columns.tolist())

['订单ID', '商品名称', '单价', '数量', '城市', '总价', '折后总价', '利润']

In [15]:
print(len(df.columns))

8

In [16]:
df

   订单ID 商品名称    单价  数量  城市    总价    折后总价      利润
0  1001   手机  2999   2  北京  5998  5398.2  1199.6
1  1002   耳机   399   5  上海  1995  1795.5   399.0
2  1003   卫衣   199  10  广州  1990  1791.0   398.0
3  1004   水杯    59  20  深圳  1180  1062.0   236.0
4  1005   键盘   899   3  北京  2697  2427.3   539.4

In [17]:
cols_to_drop = [col for col in df.columns if '价' in col and col != '总价']
cols_to_drop

['单价', '折后总价']

In [18]:
df.drop(columns=cols_to_drop, inplace=True)
df

   订单ID 商品名称  数量  城市    总价      利润
0  1001   手机   2  北京  5998  1199.6
1  1002   耳机   5  上海  1995   399.0
2  1003   卫衣  10  广州  1990   398.0
3  1004   水杯  20  深圳  1180   236.0
4  1005   键盘   3  北京  2697   539.4

In [19]:
print(df.columns.tolist())

['订单ID', '商品名称', '数量', '城市', '总价', '利润']

In [20]:
print(len(df.columns))

6

In [21]:
df

   订单ID 商品名称  数量  城市    总价      利润
0  1001   手机   2  北京  5998  1199.6
1  1002   耳机   5  上海  1995   399.0
2  1003   卫衣  10  广州  1990   398.0
3  1004   水杯  20  深圳  1180   236.0
4  1005   键盘   3  北京  2697   539.4

In [22]:
df_core = df[['订单ID', '商品名称', '总价']].copy()
df_core

   订单ID 商品名称    总价
0  1001   手机  5998
1  1002   耳机  1995
2  1003   卫衣  1990
3  1004   水杯  1180
4  1005   键盘  2697