In [1]:
import pandas as pd

In [2]:
file_path = r'column_select.csv'

df = pd.read_csv(file_path, encoding='utf-8')
df

   订单ID  用户ID  姓名  城市 商品名称  消费金额        下单时间
0  1001   201  张三  北京   手机  2999  2024-01-01
1  1002   202  李四  上海   耳机   399  2024-01-01
2  1003   201  张三  北京   卫衣   199  2024-01-02
3  1004   203  王五  广州   水杯    59  2024-01-02
4  1005   202  李四  上海   键盘   899  2024-01-03

In [5]:
col_name = df['姓名']
print(type(col_name))

<class 'pandas.Series'>

In [6]:
print(col_name)

0    张三
1    李四
2    张三
3    王五
4    李四
Name: 姓名, dtype: str

In [7]:
col_id = df.用户ID
print(type(col_id))

<class 'pandas.Series'>

In [8]:
print(col_id)

0    201
1    202
2    201
3    203
4    202
Name: 用户ID, dtype: int64

In [9]:
col_amount = df.loc[:, '消费金额']
col_amount

0    2999
1     399
2     199
3      59
4     899
Name: 消费金额, dtype: int64

In [10]:
print(type(col_amount))

<class 'pandas.Series'>

In [11]:
df

   订单ID  用户ID  姓名  城市 商品名称  消费金额        下单时间
0  1001   201  张三  北京   手机  2999  2024-01-01
1  1002   202  李四  上海   耳机   399  2024-01-01
2  1003   201  张三  北京   卫衣   199  2024-01-02
3  1004   203  王五  广州   水杯    59  2024-01-02
4  1005   202  李四  上海   键盘   899  2024-01-03

In [12]:
cols_basic = df[['订单ID', '姓名', '消费金额']]
cols_basic

   订单ID  姓名  消费金额
0  1001  张三  2999
1  1002  李四   399
2  1003  张三   199
3  1004  王五    59
4  1005  李四   899

In [13]:
print(type(cols_basic))

<class 'pandas.DataFrame'>

In [15]:
cols_loc = df.loc[:, ['城市', '商品名称', '下单时间']]
print(type(cols_loc))

<class 'pandas.DataFrame'>

In [16]:
cols_loc

   城市 商品名称        下单时间
0  北京   手机  2024-01-01
1  上海   耳机  2024-01-01
2  北京   卫衣  2024-01-02
3  广州   水杯  2024-01-02
4  上海   键盘  2024-01-03

In [17]:
cols_numeric = df.select_dtypes(include=['int64', 'float64'])
cols_numeric

   订单ID  用户ID  消费金额
0  1001   201  2999
1  1002   202   399
2  1003   201   199
3  1004   203    59
4  1005   202   899

In [19]:
cols_object = df.select_dtypes(include=['str'])
cols_object

   姓名  城市 商品名称        下单时间
0  张三  北京   手机  2024-01-01
1  李四  上海   耳机  2024-01-01
2  张三  北京   卫衣  2024-01-02
3  王五  广州   水杯  2024-01-02
4  李四  上海   键盘  2024-01-03

In [20]:
print(cols_numeric.columns.tolist())

['订单ID', '用户ID', '消费金额']

In [21]:
df

   订单ID  用户ID  姓名  城市 商品名称  消费金额        下单时间
0  1001   201  张三  北京   手机  2999  2024-01-01
1  1002   202  李四  上海   耳机   399  2024-01-01
2  1003   201  张三  北京   卫衣   199  2024-01-02
3  1004   203  王五  广州   水杯    59  2024-01-02
4  1005   202  李四  上海   键盘   899  2024-01-03

In [22]:
df_reset = df.reset_index(drop=True)

In [23]:
df_reset

   订单ID  用户ID  姓名  城市 商品名称  消费金额        下单时间
0  1001   201  张三  北京   手机  2999  2024-01-01
1  1002   202  李四  上海   耳机   399  2024-01-01
2  1003   201  张三  北京   卫衣   199  2024-01-02
3  1004   203  王五  广州   水杯    59  2024-01-02
4  1005   202  李四  上海   键盘   899  2024-01-03

In [24]:
cols_slice = df_reset.iloc[:, 0:4]
cols_slice

   订单ID  用户ID  姓名  城市
0  1001   201  张三  北京
1  1002   202  李四  上海
2  1003   201  张三  北京
3  1004   203  王五  广州
4  1005   202  李四  上海