In [1]:
import pandas as pd

In [2]:
file_path = 'column_add.csv'

df = pd.read_csv(file_path, encoding='utf-8')
df

   订单ID 商品名称    单价  数量  城市
0  1001   手机  2999   2  北京
1  1002   耳机   399   5  上海
2  1003   卫衣   199  10  广州
3  1004   水杯    59  20  深圳
4  1005   键盘   899   3  北京

In [3]:
print(df.columns.tolist())

['订单ID', '商品名称', '单价', '数量', '城市']

In [4]:
df['订单状态'] = '已完成'
df

   订单ID 商品名称    单价  数量  城市 订单状态
0  1001   手机  2999   2  北京  已完成
1  1002   耳机   399   5  上海  已完成
2  1003   卫衣   199  10  广州  已完成
3  1004   水杯    59  20  深圳  已完成
4  1005   键盘   899   3  北京  已完成

In [5]:
df['支付方式'] = ['微信', '支付宝', '微信', '支付宝', '微信']
df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式
0  1001   手机  2999   2  北京  已完成   微信
1  1002   耳机   399   5  上海  已完成  支付宝
2  1003   卫衣   199  10  广州  已完成   微信
3  1004   水杯    59  20  深圳  已完成  支付宝
4  1005   键盘   899   3  北京  已完成   微信

In [6]:
df['总价'] = df['单价'] * df['数量']
df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价
0  1001   手机  2999   2  北京  已完成   微信  5998
1  1002   耳机   399   5  上海  已完成  支付宝  1995
2  1003   卫衣   199  10  广州  已完成   微信  1990
3  1004   水杯    59  20  深圳  已完成  支付宝  1180
4  1005   键盘   899   3  北京  已完成   微信  2697

In [7]:
df['商品信息'] = df['商品名称'] + '（' + df['城市'] + '）'
df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价    商品信息
0  1001   手机  2999   2  北京  已完成   微信  5998  手机（北京）
1  1002   耳机   399   5  上海  已完成  支付宝  1995  耳机（上海）
2  1003   卫衣   199  10  广州  已完成   微信  1990  卫衣（广州）
3  1004   水杯    59  20  深圳  已完成  支付宝  1180  水杯（深圳）
4  1005   键盘   899   3  北京  已完成   微信  2697  键盘（北京）

In [8]:
new_cols = {
    '折扣率': 0.9,
    '折扣总价': df['总价'] * 0.9,
    '利润': df['总价'] * 0.2
}

for col, value in new_cols.items():
    df[col] = value

df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价    商品信息  折扣率    折扣总价      利润
0  1001   手机  2999   2  北京  已完成   微信  5998  手机（北京）  0.9  5398.2  1199.6
1  1002   耳机   399   5  上海  已完成  支付宝  1995  耳机（上海）  0.9  1795.5   399.0
2  1003   卫衣   199  10  广州  已完成   微信  1990  卫衣（广州）  0.9  1791.0   398.0
3  1004   水杯    59  20  深圳  已完成  支付宝  1180  水杯（深圳）  0.9  1062.0   236.0
4  1005   键盘   899   3  北京  已完成   微信  2697  键盘（北京）  0.9  2427.3   539.4

In [9]:
print(df.columns.tolist())

['订单ID', '商品名称', '单价', '数量', '城市', '订单状态', '支付方式', '总价', '商品信息', '折扣率', '折扣总价', '利润']

In [10]:
df['支付方式'] = ['QQ', '支付宝', '微信', '支付宝', '微信']
df

   订单ID 商品名称    单价  数量  城市 订单状态 支付方式    总价    商品信息  折扣率    折扣总价      利润
0  1001   手机  2999   2  北京  已完成   QQ  5998  手机（北京）  0.9  5398.2  1199.6
1  1002   耳机   399   5  上海  已完成  支付宝  1995  耳机（上海）  0.9  1795.5   399.0
2  1003   卫衣   199  10  广州  已完成   微信  1990  卫衣（广州）  0.9  1791.0   398.0
3  1004   水杯    59  20  深圳  已完成  支付宝  1180  水杯（深圳）  0.9  1062.0   236.0
4  1005   键盘   899   3  北京  已完成   微信  2697  键盘（北京）  0.9  2427.3   539.4