In [1]:
import pandas as pd

In [2]:
file_path = r'column_rename.csv'

df = pd.read_csv(file_path, encoding='utf-8')
df

   订单ID  用户ID  姓名  城市  消费金额        下单时间
0  1001   201  张三  北京  2999  2024-01-01
1  1002   202  李四  上海   399  2024-01-01
2  1003   201  张三  北京   199  2024-01-02
3  1004   203  王五  广州    59  2024-01-02
4  1005   202  李四  上海   899  2024-01-03

In [3]:
print(df.columns.tolist())

['订单ID', '用户ID', '姓名', '城市', '消费金额', '下单时间']

In [4]:
df.rename(
    columns={
        '订单ID': 'order_id',
        '消费金额': 'payment',
        '下单时间': 'order_time'
    },
    inplace=True
)

df

   order_id  用户ID  姓名  城市  payment  order_time
0      1001   201  张三  北京     2999  2024-01-01
1      1002   202  李四  上海      399  2024-01-01
2      1003   201  张三  北京      199  2024-01-02
3      1004   203  王五  广州       59  2024-01-02
4      1005   202  李四  上海      899  2024-01-03

In [5]:
print(df.columns.tolist())

['order_id', '用户ID', '姓名', '城市', 'payment', 'order_time']

In [6]:
df

   order_id  用户ID  姓名  城市  payment  order_time
0      1001   201  张三  北京     2999  2024-01-01
1      1002   202  李四  上海      399  2024-01-01
2      1003   201  张三  北京      199  2024-01-02
3      1004   203  王五  广州       59  2024-01-02
4      1005   202  李四  上海      899  2024-01-03

In [7]:
df.rename(columns={'用户ID': 'user_id'}, inplace=True)
df

   order_id  user_id  姓名  城市  payment  order_time
0      1001      201  张三  北京     2999  2024-01-01
1      1002      202  李四  上海      399  2024-01-01
2      1003      201  张三  北京      199  2024-01-02
3      1004      203  王五  广州       59  2024-01-02
4      1005      202  李四  上海      899  2024-01-03

In [8]:
print(df.columns.tolist())

['order_id', 'user_id', '姓名', '城市', 'payment', 'order_time']

In [9]:
df

   order_id  user_id  姓名  城市  payment  order_time
0      1001      201  张三  北京     2999  2024-01-01
1      1002      202  李四  上海      399  2024-01-01
2      1003      201  张三  北京      199  2024-01-02
3      1004      203  王五  广州       59  2024-01-02
4      1005      202  李四  上海      899  2024-01-03

In [10]:
df_all_rename = df.copy()

In [11]:
df_all_rename

   order_id  user_id  姓名  城市  payment  order_time
0      1001      201  张三  北京     2999  2024-01-01
1      1002      202  李四  上海      399  2024-01-01
2      1003      201  张三  北京      199  2024-01-02
3      1004      203  王五  广州       59  2024-01-02
4      1005      202  李四  上海      899  2024-01-03

In [18]:
df_all_rename.columns = ['订单编号', '用户编号', '姓名', '城市', '支付金额', '下单日期']

In [19]:
df_all_rename

   订单编号  用户编号  姓名  城市  支付金额        下单日期
0  1001   201  张三  北京  2999  2024-01-01
1  1002   202  李四  上海   399  2024-01-01
2  1003   201  张三  北京   199  2024-01-02
3  1004   203  王五  广州    59  2024-01-02
4  1005   202  李四  上海   899  2024-01-03

In [20]:
print(df_all_rename.columns.tolist())

['订单编号', '用户编号', '姓名', '城市', '支付金额', '下单日期']

In [21]:
df_space = df.copy()

In [22]:
df_space

   order_id  user_id  姓名  城市  payment  order_time
0      1001      201  张三  北京     2999  2024-01-01
1      1002      202  李四  上海      399  2024-01-01
2      1003      201  张三  北京      199  2024-01-02
3      1004      203  王五  广州       59  2024-01-02
4      1005      202  李四  上海      899  2024-01-03

In [23]:
df_space.columns = [' order_id ', ' user_id ', ' 姓名 ', ' 城市 ', ' payment ', ' order_time ']

In [24]:
df_space

   order_id   user_id  姓名  城市   payment  order_time
0       1001       201  张三  北京      2999  2024-01-01
1       1002       202  李四  上海       399  2024-01-01
2       1003       201  张三  北京       199  2024-01-02
3       1004       203  王五  广州        59  2024-01-02
4       1005       202  李四  上海       899  2024-01-03

In [25]:
print(df_space.columns.tolist())

[' order_id ', ' user_id ', ' 姓名 ', ' 城市 ', ' payment ', ' order_time ']

In [26]:
df_space.columns = df_space.columns.str.strip()

In [27]:
print(df_space.columns.tolist())

['order_id', 'user_id', '姓名', '城市', 'payment', 'order_time']