In [2]:
import pandas as pd

In [3]:
file1_path = r'concat_col1.csv'
file2_path = r'concat_col2.csv'

df1 = pd.read_csv(file1_path, encoding='utf-8')
df2 = pd.read_csv(file2_path, encoding='utf-8')

df1

   订单ID 商品名称  城市    单价
0  1001   手机  北京  2999
1  1002   耳机  上海   399
2  1003   卫衣  广州   199
3  1004   水杯  深圳    59
4  1005   键盘  北京   899

In [4]:
df2

   订单ID  数量    总价   是否包邮
0  1001   2  5998   True
1  1002   5  1995  False
2  1003  10  1990   True
3  1004  20  1180  False
4  1006   8   792  False

In [5]:
df1 = df1.set_index('订单ID')
df2 = df2.set_index('订单ID')

df1

     商品名称  城市    单价
订单ID
1001   手机  北京  2999
1002   耳机  上海   399
1003   卫衣  广州   199
1004   水杯  深圳    59
1005   键盘  北京   899

In [6]:
df2

      数量    总价   是否包邮
订单ID
1001   2  5998   True
1002   5  1995  False
1003  10  1990   True
1004  20  1180  False
1006   8   792  False

In [7]:
df_concat = pd.concat([df1, df2], axis=1)

df_concat

     商品名称   城市      单价    数量      总价   是否包邮
订单ID
1001   手机   北京  2999.0   2.0  5998.0   True
1002   耳机   上海   399.0   5.0  1995.0  False
1003   卫衣   广州   199.0  10.0  1990.0   True
1004   水杯   深圳    59.0  20.0  1180.0  False
1005   键盘   北京   899.0   NaN     NaN    NaN
1006  NaN  NaN     NaN   8.0   792.0  False

In [8]:
df_concat_inner = pd.concat([df1, df2], axis=1, join='inner')
df_concat_inner

     商品名称  城市    单价  数量    总价   是否包邮
订单ID
1001   手机  北京  2999   2  5998   True
1002   耳机  上海   399   5  1995  False
1003   卫衣  广州   199  10  1990   True
1004   水杯  深圳    59  20  1180  False

In [9]:
df1

     商品名称  城市    单价
订单ID
1001   手机  北京  2999
1002   耳机  上海   399
1003   卫衣  广州   199
1004   水杯  深圳    59
1005   键盘  北京   899

In [10]:
df2

      数量    总价   是否包邮
订单ID
1001   2  5998   True
1002   5  1995  False
1003  10  1990   True
1004  20  1180  False
1006   8   792  False

In [11]:
df_concat_lev = pd.concat([df1, df2],
                          axis=1,
                          keys=['基础信息', '补充信息'])

df_concat_lev

     基础信息               补充信息
     商品名称   城市      单价    数量      总价   是否包邮
订单ID
1001   手机   北京  2999.0   2.0  5998.0   True
1002   耳机   上海   399.0   5.0  1995.0  False
1003   卫衣   广州   199.0  10.0  1990.0   True
1004   水杯   深圳    59.0  20.0  1180.0  False
1005   键盘   北京   899.0   NaN     NaN    NaN
1006  NaN  NaN     NaN   8.0   792.0  False

In [12]:
df3 = pd.DataFrame(
    {
        '订单ID': [1001, 1002, 1003],
        '快递公司': ['顺丰', '圆通', '中通'],
        '发货时间': ['2024-01-01', '2024-01-02', '2024-01-03']
    }
).set_index('订单ID')

df3

     快递公司        发货时间
订单ID
1001   顺丰  2024-01-01
1002   圆通  2024-01-02
1003   中通  2024-01-03

In [13]:
df_concat_multi = pd.concat([df1, df2, df3], axis=1)

df_concat_multi

     商品名称   城市      单价    数量      总价   是否包邮 快递公司        发货时间
订单ID
1001   手机   北京  2999.0   2.0  5998.0   True   顺丰  2024-01-01
1002   耳机   上海   399.0   5.0  1995.0  False   圆通  2024-01-02
1003   卫衣   广州   199.0  10.0  1990.0   True   中通  2024-01-03
1004   水杯   深圳    59.0  20.0  1180.0  False  NaN         NaN
1005   键盘   北京   899.0   NaN     NaN    NaN  NaN         NaN
1006  NaN  NaN     NaN   8.0   792.0  False  NaN         NaN

In [14]:
df_concat_reset = df_concat_inner.reset_index()

In [15]:
df_concat_reset

   订单ID 商品名称  城市    单价  数量    总价   是否包邮
0  1001   手机  北京  2999   2  5998   True
1  1002   耳机  上海   399   5  1995  False
2  1003   卫衣  广州   199  10  1990   True
3  1004   水杯  深圳    59  20  1180  False