In [1]:
import pandas as pd

In [2]:
path1 = r'data_part1.csv'
path2 = r'data_part2.csv'

df1 = pd.read_csv(path1, encoding='utf-8')
df2 = pd.read_csv(path2, encoding='utf-8')

df1

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990

In [3]:
df2

   订单ID 商品名称   单价  数量  城市    总价
0  1004   水杯   59  20  深圳  1180
1  1005   键盘  899   3  北京  2697
2  1006   鼠标   99   8  上海   792

In [4]:
df_concat_basic = pd.concat([df1, df2], axis=0)
df_concat_basic

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
0  1004   水杯    59  20  深圳  1180
1  1005   键盘   899   3  北京  2697
2  1006   鼠标    99   8  上海   792

In [5]:
df_concat_basic = pd.concat([df1, df2])
df_concat_basic

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
0  1004   水杯    59  20  深圳  1180
1  1005   键盘   899   3  北京  2697
2  1006   鼠标    99   8  上海   792

In [6]:
df_concat_reset = pd.concat([df1, df2], axis=0, ignore_index=True)
df_concat_reset

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792

In [7]:
df1

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990

In [8]:
df2

   订单ID 商品名称   单价  数量  城市    总价
0  1004   水杯   59  20  深圳  1180
1  1005   键盘  899   3  北京  2697
2  1006   鼠标   99   8  上海   792

In [9]:
df3 = pd.DataFrame(
    {'订单ID': [1007, 1008],
     '商品名称': ['裤子', '毛巾'],
     '单价': [299, 19],
     '数量': [6, 15],
     '城市': ['广州', '深圳'],
     '总价': [1794, 285],
     '是否包邮': [True, False]
     })

df3

   订单ID 商品名称   单价  数量  城市    总价   是否包邮
0  1007   裤子  299   6  广州  1794   True
1  1008   毛巾   19  15  深圳   285  False

In [10]:
df_concat_diff = pd.concat([df1, df3], axis=0, ignore_index=True)

df_concat_diff

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998    NaN
1  1002   耳机   399   5  上海  1995    NaN
2  1003   卫衣   199  10  广州  1990    NaN
3  1007   裤子   299   6  广州  1794   True
4  1008   毛巾    19  15  深圳   285  False

In [11]:
df1

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990

In [12]:
df2

   订单ID 商品名称   单价  数量  城市    总价
0  1004   水杯   59  20  深圳  1180
1  1005   键盘  899   3  北京  2697
2  1006   鼠标   99   8  上海   792

In [13]:
df3

   订单ID 商品名称   单价  数量  城市    总价   是否包邮
0  1007   裤子  299   6  广州  1794   True
1  1008   毛巾   19  15  深圳   285  False

In [14]:
df_concat_multi = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

df_concat_multi

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998    NaN
1  1002   耳机   399   5  上海  1995    NaN
2  1003   卫衣   199  10  广州  1990    NaN
3  1004   水杯    59  20  深圳  1180    NaN
4  1005   键盘   899   3  北京  2697    NaN
5  1006   鼠标    99   8  上海   792    NaN
6  1007   裤子   299   6  广州  1794   True
7  1008   毛巾    19  15  深圳   285  False

In [15]:
df_concat_keys = pd.concat([df1, df2],
                           axis=0,
                           keys=['part1', 'part2'],
                           names=['数据来源', '原始索引'])

df_concat_keys

            订单ID 商品名称    单价  数量  城市    总价
数据来源  原始索引
part1 0     1001   手机  2999   2  北京  5998
      1     1002   耳机   399   5  上海  1995
      2     1003   卫衣   199  10  广州  1990
part2 0     1004   水杯    59  20  深圳  1180
      1     1005   键盘   899   3  北京  2697
      2     1006   鼠标    99   8  上海   792

In [16]:
df_part1 = df_concat_keys.loc['part1']

df_part1

      订单ID 商品名称    单价  数量  城市    总价
原始索引
0     1001   手机  2999   2  北京  5998
1     1002   耳机   399   5  上海  1995
2     1003   卫衣   199  10  广州  1990