In [45]:
import pandas as pd

In [46]:
file_path = r'mix_index.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价
0  华北  北京   手机  2999   2  5998
1  华北  北京   键盘   899   3  2697
2  华东  上海   耳机   399   5  1995
3  华南  广州   卫衣   199  10  1990
4  华南  深圳   水杯    59  20  1180

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   大区      5 non-null      str
 1   城市      5 non-null      str
 2   商品名称    5 non-null      str
 3   单价      5 non-null      int64
 4   数量      5 non-null      int64
 5   总价      5 non-null      int64
dtypes: int64(3), str(3)
memory usage: 372.0 bytes

In [48]:
df_multi = df.set_index(['大区', '城市'])
df_multi

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   2  5998
   北京   键盘   899   3  2697
华东 上海   耳机   399   5  1995
华南 广州   卫衣   199  10  1990
   深圳   水杯    59  20  1180

In [49]:
mix1 = df_multi.loc['华北', :].iloc[:, :2]
mix1

   商品名称    单价
城市
北京   手机  2999
北京   键盘   899

In [50]:
for idx, col in enumerate(df_multi.columns):
    print(f"列位置{idx} -> {col}")

列位置0 -> 商品名称
列位置1 -> 单价
列位置2 -> 数量
列位置3 -> 总价

In [51]:
mix2 = df_multi.iloc[:3, :]
mix2

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   2  5998
   北京   键盘   899   3  2697
华东 上海   耳机   399   5  1995

In [52]:
mix2.loc[:, ['商品名称', '总价']]

      商品名称    总价
大区 城市
华北 北京   手机  5998
   北京   键盘  2697
华东 上海   耳机  1995

In [53]:
df_multi

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   2  5998
   北京   键盘   899   3  2697
华东 上海   耳机   399   5  1995
华南 广州   卫衣   199  10  1990
   深圳   水杯    59  20  1180

In [54]:
multi1 = df_multi.loc['华南', :]
multi1

   商品名称   单价  数量    总价
城市
广州   卫衣  199  10  1990
深圳   水杯   59  20  1180

In [55]:
multi2 = df_multi.loc[('华北', '北京'), :]
multi2

C:\Users\LocalHost\AppData\Local\Temp\ipykernel_31984\2466696100.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  multi2 = df_multi.loc[('华北', '北京'), :]

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   2  5998
   北京   键盘   899   3  2697

In [56]:
multi3 = df_multi.loc[('华北', '北京'), ['单价', '数量']]
multi3

C:\Users\LocalHost\AppData\Local\Temp\ipykernel_31984\4176677146.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  multi3 = df_multi.loc[('华北', '北京'), ['单价', '数量']]

         单价  数量
大区 城市
华北 北京  2999   2
   北京   899   3

In [57]:
df_multi

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   2  5998
   北京   键盘   899   3  2697
华东 上海   耳机   399   5  1995
华南 广州   卫衣   199  10  1990
   深圳   水杯    59  20  1180

In [58]:
multi_loc1 = df_multi.loc[df_multi.index.get_level_values(0) == '华东']
multi_loc1

      商品名称   单价  数量    总价
大区 城市
华东 上海   耳机  399   5  1995

In [59]:
df_multi

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   2  5998
   北京   键盘   899   3  2697
华东 上海   耳机   399   5  1995
华南 广州   卫衣   199  10  1990
   深圳   水杯    59  20  1180

In [60]:
df_multi.loc[('华北', '北京'), '数量'] = 5
df_multi

C:\Users\LocalHost\AppData\Local\Temp\ipykernel_31984\3436710779.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc[('华北', '北京'), '数量'] = 5

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   5  5998
   北京   键盘   899   5  2697
华东 上海   耳机   399   5  1995
华南 广州   卫衣   199  10  1990
   深圳   水杯    59  20  1180

In [61]:
# df_multi.iloc[df_multi.index == ('华北', '北京'), -1] = df_multi['单价'] * df_multi['数量']
# df_multi

In [62]:
# 直接通算一遍也行
# df_multi['总价'] = df_multi['单价'] * df_multi['数量']

In [63]:
df_multi

      商品名称    单价  数量    总价
大区 城市
华北 北京   手机  2999   5  5998
   北京   键盘   899   5  2697
华东 上海   耳机   399   5  1995
华南 广州   卫衣   199  10  1990
   深圳   水杯    59  20  1180

In [66]:
# 直接定位多级索引，给总价赋值
df_multi.loc[('华北', '北京'), '总价'] = df_multi.loc[('华北', '北京'), '单价'] * df_multi.loc[('华北', '北京'), '数量']

C:\Users\LocalHost\AppData\Local\Temp\ipykernel_31984\3878589922.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc[('华北', '北京'), '总价'] = df_multi.loc[('华北', '北京'), '单价'] * df_multi.loc[('华北', '北京'), '数量']
C:\Users\LocalHost\AppData\Local\Temp\ipykernel_31984\3878589922.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc[('华北', '北京'), '总价'] = df_multi.loc[('华北', '北京'), '单价'] * df_multi.loc[('华北', '北京'), '数量']

In [67]:
df_multi

      商品名称    单价  数量     总价
大区 城市
华北 北京   手机  2999   5  14995
   北京   键盘   899   5   4495
华东 上海   耳机   399   5   1995
华南 广州   卫衣   199  10   1990
   深圳   水杯    59  20   1180

In [68]:
df_multi

      商品名称    单价  数量     总价
大区 城市
华北 北京   手机  2999   5  14995
   北京   键盘   899   5   4495
华东 上海   耳机   399   5   1995
华南 广州   卫衣   199  10   1990
   深圳   水杯    59  20   1180

In [69]:
df_reset = df_multi.reset_index()
df_reset

   大区  城市 商品名称    单价  数量     总价
0  华北  北京   手机  2999   5  14995
1  华北  北京   键盘   899   5   4495
2  华东  上海   耳机   399   5   1995
3  华南  广州   卫衣   199  10   1990
4  华南  深圳   水杯    59  20   1180

In [70]:
df_new_idx = df_reset.set_index(['商品名称', '大区'])
df_new_idx

         城市    单价  数量     总价
商品名称 大区
手机   华北  北京  2999   5  14995
键盘   华北  北京   899   5   4495
耳机   华东  上海   399   5   1995
卫衣   华南  广州   199  10   1990
水杯   华南  深圳    59  20   1180

In [75]:
mix3 = df_new_idx.loc[('手机', '华北'), :][1:3]
mix3

单价    2999
数量       5
Name: (手机, 华北), dtype: object