In [1]:
import pandas as pd

In [2]:
file_path = r'iloc_slice.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True

In [3]:
for idx, col in enumerate(df.columns):
    print(f"列位置{idx} -> {col}")

列位置0 -> 订单ID
列位置1 -> 商品名称
列位置2 -> 单价
列位置3 -> 数量
列位置4 -> 城市
列位置5 -> 总价
列位置6 -> 是否包邮

In [4]:
val1 = df.iloc[0, 2]
print(val1)

2999

In [5]:
row_multi_col = df.iloc[1, [1, 4, 5]]
row_multi_col

商品名称      耳机
城市        上海
总价      1995
Name: 1, dtype: object

In [6]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True

In [7]:
rows_cols_cont = df.iloc[0:3, 0:4]
rows_cols_cont

   订单ID 商品名称    单价  数量
0  1001   手机  2999   2
1  1002   耳机   399   5
2  1003   卫衣   199  10

In [8]:
rows_cols_noncont = df.iloc[[0, 3, 4], [1, 2, 6]]
rows_cols_noncont

  商品名称    单价   是否包邮
0   手机  2999   True
3   水杯    59  False
4   键盘   899   True

In [9]:
row_all_col = df.iloc[4, :]
row_all_col

订单ID    1005
商品名称      键盘
单价       899
数量         3
城市        北京
总价      2697
是否包邮    True
Name: 4, dtype: object

In [10]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True

In [11]:
col_all_row = df.iloc[:, 3]
col_all_row

0     2
1     5
2    10
3    20
4     3
Name: 数量, dtype: int64

In [12]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True

In [13]:
df.iloc[2, 3] = 15
df.iloc[2, 5] = df.iloc[2, 2] * df.iloc[2, 3]

df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  15  广州  2985   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True

In [14]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  15  广州  2985   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True

In [15]:
df_head2 = df.iloc[:2, :]
df_head2

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False

In [16]:
df.head(2)

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False

In [17]:
df_tail2 = df.iloc[-2:, :]
df_tail2

   订单ID 商品名称   单价  数量  城市    总价   是否包邮
3  1004   水杯   59  20  深圳  1180  False
4  1005   键盘  899   3  北京  2697   True

In [18]:
df.tail(2)

   订单ID 商品名称   单价  数量  城市    总价   是否包邮
3  1004   水杯   59  20  深圳  1180  False
4  1005   键盘  899   3  北京  2697   True