In [16]:
import pandas as pd

In [17]:
file_path = r'loc_slice.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True

In [18]:
df = df.set_index('订单ID')
df

     商品名称    单价  数量  城市    总价   是否包邮
订单ID
1001   手机  2999   2  北京  5998   True
1002   耳机   399   5  上海  1995  False
1003   卫衣   199  10  广州  1990   True
1004   水杯    59  20  深圳  1180  False
1005   键盘   899   3  北京  2697   True

In [19]:
val1 = df.loc[1001, '单价']
val1

np.int64(2999)

In [20]:
print(val1)

2999

In [21]:
row_multi_col = df.loc[1002, ['商品名称', '城市', '总价']]
row_multi_col

商品名称      耳机
城市        上海
总价      1995
Name: 1002, dtype: object

In [22]:
print(type(row_multi_col))

<class 'pandas.Series'>

In [23]:
df

     商品名称    单价  数量  城市    总价   是否包邮
订单ID
1001   手机  2999   2  北京  5998   True
1002   耳机   399   5  上海  1995  False
1003   卫衣   199  10  广州  1990   True
1004   水杯    59  20  深圳  1180  False
1005   键盘   899   3  北京  2697   True

In [24]:
rows_cols = df.loc[1001:1003, ['商品名称', '单价', '是否包邮']]
rows_cols

     商品名称    单价   是否包邮
订单ID
1001   手机  2999   True
1002   耳机   399  False
1003   卫衣   199   True

In [25]:
print(type(rows_cols))

<class 'pandas.DataFrame'>

In [26]:
multi_rows = df.loc[[1001, 1004, 1005], :]
multi_rows

     商品名称    单价  数量  城市    总价   是否包邮
订单ID
1001   手机  2999   2  北京  5998   True
1004   水杯    59  20  深圳  1180  False
1005   键盘   899   3  北京  2697   True

In [27]:
df

     商品名称    单价  数量  城市    总价   是否包邮
订单ID
1001   手机  2999   2  北京  5998   True
1002   耳机   399   5  上海  1995  False
1003   卫衣   199  10  广州  1990   True
1004   水杯    59  20  深圳  1180  False
1005   键盘   899   3  北京  2697   True

In [28]:
cond_loc = df.loc[df['是否包邮'] == True, ['商品名称', '单价']]
cond_loc

     商品名称    单价
订单ID
1001   手机  2999
1003   卫衣   199
1005   键盘   899

In [29]:
df

     商品名称    单价  数量  城市    总价   是否包邮
订单ID
1001   手机  2999   2  北京  5998   True
1002   耳机   399   5  上海  1995  False
1003   卫衣   199  10  广州  1990   True
1004   水杯    59  20  深圳  1180  False
1005   键盘   899   3  北京  2697   True

In [30]:
df.loc[(df['单价'] > 500) & (df['城市'] == '北京'), '折扣价'] = df['单价'] * 0.9
df

     商品名称    单价  数量  城市    总价   是否包邮     折扣价
订单ID
1001   手机  2999   2  北京  5998   True  2699.1
1002   耳机   399   5  上海  1995  False     NaN
1003   卫衣   199  10  广州  1990   True     NaN
1004   水杯    59  20  深圳  1180  False     NaN
1005   键盘   899   3  北京  2697   True   809.1

In [31]:
df

     商品名称    单价  数量  城市    总价   是否包邮     折扣价
订单ID
1001   手机  2999   2  北京  5998   True  2699.1
1002   耳机   399   5  上海  1995  False     NaN
1003   卫衣   199  10  广州  1990   True     NaN
1004   水杯    59  20  深圳  1180  False     NaN
1005   键盘   899   3  北京  2697   True   809.1

In [32]:
df.loc[1003, '数量'] = 15
df.loc[1003, '总价'] = df.loc[1003, '单价'] * df.loc[1003, '数量']

df

     商品名称    单价  数量  城市    总价   是否包邮     折扣价
订单ID
1001   手机  2999   2  北京  5998   True  2699.1
1002   耳机   399   5  上海  1995  False     NaN
1003   卫衣   199  15  广州  2985   True     NaN
1004   水杯    59  20  深圳  1180  False     NaN
1005   键盘   899   3  北京  2697   True   809.1

In [33]:
df

     商品名称    单价  数量  城市    总价   是否包邮     折扣价
订单ID
1001   手机  2999   2  北京  5998   True  2699.1
1002   耳机   399   5  上海  1995  False     NaN
1003   卫衣   199  15  广州  2985   True     NaN
1004   水杯    59  20  深圳  1180  False     NaN
1005   键盘   899   3  北京  2697   True   809.1

In [38]:
df_text_idx = df.reset_index().set_index('商品名称')
df_text_idx

      订单ID    单价  数量  城市    总价   是否包邮     折扣价
商品名称
手机    1001  2999   2  北京  5998   True  2699.1
耳机    1002   399   5  上海  1995  False     NaN
卫衣    1003   199  15  广州  2985   True     NaN
水杯    1004    59  20  深圳  1180  False     NaN
键盘    1005   899   3  北京  2697   True   809.1

In [39]:
val_text = df_text_idx.loc['耳机', '城市']
print(val_text)

上海