In [1]:
from hashlib import file_digest

import pandas as pd
import numpy as np
from Demos.security.set_file_audit import file_dacl

In [2]:
file_path = r'missing_fill.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [3]:
df_fill_all = df.fillna('未知')

df_fill_all

   订单ID 商品名称      单价    数量  城市      总价        下单时间
0  1001   手机  2999.0   2.0  北京      未知  2024-01-01
1  1002   耳机      未知   5.0  上海  1995.0          未知
2  1003   卫衣   199.0    未知  广州  1990.0  2024-01-02
3  1004   未知    59.0  20.0  深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  未知  2697.0  2024-01-03

In [4]:
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [5]:
fill_dict = {'商品名称': '未命名', '城市': '未知城市', '单价': 0, '数量': 1}

df_fill_spec = df.fillna(fill_dict)

df_fill_spec

   订单ID 商品名称      单价    数量    城市      总价        下单时间
0  1001   手机  2999.0   2.0    北京     NaN  2024-01-01
1  1002   耳机     0.0   5.0    上海  1995.0         NaN
2  1003   卫衣   199.0   1.0    广州  1990.0  2024-01-02
3  1004  未命名    59.0  20.0    深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  未知城市  2697.0  2024-01-03

In [6]:
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [7]:
df['单价'] = df['单价'].fillna(df['单价'].mean())
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机  1039.0   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [8]:
df['数量'] = df['数量'].fillna(df['数量'].median())
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机  1039.0   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   4.0   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [12]:
city_mode = df['城市'].mode()[0]
city_mode

'上海'

In [13]:
df['城市'].mode()

0    上海
1    北京
2    广州
3    深圳
Name: 城市, dtype: str

In [14]:
df['城市'] = df['城市'].fillna(city_mode)
df

   订单ID 商品名称      单价    数量  城市      总价        下单时间
0  1001   手机  2999.0   2.0  北京     NaN  2024-01-01
1  1002   耳机  1039.0   5.0  上海  1995.0         NaN
2  1003   卫衣   199.0   4.0  广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0  深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  上海  2697.0  2024-01-03

In [15]:
df

   订单ID 商品名称      单价    数量  城市      总价        下单时间
0  1001   手机  2999.0   2.0  北京     NaN  2024-01-01
1  1002   耳机  1039.0   5.0  上海  1995.0         NaN
2  1003   卫衣   199.0   4.0  广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0  深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  上海  2697.0  2024-01-03

In [16]:
df['总价'] = df['总价'].fillna(df['单价'] * df['数量'])
df

   订单ID 商品名称      单价    数量  城市      总价        下单时间
0  1001   手机  2999.0   2.0  北京  5998.0  2024-01-01
1  1002   耳机  1039.0   5.0  上海  1995.0         NaN
2  1003   卫衣   199.0   4.0  广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0  深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  上海  2697.0  2024-01-03