In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = r'missing_data.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [4]:
missing_flag = df.isnull()
missing_flag

    订单ID   商品名称     单价     数量     城市     总价   下单时间
0  False  False  False  False  False   True  False
1  False  False   True  False  False  False   True
2  False  False  False   True  False  False  False
3  False   True  False  False  False  False  False
4  False  False  False  False   True  False  False

In [5]:
missing_count = df.isnull().sum()
missing_count

订单ID    0
商品名称    1
单价      1
数量      1
城市      1
总价      1
下单时间    1
dtype: int64

In [6]:
missing_ratio = (df.isnull().sum() / len(df)) * 100
missing_ratio

订单ID     0.0
商品名称    20.0
单价      20.0
数量      20.0
城市      20.0
总价      20.0
下单时间    20.0
dtype: float64

In [7]:
missing_info = pd.DataFrame(
    {
        '缺失数量': missing_count,
        '缺失占比（%）': missing_ratio.round(2)
    }
)

missing_info

      缺失数量  缺失占比（%）
订单ID     0      0.0
商品名称     1     20.0
单价       1     20.0
数量       1     20.0
城市       1     20.0
总价       1     20.0
下单时间     1     20.0

In [8]:
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [9]:
missing_rows = df[df.isnull().any(axis=1)]
missing_rows

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03

In [10]:
missing_price_rows = df[df['单价'].isnull()]
missing_price_rows

   订单ID 商品名称  单价   数量  城市      总价 下单时间
1  1002   耳机 NaN  5.0  上海  1995.0  NaN

In [11]:
non_missing_count = df.notnull().sum()
non_missing_count

订单ID    5
商品名称    4
单价      4
数量      4
城市      4
总价      4
下单时间    4
dtype: int64