In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = r'missing_drop.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03
5  1006   鼠标    99.0   8.0   杭州   792.0  2024-01-03

In [3]:
print(len(df))

6

In [4]:
print(len(df.columns))

7

In [5]:
df_drop_row = df.dropna()
df_drop_row

   订单ID 商品名称    单价   数量  城市     总价        下单时间
5  1006   鼠标  99.0  8.0  杭州  792.0  2024-01-03

In [6]:
print(len(df_drop_row))

1

In [7]:
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03
5  1006   鼠标    99.0   8.0   杭州   792.0  2024-01-03

In [8]:
df_drop_spec_col = df.dropna(subset=['单价', '城市'])
df_drop_spec_col

   订单ID 商品名称      单价    数量  城市      总价        下单时间
0  1001   手机  2999.0   2.0  北京     NaN  2024-01-01
2  1003   卫衣   199.0   NaN  广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0  深圳  1180.0  2024-01-02
5  1006   鼠标    99.0   8.0  杭州   792.0  2024-01-03

In [9]:
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03
5  1006   鼠标    99.0   8.0   杭州   792.0  2024-01-03

In [14]:
df_drop_col = df.dropna(thresh=len(df) * 0.9, axis=1)
df_drop_col

   订单ID
0  1001
1  1002
2  1003
3  1004
4  1005
5  1006

In [15]:
df

   订单ID 商品名称      单价    数量   城市      总价        下单时间
0  1001   手机  2999.0   2.0   北京     NaN  2024-01-01
1  1002   耳机     NaN   5.0   上海  1995.0         NaN
2  1003   卫衣   199.0   NaN   广州  1990.0  2024-01-02
3  1004  NaN    59.0  20.0   深圳  1180.0  2024-01-02
4  1005   键盘   899.0   3.0  NaN  2697.0  2024-01-03
5  1006   鼠标    99.0   8.0   杭州   792.0  2024-01-03

In [16]:
missing_ratio = (df.isnull().sum() / len(df)) * 100
missing_ratio

订单ID     0.000000
商品名称    16.666667
单价      16.666667
数量      16.666667
城市      16.666667
总价      16.666667
下单时间    16.666667
dtype: float64

In [17]:
cols_keep = missing_ratio[missing_ratio < 20].index
cols_keep

Index(['订单ID', '商品名称', '单价', '数量', '城市', '总价', '下单时间'], dtype='str')

In [18]:
df_keep_col = df[cols_keep].dropna()
df_keep_col

   订单ID 商品名称    单价   数量  城市     总价        下单时间
5  1006   鼠标  99.0  8.0  杭州  792.0  2024-01-03