In [1]:
import pandas as pd

In [2]:
file_path = r'agg_basic.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [3]:
group_cat = df.groupby('品类')
group_cat

In [4]:
agg_sum = group_cat['总价'].sum()
agg_sum

品类
数码     21571
日用品     1465
服饰      3784
Name: 总价, dtype: int64

In [6]:
agg_mean = group_cat[['单价', '数量']].mean()
agg_mean.round(2)

          单价     数量
品类
数码   1115.67   4.83
日用品    39.00  17.50
服饰    249.00   8.00

In [7]:
agg_multi_func = group_cat['总价'].agg(['sum', 'mean', 'max'])
agg_multi_func

       sum         mean   max
品类
数码   21571  3595.166667  7996
日用品   1465   732.500000  1180
服饰    3784  1892.000000  1990

In [8]:
agg_rename = group_cat['总价'].agg(
    总价合计='sum',
    总价均值='mean',
    总价最大值='max'
).round(2)
agg_rename

      总价合计     总价均值  总价最大值
品类
数码   21571  3595.17   7996
日用品   1465   732.50   1180
服饰    3784  1892.00   1990

In [9]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [10]:
agg_col_func = group_cat.agg(
    单价最大值=('单价', 'max'),
    数量合计=('数量', 'sum'),
    总价均值=('总价', 'mean')
).round(2)

agg_col_func

     单价最大值  数量合计     总价均值
品类
数码    2999    29  3595.17
日用品     59    35   732.50
服饰     299    16  1892.00

In [11]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [12]:
group_multi = df.groupby(['大区', '品类'])
group_multi

In [13]:
agg_multi_group = group_multi['总价'].sum()
agg_multi_group

大区  品类
华东  数码      4880
华北  数码     16691
华南  日用品     1465
    服饰      3784
Name: 总价, dtype: int64

In [14]:
agg_reset = agg_sum.reset_index()
agg_reset

    品类     总价
0   数码  21571
1  日用品   1465
2   服饰   3784

In [15]:
group_cat

In [16]:
agg_common = group_cat['总价'].agg(
    ['count',
     'sum',
     'mean',
     'median',
     'min',
     'max']
).round(2)

agg_common

     count    sum     mean  median   min   max
品类
数码       6  21571  3595.17  2395.0   792  7996
日用品      2   1465   732.50   732.5   285  1180
服饰       2   3784  1892.00  1892.0  1794  1990