In [1]:
import pandas as pd

In [2]:
file_path = r'agg_rename.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [3]:
group_cat = df.groupby('品类')
group_cat

In [4]:
agg_rename1 = group_cat['总价'].agg(品类总价合计='sum')
agg_rename1

     品类总价合计
品类
数码    21571
日用品    1465
服饰     3784

In [5]:
agg_rename2 = group_cat['总价'].sum().rename('品类总价求和')
agg_rename2

品类
数码     21571
日用品     1465
服饰      3784
Name: 品类总价求和, dtype: int64

In [6]:
agg_rename_multi = group_cat['总价'].agg(
    总价合计='sum',
    总价均值='mean',
    总价最大值='max',
    总价最小值='min'
).round(2)

agg_rename_multi

      总价合计     总价均值  总价最大值  总价最小值
品类
数码   21571  3595.17   7996    792
日用品   1465   732.50   1180    285
服饰    3784  1892.00   1990   1794

In [7]:
agg_col_rename = group_cat.agg(
    单价最高值 = ('单价', 'max'),
    数量总计 = ('数量', 'sum'),
    总价中位数 = ('总价', 'median')
).round(2)

agg_col_rename

     单价最高值  数量总计   总价中位数
品类
数码    2999    29  2395.0
日用品     59    35   732.5
服饰     299    16  1892.0

In [8]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [9]:
group_multi = df.groupby(['大区', '品类'])
group_multi

In [10]:
agg_multi_rename = group_multi['总价'].agg(大区品类总价合计 = 'sum').reset_index()
agg_multi_rename

   大区   品类  大区品类总价合计
0  华东   数码      4880
1  华北   数码     16691
2  华南  日用品      1465
3  华南   服饰      3784

In [14]:
agg_temp = group_cat[['单价', '数量', '总价']].agg(['sum', 'mean'])
agg_temp

       单价               数量                总价
      sum         mean sum       mean    sum         mean
品类
数码   6694  1115.666667  29   4.833333  21571  3595.166667
日用品    78    39.000000  35  17.500000   1465   732.500000
服饰    498   249.000000  16   8.000000   3784  1892.000000

In [18]:
agg_batch_flat = agg_temp.copy()
agg_batch_flat.columns = ['_'.join(col) for col in agg_batch_flat.columns]

# 再重命名
agg_batch_rename = agg_batch_flat.rename(columns={
    '单价_sum': '单价总价',
    '单价_mean': '单价均值',
    '数量_sum': '数量总和',
    '数量_mean': '数量均值',
    '总价_sum': '总价总和',
    '总价_mean': '总价均值'
}).round(2)

agg_batch_rename

     单价总价     单价均值  数量总和   数量均值   总价总和     总价均值
品类
数码   6694  1115.67    29   4.83  21571  3595.17
日用品    78    39.00    35  17.50   1465   732.50
服饰    498   249.00    16   8.00   3784  1892.00

In [19]:
agg_batch_rename = agg_temp.rename(
    columns={
        ('单价', 'sum'): '单价总和',
        ('单价', 'mean'): '单价均值',
        ('数量', 'sum'): '数量总和',
        ('数量', 'mean'): '数量均值',
        ('总价', 'sum'): '总价总和',
        ('总价', 'mean'): '总价均值'}
).round(2)
agg_batch_rename

       单价           数量            总价
      sum     mean sum   mean    sum     mean
品类
数码   6694  1115.67  29   4.83  21571  3595.17
日用品    78    39.00  35  17.50   1465   732.50
服饰    498   249.00  16   8.00   3784  1892.00

In [20]:
agg_temp.columns

MultiIndex([('单价',  'sum'),
            ('单价', 'mean'),
            ('数量',  'sum'),
            ('数量', 'mean'),
            ('总价',  'sum'),
            ('总价', 'mean')],
           )

In [21]:
agg_rename_multi

      总价合计     总价均值  总价最大值  总价最小值
品类
数码   21571  3595.17   7996    792
日用品   1465   732.50   1180    285
服饰    3784  1892.00   1990   1794

In [22]:
agg_filter = agg_rename_multi[agg_rename_multi['总价合计'] > 2000]
agg_filter

     总价合计     总价均值  总价最大值  总价最小值
品类
数码  21571  3595.17   7996    792
服饰   3784  1892.00   1990   1794