In [1]:
import pandas as pd

In [2]:
file_path = r'sample_data.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True
5  1006   鼠标    99   8  上海   792  False
6  1007   裤子   299   6  广州  1794   True
7  1008   毛巾    19  15  深圳   285  False
8  1009   平板  1999   4  北京  7996   True
9  1010   音箱   299   7  上海  2093  False

In [11]:
sample_n = df.sample(n=3)
sample_n

   订单ID 商品名称   单价  数量  城市    总价  是否包邮
2  1003   卫衣  199  10  广州  1990  True
4  1005   键盘  899   3  北京  2697  True
6  1007   裤子  299   6  广州  1794  True

In [12]:
sample_frac = df.sample(frac=0.3)
sample_frac

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
1  1002   耳机   399   5  上海  1995  False
8  1009   平板  1999   4  北京  7996   True
4  1005   键盘   899   3  北京  2697   True

In [16]:
sample_fixed = df.sample(n=4, random_state=123)
sample_fixed

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
4  1005   键盘   899   3  北京  2697   True
0  1001   手机  2999   2  北京  5998   True
7  1008   毛巾    19  15  深圳   285  False
5  1006   鼠标    99   8  上海   792  False

In [20]:
sample_replace = df.sample(n=5, replace=True, random_state=456)
sample_replace

   订单ID 商品名称   单价  数量  城市    总价   是否包邮
5  1006   鼠标   99   8  上海   792  False
9  1010   音箱  299   7  上海  2093  False
4  1005   键盘  899   3  北京  2697   True
5  1006   鼠标   99   8  上海   792  False
7  1008   毛巾   19  15  深圳   285  False

In [24]:
sample_replace = df.sample(n=5, replace=True)
sample_replace

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
2  1003   卫衣   199  10  广州  1990   True
1  1002   耳机   399   5  上海  1995  False
9  1010   音箱   299   7  上海  2093  False
0  1001   手机  2999   2  北京  5998   True
2  1003   卫衣   199  10  广州  1990   True

In [25]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True
5  1006   鼠标    99   8  上海   792  False
6  1007   裤子   299   6  广州  1794   True
7  1008   毛巾    19  15  深圳   285  False
8  1009   平板  1999   4  北京  7996   True
9  1010   音箱   299   7  上海  2093  False

In [29]:
sample_stratified = df.groupby('城市').apply(lambda x: x.sample(n=1, random_state=789))
sample_stratified

      订单ID 商品名称   单价  数量    总价   是否包邮
城市
上海 5  1006   鼠标   99   8   792  False
北京 4  1005   键盘  899   3  2697   True
广州 2  1003   卫衣  199  10  1990   True
深圳 3  1004   水杯   59  20  1180  False

In [31]:
sample_reset = df.sample(n=3, random_state=100)
sample_reset

   订单ID 商品名称   单价  数量  城市    总价   是否包邮
7  1008   毛巾   19  15  深圳   285  False
6  1007   裤子  299   6  广州  1794   True
1  1002   耳机  399   5  上海  1995  False

In [32]:
sample_reset = df.sample(n=3, random_state=100).reset_index(drop=True)
sample_reset

   订单ID 商品名称   单价  数量  城市    总价   是否包邮
0  1008   毛巾   19  15  深圳   285  False
1  1007   裤子  299   6  广州  1794   True
2  1002   耳机  399   5  上海  1995  False

In [33]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮
0  1001   手机  2999   2  北京  5998   True
1  1002   耳机   399   5  上海  1995  False
2  1003   卫衣   199  10  广州  1990   True
3  1004   水杯    59  20  深圳  1180  False
4  1005   键盘   899   3  北京  2697   True
5  1006   鼠标    99   8  上海   792  False
6  1007   裤子   299   6  广州  1794   True
7  1008   毛巾    19  15  深圳   285  False
8  1009   平板  1999   4  北京  7996   True
9  1010   音箱   299   7  上海  2093  False

In [48]:
sample_weight = df.sample(n = 2, weights='单价')
sample_weight

   订单ID 商品名称    单价  数量  城市    总价  是否包邮
8  1009   平板  1999   4  北京  7996  True
0  1001   手机  2999   2  北京  5998  True