In [1]:
import pandas as pd

In [2]:
file_path = r'stratified_sample.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

    订单ID 商品名称    单价  数量  城市   品类   是否包邮
0   1001   手机  2999   2  北京   数码   True
1   1002   耳机   399   5  上海   数码  False
2   1003   卫衣   199  10  广州   服饰   True
3   1004   水杯    59  20  深圳  日用品  False
4   1005   键盘   899   3  北京   数码   True
5   1006   鼠标    99   8  上海   数码  False
6   1007   裤子   299   6  广州   服饰   True
7   1008   毛巾    19  15  深圳  日用品  False
8   1009   平板  1999   4  北京   数码   True
9   1010   音箱   299   7  上海   数码  False
10  1011   帽子    59  12  广州   服饰  False
11  1012   牙刷     9  30  深圳  日用品   True

In [3]:
print(df['城市'].value_counts())

城市
北京    3
上海    3
广州    3
深圳    3
Name: count, dtype: int64

In [4]:
print(df['品类'].value_counts())

品类
数码     6
服饰     3
日用品    3
Name: count, dtype: int64

In [6]:
df

    订单ID 商品名称    单价  数量  城市   品类   是否包邮
0   1001   手机  2999   2  北京   数码   True
1   1002   耳机   399   5  上海   数码  False
2   1003   卫衣   199  10  广州   服饰   True
3   1004   水杯    59  20  深圳  日用品  False
4   1005   键盘   899   3  北京   数码   True
5   1006   鼠标    99   8  上海   数码  False
6   1007   裤子   299   6  广州   服饰   True
7   1008   毛巾    19  15  深圳  日用品  False
8   1009   平板  1999   4  北京   数码   True
9   1010   音箱   299   7  上海   数码  False
10  1011   帽子    59  12  广州   服饰  False
11  1012   牙刷     9  30  深圳  日用品   True

In [8]:
strat1 = df.groupby('城市').apply(lambda x: x.sample(n=1))
strat1

      订单ID 商品名称   单价  数量   品类   是否包邮
城市
上海 5  1006   鼠标   99   8   数码  False
北京 4  1005   键盘  899   3   数码   True
广州 2  1003   卫衣  199  10   服饰   True
深圳 3  1004   水杯   59  20  日用品  False

In [11]:
strat2 = df.groupby('品类').apply(lambda x: x.sample(n=2))
strat2

        订单ID 商品名称    单价  数量  城市   是否包邮
品类
数码  8   1009   平板  1999   4  北京   True
    5   1006   鼠标    99   8  上海  False
日用品 7   1008   毛巾    19  15  深圳  False
    3   1004   水杯    59  20  深圳  False
服饰  10  1011   帽子    59  12  广州  False
    2   1003   卫衣   199  10  广州   True

In [14]:
strat_frac = df.groupby('城市').apply(lambda x: x.sample(frac=0.3))
strat_frac

       订单ID 商品名称   单价  数量   品类   是否包邮
城市
上海 9   1010   音箱  299   7   数码  False
北京 4   1005   键盘  899   3   数码   True
广州 10  1011   帽子   59  12   服饰  False
深圳 7   1008   毛巾   19  15  日用品  False

In [15]:
df

    订单ID 商品名称    单价  数量  城市   品类   是否包邮
0   1001   手机  2999   2  北京   数码   True
1   1002   耳机   399   5  上海   数码  False
2   1003   卫衣   199  10  广州   服饰   True
3   1004   水杯    59  20  深圳  日用品  False
4   1005   键盘   899   3  北京   数码   True
5   1006   鼠标    99   8  上海   数码  False
6   1007   裤子   299   6  广州   服饰   True
7   1008   毛巾    19  15  深圳  日用品  False
8   1009   平板  1999   4  北京   数码   True
9   1010   音箱   299   7  上海   数码  False
10  1011   帽子    59  12  广州   服饰  False
11  1012   牙刷     9  30  深圳  日用品   True

In [19]:
strat_multi = df.groupby(['城市', '品类']).apply(lambda x: x.sample(n=1) if len(x) >= 1 else x)
strat_multi

          订单ID 商品名称    单价  数量   是否包邮
城市 品类
上海 数码  9  1010   音箱   299   7  False
北京 数码  0  1001   手机  2999   2   True
广州 服饰  2  1003   卫衣   199  10   True
深圳 日用品 3  1004   水杯    59  20  False

In [26]:
strat_replace = df.groupby('品类').apply(lambda x: x.sample(n=3, replace=True))
strat_replace

        订单ID 商品名称    单价  数量  城市   是否包邮
品类
数码  4   1005   键盘   899   3  北京   True
    5   1006   鼠标    99   8  上海  False
    8   1009   平板  1999   4  北京   True
日用品 11  1012   牙刷     9  30  深圳   True
    3   1004   水杯    59  20  深圳  False
    11  1012   牙刷     9  30  深圳   True
服饰  10  1011   帽子    59  12  广州  False
    2   1003   卫衣   199  10  广州   True
    2   1003   卫衣   199  10  广州   True

In [27]:
strat2

        订单ID 商品名称    单价  数量  城市   是否包邮
品类
数码  8   1009   平板  1999   4  北京   True
    5   1006   鼠标    99   8  上海  False
日用品 7   1008   毛巾    19  15  深圳  False
    3   1004   水杯    59  20  深圳  False
服饰  10  1011   帽子    59  12  广州  False
    2   1003   卫衣   199  10  广州   True

In [32]:
strat2 = strat2.reset_index()

strat2

   index  订单ID 商品名称    单价  数量  城市   是否包邮
0      0  1009   平板  1999   4  北京   True
1      1  1006   鼠标    99   8  上海  False
2      2  1008   毛巾    19  15  深圳  False
3      3  1004   水杯    59  20  深圳  False
4      4  1011   帽子    59  12  广州  False
5      5  1003   卫衣   199  10  广州   True

In [34]:
strat2 = df.groupby('品类').apply(lambda x: x.sample(n=2)).reset_index()
strat2

    品类  level_1  订单ID 商品名称   单价  数量  城市   是否包邮
0   数码        5  1006   鼠标   99   8  上海  False
1   数码        1  1002   耳机  399   5  上海  False
2  日用品        3  1004   水杯   59  20  深圳  False
3  日用品        7  1008   毛巾   19  15  深圳  False
4   服饰       10  1011   帽子   59  12  广州  False
5   服饰        6  1007   裤子  299   6  广州   True

In [35]:
strat_check = strat2['品类'].value_counts()
strat_check

品类
数码     2
日用品    2
服饰     2
Name: count, dtype: int64