In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = r'random_seed.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1007   裤子   299   6  广州  1794
7  1008   毛巾    19  15  深圳   285

In [3]:
print(len(df))

8

In [4]:
sample_no_seed1 = df.sample(n=3)
sample_no_seed2 = df.sample(n=3)

In [5]:
sample_no_seed1

   订单ID 商品名称   单价  数量  城市    总价
5  1006   鼠标   99   8  上海   792
6  1007   裤子  299   6  广州  1794
3  1004   水杯   59  20  深圳  1180

In [6]:
sample_no_seed2

   订单ID 商品名称    单价  数量  城市    总价
2  1003   卫衣   199  10  广州  1990
1  1002   耳机   399   5  上海  1995
0  1001   手机  2999   2  北京  5998

In [7]:
sample_fixed1 = df.sample(n=3, random_state=123)
sample_fixed2 = df.sample(n=3, random_state=123)

In [8]:
sample_fixed1

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
3  1004   水杯    59  20  深圳  1180

In [10]:
sample_fixed2

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
3  1004   水杯    59  20  深圳  1180

In [14]:
np.random.seed(456)
sample_global1 = df.sample(n=3)
np.random.seed(456)
sample_global2 = df.sample(n=3)

In [15]:
sample_global1

   订单ID 商品名称    单价  数量  城市    总价
4  1005   键盘   899   3  北京  2697
6  1007   裤子   299   6  广州  1794
0  1001   手机  2999   2  北京  5998

In [16]:
sample_global2

   订单ID 商品名称    单价  数量  城市    总价
4  1005   键盘   899   3  北京  2697
6  1007   裤子   299   6  广州  1794
0  1001   手机  2999   2  北京  5998

In [18]:
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1007   裤子   299   6  广州  1794
7  1008   毛巾    19  15  深圳   285

In [17]:
def stratified_sample(df, group_col, n, seed):
    np.random.seed(seed)
    return df.groupby(group_col).apply(lambda x: x.sample(n=n)).reset_index(drop=True)

sample_strat1 = stratified_sample(df, '城市', 1, 789)
sample_strat1

   订单ID 商品名称   单价  数量    总价
0  1002   耳机  399   5  1995
1  1005   键盘  899   3  2697
2  1007   裤子  299   6  1794
3  1008   毛巾   19  15   285

In [19]:
sample_strat2 = stratified_sample(df, '城市', 1, 789)
sample_strat2

   订单ID 商品名称   单价  数量    总价
0  1002   耳机  399   5  1995
1  1005   键盘  899   3  2697
2  1007   裤子  299   6  1794
3  1008   毛巾   19  15   285

In [20]:
np.random.seed(100)
sample_a = df.sample(n = 2)
sample_b = df[df['单价'] > 200].sample(n = 1)

In [21]:
sample_a

   订单ID 商品名称   单价  数量  城市    总价
1  1002   耳机  399   5  上海  1995
4  1005   键盘  899   3  北京  2697

In [22]:
sample_b

   订单ID 商品名称   单价  数量  城市    总价
6  1007   裤子  299   6  广州  1794

In [23]:
np.random.seed(100)
sample_a2 = df.sample(n = 2)
sample_b2 = df[df['单价'] > 200].sample(n = 1)

In [24]:
sample_a2

   订单ID 商品名称   单价  数量  城市    总价
1  1002   耳机  399   5  上海  1995
4  1005   键盘  899   3  北京  2697

In [25]:
sample_b2

   订单ID 商品名称   单价  数量  城市    总价
6  1007   裤子  299   6  广州  1794

In [26]:
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1007   裤子   299   6  广州  1794
7  1008   毛巾    19  15  深圳   285

In [27]:
sample_seed101 = df.sample(n = 3, random_state=101)
sample_seed102 = df.sample(n = 3, random_state=102)

In [28]:
sample_seed101

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
2  1003   卫衣   199  10  广州  1990
5  1006   鼠标    99   8  上海   792

In [29]:
sample_seed102

   订单ID 商品名称   单价  数量  城市    总价
7  1008   毛巾   19  15  深圳   285
1  1002   耳机  399   5  上海  1995
4  1005   键盘  899   3  北京  2697