In [53]:
import numpy as np
import pandas as pd

In [54]:
main_path = r'main_data.csv'
fill_path = r'fill_data.csv'

df_main = pd.read_csv(main_path, encoding='utf-8')
df_fill = pd.read_csv(fill_path, encoding='utf-8')

df_main

   用户ID  姓名    年龄   城市           手机号
0   101  张三  25.0   北京  1.380014e+10
1   102  李四   NaN   上海           NaN
2   103  王五  31.0  NaN  1.390014e+10
3   104  赵六  28.0   广州           NaN
4   105  钱七   NaN   深圳  1.370014e+10

In [55]:
df_fill

   用户ID    年龄  城市          手机号
0   102    27  上海  13600136000
1   103  1000  杭州  13900139000
2   104    28  广州  13500135000
3   105    32  深圳  13700137000
4   106    40  成都  13400134000

In [56]:
df_main = df_main.set_index('用户ID')
df_main

      姓名    年龄   城市           手机号
用户ID
101   张三  25.0   北京  1.380014e+10
102   李四   NaN   上海           NaN
103   王五  31.0  NaN  1.390014e+10
104   赵六  28.0   广州           NaN
105   钱七   NaN   深圳  1.370014e+10

In [57]:
df_fill = df_fill.set_index('用户ID')
df_fill

        年龄  城市          手机号
用户ID
102     27  上海  13600136000
103   1000  杭州  13900139000
104     28  广州  13500135000
105     32  深圳  13700137000
106     40  成都  13400134000

In [58]:
df_combined = df_main.combine_first(df_fill)

df_combined

       姓名    年龄  城市           手机号
用户ID
101    张三  25.0  北京  1.380014e+10
102    李四  27.0  上海  1.360014e+10
103    王五  31.0  杭州  1.390014e+10
104    赵六  28.0  广州  1.350014e+10
105    钱七  32.0  深圳  1.370014e+10
106   NaN  40.0  成都  1.340013e+10

In [59]:
df_main.columns

Index(['姓名', '年龄', '城市', '手机号'], dtype='str')

In [60]:
df_combined.columns

Index(['姓名', '年龄', '城市', '手机号'], dtype='str')

In [61]:
df_combined_reset = df_combined.reset_index()
df_combined_reset

   用户ID   姓名    年龄  城市           手机号
0   101   张三  25.0  北京  1.380014e+10
1   102   李四  27.0  上海  1.360014e+10
2   103   王五  31.0  杭州  1.390014e+10
3   104   赵六  28.0  广州  1.350014e+10
4   105   钱七  32.0  深圳  1.370014e+10
5   106  NaN  40.0  成都  1.340013e+10

In [62]:
df_main

      姓名    年龄   城市           手机号
用户ID
101   张三  25.0   北京  1.380014e+10
102   李四   NaN   上海           NaN
103   王五  31.0  NaN  1.390014e+10
104   赵六  28.0   广州           NaN
105   钱七   NaN   深圳  1.370014e+10

In [63]:
df_fill

        年龄  城市          手机号
用户ID
102     27  上海  13600136000
103   1000  杭州  13900139000
104     28  广州  13500135000
105     32  深圳  13700137000
106     40  成都  13400134000

In [64]:
df_combined

       姓名    年龄  城市           手机号
用户ID
101    张三  25.0  北京  1.380014e+10
102    李四  27.0  上海  1.360014e+10
103    王五  31.0  杭州  1.390014e+10
104    赵六  28.0  广州  1.350014e+10
105    钱七  32.0  深圳  1.370014e+10
106   NaN  40.0  成都  1.340013e+10