In [30]:
import pandas as pd

sales_data = {
    'product_name': ['手机', '耳机', '卫衣', '水杯'],
    'sales_num': [50, 80, 120, 200],
    'sale_date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'city': ['北京', '上海', '广州', '深圳']
}

print(sales_data)

{'product_name': ['手机', '耳机', '卫衣', '水杯'], 'sales_num': [50, 80, 120, 200], 'sale_date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'], 'city': ['北京', '上海', '广州', '深圳']}

In [31]:
sales_df = pd.DataFrame(sales_data)
sales_df

  product_name  sales_num   sale_date city
0           手机         50  2024-01-01   北京
1           耳机         80  2024-01-01   上海
2           卫衣        120  2024-01-02   广州
3           水杯        200  2024-01-02   深圳

In [32]:
from sqlalchemy import create_engine, INTEGER

In [33]:
engine = create_engine('sqlite:///sales')
print(engine.name)

sqlite

In [34]:
print(engine.engine)

Engine(sqlite:///sales)

In [35]:
sales_df.to_sql(
    name='sales',
    con=engine,
    if_exists='append',
    index=False,
    dtype={'sales_num': INTEGER}
)

4

In [36]:
df_read_all = pd.read_sql('sales', con=engine)
df_read_all

   id product_name  sales_num  sale_date city
0   1           手机         50 2024-01-01   北京
1   2           耳机         80 2024-01-01   上海
2   3           卫衣        120 2024-01-02   广州
3   4           水杯        200 2024-01-02   深圳

In [37]:
sql_query = "select product_name, sales_num, city from sales where sales_num > 60"
df_read_query = pd.read_sql(sql_query, con=engine)
df_read_query

  product_name  sales_num city
0           耳机         80   上海
1           卫衣        120   广州
2           水杯        200   深圳

In [38]:
engine.dispose()