In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
mysql_engine = create_engine('mysql+pymysql://root:123456abc@gz-cdb-ekasbukn.sql.tencentcdb.com:29432/pandas_test')

In [3]:
df_mysql = pd.read_sql('user_info', mysql_engine)
df_mysql

   id name  age city   salary
0   1   张三   25   北京   8000.0
1   2   李四   30   上海  10000.0
2   3   王五   28   广州      NaN
3   4   赵六   35   深圳  15000.0

In [4]:
df_mysql_query = pd.read_sql("select name, city, salary from user_info where age > 25", con=mysql_engine)

print(df_mysql_query)

  name city   salary
0   李四   上海  10000.0
1   王五   广州      NaN
2   赵六   深圳  15000.0

In [5]:
df_mysql_query

  name city   salary
0   李四   上海  10000.0
1   王五   广州      NaN
2   赵六   深圳  15000.0

In [6]:
sqlite_engine = create_engine('sqlite:///:memory:')

In [7]:
test_df = pd.DataFrame(
    {
        'name': ['张三', '李四', '王五'],
        'age': [25, 30, 28],
        'city': ['北京', '上海', '广州']
    }
)
test_df

  name  age city
0   张三   25   北京
1   李四   30   上海
2   王五   28   广州

In [8]:
test_df.to_sql('user_info', con=sqlite_engine, index=False)

3

In [9]:
df_sqlite = pd.read_sql('user_info', con=sqlite_engine)
df_sqlite

  name  age city
0   张三   25   北京
1   李四   30   上海
2   王五   28   广州

In [10]:
mysql_engine.dispose()
sqlite_engine.dispose()

In [12]:
sqlite_engine2 = create_engine('sqlite:///user_info')
df_sqlite = pd.read_sql('user_info', con=sqlite_engine2)

df_sqlite

   id name  age city   salary
0   1   张三   25   北京   8000.0
1   2   李四   30   上海  10000.0
2   3   王五   28   广州      NaN
3   4   赵六   35   深圳  15000.0