In [21]:
import pandas as pd

In [22]:
file_path = r'rank_basic.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   商品ID 商品名称    单价   销量     总价  城市
0   101   手机  2999   20  59980  北京
1   102   耳机   399   50  19950  上海
2   103   卫衣   199   80  15920  广州
3   104   水杯    59  100   5900  深圳
4   105   键盘   899   30  26970  北京
5   106   鼠标    99   60   5940  上海
6   107   裤子   299   70  20930  广州
7   108   毛巾    19  120   2280  深圳
8   109   平板  1999   25  49975  北京
9   110   音箱   299   40  11960  上海

In [23]:
df['销量排名'] = df['销量'].rank(ascending=False)

df

   商品ID 商品名称    单价   销量     总价  城市  销量排名
0   101   手机  2999   20  59980  北京  10.0
1   102   耳机   399   50  19950  上海   6.0
2   103   卫衣   199   80  15920  广州   3.0
3   104   水杯    59  100   5900  深圳   2.0
4   105   键盘   899   30  26970  北京   8.0
5   106   鼠标    99   60   5940  上海   5.0
6   107   裤子   299   70  20930  广州   4.0
7   108   毛巾    19  120   2280  深圳   1.0
8   109   平板  1999   25  49975  北京   9.0
9   110   音箱   299   40  11960  上海   7.0

In [24]:
df['总价排名'] = df['总价'].rank(ascending=True)

df

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名
0   101   手机  2999   20  59980  北京  10.0  10.0
1   102   耳机   399   50  19950  上海   6.0   6.0
2   103   卫衣   199   80  15920  广州   3.0   5.0
3   104   水杯    59  100   5900  深圳   2.0   2.0
4   105   键盘   899   30  26970  北京   8.0   8.0
5   106   鼠标    99   60   5940  上海   5.0   3.0
6   107   裤子   299   70  20930  广州   4.0   7.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0
8   109   平板  1999   25  49975  北京   9.0   9.0
9   110   音箱   299   40  11960  上海   7.0   4.0

In [25]:
df_dup = df.copy()

df_dup

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名
0   101   手机  2999   20  59980  北京  10.0  10.0
1   102   耳机   399   50  19950  上海   6.0   6.0
2   103   卫衣   199   80  15920  广州   3.0   5.0
3   104   水杯    59  100   5900  深圳   2.0   2.0
4   105   键盘   899   30  26970  北京   8.0   8.0
5   106   鼠标    99   60   5940  上海   5.0   3.0
6   107   裤子   299   70  20930  广州   4.0   7.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0
8   109   平板  1999   25  49975  北京   9.0   9.0
9   110   音箱   299   40  11960  上海   7.0   4.0

In [26]:
df_dup['单价排名_平均'] = df_dup['单价'].rank(ascending=False, method='average')

df_dup

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  单价排名_平均
0   101   手机  2999   20  59980  北京  10.0  10.0      1.0
1   102   耳机   399   50  19950  上海   6.0   6.0      4.0
2   103   卫衣   199   80  15920  广州   3.0   5.0      7.0
3   104   水杯    59  100   5900  深圳   2.0   2.0      9.0
4   105   键盘   899   30  26970  北京   8.0   8.0      3.0
5   106   鼠标    99   60   5940  上海   5.0   3.0      8.0
6   107   裤子   299   70  20930  广州   4.0   7.0      5.5
7   108   毛巾    19  120   2280  深圳   1.0   1.0     10.0
8   109   平板  1999   25  49975  北京   9.0   9.0      2.0
9   110   音箱   299   40  11960  上海   7.0   4.0      5.5

In [27]:
df_dup['单价排名_最小'] = df_dup['单价'].rank(ascending=False, method='min')

df_dup

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  单价排名_平均  单价排名_最小
0   101   手机  2999   20  59980  北京  10.0  10.0      1.0      1.0
1   102   耳机   399   50  19950  上海   6.0   6.0      4.0      4.0
2   103   卫衣   199   80  15920  广州   3.0   5.0      7.0      7.0
3   104   水杯    59  100   5900  深圳   2.0   2.0      9.0      9.0
4   105   键盘   899   30  26970  北京   8.0   8.0      3.0      3.0
5   106   鼠标    99   60   5940  上海   5.0   3.0      8.0      8.0
6   107   裤子   299   70  20930  广州   4.0   7.0      5.5      5.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0     10.0     10.0
8   109   平板  1999   25  49975  北京   9.0   9.0      2.0      2.0
9   110   音箱   299   40  11960  上海   7.0   4.0      5.5      5.0

In [28]:
df_dup['单价排名_最大'] = df_dup['单价'].rank(ascending=False, method='max')

df_dup

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  单价排名_平均  单价排名_最小  单价排名_最大
0   101   手机  2999   20  59980  北京  10.0  10.0      1.0      1.0      1.0
1   102   耳机   399   50  19950  上海   6.0   6.0      4.0      4.0      4.0
2   103   卫衣   199   80  15920  广州   3.0   5.0      7.0      7.0      7.0
3   104   水杯    59  100   5900  深圳   2.0   2.0      9.0      9.0      9.0
4   105   键盘   899   30  26970  北京   8.0   8.0      3.0      3.0      3.0
5   106   鼠标    99   60   5940  上海   5.0   3.0      8.0      8.0      8.0
6   107   裤子   299   70  20930  广州   4.0   7.0      5.5      5.0      6.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0     10.0     10.0     10.0
8   109   平板  1999   25  49975  北京   9.0   9.0      2.0      2.0      2.0
9   110   音箱   299   40  11960  上海   7.0   4.0      5.5      5.0      6.0

In [29]:
df_dup['单价排名_连续'] = df_dup['单价'].rank(ascending=False, method='dense')

df_dup

,商品ID,商品名称,单价,销量,总价,城市,销量排名,总价排名,单价排名_平均,单价排名_最小,单价排名_最大,单价排名_连续
0,101,手机,2999,20,59980,北京,10.0,10.0,1.0,1.0,1.0,1.0
1,102,耳机,399,50,19950,上海,6.0,6.0,4.0,4.0,4.0,4.0
2,103,卫衣,199,80,15920,广州,3.0,5.0,7.0,7.0,7.0,6.0
3,104,水杯,59,100,5900,深圳,2.0,2.0,9.0,9.0,9.0,8.0
4,105,键盘,899,30,26970,北京,8.0,8.0,3.0,3.0,3.0,3.0
5,106,鼠标,99,60,5940,上海,5.0,3.0,8.0,8.0,8.0,7.0
6,107,裤子,299,70,20930,广州,4.0,7.0,5.5,5.0,6.0,5.0
7,108,毛巾,19,120,2280,深圳,1.0,1.0,10.0,10.0,10.0,9.0
8,109,平板,1999,25,49975,北京,9.0,9.0,2.0,2.0,2.0,2.0
9,110,音箱,299,40,11960,上海,7.0,4.0,5.5,5.0,6.0,5.0

In [30]:
df

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名
0   101   手机  2999   20  59980  北京  10.0  10.0
1   102   耳机   399   50  19950  上海   6.0   6.0
2   103   卫衣   199   80  15920  广州   3.0   5.0
3   104   水杯    59  100   5900  深圳   2.0   2.0
4   105   键盘   899   30  26970  北京   8.0   8.0
5   106   鼠标    99   60   5940  上海   5.0   3.0
6   107   裤子   299   70  20930  广州   4.0   7.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0
8   109   平板  1999   25  49975  北京   9.0   9.0
9   110   音箱   299   40  11960  上海   7.0   4.0

In [31]:
df['销量排名_int'] = df['销量排名'].astype(int)
df

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  销量排名_int
0   101   手机  2999   20  59980  北京  10.0  10.0        10
1   102   耳机   399   50  19950  上海   6.0   6.0         6
2   103   卫衣   199   80  15920  广州   3.0   5.0         3
3   104   水杯    59  100   5900  深圳   2.0   2.0         2
4   105   键盘   899   30  26970  北京   8.0   8.0         8
5   106   鼠标    99   60   5940  上海   5.0   3.0         5
6   107   裤子   299   70  20930  广州   4.0   7.0         4
7   108   毛巾    19  120   2280  深圳   1.0   1.0         1
8   109   平板  1999   25  49975  北京   9.0   9.0         9
9   110   音箱   299   40  11960  上海   7.0   4.0         7

In [32]:
top3_sales = df[df['销量排名_int'] <= 3]
top3_sales

   商品ID 商品名称   单价   销量     总价  城市  销量排名  总价排名  销量排名_int
2   103   卫衣  199   80  15920  广州   3.0   5.0         3
3   104   水杯   59  100   5900  深圳   2.0   2.0         2
7   108   毛巾   19  120   2280  深圳   1.0   1.0         1

In [33]:
df

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  销量排名_int
0   101   手机  2999   20  59980  北京  10.0  10.0        10
1   102   耳机   399   50  19950  上海   6.0   6.0         6
2   103   卫衣   199   80  15920  广州   3.0   5.0         3
3   104   水杯    59  100   5900  深圳   2.0   2.0         2
4   105   键盘   899   30  26970  北京   8.0   8.0         8
5   106   鼠标    99   60   5940  上海   5.0   3.0         5
6   107   裤子   299   70  20930  广州   4.0   7.0         4
7   108   毛巾    19  120   2280  深圳   1.0   1.0         1
8   109   平板  1999   25  49975  北京   9.0   9.0         9
9   110   音箱   299   40  11960  上海   7.0   4.0         7

In [34]:
df['城市内总价排名'] = df.groupby('城市')['总价'].rank(ascending=False, method='min')

df

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名
0   101   手机  2999   20  59980  北京  10.0  10.0        10      1.0
1   102   耳机   399   50  19950  上海   6.0   6.0         6      1.0
2   103   卫衣   199   80  15920  广州   3.0   5.0         3      2.0
3   104   水杯    59  100   5900  深圳   2.0   2.0         2      1.0
4   105   键盘   899   30  26970  北京   8.0   8.0         8      3.0
5   106   鼠标    99   60   5940  上海   5.0   3.0         5      3.0
6   107   裤子   299   70  20930  广州   4.0   7.0         4      1.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0         1      2.0
8   109   平板  1999   25  49975  北京   9.0   9.0         9      2.0
9   110   音箱   299   40  11960  上海   7.0   4.0         7      2.0

In [35]:
df

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名
0   101   手机  2999   20  59980  北京  10.0  10.0        10      1.0
1   102   耳机   399   50  19950  上海   6.0   6.0         6      1.0
2   103   卫衣   199   80  15920  广州   3.0   5.0         3      2.0
3   104   水杯    59  100   5900  深圳   2.0   2.0         2      1.0
4   105   键盘   899   30  26970  北京   8.0   8.0         8      3.0
5   106   鼠标    99   60   5940  上海   5.0   3.0         5      3.0
6   107   裤子   299   70  20930  广州   4.0   7.0         4      1.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0         1      2.0
8   109   平板  1999   25  49975  北京   9.0   9.0         9      2.0
9   110   音箱   299   40  11960  上海   7.0   4.0         7      2.0

In [36]:
df_rank_sort = df.sort_values('销量排名')
df_rank_sort

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名
7   108   毛巾    19  120   2280  深圳   1.0   1.0         1      2.0
3   104   水杯    59  100   5900  深圳   2.0   2.0         2      1.0
2   103   卫衣   199   80  15920  广州   3.0   5.0         3      2.0
6   107   裤子   299   70  20930  广州   4.0   7.0         4      1.0
5   106   鼠标    99   60   5940  上海   5.0   3.0         5      3.0
1   102   耳机   399   50  19950  上海   6.0   6.0         6      1.0
9   110   音箱   299   40  11960  上海   7.0   4.0         7      2.0
4   105   键盘   899   30  26970  北京   8.0   8.0         8      3.0
8   109   平板  1999   25  49975  北京   9.0   9.0         9      2.0
0   101   手机  2999   20  59980  北京  10.0  10.0        10      1.0

In [37]:
df

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名
0   101   手机  2999   20  59980  北京  10.0  10.0        10      1.0
1   102   耳机   399   50  19950  上海   6.0   6.0         6      1.0
2   103   卫衣   199   80  15920  广州   3.0   5.0         3      2.0
3   104   水杯    59  100   5900  深圳   2.0   2.0         2      1.0
4   105   键盘   899   30  26970  北京   8.0   8.0         8      3.0
5   106   鼠标    99   60   5940  上海   5.0   3.0         5      3.0
6   107   裤子   299   70  20930  广州   4.0   7.0         4      1.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0         1      2.0
8   109   平板  1999   25  49975  北京   9.0   9.0         9      2.0
9   110   音箱   299   40  11960  上海   7.0   4.0         7      2.0

In [38]:
df_null = df.copy()

df_null

   商品ID 商品名称    单价   销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名
0   101   手机  2999   20  59980  北京  10.0  10.0        10      1.0
1   102   耳机   399   50  19950  上海   6.0   6.0         6      1.0
2   103   卫衣   199   80  15920  广州   3.0   5.0         3      2.0
3   104   水杯    59  100   5900  深圳   2.0   2.0         2      1.0
4   105   键盘   899   30  26970  北京   8.0   8.0         8      3.0
5   106   鼠标    99   60   5940  上海   5.0   3.0         5      3.0
6   107   裤子   299   70  20930  广州   4.0   7.0         4      1.0
7   108   毛巾    19  120   2280  深圳   1.0   1.0         1      2.0
8   109   平板  1999   25  49975  北京   9.0   9.0         9      2.0
9   110   音箱   299   40  11960  上海   7.0   4.0         7      2.0

In [39]:
df_null.loc[2, '销量'] = None
df_null

   商品ID 商品名称    单价     销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名
0   101   手机  2999   20.0  59980  北京  10.0  10.0        10      1.0
1   102   耳机   399   50.0  19950  上海   6.0   6.0         6      1.0
2   103   卫衣   199    NaN  15920  广州   3.0   5.0         3      2.0
3   104   水杯    59  100.0   5900  深圳   2.0   2.0         2      1.0
4   105   键盘   899   30.0  26970  北京   8.0   8.0         8      3.0
5   106   鼠标    99   60.0   5940  上海   5.0   3.0         5      3.0
6   107   裤子   299   70.0  20930  广州   4.0   7.0         4      1.0
7   108   毛巾    19  120.0   2280  深圳   1.0   1.0         1      2.0
8   109   平板  1999   25.0  49975  北京   9.0   9.0         9      2.0
9   110   音箱   299   40.0  11960  上海   7.0   4.0         7      2.0

In [41]:
df_null['销量排名_null'] = df_null['销量'].rank(ascending=False, na_option='bottom')
df_null

   商品ID 商品名称    单价     销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名  销量排名_null
0   101   手机  2999   20.0  59980  北京  10.0  10.0        10      1.0        9.0
1   102   耳机   399   50.0  19950  上海   6.0   6.0         6      1.0        5.0
2   103   卫衣   199    NaN  15920  广州   3.0   5.0         3      2.0       10.0
3   104   水杯    59  100.0   5900  深圳   2.0   2.0         2      1.0        2.0
4   105   键盘   899   30.0  26970  北京   8.0   8.0         8      3.0        7.0
5   106   鼠标    99   60.0   5940  上海   5.0   3.0         5      3.0        4.0
6   107   裤子   299   70.0  20930  广州   4.0   7.0         4      1.0        3.0
7   108   毛巾    19  120.0   2280  深圳   1.0   1.0         1      2.0        1.0
8   109   平板  1999   25.0  49975  北京   9.0   9.0         9      2.0        8.0
9   110   音箱   299   40.0  11960  上海   7.0   4.0         7      2.0        6.0

In [42]:
df_null['销量排名_null'] = df_null['销量'].rank(ascending=False, na_option='top')
df_null

   商品ID 商品名称    单价     销量     总价  城市  销量排名  总价排名  销量排名_int  城市内总价排名  销量排名_null
0   101   手机  2999   20.0  59980  北京  10.0  10.0        10      1.0       10.0
1   102   耳机   399   50.0  19950  上海   6.0   6.0         6      1.0        6.0
2   103   卫衣   199    NaN  15920  广州   3.0   5.0         3      2.0        1.0
3   104   水杯    59  100.0   5900  深圳   2.0   2.0         2      1.0        3.0
4   105   键盘   899   30.0  26970  北京   8.0   8.0         8      3.0        8.0
5   106   鼠标    99   60.0   5940  上海   5.0   3.0         5      3.0        5.0
6   107   裤子   299   70.0  20930  广州   4.0   7.0         4      1.0        4.0
7   108   毛巾    19  120.0   2280  深圳   1.0   1.0         1      2.0        2.0
8   109   平板  1999   25.0  49975  北京   9.0   9.0         9      2.0        9.0
9   110   音箱   299   40.0  11960  上海   7.0   4.0         7      2.0        7.0