In [1]:
import pandas as pd

In [2]:
file_path = r'rank_group.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   商品ID 商品名称   品类    单价   销量     总价  城市  大区
0   101   手机   数码  2999   20  59980  北京  华北
1   102   耳机   数码   399   50  19950  上海  华东
2   103   卫衣   服饰   199   80  15920  广州  华南
3   104   水杯  日用品    59  100   5900  深圳  华南
4   105   键盘   数码   899   30  26970  北京  华北
5   106   鼠标   数码    99   60   5940  上海  华东
6   107   裤子   服饰   299   70  20930  广州  华南
7   108   毛巾  日用品    19  120   2280  深圳  华南
8   109   平板   数码  1999   25  49975  北京  华北
9   110   音箱   数码   299   40  11960  上海  华东

In [3]:
df['城市内销量排名'] = df.groupby('城市')['销量'].rank(ascending=False, method='min')
df

   商品ID 商品名称   品类    单价   销量     总价  城市  大区  城市内销量排名
0   101   手机   数码  2999   20  59980  北京  华北      3.0
1   102   耳机   数码   399   50  19950  上海  华东      2.0
2   103   卫衣   服饰   199   80  15920  广州  华南      1.0
3   104   水杯  日用品    59  100   5900  深圳  华南      2.0
4   105   键盘   数码   899   30  26970  北京  华北      1.0
5   106   鼠标   数码    99   60   5940  上海  华东      1.0
6   107   裤子   服饰   299   70  20930  广州  华南      2.0
7   108   毛巾  日用品    19  120   2280  深圳  华南      1.0
8   109   平板   数码  1999   25  49975  北京  华北      2.0
9   110   音箱   数码   299   40  11960  上海  华东      3.0

In [4]:
df['品类内单价排名'] = df.groupby('品类')['单价'].rank(ascending=False, method='min')
df

   商品ID 商品名称   品类    单价   销量     总价  城市  大区  城市内销量排名  品类内单价排名
0   101   手机   数码  2999   20  59980  北京  华北      3.0      1.0
1   102   耳机   数码   399   50  19950  上海  华东      2.0      4.0
2   103   卫衣   服饰   199   80  15920  广州  华南      1.0      2.0
3   104   水杯  日用品    59  100   5900  深圳  华南      2.0      1.0
4   105   键盘   数码   899   30  26970  北京  华北      1.0      3.0
5   106   鼠标   数码    99   60   5940  上海  华东      1.0      6.0
6   107   裤子   服饰   299   70  20930  广州  华南      2.0      1.0
7   108   毛巾  日用品    19  120   2280  深圳  华南      1.0      2.0
8   109   平板   数码  1999   25  49975  北京  华北      2.0      2.0
9   110   音箱   数码   299   40  11960  上海  华东      3.0      5.0

In [6]:
df['大区城市内总价排名'] = df.groupby(['大区', '城市'])['总价'].rank(ascending=False, method='dense')

df

   商品ID 商品名称   品类    单价   销量     总价  城市  大区  城市内销量排名  品类内单价排名  大区城市内总价排名
0   101   手机   数码  2999   20  59980  北京  华北      3.0      1.0        1.0
1   102   耳机   数码   399   50  19950  上海  华东      2.0      4.0        1.0
2   103   卫衣   服饰   199   80  15920  广州  华南      1.0      2.0        2.0
3   104   水杯  日用品    59  100   5900  深圳  华南      2.0      1.0        1.0
4   105   键盘   数码   899   30  26970  北京  华北      1.0      3.0        3.0
5   106   鼠标   数码    99   60   5940  上海  华东      1.0      6.0        3.0
6   107   裤子   服饰   299   70  20930  广州  华南      2.0      1.0        1.0
7   108   毛巾  日用品    19  120   2280  深圳  华南      1.0      2.0        2.0
8   109   平板   数码  1999   25  49975  北京  华北      2.0      2.0        2.0
9   110   音箱   数码   299   40  11960  上海  华东      3.0      5.0        2.0

In [7]:
df[df['城市'] == '北京']

   商品ID 商品名称  品类    单价  销量     总价  城市  大区  城市内销量排名  品类内单价排名  大区城市内总价排名
0   101   手机  数码  2999  20  59980  北京  华北      3.0      1.0        1.0
4   105   键盘  数码   899  30  26970  北京  华北      1.0      3.0        3.0
8   109   平板  数码  1999  25  49975  北京  华北      2.0      2.0        2.0

In [8]:
df

   商品ID 商品名称   品类    单价   销量     总价  城市  大区  城市内销量排名  品类内单价排名  大区城市内总价排名
0   101   手机   数码  2999   20  59980  北京  华北      3.0      1.0        1.0
1   102   耳机   数码   399   50  19950  上海  华东      2.0      4.0        1.0
2   103   卫衣   服饰   199   80  15920  广州  华南      1.0      2.0        2.0
3   104   水杯  日用品    59  100   5900  深圳  华南      2.0      1.0        1.0
4   105   键盘   数码   899   30  26970  北京  华北      1.0      3.0        3.0
5   106   鼠标   数码    99   60   5940  上海  华东      1.0      6.0        3.0
6   107   裤子   服饰   299   70  20930  广州  华南      2.0      1.0        1.0
7   108   毛巾  日用品    19  120   2280  深圳  华南      1.0      2.0        2.0
8   109   平板   数码  1999   25  49975  北京  华北      2.0      2.0        2.0
9   110   音箱   数码   299   40  11960  上海  华东      3.0      5.0        2.0

In [9]:
df['城市内销量排名_int'] = df['城市内销量排名'].astype(int)
df

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int
0,101,手机,数码,2999,20,59980,北京,华北,3.0,1.0,1.0,3
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2
9,110,音箱,数码,299,40,11960,上海,华东,3.0,5.0,2.0,3

In [10]:
top2_by_city = df[df['城市内销量排名_int'] <= 2]
top2_by_city

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2

In [11]:
top2_by_city = top2_by_city.sort_values(['城市', '城市内销量排名_int'])

top2_by_city

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2

In [12]:
df

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int
0,101,手机,数码,2999,20,59980,北京,华北,3.0,1.0,1.0,3
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2
9,110,音箱,数码,299,40,11960,上海,华东,3.0,5.0,2.0,3

In [13]:
df['城市内销量排名_min'] = df.groupby('城市')['销量'].rank(ascending=False, method='min')
df['城市内销量排名_dense'] = df.groupby('城市')['销量'].rank(ascending=False, method='dense')

In [14]:
df

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int,城市内销量排名_min,城市内销量排名_dense
0,101,手机,数码,2999,20,59980,北京,华北,3.0,1.0,1.0,3,3.0,3.0
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2,2.0,2.0
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1,1.0,1.0
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2,2.0,2.0
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1,1.0,1.0
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1,1.0,1.0
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2,2.0,2.0
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1,1.0,1.0
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2,2.0,2.0
9,110,音箱,数码,299,40,11960,上海,华东,3.0,5.0,2.0,3,3.0,3.0

In [15]:
df

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int,城市内销量排名_min,城市内销量排名_dense
0,101,手机,数码,2999,20,59980,北京,华北,3.0,1.0,1.0,3,3.0,3.0
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2,2.0,2.0
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1,1.0,1.0
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2,2.0,2.0
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1,1.0,1.0
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1,1.0,1.0
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2,2.0,2.0
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1,1.0,1.0
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2,2.0,2.0
9,110,音箱,数码,299,40,11960,上海,华东,3.0,5.0,2.0,3,3.0,3.0

In [16]:
df_final = df.sort_values(['大区', '城市', '城市内销量排名'])

df_final

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int,城市内销量排名_min,城市内销量排名_dense
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1,1.0,1.0
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2,2.0,2.0
9,110,音箱,数码,299,40,11960,上海,华东,3.0,5.0,2.0,3,3.0,3.0
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1,1.0,1.0
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2,2.0,2.0
0,101,手机,数码,2999,20,59980,北京,华北,3.0,1.0,1.0,3,3.0,3.0
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1,1.0,1.0
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2,2.0,2.0
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1,1.0,1.0
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2,2.0,2.0

In [17]:
df_null = df.copy()

df_null

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int,城市内销量排名_min,城市内销量排名_dense
0,101,手机,数码,2999,20,59980,北京,华北,3.0,1.0,1.0,3,3.0,3.0
1,102,耳机,数码,399,50,19950,上海,华东,2.0,4.0,1.0,2,2.0,2.0
2,103,卫衣,服饰,199,80,15920,广州,华南,1.0,2.0,2.0,1,1.0,1.0
3,104,水杯,日用品,59,100,5900,深圳,华南,2.0,1.0,1.0,2,2.0,2.0
4,105,键盘,数码,899,30,26970,北京,华北,1.0,3.0,3.0,1,1.0,1.0
5,106,鼠标,数码,99,60,5940,上海,华东,1.0,6.0,3.0,1,1.0,1.0
6,107,裤子,服饰,299,70,20930,广州,华南,2.0,1.0,1.0,2,2.0,2.0
7,108,毛巾,日用品,19,120,2280,深圳,华南,1.0,2.0,2.0,1,1.0,1.0
8,109,平板,数码,1999,25,49975,北京,华北,2.0,2.0,2.0,2,2.0,2.0
9,110,音箱,数码,299,40,11960,上海,华东,3.0,5.0,2.0,3,3.0,3.0

In [18]:
df_null.loc[3, '销量'] = None

df_null

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int,城市内销量排名_min,城市内销量排名_dense
0,101,手机,数码,2999,20.0,59980,北京,华北,3.0,1.0,1.0,3,3.0,3.0
1,102,耳机,数码,399,50.0,19950,上海,华东,2.0,4.0,1.0,2,2.0,2.0
2,103,卫衣,服饰,199,80.0,15920,广州,华南,1.0,2.0,2.0,1,1.0,1.0
3,104,水杯,日用品,59,NaN,5900,深圳,华南,2.0,1.0,1.0,2,2.0,2.0
4,105,键盘,数码,899,30.0,26970,北京,华北,1.0,3.0,3.0,1,1.0,1.0
5,106,鼠标,数码,99,60.0,5940,上海,华东,1.0,6.0,3.0,1,1.0,1.0
6,107,裤子,服饰,299,70.0,20930,广州,华南,2.0,1.0,1.0,2,2.0,2.0
7,108,毛巾,日用品,19,120.0,2280,深圳,华南,1.0,2.0,2.0,1,1.0,1.0
8,109,平板,数码,1999,25.0,49975,北京,华北,2.0,2.0,2.0,2,2.0,2.0
9,110,音箱,数码,299,40.0,11960,上海,华东,3.0,5.0,2.0,3,3.0,3.0

In [19]:
df_null['城市内销量排名_null'] = df_null.groupby('城市')['销量'].rank(ascending=False, method='min', na_option='bottom')

df_null

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int,城市内销量排名_min,城市内销量排名_dense,城市内销量排名_null
0,101,手机,数码,2999,20.0,59980,北京,华北,3.0,1.0,1.0,3,3.0,3.0,3.0
1,102,耳机,数码,399,50.0,19950,上海,华东,2.0,4.0,1.0,2,2.0,2.0,2.0
2,103,卫衣,服饰,199,80.0,15920,广州,华南,1.0,2.0,2.0,1,1.0,1.0,1.0
3,104,水杯,日用品,59,NaN,5900,深圳,华南,2.0,1.0,1.0,2,2.0,2.0,2.0
4,105,键盘,数码,899,30.0,26970,北京,华北,1.0,3.0,3.0,1,1.0,1.0,1.0
5,106,鼠标,数码,99,60.0,5940,上海,华东,1.0,6.0,3.0,1,1.0,1.0,1.0
6,107,裤子,服饰,299,70.0,20930,广州,华南,2.0,1.0,1.0,2,2.0,2.0,2.0
7,108,毛巾,日用品,19,120.0,2280,深圳,华南,1.0,2.0,2.0,1,1.0,1.0,1.0
8,109,平板,数码,1999,25.0,49975,北京,华北,2.0,2.0,2.0,2,2.0,2.0,2.0
9,110,音箱,数码,299,40.0,11960,上海,华东,3.0,5.0,2.0,3,3.0,3.0,3.0

In [20]:
df_null['城市内销量排名_null'] = df_null.groupby('城市')['销量'].rank(ascending=False, method='min', na_option='top')

df_null

,商品ID,商品名称,品类,单价,销量,总价,城市,大区,城市内销量排名,品类内单价排名,大区城市内总价排名,城市内销量排名_int,城市内销量排名_min,城市内销量排名_dense,城市内销量排名_null
0,101,手机,数码,2999,20.0,59980,北京,华北,3.0,1.0,1.0,3,3.0,3.0,3.0
1,102,耳机,数码,399,50.0,19950,上海,华东,2.0,4.0,1.0,2,2.0,2.0,2.0
2,103,卫衣,服饰,199,80.0,15920,广州,华南,1.0,2.0,2.0,1,1.0,1.0,1.0
3,104,水杯,日用品,59,NaN,5900,深圳,华南,2.0,1.0,1.0,2,2.0,2.0,1.0
4,105,键盘,数码,899,30.0,26970,北京,华北,1.0,3.0,3.0,1,1.0,1.0,1.0
5,106,鼠标,数码,99,60.0,5940,上海,华东,1.0,6.0,3.0,1,1.0,1.0,1.0
6,107,裤子,服饰,299,70.0,20930,广州,华南,2.0,1.0,1.0,2,2.0,2.0,2.0
7,108,毛巾,日用品,19,120.0,2280,深圳,华南,1.0,2.0,2.0,1,1.0,1.0,2.0
8,109,平板,数码,1999,25.0,49975,北京,华北,2.0,2.0,2.0,2,2.0,2.0,2.0
9,110,音箱,数码,299,40.0,11960,上海,华东,3.0,5.0,2.0,3,3.0,3.0,3.0