In [11]:
import pandas as pd

In [12]:
file1 = r'append_data1.csv'
file2 = r'append_data2.csv'
file3 = r'append_data3.csv'

df1 = pd.read_csv(file1, encoding='utf-8')
df2 = pd.read_csv(file2, encoding='utf-8')
df3 = pd.read_csv(file3, encoding='utf-8')

df1

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990

In [13]:
df2

   订单ID 商品名称   单价  数量  城市    总价
0  1004   水杯   59  20  深圳  1180
1  1005   键盘  899   3  北京  2697
2  1006   鼠标   99   8  上海   792

In [14]:
df3

   订单ID 商品名称   单价  数量   是否包邮
0  1007   裤子  299   6   True
1  1008   毛巾   19  15  False

In [15]:
df_append_basic = df1.append(df2, ignore_index=True)
df_append_basic

AttributeError: 'DataFrame' object has no attribute 'append'

In [16]:
df_append_basic = pd.concat([df1, df2], ignore_index=True)

df_append_basic

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792

In [17]:
df_custom = pd.DataFrame(
    {
        '订单ID': [1009],
        '商品名称': ['平板'],
        '单价': [1999],
        '数量': [4],
        '城市': ['北京'],
        '总价': [7996]
    }
)

df_custom

   订单ID 商品名称    单价  数量  城市    总价
0  1009   平板  1999   4  北京  7996

In [18]:
df_append_multi = pd.concat([df1, df2, df_custom], ignore_index=True)
df_append_multi

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1009   平板  1999   4  北京  7996

In [19]:
df_append_diff = pd.concat([df1, df3], ignore_index=True)
df_append_diff

   订单ID 商品名称    单价  数量   城市      总价   是否包邮
0  1001   手机  2999   2   北京  5998.0    NaN
1  1002   耳机   399   5   上海  1995.0    NaN
2  1003   卫衣   199  10   广州  1990.0    NaN
3  1007   裤子   299   6  NaN     NaN   True
4  1008   毛巾    19  15  NaN     NaN  False

In [20]:
df_dup = pd.DataFrame(
    {
        '订单ID': [1001, 1010],
        '商品名称': ['手机', '音箱'],
        '单价': [2999, 299],
        '数量': [2, 7],
        '城市': ['北京', '上海'],
        '总价': [5998, 2093]
    }
)

df_dup

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1010   音箱   299   7  上海  2093

In [21]:
df1

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990

In [22]:
df2

   订单ID 商品名称   单价  数量  城市    总价
0  1004   水杯   59  20  深圳  1180
1  1005   键盘  899   3  北京  2697
2  1006   鼠标   99   8  上海   792

In [23]:
df_append_dup = pd.concat([df1, df2, df_dup], ignore_index=True)
df_append_dup

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1001   手机  2999   2  北京  5998
7  1010   音箱   299   7  上海  2093

In [24]:
df_append_dropdup = df_append_dup.drop_duplicates(subset='订单ID', keep='first')
df_append_dropdup

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
7  1010   音箱   299   7  上海  2093

In [25]:
df_concat = pd.concat([df1, df2], ignore_index=True)

df_concat

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792