In [1]:
import pandas as pd

In [2]:
file_path = r'duplicate_data.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1001   手机  2999   2  北京  5998
3  1003   卫衣   199  10  广州  1990
4  1002   耳机   399   5  上海  1995
5  1004   水杯    59  20  深圳  1180
6  1004   水杯    59  20  深圳  1180
7  1004   水杯    59  20  深圳  1180

In [3]:
print(len(df))

8

In [5]:
dup_flag = df.duplicated()
dup_flag

0    False
1    False
2     True
3    False
4     True
5    False
6     True
7     True
dtype: bool

In [6]:
dup_count = dup_flag.sum()

print(dup_count)

4

In [7]:
print(len(df) - dup_count)

4

In [8]:
dup_all_rows = df[df.duplicated(keep=False)]

dup_all_rows

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1001   手机  2999   2  北京  5998
4  1002   耳机   399   5  上海  1995
5  1004   水杯    59  20  深圳  1180
6  1004   水杯    59  20  深圳  1180
7  1004   水杯    59  20  深圳  1180

In [9]:
dup_only_rows = df[df.duplicated()]
dup_only_rows

   订单ID 商品名称    单价  数量  城市    总价
2  1001   手机  2999   2  北京  5998
4  1002   耳机   399   5  上海  1995
6  1004   水杯    59  20  深圳  1180
7  1004   水杯    59  20  深圳  1180

In [10]:
dup_by_id = df.duplicated(subset=['订单ID'])
dup_by_id

0    False
1    False
2     True
3    False
4     True
5    False
6     True
7     True
dtype: bool

In [11]:
dup_id_count = dup_by_id.sum()
print(dup_id_count)

4

In [12]:
dup_by_multi = df.duplicated(subset=['订单ID', '商品名称'])
dup_by_multi

0    False
1    False
2     True
3    False
4     True
5    False
6     True
7     True
dtype: bool

In [13]:
dup_freq = df.groupby('订单ID').size().reset_index(name='重复次数')
dup_freq

   订单ID  重复次数
0  1001     2
1  1002     2
2  1003     1
3  1004     3