In [1]:
import pandas as pd

In [2]:
file_path = r'duplicate_drop.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1001   手机  2999   2  北京  5998
3  1003   卫衣   199  10  广州  1990
4  1002   耳机   399   5  上海  1995
5  1004   水杯    59  20  深圳  1180
6  1004   水杯    59  20  深圳  1180
7  1004   水杯    59  20  深圳  1180

In [3]:
print(len(df))

8

In [4]:
df_drop_default = df.drop_duplicates()

df_drop_default

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
3  1003   卫衣   199  10  广州  1990
5  1004   水杯    59  20  深圳  1180

In [5]:
df_drop_last = df.drop_duplicates(keep='last')
df_drop_last

   订单ID 商品名称    单价  数量  城市    总价
2  1001   手机  2999   2  北京  5998
3  1003   卫衣   199  10  广州  1990
4  1002   耳机   399   5  上海  1995
7  1004   水杯    59  20  深圳  1180

In [6]:
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1001   手机  2999   2  北京  5998
3  1003   卫衣   199  10  广州  1990
4  1002   耳机   399   5  上海  1995
5  1004   水杯    59  20  深圳  1180
6  1004   水杯    59  20  深圳  1180
7  1004   水杯    59  20  深圳  1180

In [7]:
df_drop_id = df.drop_duplicates(subset=['订单ID'])

df_drop_id

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
3  1003   卫衣   199  10  广州  1990
5  1004   水杯    59  20  深圳  1180

In [8]:
df_drop_multi = df.drop_duplicates(subset=['订单ID', '商品名称'], keep='last')

df_drop_multi

   订单ID 商品名称    单价  数量  城市    总价
2  1001   手机  2999   2  北京  5998
3  1003   卫衣   199  10  广州  1990
4  1002   耳机   399   5  上海  1995
7  1004   水杯    59  20  深圳  1180

In [9]:
df_drop_all = df.drop_duplicates(keep=False)

df_drop_all

   订单ID 商品名称   单价  数量  城市    总价
3  1003   卫衣  199  10  广州  1990