In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = r'outlier_handle.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称     单价   数量  城市     总价
0  1001   手机   2999    2  北京   5998
1  1002   耳机    399    5  上海   1995
2  1003   卫衣    199   10  广州   1990
3  1004   水杯     59   20  深圳   1180
4  1005   键盘    899    3  北京   2697
5  1006   鼠标     99    8  上海    792
6  1007   背包    199  500  广州  99500
7  1008   手表  99999    1  深圳  99999

In [4]:
cond_delete = (df['数量'] > 100) | (df['单价'] > 10000)

df_delete = df[~cond_delete]
df_delete

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792

In [5]:
df

   订单ID 商品名称     单价   数量  城市     总价
0  1001   手机   2999    2  北京   5998
1  1002   耳机    399    5  上海   1995
2  1003   卫衣    199   10  广州   1990
3  1004   水杯     59   20  深圳   1180
4  1005   键盘    899    3  北京   2697
5  1006   鼠标     99    8  上海    792
6  1007   背包    199  500  广州  99500
7  1008   手表  99999    1  深圳  99999

In [7]:
df_fix = df.copy()

df_fix.loc[df_fix['数量'] > 100, '数量'] = 100
price_mean = df_fix[df_fix['单价'] <= 10000]['单价'].mean()

df_fix.loc[df_fix['单价'] > 10000, '单价'] = round(price_mean, 0)
df_fix['总价'] = df_fix['单价'] * df_fix['数量']

df_fix

   订单ID 商品名称    单价   数量  城市     总价
0  1001   手机  2999    2  北京   5998
1  1002   耳机   399    5  上海   1995
2  1003   卫衣   199   10  广州   1990
3  1004   水杯    59   20  深圳   1180
4  1005   键盘   899    3  北京   2697
5  1006   鼠标    99    8  上海    792
6  1007   背包   199  100  广州  19900
7  1008   手表   693    1  深圳    693

In [8]:
df

   订单ID 商品名称     单价   数量  城市     总价
0  1001   手机   2999    2  北京   5998
1  1002   耳机    399    5  上海   1995
2  1003   卫衣    199   10  广州   1990
3  1004   水杯     59   20  深圳   1180
4  1005   键盘    899    3  北京   2697
5  1006   鼠标     99    8  上海    792
6  1007   背包    199  500  广州  99500
7  1008   手表  99999    1  深圳  99999

In [9]:
df_replace = df.copy()

df_replace['数量异常标记'] = df_replace['数量'] > 100
df_replace['单价异常标记'] = df_replace['单价'] > 10000

df_replace

   订单ID 商品名称     单价   数量  城市     总价  数量异常标记  单价异常标记
0  1001   手机   2999    2  北京   5998   False   False
1  1002   耳机    399    5  上海   1995   False   False
2  1003   卫衣    199   10  广州   1990   False   False
3  1004   水杯     59   20  深圳   1180   False   False
4  1005   键盘    899    3  北京   2697   False   False
5  1006   鼠标     99    8  上海    792   False   False
6  1007   背包    199  500  广州  99500    True   False
7  1008   手表  99999    1  深圳  99999   False    True

In [11]:
q3_qty = df_replace['数量'].quantile(0.75)
iqr_qty = df_replace['数量'].quantile(0.75) - df_replace['数量'].quantile(0.25)

upper_qty = round(q3_qty + 1.5 * iqr_qty, 0)
df_replace.loc[df_replace['数量'] > upper_qty, '数量'] = upper_qty
df_replace

   订单ID 商品名称     单价  数量  城市     总价  数量异常标记  单价异常标记
0  1001   手机   2999   2  北京   5998   False   False
1  1002   耳机    399   5  上海   1995   False   False
2  1003   卫衣    199  10  广州   1990   False   False
3  1004   水杯     59  20  深圳   1180   False   False
4  1005   键盘    899   3  北京   2697   False   False
5  1006   鼠标     99   8  上海    792   False   False
6  1007   背包    199  27  广州  99500    True   False
7  1008   手表  99999   1  深圳  99999   False    True

In [12]:
df_replace['数量异常标记'] = df_replace['数量'] > 100
df_replace['单价异常标记'] = df_replace['单价'] > 10000

df_replace

   订单ID 商品名称     单价  数量  城市     总价  数量异常标记  单价异常标记
0  1001   手机   2999   2  北京   5998   False   False
1  1002   耳机    399   5  上海   1995   False   False
2  1003   卫衣    199  10  广州   1990   False   False
3  1004   水杯     59  20  深圳   1180   False   False
4  1005   键盘    899   3  北京   2697   False   False
5  1006   鼠标     99   8  上海    792   False   False
6  1007   背包    199  27  广州  99500   False   False
7  1008   手表  99999   1  深圳  99999   False    True