In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = r'outlier_data.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称     单价   数量  城市     总价
0  1001   手机   2999    2  北京   5998
1  1002   耳机    399    5  上海   1995
2  1003   卫衣    199   10  广州   1990
3  1004   水杯     59   20  深圳   1180
4  1005   键盘    899    3  北京   2697
5  1006   鼠标     99    8  上海    792
6  1007   背包    199  500  广州  99500
7  1008   手表  99999    1  深圳  99999

In [3]:
price_outlier = df[(df['单价'] > 10000) | (df['单价'] < 0)]
qty_outlier = df[(df['数量'] > 100) | (df['数量'] < 1)]

price_outlier

   订单ID 商品名称     单价  数量  城市     总价
7  1008   手表  99999   1  深圳  99999

In [4]:
qty_outlier

   订单ID 商品名称   单价   数量  城市     总价
6  1007   背包  199  500  广州  99500

In [5]:
df

   订单ID 商品名称     单价   数量  城市     总价
0  1001   手机   2999    2  北京   5998
1  1002   耳机    399    5  上海   1995
2  1003   卫衣    199   10  广州   1990
3  1004   水杯     59   20  深圳   1180
4  1005   键盘    899    3  北京   2697
5  1006   鼠标     99    8  上海    792
6  1007   背包    199  500  广州  99500
7  1008   手表  99999    1  深圳  99999

In [6]:
def detect_outlier_std(df_col):
    mean = df_col.mean()
    std = df_col.std()
    lower = mean - 3 * std
    upper = mean + 3 * std
    return df_col[(df_col < lower) | (df_col > upper)]

total_price_outlier = detect_outlier_std(df['总价'])
total_price_outlier

Series([], Name: 总价, dtype: int64)

In [7]:
q1 = df['数量'].quantile(0.25)
q3 = df['数量'].quantile(0.75)

iqr = q3 - q1
lower_q = q1 - 1.5 * iqr
upper_q = q3 + 1.5 * iqr

qty_outlier_iqr = df[(df['数量'] < lower_q) | (df['数量'] > upper_q)]
qty_outlier_iqr

   订单ID 商品名称   单价   数量  城市     总价
6  1007   背包  199  500  广州  99500

In [8]:
df

   订单ID 商品名称     单价   数量  城市     总价
0  1001   手机   2999    2  北京   5998
1  1002   耳机    399    5  上海   1995
2  1003   卫衣    199   10  广州   1990
3  1004   水杯     59   20  深圳   1180
4  1005   键盘    899    3  北京   2697
5  1006   鼠标     99    8  上海    792
6  1007   背包    199  500  广州  99500
7  1008   手表  99999    1  深圳  99999

In [9]:
desc = df[['单价', '数量', '总价']].describe()

desc

                 单价          数量            总价
count      8.000000    8.000000      8.000000
mean   13106.500000   68.625000  26768.875000
std    35123.478411  174.408337  45072.446846
min       59.000000    1.000000    792.000000
25%      174.000000    2.750000   1787.500000
50%      299.000000    6.500000   2346.000000
75%     1424.000000   12.500000  29373.500000
max    99999.000000  500.000000  99999.000000