In [1]:
import pandas as pd

In [2]:
path_main = r'order_main.csv'
path_product = r'product_info.csv'

df_order = pd.read_csv(path_main, encoding='utf-8')
df_product = pd.read_csv(path_product, encoding='utf-8')

df_order

   订单ID  用户ID  商品ID  下单金额
0  1001     1   101  5998
1  1002     2   102  1995
2  1003     3   103  1990
3  1004     4   104  1180
4  1005     5   105  2697

In [3]:
df_product

   商品ID 商品名称  品类    单价
0   101   手机  数码  2999
1   102   耳机  数码   399
2   103   卫衣  服饰   199
3   106   平板  数码  1999
4   107   键盘  数码   899

In [4]:
merge_inner = pd.merge(df_order, df_product, on='商品ID', how='inner')

merge_inner

   订单ID  用户ID  商品ID  下单金额 商品名称  品类    单价
0  1001     1   101  5998   手机  数码  2999
1  1002     2   102  1995   耳机  数码   399
2  1003     3   103  1990   卫衣  服饰   199

In [5]:
merge_left = pd.merge(df_order, df_product, on='商品ID', how='left')

merge_left

   订单ID  用户ID  商品ID  下单金额 商品名称   品类      单价
0  1001     1   101  5998   手机   数码  2999.0
1  1002     2   102  1995   耳机   数码   399.0
2  1003     3   103  1990   卫衣   服饰   199.0
3  1004     4   104  1180  NaN  NaN     NaN
4  1005     5   105  2697  NaN  NaN     NaN

In [6]:
merge_right = pd.merge(df_order, df_product, on='商品ID', how='right')

merge_right

     订单ID  用户ID  商品ID    下单金额 商品名称  品类    单价
0  1001.0   1.0   101  5998.0   手机  数码  2999
1  1002.0   2.0   102  1995.0   耳机  数码   399
2  1003.0   3.0   103  1990.0   卫衣  服饰   199
3     NaN   NaN   106     NaN   平板  数码  1999
4     NaN   NaN   107     NaN   键盘  数码   899

In [7]:
merge_outer = pd.merge(df_order, df_product, on='商品ID', how='outer')

merge_outer

     订单ID  用户ID  商品ID    下单金额 商品名称   品类      单价
0  1001.0   1.0   101  5998.0   手机   数码  2999.0
1  1002.0   2.0   102  1995.0   耳机   数码   399.0
2  1003.0   3.0   103  1990.0   卫衣   服饰   199.0
3  1004.0   4.0   104  1180.0  NaN  NaN     NaN
4  1005.0   5.0   105  2697.0  NaN  NaN     NaN
5     NaN   NaN   106     NaN   平板   数码  1999.0
6     NaN   NaN   107     NaN   键盘   数码   899.0

In [8]:
merge_outer.fillna('无')

     订单ID 用户ID  商品ID    下单金额 商品名称  品类      单价
0  1001.0  1.0   101  5998.0   手机  数码  2999.0
1  1002.0  2.0   102  1995.0   耳机  数码   399.0
2  1003.0  3.0   103  1990.0   卫衣  服饰   199.0
3  1004.0  4.0   104  1180.0    无   无       无
4  1005.0  5.0   105  2697.0    无   无       无
5       无    无   106       无   平板  数码  1999.0
6       无    无   107       无   键盘  数码   899.0

In [9]:
merge_left

   订单ID  用户ID  商品ID  下单金额 商品名称   品类      单价
0  1001     1   101  5998   手机   数码  2999.0
1  1002     2   102  1995   耳机   数码   399.0
2  1003     3   103  1990   卫衣   服饰   199.0
3  1004     4   104  1180  NaN  NaN     NaN
4  1005     5   105  2697  NaN  NaN     NaN

In [10]:
merge_left['商品名称'] = merge_left['商品名称'].fillna('未知商品')

merge_left

   订单ID  用户ID  商品ID  下单金额  商品名称   品类      单价
0  1001     1   101  5998    手机   数码  2999.0
1  1002     2   102  1995    耳机   数码   399.0
2  1003     3   103  1990    卫衣   服饰   199.0
3  1004     4   104  1180  未知商品  NaN     NaN
4  1005     5   105  2697  未知商品  NaN     NaN