In [17]:
import pandas as pd

In [18]:
order_path = r'order_info.csv'
user_path = r'user_info.csv'

df_order = pd.read_csv(order_path, encoding='utf-8')
df_user = pd.read_csv(user_path, encoding='utf-8')

df_order

   订单ID  用户ID  商品ID  下单金额
0  1001     1   101  2999
1  1002     2   102   399
2  1003     3   103   199
3  1004     4   104    59
4  1005     5   105   899

In [19]:
df_user

   ID 用户名  城市        注册时间
0   1  张三  北京  2024-01-01
1   2  李四  上海  2024-02-15
2   6  王五  广州  2024-03-20
3   7  赵六  深圳  2024-04-10

In [20]:
merge_on = pd.merge(
    df_order,
    df_user,
    left_on='用户ID',
    right_on='ID',
    how='left'
)

merge_on

   订单ID  用户ID  商品ID  下单金额   ID  用户名   城市        注册时间
0  1001     1   101  2999  1.0   张三   北京  2024-01-01
1  1002     2   102   399  2.0   李四   上海  2024-02-15
2  1003     3   103   199  NaN  NaN  NaN         NaN
3  1004     4   104    59  NaN  NaN  NaN         NaN
4  1005     5   105   899  NaN  NaN  NaN         NaN

In [21]:
df_order

   订单ID  用户ID  商品ID  下单金额
0  1001     1   101  2999
1  1002     2   102   399
2  1003     3   103   199
3  1004     4   104    59
4  1005     5   105   899

In [22]:
df_user

   ID 用户名  城市        注册时间
0   1  张三  北京  2024-01-01
1   2  李四  上海  2024-02-15
2   6  王五  广州  2024-03-20
3   7  赵六  深圳  2024-04-10

In [23]:
df_user['下单金额'] = [100, 200, 300, 400]

In [24]:
df_user

   ID 用户名  城市        注册时间  下单金额
0   1  张三  北京  2024-01-01   100
1   2  李四  上海  2024-02-15   200
2   6  王五  广州  2024-03-20   300
3   7  赵六  深圳  2024-04-10   400

In [25]:
merge_suffix = pd.merge(
    df_order,
    df_user,
    left_on='用户ID',
    right_on='ID',
    how='inner',
    suffixes=('_订单', '_用户')
)

merge_suffix

   订单ID  用户ID  商品ID  下单金额_订单  ID 用户名  城市        注册时间  下单金额_用户
0  1001     1   101     2999   1  张三  北京  2024-01-01      100
1  1002     2   102      399   2  李四  上海  2024-02-15      200

In [26]:
df_order

   订单ID  用户ID  商品ID  下单金额
0  1001     1   101  2999
1  1002     2   102   399
2  1003     3   103   199
3  1004     4   104    59
4  1005     5   105   899

In [27]:
df_user

   ID 用户名  城市        注册时间  下单金额
0   1  张三  北京  2024-01-01   100
1   2  李四  上海  2024-02-15   200
2   6  王五  广州  2024-03-20   300
3   7  赵六  深圳  2024-04-10   400

In [28]:
merge_indicator = pd.merge(
    df_order,
    df_user,
    left_on='用户ID',
    right_on='ID',
    how='outer',
    indicator=True
)

merge_indicator

     订单ID  用户ID   商品ID  下单金额_x   ID  用户名   城市        注册时间  下单金额_y      _merge
0  1001.0   1.0  101.0  2999.0  1.0   张三   北京  2024-01-01   100.0        both
1  1002.0   2.0  102.0   399.0  2.0   李四   上海  2024-02-15   200.0        both
2  1003.0   3.0  103.0   199.0  NaN  NaN  NaN         NaN     NaN   left_only
3  1004.0   4.0  104.0    59.0  NaN  NaN  NaN         NaN     NaN   left_only
4  1005.0   5.0  105.0   899.0  NaN  NaN  NaN         NaN     NaN   left_only
5     NaN   NaN    NaN     NaN  6.0   王五   广州  2024-03-20   300.0  right_only
6     NaN   NaN    NaN     NaN  7.0   赵六   深圳  2024-04-10   400.0  right_only

In [29]:
df_user_idx = df_user.set_index('ID')
df_user_idx

   用户名  城市        注册时间  下单金额
ID
1   张三  北京  2024-01-01   100
2   李四  上海  2024-02-15   200
6   王五  广州  2024-03-20   300
7   赵六  深圳  2024-04-10   400

In [30]:
df_user

   ID 用户名  城市        注册时间  下单金额
0   1  张三  北京  2024-01-01   100
1   2  李四  上海  2024-02-15   200
2   6  王五  广州  2024-03-20   300
3   7  赵六  深圳  2024-04-10   400

In [31]:
df_user_idx

   用户名  城市        注册时间  下单金额
ID
1   张三  北京  2024-01-01   100
2   李四  上海  2024-02-15   200
6   王五  广州  2024-03-20   300
7   赵六  深圳  2024-04-10   400

In [34]:
df_order

   订单ID  用户ID  商品ID  下单金额
0  1001     1   101  2999
1  1002     2   102   399
2  1003     3   103   199
3  1004     4   104    59
4  1005     5   105   899

In [33]:
merge_index = pd.merge(
    df_order,
    df_user_idx,
    left_on='用户ID',
    right_index=True,
    how='inner'
)

merge_index

   订单ID  用户ID  商品ID  下单金额_x 用户名  城市        注册时间  下单金额_y
0  1001     1   101    2999  张三  北京  2024-01-01     100
1  1002     2   102     399  李四  上海  2024-02-15     200

In [35]:
df_order

   订单ID  用户ID  商品ID  下单金额
0  1001     1   101  2999
1  1002     2   102   399
2  1003     3   103   199
3  1004     4   104    59
4  1005     5   105   899

In [36]:
df_user

   ID 用户名  城市        注册时间  下单金额
0   1  张三  北京  2024-01-01   100
1   2  李四  上海  2024-02-15   200
2   6  王五  广州  2024-03-20   300
3   7  赵六  深圳  2024-04-10   400

In [37]:
try:
    merge_validate = pd.merge(
        df_order,
        df_user,
        left_on='用户ID',
        right_on='ID',
        how='inner',
        validate='one_to_one'
    )
    print('通过')
except Exception as e:
    print('验证失败', e)

通过

In [38]:
merge_final = pd.merge(
    df_order[['订单ID', '用户ID', '下单金额']],
    df_user[['ID', '用户名', '城市']],
    left_on='用户ID',
    right_on='ID',
    how='left',
    suffixes=('', '_用户'),
    indicator='匹配状态'
).drop('ID', axis=1)

merge_final

   订单ID  用户ID  下单金额  用户名   城市       匹配状态
0  1001     1  2999   张三   北京       both
1  1002     2   399   李四   上海       both
2  1003     3   199  NaN  NaN  left_only
3  1004     4    59  NaN  NaN  left_only
4  1005     5   899  NaN  NaN  left_only