In [1]:
import pandas as pd

In [2]:
file_path = r'groupby_create.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [3]:
print(len(df))

10

In [4]:
group_category = df.groupby('品类')
group_category

In [5]:
for name, group in group_category:
    print(f"组名：{name} → 行数：{len(group)}")

组名：数码 → 行数：6
组名：日用品 → 行数：2
组名：服饰 → 行数：2

In [6]:
group_digital = group_category.get_group('数码')
group_digital

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
5  华东  上海   鼠标    99   8   792  数码  False
8  华北  北京   平板  1999   4  7996  数码   True
9  华东  上海   音箱   299   7  2093  数码  False

In [7]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [8]:
group_multi = df.groupby(['大区', '品类'])
group_multi

In [9]:
print([name for name in group_multi.groups.keys()])

[('华东', '数码'), ('华北', '数码'), ('华南', '日用品'), ('华南', '服饰')]

In [10]:
group_north_digital = group_multi.get_group(('华北', '数码'))
group_north_digital

   大区  城市 商品名称    单价  数量    总价  品类  是否包邮
0  华北  北京   手机  2999   2  5998  数码  True
1  华北  北京   键盘   899   3  2697  数码  True
8  华北  北京   平板  1999   4  7996  数码  True

In [11]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [12]:
group_shanghai = df.groupby('城市').get_group('上海').reset_index(drop=True)
group_shanghai

   大区  城市 商品名称   单价  数量    总价  品类   是否包邮
0  华东  上海   耳机  399   5  1995  数码  False
1  华东  上海   鼠标   99   8   792  数码  False
2  华东  上海   音箱  299   7  2093  数码  False

In [13]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [14]:
group_size = df.groupby('大区').size()
group_size

大区
华东    3
华北    3
华南    4
dtype: int64

In [15]:
group_indices = df.groupby('品类').indices
group_indices

{'数码': array([0, 1, 2, 5, 8, 9]), '日用品': array([4, 7]), '服饰': array([3, 6])}

In [16]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [17]:
group_free = df.groupby('是否包邮').size()
group_free

是否包邮
False    5
True     5
dtype: int64