In [1]:
import pandas as pd

In [2]:
file_path = r'groupby_view.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [3]:
group_cat = df.groupby('品类')
group_multi = df.groupby(['大区', '城市'])

In [4]:
group_cat.groups.keys()

dict_keys(['数码', '日用品', '服饰'])

In [5]:
group_multi.groups.keys()

dict_keys([('华东', '上海'), ('华北', '北京'), ('华南', '广州'), ('华南', '深圳')])

In [6]:
list(group_multi.groups.keys())

[('华东', '上海'), ('华北', '北京'), ('华南', '广州'), ('华南', '深圳')]

In [7]:
group_cat.size()

品类
数码     6
日用品    2
服饰     2
dtype: int64

In [8]:
group_multi.size()

大区  城市
华东  上海    3
华北  北京    3
华南  广州    2
    深圳    2
dtype: int64

In [9]:
digital_group = group_cat.get_group('数码')
digital_group

   大区  城市 商品名称    单价  数量    总价  品类   是否包邮
0  华北  北京   手机  2999   2  5998  数码   True
1  华北  北京   键盘   899   3  2697  数码   True
2  华东  上海   耳机   399   5  1995  数码  False
5  华东  上海   鼠标    99   8   792  数码  False
8  华北  北京   平板  1999   4  7996  数码   True
9  华东  上海   音箱   299   7  2093  数码  False

In [10]:
north_beijing = group_multi.get_group(('华北', '北京'))
north_beijing

   大区  城市 商品名称    单价  数量    总价  品类  是否包邮
0  华北  北京   手机  2999   2  5998  数码  True
1  华北  北京   键盘   899   3  2697  数码  True
8  华北  北京   平板  1999   4  7996  数码  True

In [11]:
for name, group in group_cat:
    print(f"组名: {name}")
    print(f"总行数: {len(group)} | 总价合计: {group['总价'].sum()}")
    print(group['商品名称'].tolist())

组名: 数码
总行数: 6 | 总价合计: 21571
['手机', '键盘', '耳机', '鼠标', '平板', '音箱']
组名: 日用品
总行数: 2 | 总价合计: 1465
['水杯', '毛巾']
组名: 服饰
总行数: 2 | 总价合计: 3784
['卫衣', '裤子']

In [12]:
group_head = group_cat.head(1)
group_head

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False

In [13]:
group_tail = group_cat.tail(1)
group_tail

   大区  城市 商品名称   单价  数量    总价   品类   是否包邮
6  华南  广州   裤子  299   6  1794   服饰   True
7  华南  深圳   毛巾   19  15   285  日用品  False
9  华东  上海   音箱  299   7  2093   数码  False

In [15]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [14]:
cat_indices = group_cat.indices
cat_indices

{'数码': array([0, 1, 2, 5, 8, 9]), '日用品': array([4, 7]), '服饰': array([3, 6])}

In [16]:
cat_describe = group_cat['总价'].describe()
cat_describe

     count         mean          std     min      25%     50%      75%     max
品类
数码     6.0  3595.166667  2779.295840   792.0  2019.50  2395.0  5172.75  7996.0
日用品    2.0   732.500000   632.860569   285.0   508.75   732.5   956.25  1180.0
服饰     2.0  1892.000000   138.592929  1794.0  1843.00  1892.0  1941.00  1990.0

In [17]:
east_groups = [name for name in group_multi.groups.keys() if name[0] == '华东']
east_groups

[('华东', '上海')]

In [18]:
east_shanghai = group_multi.get_group(('华东', '上海'))
east_shanghai

   大区  城市 商品名称   单价  数量    总价  品类   是否包邮
2  华东  上海   耳机  399   5  1995  数码  False
5  华东  上海   鼠标   99   8   792  数码  False
9  华东  上海   音箱  299   7  2093  数码  False

In [19]:
east_shanghai['总价'].sum()

np.int64(4880)