In [1]:
import pandas as pd

In [2]:
file_path = r'crosstab_data.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称   品类   是否包邮  销量 客户等级
0  华北  北京   手机   数码   True   2  VIP
1  华北  北京   键盘   数码   True   3   普通
2  华东  上海   耳机   数码  False   5  VIP
3  华南  广州   卫衣   服饰   True  10   普通
4  华南  深圳   水杯  日用品  False  20  VIP
5  华东  上海   鼠标   数码  False   8   普通
6  华南  广州   裤子   服饰   True   6  VIP
7  华南  深圳   毛巾  日用品  False  15   普通
8  华北  北京   平板   数码   True   4  VIP
9  华东  上海   音箱   数码  False   7  VIP

In [3]:
ct_basic = pd.crosstab(df['品类'], df['是否包邮'])
ct_basic

是否包邮  False  True
品类
数码        3      3
日用品       2      0
服饰        0      2

In [4]:
ct_margin = pd.crosstab(df['品类'], df['是否包邮'], margins=True, margins_name='总计')

ct_margin

是否包邮  False  True  总计
品类
数码        3     3   6
日用品       2     0   2
服饰        0     2   2
总计        5     5  10

In [5]:
df

   大区  城市 商品名称   品类   是否包邮  销量 客户等级
0  华北  北京   手机   数码   True   2  VIP
1  华北  北京   键盘   数码   True   3   普通
2  华东  上海   耳机   数码  False   5  VIP
3  华南  广州   卫衣   服饰   True  10   普通
4  华南  深圳   水杯  日用品  False  20  VIP
5  华东  上海   鼠标   数码  False   8   普通
6  华南  广州   裤子   服饰   True   6  VIP
7  华南  深圳   毛巾  日用品  False  15   普通
8  华北  北京   平板   数码   True   4  VIP
9  华东  上海   音箱   数码  False   7  VIP

In [6]:
ct_sum = pd.crosstab(df['大区'], df['客户等级'], values=df['销量'], aggfunc='sum')

ct_sum

客户等级  VIP  普通
大区
华东     12   8
华北      6   3
华南     26  25

In [7]:
ct_mean = pd.crosstab(df['大区'], df['客户等级'], values=df['销量'], aggfunc='mean').round(2)

ct_mean

客户等级   VIP    普通
大区
华东     6.0   8.0
华北     3.0   3.0
华南    13.0  12.5

In [8]:
df

   大区  城市 商品名称   品类   是否包邮  销量 客户等级
0  华北  北京   手机   数码   True   2  VIP
1  华北  北京   键盘   数码   True   3   普通
2  华东  上海   耳机   数码  False   5  VIP
3  华南  广州   卫衣   服饰   True  10   普通
4  华南  深圳   水杯  日用品  False  20  VIP
5  华东  上海   鼠标   数码  False   8   普通
6  华南  广州   裤子   服饰   True   6  VIP
7  华南  深圳   毛巾  日用品  False  15   普通
8  华北  北京   平板   数码   True   4  VIP
9  华东  上海   音箱   数码  False   7  VIP

In [9]:
ct_row_multi = pd.crosstab([df['大区'], df['品类']], df['是否包邮'], margins=True)

ct_row_multi

是否包邮     False  True  All
大区  品类
华东  数码       3     0    3
华北  数码       0     3    3
华南  日用品      2     0    2
    服饰       0     2    2
All          5     5   10

In [10]:
ct_col_multi = pd.crosstab(df['客户等级'], [df['品类'], df['是否包邮']])

ct_col_multi

品类      数码         日用品    服饰
是否包邮 False True  False True
客户等级
VIP      2     2     1     1
普通       1     1     1     1

In [11]:
ct_row_pct = pd.crosstab(df['品类'], df['是否包邮'], normalize='index').round(2) * 100

ct_row_pct

是否包邮  False  True
品类
数码     50.0   50.0
日用品   100.0    0.0
服饰      0.0  100.0

In [12]:
ct_basic

是否包邮  False  True
品类
数码        3      3
日用品       2      0
服饰        0      2

In [15]:
df

   大区  城市 商品名称   品类   是否包邮  销量 客户等级
0  华北  北京   手机   数码   True   2  VIP
1  华北  北京   键盘   数码   True   3   普通
2  华东  上海   耳机   数码  False   5  VIP
3  华南  广州   卫衣   服饰   True  10   普通
4  华南  深圳   水杯  日用品  False  20  VIP
5  华东  上海   鼠标   数码  False   8   普通
6  华南  广州   裤子   服饰   True   6  VIP
7  华南  深圳   毛巾  日用品  False  15   普通
8  华北  北京   平板   数码   True   4  VIP
9  华东  上海   音箱   数码  False   7  VIP

In [14]:
ct_col_pct = pd.crosstab(df['品类'], df['是否包邮'], normalize='columns').round(2) * 100
ct_col_pct

是否包邮  False  True
品类
数码     60.0   60.0
日用品    40.0    0.0
服饰      0.0   40.0

In [17]:
ct_fill = pd.crosstab(df['大区'], df['品类']).fillna(0)

ct_fill

品类  数码  日用品  服饰
大区
华东   3    0   0
华北   3    0   0
华南   0    2   2