In [1]:
import pandas as pd

In [2]:
file_path = r'pivot_table.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [3]:
pivot_basic = pd.pivot_table(
    df,
    index='品类',
    values='总价',
    aggfunc='sum'
)

pivot_basic

        总价
品类
数码   21571
日用品   1465
服饰    3784

In [4]:
pivot_multi = pd.pivot_table(
    df,
    index='大区',
    columns='品类',
    values='总价',
    aggfunc='sum',
    fill_value=0
)

pivot_multi

品类     数码   日用品    服饰
大区
华东   4880     0     0
华北  16691     0     0
华南      0  1465  3784

In [5]:
pivot_multi_val = pd.pivot_table(
    df,
    index='城市',
    values=['数量', '总价'],
    aggfunc={'数量': 'sum', '总价': ['sum', 'mean']},
    fill_value=0
).round(2)

pivot_multi_val

         总价         数量
       mean    sum sum
城市
上海  1626.67   4880  20
北京  5563.67  16691   9
广州  1892.00   3784  16
深圳   732.50   1465  35

In [7]:
df

   大区  城市 商品名称    单价  数量    总价   品类   是否包邮
0  华北  北京   手机  2999   2  5998   数码   True
1  华北  北京   键盘   899   3  2697   数码   True
2  华东  上海   耳机   399   5  1995   数码  False
3  华南  广州   卫衣   199  10  1990   服饰   True
4  华南  深圳   水杯    59  20  1180  日用品  False
5  华东  上海   鼠标    99   8   792   数码  False
6  华南  广州   裤子   299   6  1794   服饰   True
7  华南  深圳   毛巾    19  15   285  日用品  False
8  华北  北京   平板  1999   4  7996   数码   True
9  华东  上海   音箱   299   7  2093   数码  False

In [6]:
pivot_hier = pd.pivot_table(
    df,
    index=['大区', '城市'],
    columns=['品类', '是否包邮'],
    values='总价',
    aggfunc='sum',
    fill_value=0
)

pivot_hier

品类       数码          日用品    服饰
是否包邮  False  True  False True
大区 城市
华东 上海  4880      0     0     0
华北 北京     0  16691     0     0
华南 广州     0      0     0  3784
   深圳     0      0  1465     0

In [8]:
pivot_multi

品类     数码   日用品    服饰
大区
华东   4880     0     0
华北  16691     0     0
华南      0  1465  3784

In [9]:
pivot_reset = pivot_multi.reset_index()

pivot_reset

品类  大区     数码   日用品    服饰
0   华东   4880     0     0
1   华北  16691     0     0
2   华南      0  1465  3784

In [10]:
pivot_multi_val

         总价         数量
       mean    sum sum
城市
上海  1626.67   4880  20
北京  5563.67  16691   9
广州  1892.00   3784  16
深圳   732.50   1465  35

In [11]:
pivot_multi_val.columns

MultiIndex([('总价', 'mean'),
            ('总价',  'sum'),
            ('数量',  'sum')],
           )

In [12]:
pivot_flat = pivot_multi_val.columns.map('_'.join)
pivot_flat

Index(['总价_mean', '总价_sum', '数量_sum'], dtype='str')

In [13]:
pivot_multi_val.columns = pivot_flat
pivot_multi_val

    总价_mean  总价_sum  数量_sum
城市
上海  1626.67    4880      20
北京  5563.67   16691       9
广州  1892.00    3784      16
深圳   732.50    1465      35

In [14]:
pivot_multi

品类     数码   日用品    服饰
大区
华东   4880     0     0
华北  16691     0     0
华南      0  1465  3784

In [15]:
pivot_filter = pivot_multi[pivot_multi['数码'] > 2000]
pivot_filter

品类     数码  日用品  服饰
大区
华东   4880    0   0
华北  16691    0   0