In [1]:
import pandas as pd

In [2]:
file_path = r'time_index_filter.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['销售时间'],
    index_col='销售时间'
)

df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   音箱   40  11960  北京
2024-06-01 10:00:00   手表   18   8998  上海

In [3]:
df_0501 = df.loc['2024-05-01']
df_0501

                    商品名称  销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机  20  59980  北京
2024-05-01 14:20:00   耳机  15   5985  北京

In [4]:
df_0502_0505 = df.loc['2024-05-02': '2024-05-05']
df_0502_0505

                    商品名称   销量    销售额  城市
销售时间
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳

In [5]:
df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   音箱   40  11960  北京
2024-06-01 10:00:00   手表   18   8998  上海

In [6]:
df_may = df.loc['2024-05']
df_may

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   音箱   40  11960  北京

In [7]:
df_june = df.loc['2024-06']
df_june

                    商品名称  销量   销售额  城市
销售时间
2024-06-01 10:00:00   手表  18  8998  上海

In [8]:
df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   音箱   40  11960  北京
2024-06-01 10:00:00   手表   18   8998  上海

In [9]:
df_morning = df.between_time('9:00', '12:00')
df_morning

                    商品名称   销量    销售额  城市
销售时间
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-10 09:00:00   音箱   40  11960  北京
2024-06-01 10:00:00   手表   18   8998  上海

In [10]:
df_1000 = df.at_time('10:00')
df_1000

                    商品名称   销量   销售额  城市
销售时间
2024-05-03 10:00:00   水杯  100  5900  广州
2024-06-01 10:00:00   手表   18  8998  上海

In [11]:
df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   音箱   40  11960  北京
2024-06-01 10:00:00   手表   18   8998  上海

In [12]:
df_0503_afternoon = df.loc['2024-05-03'].between_time('11:00', '17:00')
df_0503_afternoon

                    商品名称  销量    销售额  城市
销售时间
2024-05-03 16:40:00   键盘  30  26970  广州

In [13]:
df

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   音箱   40  11960  北京
2024-06-01 10:00:00   手表   18   8998  上海

In [14]:
df['工作日'] = df.index.dayofweek
df

                    商品名称   销量    销售额  城市  工作日
销售时间
2024-05-01 08:30:00   手机   20  59980  北京    2
2024-05-01 14:20:00   耳机   15   5985  北京    2
2024-05-02 09:10:00   卫衣   80  15920  上海    3
2024-05-03 10:00:00   水杯  100   5900  广州    4
2024-05-03 16:40:00   键盘   30  26970  广州    4
2024-05-04 11:20:00   鼠标   60   5940  深圳    5
2024-05-05 15:10:00   平板   25  49975  深圳    6
2024-05-10 09:00:00   音箱   40  11960  北京    4
2024-06-01 10:00:00   手表   18   8998  上海    5

In [15]:
df_workday = df[df['工作日'] <= 4]
df_workday

                    商品名称   销量    销售额  城市  工作日
销售时间
2024-05-01 08:30:00   手机   20  59980  北京    2
2024-05-01 14:20:00   耳机   15   5985  北京    2
2024-05-02 09:10:00   卫衣   80  15920  上海    3
2024-05-03 10:00:00   水杯  100   5900  广州    4
2024-05-03 16:40:00   键盘   30  26970  广州    4
2024-05-10 09:00:00   音箱   40  11960  北京    4

In [18]:
df_monday = df[df.index.dayofweek == 0]

df_monday

Empty DataFrame
Columns: [商品名称, 销量, 销售额, 城市, 工作日]
Index: []

In [19]:
df_cross_month = df.loc['2024-05-10': '2024-06-01']
df_cross_month

                    商品名称  销量    销售额  城市  工作日
销售时间
2024-05-10 09:00:00   音箱  40  11960  北京    4
2024-06-01 10:00:00   手表  18   8998  上海    5

In [20]:
df

                    商品名称   销量    销售额  城市  工作日
销售时间
2024-05-01 08:30:00   手机   20  59980  北京    2
2024-05-01 14:20:00   耳机   15   5985  北京    2
2024-05-02 09:10:00   卫衣   80  15920  上海    3
2024-05-03 10:00:00   水杯  100   5900  广州    4
2024-05-03 16:40:00   键盘   30  26970  广州    4
2024-05-04 11:20:00   鼠标   60   5940  深圳    5
2024-05-05 15:10:00   平板   25  49975  深圳    6
2024-05-10 09:00:00   音箱   40  11960  北京    4
2024-06-01 10:00:00   手表   18   8998  上海    5

In [21]:
df_hour_9 = df[df.index.hour == 9]
df_hour_9

                    商品名称  销量    销售额  城市  工作日
销售时间
2024-05-02 09:10:00   卫衣  80  15920  上海    3
2024-05-10 09:00:00   音箱  40  11960  北京    4

In [22]:
df_day_01 = df[df.index.day == 1]

df_day_01

                    商品名称  销量    销售额  城市  工作日
销售时间
2024-05-01 08:30:00   手机  20  59980  北京    2
2024-05-01 14:20:00   耳机  15   5985  北京    2
2024-06-01 10:00:00   手表  18   8998  上海    5

In [25]:
df_bj_may_morning = df[
    (df.index.month == 5) &
    (df['城市'] == '北京') &
    (df.index.hour >= 8) &  # 小时 >=8
    (df.index.hour <= 12)  # 小时 <=12
    ]

df_bj_may_morning

                    商品名称  销量    销售额  城市  工作日
销售时间
2024-05-01 08:30:00   手机  20  59980  北京    2
2024-05-10 09:00:00   音箱  40  11960  北京    4

In [26]:
df

                    商品名称   销量    销售额  城市  工作日
销售时间
2024-05-01 08:30:00   手机   20  59980  北京    2
2024-05-01 14:20:00   耳机   15   5985  北京    2
2024-05-02 09:10:00   卫衣   80  15920  上海    3
2024-05-03 10:00:00   水杯  100   5900  广州    4
2024-05-03 16:40:00   键盘   30  26970  广州    4
2024-05-04 11:20:00   鼠标   60   5940  深圳    5
2024-05-05 15:10:00   平板   25  49975  深圳    6
2024-05-10 09:00:00   音箱   40  11960  北京    4
2024-06-01 10:00:00   手表   18   8998  上海    5

In [27]:
df_none = df.loc['2024-07-01'] if '2024-07-01' in df.index else pd.DataFrame()

df_none

Empty DataFrame
Columns: []
Index: []

In [28]:
df

                    商品名称   销量    销售额  城市  工作日
销售时间
2024-05-01 08:30:00   手机   20  59980  北京    2
2024-05-01 14:20:00   耳机   15   5985  北京    2
2024-05-02 09:10:00   卫衣   80  15920  上海    3
2024-05-03 10:00:00   水杯  100   5900  广州    4
2024-05-03 16:40:00   键盘   30  26970  广州    4
2024-05-04 11:20:00   鼠标   60   5940  深圳    5
2024-05-05 15:10:00   平板   25  49975  深圳    6
2024-05-10 09:00:00   音箱   40  11960  北京    4
2024-06-01 10:00:00   手表   18   8998  上海    5

In [29]:
df_may

                    商品名称   销量    销售额  城市
销售时间
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳
2024-05-10 09:00:00   音箱   40  11960  北京

In [30]:
df_may_city_sales = df_may.groupby('城市')['销量'].sum()

df_may_city_sales

城市
上海     80
北京     75
广州    130
深圳     85
Name: 销量, dtype: int64