In [1]:
import pandas as pd

In [2]:
file_path = r'time_index.csv'
df = pd.read_csv(file_path, encoding='utf-8')

df

               销售日期 商品名称   销量    销售额  城市
0  2024-05-01 08:30   手机   20  59980  北京
1  2024-05-01 14:20   耳机   15   5985  北京
2  2024-05-02 09:10   卫衣   80  15920  上海
3  2024-05-03 10:00   水杯  100   5900  广州
4  2024-05-03 16:40   键盘   30  26970  广州
5  2024-05-04 11:20   鼠标   60   5940  深圳
6  2024-05-05 15:10   平板   25  49975  深圳

In [3]:
df['销售日期'] = pd.to_datetime(df['销售日期'])

df

                 销售日期 商品名称   销量    销售额  城市
0 2024-05-01 08:30:00   手机   20  59980  北京
1 2024-05-01 14:20:00   耳机   15   5985  北京
2 2024-05-02 09:10:00   卫衣   80  15920  上海
3 2024-05-03 10:00:00   水杯  100   5900  广州
4 2024-05-03 16:40:00   键盘   30  26970  广州
5 2024-05-04 11:20:00   鼠标   60   5940  深圳
6 2024-05-05 15:10:00   平板   25  49975  深圳

In [4]:
df_time_idx = df.set_index('销售日期')
df_time_idx

                    商品名称   销量    销售额  城市
销售日期
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳

In [5]:
df_read_idx = pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['销售日期'],
    index_col='销售日期'
)

df_read_idx

                    商品名称   销量    销售额  城市
销售日期
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳

In [6]:
df_0501 = df_time_idx.loc['2024-05-01']

df_0501

                    商品名称  销量    销售额  城市
销售日期
2024-05-01 08:30:00   手机  20  59980  北京
2024-05-01 14:20:00   耳机  15   5985  北京

In [8]:
df_time_idx

                    商品名称   销量    销售额  城市
销售日期
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳

In [7]:
df_0502_0504 = df_time_idx.loc['2024-05-02': '2024-05-04']
df_0502_0504

                    商品名称   销量    销售额  城市
销售日期
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳

In [9]:
df_0501_morning = df_time_idx.between_time('08:00', '12:00').loc['2024-05-01']
df_0501_morning

                    商品名称  销量    销售额  城市
销售日期
2024-05-01 08:30:00   手机  20  59980  北京

In [10]:
df_time_idx

                    商品名称   销量    销售额  城市
销售日期
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳

In [11]:
df_reset = df_time_idx.reset_index()
df_reset

                 销售日期 商品名称   销量    销售额  城市
0 2024-05-01 08:30:00   手机   20  59980  北京
1 2024-05-01 14:20:00   耳机   15   5985  北京
2 2024-05-02 09:10:00   卫衣   80  15920  上海
3 2024-05-03 10:00:00   水杯  100   5900  广州
4 2024-05-03 16:40:00   键盘   30  26970  广州
5 2024-05-04 11:20:00   鼠标   60   5940  深圳
6 2024-05-05 15:10:00   平板   25  49975  深圳

In [12]:
df_daily = df_time_idx.resample('D')['销量'].sum()
df_daily

销售日期
2024-05-01     35
2024-05-02     80
2024-05-03    130
2024-05-04     60
2024-05-05     25
Freq: D, Name: 销量, dtype: int64

In [13]:
df_time_idx

                    商品名称   销量    销售额  城市
销售日期
2024-05-01 08:30:00   手机   20  59980  北京
2024-05-01 14:20:00   耳机   15   5985  北京
2024-05-02 09:10:00   卫衣   80  15920  上海
2024-05-03 10:00:00   水杯  100   5900  广州
2024-05-03 16:40:00   键盘   30  26970  广州
2024-05-04 11:20:00   鼠标   60   5940  深圳
2024-05-05 15:10:00   平板   25  49975  深圳

In [14]:
df_time_idx['年'] = df_time_idx.index.year
df_time_idx['小时'] = df_time_idx.index.hour

df_time_idx

                    商品名称   销量    销售额  城市     年  小时
销售日期
2024-05-01 08:30:00   手机   20  59980  北京  2024   8
2024-05-01 14:20:00   耳机   15   5985  北京  2024  14
2024-05-02 09:10:00   卫衣   80  15920  上海  2024   9
2024-05-03 10:00:00   水杯  100   5900  广州  2024  10
2024-05-03 16:40:00   键盘   30  26970  广州  2024  16
2024-05-04 11:20:00   鼠标   60   5940  深圳  2024  11
2024-05-05 15:10:00   平板   25  49975  深圳  2024  15

In [15]:
df_split = df_reset.copy()

df_split

                 销售日期 商品名称   销量    销售额  城市
0 2024-05-01 08:30:00   手机   20  59980  北京
1 2024-05-01 14:20:00   耳机   15   5985  北京
2 2024-05-02 09:10:00   卫衣   80  15920  上海
3 2024-05-03 10:00:00   水杯  100   5900  广州
4 2024-05-03 16:40:00   键盘   30  26970  广州
5 2024-05-04 11:20:00   鼠标   60   5940  深圳
6 2024-05-05 15:10:00   平板   25  49975  深圳

In [16]:
df_split['日期'] = df_split['销售日期'].dt.date
df_split['时间'] = df_split['销售日期'].dt.time

df_split

                 销售日期 商品名称   销量    销售额  城市          日期        时间
0 2024-05-01 08:30:00   手机   20  59980  北京  2024-05-01  08:30:00
1 2024-05-01 14:20:00   耳机   15   5985  北京  2024-05-01  14:20:00
2 2024-05-02 09:10:00   卫衣   80  15920  上海  2024-05-02  09:10:00
3 2024-05-03 10:00:00   水杯  100   5900  广州  2024-05-03  10:00:00
4 2024-05-03 16:40:00   键盘   30  26970  广州  2024-05-03  16:40:00
5 2024-05-04 11:20:00   鼠标   60   5940  深圳  2024-05-04  11:20:00
6 2024-05-05 15:10:00   平板   25  49975  深圳  2024-05-05  15:10:00

In [17]:
df_split['组合时间'] = pd.to_datetime(df_split['日期'].astype(str) + ' ' + df_split['时间'].astype(str))

df_split

,销售日期,商品名称,销量,销售额,城市,日期,时间,组合时间
0,2024-05-01 08:30:00,手机,20,59980,北京,2024-05-01,08:30:00,2024-05-01 08:30:00
1,2024-05-01 14:20:00,耳机,15,5985,北京,2024-05-01,14:20:00,2024-05-01 14:20:00
2,2024-05-02 09:10:00,卫衣,80,15920,上海,2024-05-02,09:10:00,2024-05-02 09:10:00
3,2024-05-03 10:00:00,水杯,100,5900,广州,2024-05-03,10:00:00,2024-05-03 10:00:00
4,2024-05-03 16:40:00,键盘,30,26970,广州,2024-05-03,16:40:00,2024-05-03 16:40:00
5,2024-05-04 11:20:00,鼠标,60,5940,深圳,2024-05-04,11:20:00,2024-05-04 11:20:00
6,2024-05-05 15:10:00,平板,25,49975,深圳,2024-05-05,15:10:00,2024-05-05 15:10:00

In [18]:
df_split_idx = df_split.set_index('组合时间')
df_split_idx

,销售日期,商品名称,销量,销售额,城市,日期,时间
组合时间,,,,,,,
2024-05-01 08:30:00,2024-05-01 08:30:00,手机,20,59980,北京,2024-05-01,08:30:00
2024-05-01 14:20:00,2024-05-01 14:20:00,耳机,15,5985,北京,2024-05-01,14:20:00
2024-05-02 09:10:00,2024-05-02 09:10:00,卫衣,80,15920,上海,2024-05-02,09:10:00
2024-05-03 10:00:00,2024-05-03 10:00:00,水杯,100,5900,广州,2024-05-03,10:00:00
2024-05-03 16:40:00,2024-05-03 16:40:00,键盘,30,26970,广州,2024-05-03,16:40:00
2024-05-04 11:20:00,2024-05-04 11:20:00,鼠标,60,5940,深圳,2024-05-04,11:20:00
2024-05-05 15:10:00,2024-05-05 15:10:00,平板,25,49975,深圳,2024-05-05,15:10:00

In [19]:
df_time_idx

                    商品名称   销量    销售额  城市     年  小时
销售日期
2024-05-01 08:30:00   手机   20  59980  北京  2024   8
2024-05-01 14:20:00   耳机   15   5985  北京  2024  14
2024-05-02 09:10:00   卫衣   80  15920  上海  2024   9
2024-05-03 10:00:00   水杯  100   5900  广州  2024  10
2024-05-03 16:40:00   键盘   30  26970  广州  2024  16
2024-05-04 11:20:00   鼠标   60   5940  深圳  2024  11
2024-05-05 15:10:00   平板   25  49975  深圳  2024  15

In [20]:
df_time_idx.index.duplicated().any()

np.False_

In [22]:
date_hour_seq = pd.date_range(start='2024-05-01 08:00', end='2024-05-05 16:00', freq='h')

date_hour_seq

DatetimeIndex(['2024-05-01 08:00:00', '2024-05-01 09:00:00',
               '2024-05-01 10:00:00', '2024-05-01 11:00:00',
               '2024-05-01 12:00:00', '2024-05-01 13:00:00',
               '2024-05-01 14:00:00', '2024-05-01 15:00:00',
               '2024-05-01 16:00:00', '2024-05-01 17:00:00',
               ...
               '2024-05-05 07:00:00', '2024-05-05 08:00:00',
               '2024-05-05 09:00:00', '2024-05-05 10:00:00',
               '2024-05-05 11:00:00', '2024-05-05 12:00:00',
               '2024-05-05 13:00:00', '2024-05-05 14:00:00',
               '2024-05-05 15:00:00', '2024-05-05 16:00:00'],
              dtype='datetime64[us]', length=105, freq='h')

In [23]:
df_full_hour = df_time_idx.reindex(date_hour_seq, fill_value="0")

df_full_hour

                    商品名称 销量 销售额 城市  年 小时
2024-05-01 08:00:00    0  0   0  0  0  0
2024-05-01 09:00:00    0  0   0  0  0  0
2024-05-01 10:00:00    0  0   0  0  0  0
2024-05-01 11:00:00    0  0   0  0  0  0
2024-05-01 12:00:00    0  0   0  0  0  0
...                  ... ..  .. .. .. ..
2024-05-05 12:00:00    0  0   0  0  0  0
2024-05-05 13:00:00    0  0   0  0  0  0
2024-05-05 14:00:00    0  0   0  0  0  0
2024-05-05 15:00:00    0  0   0  0  0  0
2024-05-05 16:00:00    0  0   0  0  0  0

[105 rows x 6 columns]

In [24]:
df_reset

                 销售日期 商品名称   销量    销售额  城市
0 2024-05-01 08:30:00   手机   20  59980  北京
1 2024-05-01 14:20:00   耳机   15   5985  北京
2 2024-05-02 09:10:00   卫衣   80  15920  上海
3 2024-05-03 10:00:00   水杯  100   5900  广州
4 2024-05-03 16:40:00   键盘   30  26970  广州
5 2024-05-04 11:20:00   鼠标   60   5940  深圳
6 2024-05-05 15:10:00   平板   25  49975  深圳

In [28]:
df_reset['销售日期_天'] = df_reset['销售日期'].dt.date

df_reset

                 销售日期 商品名称   销量    销售额  城市      销售日期_天
0 2024-05-01 08:30:00   手机   20  59980  北京  2024-05-01
1 2024-05-01 14:20:00   耳机   15   5985  北京  2024-05-01
2 2024-05-02 09:10:00   卫衣   80  15920  上海  2024-05-02
3 2024-05-03 10:00:00   水杯  100   5900  广州  2024-05-03
4 2024-05-03 16:40:00   键盘   30  26970  广州  2024-05-03
5 2024-05-04 11:20:00   鼠标   60   5940  深圳  2024-05-04
6 2024-05-05 15:10:00   平板   25  49975  深圳  2024-05-05

In [29]:
city_daily_sales = df_reset.groupby(['城市', '销售日期_天'])['销量'].sum()
city_daily_sales

城市  销售日期_天
上海  2024-05-02     80
北京  2024-05-01     35
广州  2024-05-03    130
深圳  2024-05-04     60
    2024-05-05     25
Name: 销量, dtype: int64

In [32]:
df_time_idx

                    商品名称   销量    销售额  城市     年  小时
销售日期
2024-05-01 08:30:00   手机   20  59980  北京  2024   8
2024-05-01 14:20:00   耳机   15   5985  北京  2024  14
2024-05-02 09:10:00   卫衣   80  15920  上海  2024   9
2024-05-03 10:00:00   水杯  100   5900  广州  2024  10
2024-05-03 16:40:00   键盘   30  26970  广州  2024  16
2024-05-04 11:20:00   鼠标   60   5940  深圳  2024  11
2024-05-05 15:10:00   平板   25  49975  深圳  2024  15

In [31]:
date_minute_seq = pd.date_range(start='2024-05-01 08:00', end='2024-05-05 16:00', freq='10min')

date_minute_seq

DatetimeIndex(['2024-05-01 08:00:00', '2024-05-01 08:10:00',
               '2024-05-01 08:20:00', '2024-05-01 08:30:00',
               '2024-05-01 08:40:00', '2024-05-01 08:50:00',
               '2024-05-01 09:00:00', '2024-05-01 09:10:00',
               '2024-05-01 09:20:00', '2024-05-01 09:30:00',
               ...
               '2024-05-05 14:30:00', '2024-05-05 14:40:00',
               '2024-05-05 14:50:00', '2024-05-05 15:00:00',
               '2024-05-05 15:10:00', '2024-05-05 15:20:00',
               '2024-05-05 15:30:00', '2024-05-05 15:40:00',
               '2024-05-05 15:50:00', '2024-05-05 16:00:00'],
              dtype='datetime64[us]', length=625, freq='10min')

In [33]:
df_full_minute = df_time_idx.reindex(date_minute_seq, fill_value="0")

df_full_minute

                    商品名称  销量    销售额  城市     年 小时
2024-05-01 08:00:00    0   0      0   0     0  0
2024-05-01 08:10:00    0   0      0   0     0  0
2024-05-01 08:20:00    0   0      0   0     0  0
2024-05-01 08:30:00   手机  20  59980  北京  2024  8
2024-05-01 08:40:00    0   0      0   0     0  0
...                  ...  ..    ...  ..   ... ..
2024-05-05 15:20:00    0   0      0   0     0  0
2024-05-05 15:30:00    0   0      0   0     0  0
2024-05-05 15:40:00    0   0      0   0     0  0
2024-05-05 15:50:00    0   0      0   0     0  0
2024-05-05 16:00:00    0   0      0   0     0  0

[625 rows x 6 columns]