In [1]:
import pandas as pd

In [2]:
file_path = r'time_series.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

         销售日期 商品名称   销量    销售额
0  2024-05-01   手机   20  59980
1  2024-05-02   耳机   50  19950
2  2024-05-04   卫衣   80  15920
3  2024-05-05   水杯  100   5900
4  2024-05-07   键盘   30  26970
5  2024-05-08   鼠标   60   5940

In [3]:
df['销售日期'] = pd.to_datetime(df['销售日期'])
df

        销售日期 商品名称   销量    销售额
0 2024-05-01   手机   20  59980
1 2024-05-02   耳机   50  19950
2 2024-05-04   卫衣   80  15920
3 2024-05-05   水杯  100   5900
4 2024-05-07   键盘   30  26970
5 2024-05-08   鼠标   60   5940

In [5]:
date_seq_basic = pd.date_range(start='2024-05-01', end='2024-05-08', freq='D')

date_seq_basic

DatetimeIndex(['2024-05-01', '2024-05-02', '2024-05-03', '2024-05-04',
               '2024-05-05', '2024-05-06', '2024-05-07', '2024-05-08'],
              dtype='datetime64[us]', freq='D')

In [6]:
date_seq_days = pd.date_range(start='2024-05-01', periods=8, freq='D')

date_seq_days

DatetimeIndex(['2024-05-01', '2024-05-02', '2024-05-03', '2024-05-04',
               '2024-05-05', '2024-05-06', '2024-05-07', '2024-05-08'],
              dtype='datetime64[us]', freq='D')

In [8]:
date_seq_hour = pd.date_range(start='2024-05-01', periods=6, freq='2h')

date_seq_hour

DatetimeIndex(['2024-05-01 00:00:00', '2024-05-01 02:00:00',
               '2024-05-01 04:00:00', '2024-05-01 06:00:00',
               '2024-05-01 08:00:00', '2024-05-01 10:00:00'],
              dtype='datetime64[us]', freq='2h')

In [9]:
date_seq_week = pd.date_range(start='2024-05-01', periods=4, freq='W-MON')

date_seq_week

DatetimeIndex(['2024-05-06', '2024-05-13', '2024-05-20', '2024-05-27'], dtype='datetime64[us]', freq='W-MON')

In [11]:
date_seq_month = pd.date_range(start='2024-01-01', periods=3, freq='ME')

date_seq_month

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31'], dtype='datetime64[us]', freq='ME')

In [12]:
df

        销售日期 商品名称   销量    销售额
0 2024-05-01   手机   20  59980
1 2024-05-02   耳机   50  19950
2 2024-05-04   卫衣   80  15920
3 2024-05-05   水杯  100   5900
4 2024-05-07   键盘   30  26970
5 2024-05-08   鼠标   60   5940

In [13]:
df_time_idx = df.set_index('销售日期')

In [15]:
df_null = df_time_idx.reindex(date_seq_basic, fill_value="0")

df_null

           商品名称   销量    销售额
2024-05-01   手机   20  59980
2024-05-02   耳机   50  19950
2024-05-03    0    0      0
2024-05-04   卫衣   80  15920
2024-05-05   水杯  100   5900
2024-05-06    0    0      0
2024-05-07   键盘   30  26970
2024-05-08   鼠标   60   5940

In [16]:
df_null = df_null.reset_index().rename(columns={'index': '销售日期'})
df_null

        销售日期 商品名称   销量    销售额
0 2024-05-01   手机   20  59980
1 2024-05-02   耳机   50  19950
2 2024-05-03    0    0      0
3 2024-05-04   卫衣   80  15920
4 2024-05-05   水杯  100   5900
5 2024-05-06    0    0      0
6 2024-05-07   键盘   30  26970
7 2024-05-08   鼠标   60   5940

In [17]:
date_seq_tz = pd.date_range(start='2024-05-01', periods=3, freq='D', tz='Asia/Shanghai')

date_seq_tz

DatetimeIndex(['2024-05-01 00:00:00+08:00', '2024-05-02 00:00:00+08:00',
               '2024-05-03 00:00:00+08:00'],
              dtype='datetime64[us, Asia/Shanghai]', freq='D')

In [19]:
date_seq_workay = pd.date_range(start='2026-03-28', end='2026-04-10', freq='B')
date_seq_workay

DatetimeIndex(['2026-03-30', '2026-03-31', '2026-04-01', '2026-04-02',
               '2026-04-03', '2026-04-06', '2026-04-07', '2026-04-08',
               '2026-04-09', '2026-04-10'],
              dtype='datetime64[us]', freq='B')

In [20]:
date_seq_dup = pd.date_range(start='2024-05-01', periods=3, freq='D')

date_seq_dup

DatetimeIndex(['2024-05-01', '2024-05-02', '2024-05-03'], dtype='datetime64[us]', freq='D')

In [21]:
date_seq_uniq = pd.Index(date_seq_dup).unique()

date_seq_uniq

DatetimeIndex(['2024-05-01', '2024-05-02', '2024-05-03'], dtype='datetime64[us]', freq='D')

In [22]:
df

        销售日期 商品名称   销量    销售额
0 2024-05-01   手机   20  59980
1 2024-05-02   耳机   50  19950
2 2024-05-04   卫衣   80  15920
3 2024-05-05   水杯  100   5900
4 2024-05-07   键盘   30  26970
5 2024-05-08   鼠标   60   5940

In [23]:
df_null

        销售日期 商品名称   销量    销售额
0 2024-05-01   手机   20  59980
1 2024-05-02   耳机   50  19950
2 2024-05-03    0    0      0
3 2024-05-04   卫衣   80  15920
4 2024-05-05   水杯  100   5900
5 2024-05-06    0    0      0
6 2024-05-07   键盘   30  26970
7 2024-05-08   鼠标   60   5940

In [26]:
df_null['销售日期_天'] = df_null['销售日期'].dt.date

daily_sales = df_null.groupby('销售日期_天')['销量'].sum()

daily_sales

销售日期_天
2024-05-01     20
2024-05-02     50
2024-05-03      0
2024-05-04     80
2024-05-05    100
2024-05-06      0
2024-05-07     30
2024-05-08     60
Name: 销量, dtype: object