In [1]:
import pandas as pd

In [2]:
file_path = r'sort_index.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1007   裤子   299   6  广州  1794
7  1008   毛巾    19  15  深圳   285
8  1009   平板  1999   4  北京  7996
9  1010   音箱   299   7  上海  2093

In [3]:
df = df.set_index('订单ID')
df

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697
1006   鼠标    99   8  上海   792
1007   裤子   299   6  广州  1794
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1010   音箱   299   7  上海  2093

In [7]:
df_shuffle = df.sample(frac=1, random_state=1)
df_shuffle

     商品名称    单价  数量  城市    总价
订单ID
1003   卫衣   199  10  广州  1990
1010   音箱   299   7  上海  2093
1007   裤子   299   6  广州  1794
1005   键盘   899   3  北京  2697
1001   手机  2999   2  北京  5998
1004   水杯    59  20  深圳  1180
1002   耳机   399   5  上海  1995
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1006   鼠标    99   8  上海   792

In [8]:
df.index.tolist()

[1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010]

In [9]:
df_shuffle.index.tolist()

[1003, 1010, 1007, 1005, 1001, 1004, 1002, 1008, 1009, 1006]

In [10]:
sort_idx_asc = df_shuffle.sort_index(ascending=True)

sort_idx_asc

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697
1006   鼠标    99   8  上海   792
1007   裤子   299   6  广州  1794
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1010   音箱   299   7  上海  2093

In [11]:
sort_idx_desc = df_shuffle.sort_index(ascending=False)

sort_idx_desc

     商品名称    单价  数量  城市    总价
订单ID
1010   音箱   299   7  上海  2093
1009   平板  1999   4  北京  7996
1008   毛巾    19  15  深圳   285
1007   裤子   299   6  广州  1794
1006   鼠标    99   8  上海   792
1005   键盘   899   3  北京  2697
1004   水杯    59  20  深圳  1180
1003   卫衣   199  10  广州  1990
1002   耳机   399   5  上海  1995
1001   手机  2999   2  北京  5998

In [12]:
df_shuffle

     商品名称    单价  数量  城市    总价
订单ID
1003   卫衣   199  10  广州  1990
1010   音箱   299   7  上海  2093
1007   裤子   299   6  广州  1794
1005   键盘   899   3  北京  2697
1001   手机  2999   2  北京  5998
1004   水杯    59  20  深圳  1180
1002   耳机   399   5  上海  1995
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1006   鼠标    99   8  上海   792

In [13]:
sort_col_idx = df_shuffle.sort_index(axis=1, ascending=True)

sort_col_idx

        单价 商品名称  城市    总价  数量
订单ID
1003   199   卫衣  广州  1990  10
1010   299   音箱  上海  2093   7
1007   299   裤子  广州  1794   6
1005   899   键盘  北京  2697   3
1001  2999   手机  北京  5998   2
1004    59   水杯  深圳  1180  20
1002   399   耳机  上海  1995   5
1008    19   毛巾  深圳   285  15
1009  1999   平板  北京  7996   4
1006    99   鼠标  上海   792   8

In [14]:
df_shuffle

     商品名称    单价  数量  城市    总价
订单ID
1003   卫衣   199  10  广州  1990
1010   音箱   299   7  上海  2093
1007   裤子   299   6  广州  1794
1005   键盘   899   3  北京  2697
1001   手机  2999   2  北京  5998
1004   水杯    59  20  深圳  1180
1002   耳机   399   5  上海  1995
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1006   鼠标    99   8  上海   792

In [15]:
df_multi = df_shuffle.copy()
df_multi

     商品名称    单价  数量  城市    总价
订单ID
1003   卫衣   199  10  广州  1990
1010   音箱   299   7  上海  2093
1007   裤子   299   6  广州  1794
1005   键盘   899   3  北京  2697
1001   手机  2999   2  北京  5998
1004   水杯    59  20  深圳  1180
1002   耳机   399   5  上海  1995
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1006   鼠标    99   8  上海   792

In [16]:
df_multi['大区'] = df_multi['城市'].map({'北京': '华北', '上海': '华东', '广州': '华南', '深圳': '华南'})
df_multi

     商品名称    单价  数量  城市    总价  大区
订单ID
1003   卫衣   199  10  广州  1990  华南
1010   音箱   299   7  上海  2093  华东
1007   裤子   299   6  广州  1794  华南
1005   键盘   899   3  北京  2697  华北
1001   手机  2999   2  北京  5998  华北
1004   水杯    59  20  深圳  1180  华南
1002   耳机   399   5  上海  1995  华东
1008   毛巾    19  15  深圳   285  华南
1009   平板  1999   4  北京  7996  华北
1006   鼠标    99   8  上海   792  华东

In [17]:
df_multi = df_multi.set_index(['大区', df_multi.index])

df_multi

        商品名称    单价  数量  城市    总价
大区 订单ID
华南 1003   卫衣   199  10  广州  1990
华东 1010   音箱   299   7  上海  2093
华南 1007   裤子   299   6  广州  1794
华北 1005   键盘   899   3  北京  2697
   1001   手机  2999   2  北京  5998
华南 1004   水杯    59  20  深圳  1180
华东 1002   耳机   399   5  上海  1995
华南 1008   毛巾    19  15  深圳   285
华北 1009   平板  1999   4  北京  7996
华东 1006   鼠标    99   8  上海   792

In [18]:
sort_multi_idx = df_multi.sort_index(ascending=[True, False])
sort_multi_idx

        商品名称    单价  数量  城市    总价
大区 订单ID
华东 1010   音箱   299   7  上海  2093
   1006   鼠标    99   8  上海   792
   1002   耳机   399   5  上海  1995
华北 1009   平板  1999   4  北京  7996
   1005   键盘   899   3  北京  2697
   1001   手机  2999   2  北京  5998
华南 1008   毛巾    19  15  深圳   285
   1007   裤子   299   6  广州  1794
   1004   水杯    59  20  深圳  1180
   1003   卫衣   199  10  广州  1990

In [19]:
sort_idx_asc

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1002   耳机   399   5  上海  1995
1003   卫衣   199  10  广州  1990
1004   水杯    59  20  深圳  1180
1005   键盘   899   3  北京  2697
1006   鼠标    99   8  上海   792
1007   裤子   299   6  广州  1794
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1010   音箱   299   7  上海  2093

In [20]:
sort_reset = sort_idx_asc.reset_index()

sort_reset

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697
5  1006   鼠标    99   8  上海   792
6  1007   裤子   299   6  广州  1794
7  1008   毛巾    19  15  深圳   285
8  1009   平板  1999   4  北京  7996
9  1010   音箱   299   7  上海  2093

In [21]:
df_shuffle

     商品名称    单价  数量  城市    总价
订单ID
1003   卫衣   199  10  广州  1990
1010   音箱   299   7  上海  2093
1007   裤子   299   6  广州  1794
1005   键盘   899   3  北京  2697
1001   手机  2999   2  北京  5998
1004   水杯    59  20  深圳  1180
1002   耳机   399   5  上海  1995
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1006   鼠标    99   8  上海   792

In [22]:
df_null_idx = df_shuffle.copy()

df_null_idx

     商品名称    单价  数量  城市    总价
订单ID
1003   卫衣   199  10  广州  1990
1010   音箱   299   7  上海  2093
1007   裤子   299   6  广州  1794
1005   键盘   899   3  北京  2697
1001   手机  2999   2  北京  5998
1004   水杯    59  20  深圳  1180
1002   耳机   399   5  上海  1995
1008   毛巾    19  15  深圳   285
1009   平板  1999   4  北京  7996
1006   鼠标    99   8  上海   792

In [23]:
df_null_idx = df_null_idx.reset_index()
df_null_idx

   订单ID 商品名称    单价  数量  城市    总价
0  1003   卫衣   199  10  广州  1990
1  1010   音箱   299   7  上海  2093
2  1007   裤子   299   6  广州  1794
3  1005   键盘   899   3  北京  2697
4  1001   手机  2999   2  北京  5998
5  1004   水杯    59  20  深圳  1180
6  1002   耳机   399   5  上海  1995
7  1008   毛巾    19  15  深圳   285
8  1009   平板  1999   4  北京  7996
9  1006   鼠标    99   8  上海   792

In [24]:
df_null_idx.loc[2, '订单ID'] = None

df_null_idx

     订单ID 商品名称    单价  数量  城市    总价
0  1003.0   卫衣   199  10  广州  1990
1  1010.0   音箱   299   7  上海  2093
2     NaN   裤子   299   6  广州  1794
3  1005.0   键盘   899   3  北京  2697
4  1001.0   手机  2999   2  北京  5998
5  1004.0   水杯    59  20  深圳  1180
6  1002.0   耳机   399   5  上海  1995
7  1008.0   毛巾    19  15  深圳   285
8  1009.0   平板  1999   4  北京  7996
9  1006.0   鼠标    99   8  上海   792

In [25]:
df_null_idx = df_null_idx.set_index('订单ID')

df_null_idx

       商品名称    单价  数量  城市    总价
订单ID
1003.0   卫衣   199  10  广州  1990
1010.0   音箱   299   7  上海  2093
NaN      裤子   299   6  广州  1794
1005.0   键盘   899   3  北京  2697
1001.0   手机  2999   2  北京  5998
1004.0   水杯    59  20  深圳  1180
1002.0   耳机   399   5  上海  1995
1008.0   毛巾    19  15  深圳   285
1009.0   平板  1999   4  北京  7996
1006.0   鼠标    99   8  上海   792

In [26]:
sort_null_idx = df_null_idx.sort_index(na_position='last')
sort_null_idx

       商品名称    单价  数量  城市    总价
订单ID
1001.0   手机  2999   2  北京  5998
1002.0   耳机   399   5  上海  1995
1003.0   卫衣   199  10  广州  1990
1004.0   水杯    59  20  深圳  1180
1005.0   键盘   899   3  北京  2697
1006.0   鼠标    99   8  上海   792
1008.0   毛巾    19  15  深圳   285
1009.0   平板  1999   4  北京  7996
1010.0   音箱   299   7  上海  2093
NaN      裤子   299   6  广州  1794

In [27]:
sort_null_idx = df_null_idx.sort_index(na_position='first')
sort_null_idx

       商品名称    单价  数量  城市    总价
订单ID
NaN      裤子   299   6  广州  1794
1001.0   手机  2999   2  北京  5998
1002.0   耳机   399   5  上海  1995
1003.0   卫衣   199  10  广州  1990
1004.0   水杯    59  20  深圳  1180
1005.0   键盘   899   3  北京  2697
1006.0   鼠标    99   8  上海   792
1008.0   毛巾    19  15  深圳   285
1009.0   平板  1999   4  北京  7996
1010.0   音箱   299   7  上海  2093

In [28]:
df_multi

        商品名称    单价  数量  城市    总价
大区 订单ID
华南 1003   卫衣   199  10  广州  1990
华东 1010   音箱   299   7  上海  2093
华南 1007   裤子   299   6  广州  1794
华北 1005   键盘   899   3  北京  2697
   1001   手机  2999   2  北京  5998
华南 1004   水杯    59  20  深圳  1180
华东 1002   耳机   399   5  上海  1995
华南 1008   毛巾    19  15  深圳   285
华北 1009   平板  1999   4  北京  7996
华东 1006   鼠标    99   8  上海   792

In [29]:
df_final = df_multi.sort_index(ascending=True)
df_final

        商品名称    单价  数量  城市    总价
大区 订单ID
华东 1002   耳机   399   5  上海  1995
   1006   鼠标    99   8  上海   792
   1010   音箱   299   7  上海  2093
华北 1001   手机  2999   2  北京  5998
   1005   键盘   899   3  北京  2697
   1009   平板  1999   4  北京  7996
华南 1003   卫衣   199  10  广州  1990
   1004   水杯    59  20  深圳  1180
   1007   裤子   299   6  广州  1794
   1008   毛巾    19  15  深圳   285

In [30]:
df_north = df_final.loc['华北']
df_north

     商品名称    单价  数量  城市    总价
订单ID
1001   手机  2999   2  北京  5998
1005   键盘   899   3  北京  2697
1009   平板  1999   4  北京  7996