In [1]:
import pandas as pd

In [2]:
file_path = r'sort_values.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
8  1009   平板  1999   4  北京  7996   数码   True
9  1010   音箱   299   7  上海  2093   数码  False

In [3]:
print(len(df))

10

In [4]:
sort_price_desc = df.sort_values(by='总价', ascending=False)

sort_price_desc

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
8  1009   平板  1999   4  北京  7996   数码   True
0  1001   手机  2999   2  北京  5998   数码   True
4  1005   键盘   899   3  北京  2697   数码   True
9  1010   音箱   299   7  上海  2093   数码  False
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
6  1007   裤子   299   6  广州  1794   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
5  1006   鼠标    99   8  上海   792   数码  False
7  1008   毛巾    19  15  深圳   285  日用品  False

In [5]:
sort_quantity_asc = df.sort_values(by='数量', ascending=True)
sort_quantity_asc

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
4  1005   键盘   899   3  北京  2697   数码   True
8  1009   平板  1999   4  北京  7996   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
9  1010   音箱   299   7  上海  2093   数码  False
5  1006   鼠标    99   8  上海   792   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
3  1004   水杯    59  20  深圳  1180  日用品  False

In [6]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
8  1009   平板  1999   4  北京  7996   数码   True
9  1010   音箱   299   7  上海  2093   数码  False

In [7]:
sort_multi = df.sort_values(by=['品类', '单价'], ascending=[True, False])

sort_multi

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
8  1009   平板  1999   4  北京  7996   数码   True
4  1005   键盘   899   3  北京  2697   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
9  1010   音箱   299   7  上海  2093   数码  False
5  1006   鼠标    99   8  上海   792   数码  False
3  1004   水杯    59  20  深圳  1180  日用品  False
7  1008   毛巾    19  15  深圳   285  日用品  False
6  1007   裤子   299   6  广州  1794   服饰   True
2  1003   卫衣   199  10  广州  1990   服饰   True

In [8]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
8  1009   平板  1999   4  北京  7996   数码   True
9  1010   音箱   299   7  上海  2093   数码  False

In [9]:
sort_reset = df.sort_values(by='总价', ascending=False).reset_index(drop=True)

sort_reset

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1009   平板  1999   4  北京  7996   数码   True
1  1001   手机  2999   2  北京  5998   数码   True
2  1005   键盘   899   3  北京  2697   数码   True
3  1010   音箱   299   7  上海  2093   数码  False
4  1002   耳机   399   5  上海  1995   数码  False
5  1003   卫衣   199  10  广州  1990   服饰   True
6  1007   裤子   299   6  广州  1794   服饰   True
7  1004   水杯    59  20  深圳  1180  日用品  False
8  1006   鼠标    99   8  上海   792   数码  False
9  1008   毛巾    19  15  深圳   285  日用品  False

In [10]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
8  1009   平板  1999   4  北京  7996   数码   True
9  1010   音箱   299   7  上海  2093   数码  False

In [11]:
sort_boolean = df.sort_values(by='是否包邮', ascending=False)

sort_boolean

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
2  1003   卫衣   199  10  广州  1990   服饰   True
4  1005   键盘   899   3  北京  2697   数码   True
6  1007   裤子   299   6  广州  1794   服饰   True
8  1009   平板  1999   4  北京  7996   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
3  1004   水杯    59  20  深圳  1180  日用品  False
5  1006   鼠标    99   8  上海   792   数码  False
7  1008   毛巾    19  15  深圳   285  日用品  False
9  1010   音箱   299   7  上海  2093   数码  False

In [12]:
df_null = df.copy()

df_null

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
8  1009   平板  1999   4  北京  7996   数码   True
9  1010   音箱   299   7  上海  2093   数码  False

In [13]:
df_null.loc[2, '单价'] = None
df_null

   订单ID 商品名称      单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999.0   2  北京  5998   数码   True
1  1002   耳机   399.0   5  上海  1995   数码  False
2  1003   卫衣     NaN  10  广州  1990   服饰   True
3  1004   水杯    59.0  20  深圳  1180  日用品  False
4  1005   键盘   899.0   3  北京  2697   数码   True
5  1006   鼠标    99.0   8  上海   792   数码  False
6  1007   裤子   299.0   6  广州  1794   服饰   True
7  1008   毛巾    19.0  15  深圳   285  日用品  False
8  1009   平板  1999.0   4  北京  7996   数码   True
9  1010   音箱   299.0   7  上海  2093   数码  False

In [14]:
sort_null = df_null.sort_values(by='单价', ascending=False, na_position='last')
sort_null

   订单ID 商品名称      单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999.0   2  北京  5998   数码   True
8  1009   平板  1999.0   4  北京  7996   数码   True
4  1005   键盘   899.0   3  北京  2697   数码   True
1  1002   耳机   399.0   5  上海  1995   数码  False
6  1007   裤子   299.0   6  广州  1794   服饰   True
9  1010   音箱   299.0   7  上海  2093   数码  False
5  1006   鼠标    99.0   8  上海   792   数码  False
3  1004   水杯    59.0  20  深圳  1180  日用品  False
7  1008   毛巾    19.0  15  深圳   285  日用品  False
2  1003   卫衣     NaN  10  广州  1990   服饰   True

In [15]:
sort_null = df_null.sort_values(by='单价', ascending=False, na_position='first')
sort_null

   订单ID 商品名称      单价  数量  城市    总价   品类   是否包邮
2  1003   卫衣     NaN  10  广州  1990   服饰   True
0  1001   手机  2999.0   2  北京  5998   数码   True
8  1009   平板  1999.0   4  北京  7996   数码   True
4  1005   键盘   899.0   3  北京  2697   数码   True
1  1002   耳机   399.0   5  上海  1995   数码  False
6  1007   裤子   299.0   6  广州  1794   服饰   True
9  1010   音箱   299.0   7  上海  2093   数码  False
5  1006   鼠标    99.0   8  上海   792   数码  False
3  1004   水杯    59.0  20  深圳  1180  日用品  False
7  1008   毛巾    19.0  15  深圳   285  日用品  False

In [16]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
8  1009   平板  1999   4  北京  7996   数码   True
9  1010   音箱   299   7  上海  2093   数码  False

In [17]:
max_price = df.sort_values(by='总价', ascending=False).iloc[0]['商品名称']
max_price

'平板'

In [18]:
min_price = df.sort_values(by='总价', ascending=True).iloc[0]['商品名称']
min_price

'毛巾'

In [19]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False
8  1009   平板  1999   4  北京  7996   数码   True
9  1010   音箱   299   7  上海  2093   数码  False

In [20]:
sort_text = df.sort_values(by='城市', ascending=True)

sort_text

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
1  1002   耳机   399   5  上海  1995   数码  False
5  1006   鼠标    99   8  上海   792   数码  False
9  1010   音箱   299   7  上海  2093   数码  False
0  1001   手机  2999   2  北京  5998   数码   True
4  1005   键盘   899   3  北京  2697   数码   True
8  1009   平板  1999   4  北京  7996   数码   True
2  1003   卫衣   199  10  广州  1990   服饰   True
6  1007   裤子   299   6  广州  1794   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
7  1008   毛巾    19  15  深圳   285  日用品  False