In [1]:
import pandas as pd

In [2]:
file_path = r'filter_col_index.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮        下单时间
0  1001   手机  2999   2  北京  5998   数码   True  2024-01-01
1  1002   耳机   399   5  上海  1995   数码  False  2024-01-02
2  1003   卫衣   199  10  广州  1990   服饰   True  2024-01-03
3  1004   水杯    59  20  深圳  1180  日用品  False  2024-01-04
4  1005   键盘   899   3  北京  2697   数码   True  2024-01-05

In [3]:
df_index = df.set_index('订单ID')
df_index

     商品名称    单价  数量  城市    总价   品类   是否包邮        下单时间
订单ID
1001   手机  2999   2  北京  5998   数码   True  2024-01-01
1002   耳机   399   5  上海  1995   数码  False  2024-01-02
1003   卫衣   199  10  广州  1990   服饰   True  2024-01-03
1004   水杯    59  20  深圳  1180  日用品  False  2024-01-04
1005   键盘   899   3  北京  2697   数码   True  2024-01-05

In [4]:
df.columns.tolist()

['订单ID', '商品名称', '单价', '数量', '城市', '总价', '品类', '是否包邮', '下单时间']

In [5]:
df_index.index.tolist()

[1001, 1002, 1003, 1004, 1005]

In [6]:
df_col_exact = df.filter(items=['订单ID', '商品名称', '单价', '总价'])
df_col_exact

   订单ID 商品名称    单价    总价
0  1001   手机  2999  5998
1  1002   耳机   399  1995
2  1003   卫衣   199  1990
3  1004   水杯    59  1180
4  1005   键盘   899  2697

In [7]:
df_col_like = df.filter(like='价', axis=1)
df_col_like

     单价    总价
0  2999  5998
1   399  1995
2   199  1990
3    59  1180
4   899  2697

In [8]:
df_index

     商品名称    单价  数量  城市    总价   品类   是否包邮        下单时间
订单ID
1001   手机  2999   2  北京  5998   数码   True  2024-01-01
1002   耳机   399   5  上海  1995   数码  False  2024-01-02
1003   卫衣   199  10  广州  1990   服饰   True  2024-01-03
1004   水杯    59  20  深圳  1180  日用品  False  2024-01-04
1005   键盘   899   3  北京  2697   数码   True  2024-01-05

In [9]:
df_idx_exact = df_index.filter(items=[1001, 1003, 1005], axis=0)

df_idx_exact

     商品名称    单价  数量  城市    总价  品类  是否包邮        下单时间
1001   手机  2999   2  北京  5998  数码  True  2024-01-01
1003   卫衣   199  10  广州  1990  服饰  True  2024-01-03
1005   键盘   899   3  北京  2697  数码  True  2024-01-05

In [10]:
df_idx_regex = df_index.filter(regex='^100', axis=0)

df_idx_regex

     商品名称    单价  数量  城市    总价   品类   是否包邮        下单时间
订单ID
1001   手机  2999   2  北京  5998   数码   True  2024-01-01
1002   耳机   399   5  上海  1995   数码  False  2024-01-02
1003   卫衣   199  10  广州  1990   服饰   True  2024-01-03
1004   水杯    59  20  深圳  1180  日用品  False  2024-01-04
1005   键盘   899   3  北京  2697   数码   True  2024-01-05

In [11]:
df_index

     商品名称    单价  数量  城市    总价   品类   是否包邮        下单时间
订单ID
1001   手机  2999   2  北京  5998   数码   True  2024-01-01
1002   耳机   399   5  上海  1995   数码  False  2024-01-02
1003   卫衣   199  10  广州  1990   服饰   True  2024-01-03
1004   水杯    59  20  深圳  1180  日用品  False  2024-01-04
1005   键盘   899   3  北京  2697   数码   True  2024-01-05

In [12]:
df_comb = df.filter(like='单', axis=1)
df_comb

   订单ID    单价        下单时间
0  1001  2999  2024-01-01
1  1002   399  2024-01-02
2  1003   199  2024-01-03
3  1004    59  2024-01-04
4  1005   899  2024-01-05

In [13]:
df_comb = df_comb.query('单价 > 500')
df_comb

   订单ID    单价        下单时间
0  1001  2999  2024-01-01
4  1005   899  2024-01-05

In [14]:
df_index

     商品名称    单价  数量  城市    总价   品类   是否包邮        下单时间
订单ID
1001   手机  2999   2  北京  5998   数码   True  2024-01-01
1002   耳机   399   5  上海  1995   数码  False  2024-01-02
1003   卫衣   199  10  广州  1990   服饰   True  2024-01-03
1004   水杯    59  20  深圳  1180  日用品  False  2024-01-04
1005   键盘   899   3  北京  2697   数码   True  2024-01-05

In [15]:
df_both = df_index.filter(like='品', axis=1)
df_both

     商品名称   品类
订单ID
1001   手机   数码
1002   耳机   数码
1003   卫衣   服饰
1004   水杯  日用品
1005   键盘   数码

In [16]:
df_both = df_both.filter(items=[1003, 1004, 1005], axis=0)
df_both

     商品名称   品类
1003   卫衣   服饰
1004   水杯  日用品
1005   键盘   数码