In [1]:
import pandas as pd

In [2]:
file_path = r'query_filter.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮        下单时间
0  1001   手机  2999   2  北京  5998   数码   True  2024-01-01
1  1002   耳机   399   5  上海  1995   数码  False  2024-01-02
2  1003   卫衣   199  10  广州  1990   服饰   True  2024-01-03
3  1004   水杯    59  20  深圳  1180  日用品  False  2024-01-04
4  1005   键盘   899   3  北京  2697   数码   True  2024-01-05
5  1006   鼠标    99   8  上海   792   数码  False  2024-01-06

In [3]:
df['下单时间'] = pd.to_datetime(df['下单时间'])
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   数码   True 2024-01-01
1  1002   耳机   399   5  上海  1995   数码  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   服饰   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  日用品  False 2024-01-04
4  1005   键盘   899   3  北京  2697   数码   True 2024-01-05
5  1006   鼠标    99   8  上海   792   数码  False 2024-01-06

In [4]:
print(len(df))

6

In [5]:
df_q1 = df.query('单价 > 500')
df_q1

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  数码  True 2024-01-01
4  1005   键盘   899   3  北京  2697  数码  True 2024-01-05

In [6]:
df_q2 = df.query('城市  == "北京"')
df_q2

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  数码  True 2024-01-01
4  1005   键盘   899   3  北京  2697  数码  True 2024-01-05

In [7]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   数码   True 2024-01-01
1  1002   耳机   399   5  上海  1995   数码  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   服饰   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  日用品  False 2024-01-04
4  1005   键盘   899   3  北京  2697   数码   True 2024-01-05
5  1006   鼠标    99   8  上海   792   数码  False 2024-01-06

In [8]:
df_q3 = df.query('是否包邮 and 品类 == "数码" and 总价 > 2000')
df_q3

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  数码  True 2024-01-01
4  1005   键盘   899   3  北京  2697  数码  True 2024-01-05

In [10]:
df_q4 = df.query('城市 == "上海" or 数量 > 10 or 单价 < 100')
df_q4

   订单ID 商品名称   单价  数量  城市    总价   品类   是否包邮       下单时间
1  1002   耳机  399   5  上海  1995   数码  False 2024-01-02
3  1004   水杯   59  20  深圳  1180  日用品  False 2024-01-04
5  1006   鼠标   99   8  上海   792   数码  False 2024-01-06

In [11]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   数码   True 2024-01-01
1  1002   耳机   399   5  上海  1995   数码  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   服饰   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  日用品  False 2024-01-04
4  1005   键盘   899   3  北京  2697   数码   True 2024-01-05
5  1006   鼠标    99   8  上海   792   数码  False 2024-01-06

In [12]:
df_q5 = df.query('城市 in ["北京", "广州"]')
df_q5

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  数码  True 2024-01-01
2  1003   卫衣   199  10  广州  1990  服饰  True 2024-01-03
4  1005   键盘   899   3  北京  2697  数码  True 2024-01-05

In [13]:
df_q6 = df.query('品类 not in ["数码"]')
df_q6

   订单ID 商品名称   单价  数量  城市    总价   品类   是否包邮       下单时间
2  1003   卫衣  199  10  广州  1990   服饰   True 2024-01-03
3  1004   水杯   59  20  深圳  1180  日用品  False 2024-01-04

In [14]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   数码   True 2024-01-01
1  1002   耳机   399   5  上海  1995   数码  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   服饰   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  日用品  False 2024-01-04
4  1005   键盘   899   3  北京  2697   数码   True 2024-01-05
5  1006   鼠标    99   8  上海   792   数码  False 2024-01-06

In [15]:
price_threshold = 200
df_q7 = df.query('单价 > @price_threshold and 数量 < 5')
df_q7

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  数码  True 2024-01-01
4  1005   键盘   899   3  北京  2697  数码  True 2024-01-05

In [16]:
df_q8 = df.query('下单时间 >= "2024-01-04"')
df_q8

   订单ID 商品名称   单价  数量  城市    总价   品类   是否包邮       下单时间
3  1004   水杯   59  20  深圳  1180  日用品  False 2024-01-04
4  1005   键盘  899   3  北京  2697   数码   True 2024-01-05
5  1006   鼠标   99   8  上海   792   数码  False 2024-01-06

In [17]:
df_q9 = df.query('单价 * 数量 > 总价')
df_q9

Empty DataFrame
Columns: [订单ID, 商品名称, 单价, 数量, 城市, 总价, 品类, 是否包邮, 下单时间]
Index: []