In [1]:
import pandas as pd

In [2]:
file_path = r'filter_member.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False

In [3]:
print(len(df))

8

In [4]:
city_list = ['北京', '上海']
df_city_isin = df[df['城市'].isin(city_list)]

df_city_isin

   订单ID 商品名称    单价  数量  城市    总价  品类   是否包邮
0  1001   手机  2999   2  北京  5998  数码   True
1  1002   耳机   399   5  上海  1995  数码  False
4  1005   键盘   899   3  北京  2697  数码   True
5  1006   鼠标    99   8  上海   792  数码  False

In [5]:
id_list = [1001, 1003, 1005]
df_id_isin = df[df['订单ID'].isin(id_list)]

df_id_isin

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮
0  1001   手机  2999   2  北京  5998  数码  True
2  1003   卫衣   199  10  广州  1990  服饰  True
4  1005   键盘   899   3  北京  2697  数码  True

In [6]:
category_exclude = ['数码']
df_category_not = df[~df['品类'].isin(category_exclude)]

df_category_not

   订单ID 商品名称   单价  数量  城市    总价   品类   是否包邮
2  1003   卫衣  199  10  广州  1990   服饰   True
3  1004   水杯   59  20  深圳  1180  日用品  False
6  1007   裤子  299   6  广州  1794   服饰   True
7  1008   毛巾   19  15  深圳   285  日用品  False

In [7]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False

In [8]:
qty_exclude = [5, 10, 15]

df_qty_not = df[~df['数量'].isin(qty_exclude)]
df_qty_not

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True

In [9]:
cond_multi = (df['品类'].isin(['数码'])) & (df['城市'].isin(['北京', '广州'])) & (df['单价'].isin([399, 899, 2999]))

df_multi_isin = df[cond_multi]

df_multi_isin

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮
0  1001   手机  2999   2  北京  5998  数码  True
4  1005   键盘   899   3  北京  2697  数码  True

In [11]:
df

   订单ID 商品名称    单价  数量  城市    总价   品类   是否包邮
0  1001   手机  2999   2  北京  5998   数码   True
1  1002   耳机   399   5  上海  1995   数码  False
2  1003   卫衣   199  10  广州  1990   服饰   True
3  1004   水杯    59  20  深圳  1180  日用品  False
4  1005   键盘   899   3  北京  2697   数码   True
5  1006   鼠标    99   8  上海   792   数码  False
6  1007   裤子   299   6  广州  1794   服饰   True
7  1008   毛巾    19  15  深圳   285  日用品  False

In [10]:
free_category = df[df['是否包邮']]['品类'].unique().tolist()
free_category

['数码', '服饰']

In [13]:
df_free_category = df[df['品类'].isin(free_category) & df['是否包邮']]

df_free_category

   订单ID 商品名称    单价  数量  城市    总价  品类  是否包邮
0  1001   手机  2999   2  北京  5998  数码  True
2  1003   卫衣   199  10  广州  1990  服饰  True
4  1005   键盘   899   3  北京  2697  数码  True
6  1007   裤子   299   6  广州  1794  服饰  True