In [1]:
import pandas as pd

In [2]:
file_path = r'filter_single.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮        下单时间
0  1001   手机  2999   2  北京  5998   True  2024-01-01
1  1002   耳机   399   5  上海  1995  False  2024-01-02
2  1003   卫衣   199  10  广州  1990   True  2024-01-03
3  1004   水杯    59  20  深圳  1180  False  2024-01-04
4  1005   键盘   899   3  北京  2697   True  2024-01-05
5  1006   鼠标    99   8  上海   792  False  2024-01-06

In [3]:
df['下单时间'] = pd.to_datetime(df['下单时间'])
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  False 2024-01-04
4  1005   键盘   899   3  北京  2697   True 2024-01-05
5  1006   鼠标    99   8  上海   792  False 2024-01-06

In [4]:
filter_price = df[df['单价'] > 500]
filter_price

   订单ID 商品名称    单价  数量  城市    总价  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  True 2024-01-01
4  1005   键盘   899   3  北京  2697  True 2024-01-05

In [5]:
filter_qty = df[df['数量'] == 10]
filter_qty

   订单ID 商品名称   单价  数量  城市    总价  是否包邮       下单时间
2  1003   卫衣  199  10  广州  1990  True 2024-01-03

In [6]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  False 2024-01-04
4  1005   键盘   899   3  北京  2697   True 2024-01-05
5  1006   鼠标    99   8  上海   792  False 2024-01-06

In [7]:
filter_city_eq = df[df['城市'] == '北京']
filter_city_eq

   订单ID 商品名称    单价  数量  城市    总价  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  True 2024-01-01
4  1005   键盘   899   3  北京  2697  True 2024-01-05

In [8]:
filter_goods_contain = df[df['商品名称'].str.contains('机', na=False)]
filter_goods_contain

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02

In [9]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  False 2024-01-04
4  1005   键盘   899   3  北京  2697   True 2024-01-05
5  1006   鼠标    99   8  上海   792  False 2024-01-06

In [10]:
filter_free = df[df['是否包邮'] == True]
filter_free

   订单ID 商品名称    单价  数量  城市    总价  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  True 2024-01-01
2  1003   卫衣   199  10  广州  1990  True 2024-01-03
4  1005   键盘   899   3  北京  2697  True 2024-01-05

In [11]:
filter_free_simple = df[df['是否包邮']]
filter_free_simple

   订单ID 商品名称    单价  数量  城市    总价  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  True 2024-01-01
2  1003   卫衣   199  10  广州  1990  True 2024-01-03
4  1005   键盘   899   3  北京  2697  True 2024-01-05

In [13]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  False 2024-01-04
4  1005   键盘   899   3  北京  2697   True 2024-01-05
5  1006   鼠标    99   8  上海   792  False 2024-01-06

In [14]:
filter_date = df[df['下单时间'] >= '2024-01-03']
filter_date

   订单ID 商品名称   单价  数量  城市    总价   是否包邮       下单时间
2  1003   卫衣  199  10  广州  1990   True 2024-01-03
3  1004   水杯   59  20  深圳  1180  False 2024-01-04
4  1005   键盘  899   3  北京  2697   True 2024-01-05
5  1006   鼠标   99   8  上海   792  False 2024-01-06

In [15]:
filter_spec_col = df[df['单价'] > 200][['订单ID', '商品名称', '单价']]
filter_spec_col

   订单ID 商品名称    单价
0  1001   手机  2999
1  1002   耳机   399
4  1005   键盘   899