In [1]:
import pandas as pd

In [2]:
file_path = r'filter_multi.csv'

df = pd.read_csv(file_path, encoding='utf-8')
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮        下单时间
0  1001   手机  2999   2  北京  5998   True  2024-01-01
1  1002   耳机   399   5  上海  1995  False  2024-01-02
2  1003   卫衣   199  10  广州  1990   True  2024-01-03
3  1004   水杯    59  20  深圳  1180  False  2024-01-04
4  1005   键盘   899   3  北京  2697   True  2024-01-05
5  1006   鼠标    99   8  上海   792  False  2024-01-06

In [3]:
df['下单时间'] = pd.to_datetime(df['下单时间'])
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  False 2024-01-04
4  1005   键盘   899   3  北京  2697   True 2024-01-05
5  1006   鼠标    99   8  上海   792  False 2024-01-06

In [4]:
print(len(df))

6

In [5]:
cond_and = (df['单价'] > 200) & (df['城市'] == '北京') & (df['是否包邮'])
df_and = df[cond_and]

df_and

   订单ID 商品名称    单价  数量  城市    总价  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  True 2024-01-01
4  1005   键盘   899   3  北京  2697  True 2024-01-05

In [6]:
cond_or = (df['城市'] == '上海') | (df['数量'] > 10) | (df['总价'] < 1000)
df_or = df[cond_or]

df_or

   订单ID 商品名称   单价  数量  城市    总价   是否包邮       下单时间
1  1002   耳机  399   5  上海  1995  False 2024-01-02
3  1004   水杯   59  20  深圳  1180  False 2024-01-04
5  1006   鼠标   99   8  上海   792  False 2024-01-06

In [7]:
cond_mix = df['是否包邮'] & ((df['单价'] > 500) | (df['下单时间'] >= '2024-01-04'))
df_mix = df[cond_mix]

df_mix

   订单ID 商品名称    单价  数量  城市    总价  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  True 2024-01-01
4  1005   键盘   899   3  北京  2697  True 2024-01-05

In [8]:
cond_isin = df['城市'].isin(['北京', '上海']) & (df['总价'] > 1500)

df_isin = df[cond_isin]
df_isin

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02
4  1005   键盘   899   3  北京  2697   True 2024-01-05

In [9]:
df

   订单ID 商品名称    单价  数量  城市    总价   是否包邮       下单时间
0  1001   手机  2999   2  北京  5998   True 2024-01-01
1  1002   耳机   399   5  上海  1995  False 2024-01-02
2  1003   卫衣   199  10  广州  1990   True 2024-01-03
3  1004   水杯    59  20  深圳  1180  False 2024-01-04
4  1005   键盘   899   3  北京  2697   True 2024-01-05
5  1006   鼠标    99   8  上海   792  False 2024-01-06

In [10]:
df_query = df.query('单价 > 100 and 城市 == "广州" or (数量 < 5 and 是否包邮)')
df_query

   订单ID 商品名称    单价  数量  城市    总价  是否包邮       下单时间
0  1001   手机  2999   2  北京  5998  True 2024-01-01
2  1003   卫衣   199  10  广州  1990  True 2024-01-03
4  1005   键盘   899   3  北京  2697  True 2024-01-05