In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer

In [2]:
df = pd.DataFrame({
    '年龄': [25, np.nan, 35, 28, np.nan, 42, 31, 29],
    '收入': [8000, 15000, np.nan, 12000, 9500, np.nan, 11000, 13000],
})

df

     年龄       收入
0  25.0   8000.0
1   NaN  15000.0
2  35.0      NaN
3  28.0  12000.0
4   NaN   9500.0
5  42.0      NaN
6  31.0  11000.0
7  29.0  13000.0

In [3]:
print(df)

     年龄       收入
0  25.0   8000.0
1   NaN  15000.0
2  35.0      NaN
3  28.0  12000.0
4   NaN   9500.0
5  42.0      NaN
6  31.0  11000.0
7  29.0  13000.0

In [4]:
imputer_mean = SimpleImputer(strategy='mean')

df_mean = pd.DataFrame(imputer_mean.fit_transform(df), columns=df.columns)

df_mean

          年龄            收入
0  25.000000   8000.000000
1  31.666667  15000.000000
2  35.000000  11416.666667
3  28.000000  12000.000000
4  31.666667   9500.000000
5  42.000000  11416.666667
6  31.000000  11000.000000
7  29.000000  13000.000000

In [5]:
df_mean.round(1)

     年龄       收入
0  25.0   8000.0
1  31.7  15000.0
2  35.0  11416.7
3  28.0  12000.0
4  31.7   9500.0
5  42.0  11416.7
6  31.0  11000.0
7  29.0  13000.0

In [9]:
imputer_median = SimpleImputer(strategy='median')

df_median = pd.DataFrame(imputer_median.fit_transform(df), columns=df.columns)

df_median

     年龄       收入
0  25.0   8000.0
1  30.0  15000.0
2  35.0  11500.0
3  28.0  12000.0
4  30.0   9500.0
5  42.0  11500.0
6  31.0  11000.0
7  29.0  13000.0

In [7]:
df_median.round(1)

     年龄       收入
0  25.0   8000.0
1  31.7  15000.0
2  35.0  11416.7
3  28.0  12000.0
4  31.7   9500.0
5  42.0  11416.7
6  31.0  11000.0
7  29.0  13000.0

In [10]:
imputer_most_frequent = SimpleImputer(strategy='most_frequent')

df_most_frequent = pd.DataFrame(imputer_most_frequent.fit_transform(df), columns=df.columns)

df_most_frequent

     年龄       收入
0  25.0   8000.0
1  25.0  15000.0
2  35.0   8000.0
3  28.0  12000.0
4  25.0   9500.0
5  42.0   8000.0
6  31.0  11000.0
7  29.0  13000.0

In [11]:
imputer_constant = SimpleImputer(strategy='constant', fill_value=10000)

df_constant = pd.DataFrame(imputer_constant.fit_transform(df), columns=df.columns)

df_constant

        年龄       收入
0     25.0   8000.0
1  10000.0  15000.0
2     35.0  10000.0
3     28.0  12000.0
4  10000.0   9500.0
5     42.0  10000.0
6     31.0  11000.0
7     29.0  13000.0

In [25]:
# 用众数填充类别特征
df_city = pd.DataFrame({'城市': ['北京', '上海', np.nan, '深圳', '北京', np.nan]})

In [26]:
df_city

    城市
0   北京
1   上海
2  NaN
3   深圳
4   北京
5  NaN

In [17]:
import pandas as pd

df_city = pd.DataFrame({'城市': ['北京', '上海', None, '深圳', '北京', None]})
# 取出众数值填充
mode_val = df_city['城市'].mode()[0]
df_city['城市'] = df_city['城市'].fillna(mode_val)
print(df_city)

   城市
0  北京
1  上海
2  北京
3  深圳
4  北京
5  北京

In [18]:
df_city

   城市
0  北京
1  上海
2  北京
3  深圳
4  北京
5  北京

In [22]:
# 用众数填充类别特征
df_city = pd.DataFrame({'城市': ['北京', '上海', np.nan, '深圳', '北京', np.nan]})

In [23]:
df_city

    城市
0   北京
1   上海
2  NaN
3   深圳
4   北京
5  NaN

In [24]:
imputer_mode = SimpleImputer(strategy='most_frequent')
# 加 .ravel() / .flatten() 把二维转一维
df_city['城市'] = imputer_mode.fit_transform(df_city[['城市']]).ravel()

df_city

   城市
0  北京
1  上海
2  北京
3  深圳
4  北京
5  北京

In [31]:
# 用众数填充类别特征
df_city = pd.DataFrame({'城市': ['北京', '上海', np.nan, '深圳', '北京', np.nan]})
imputer_mode = SimpleImputer(strategy='most_frequent')
df_city['城市'] = imputer_mode.fit_transform(df_city[['城市']]).ravel()
print(df_city)

   城市
0  北京
1  上海
2  北京
3  深圳
4  北京
5  北京

In [32]:
df_city

   城市
0  北京
1  上海
2  北京
3  深圳
4  北京
5  北京