In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '年龄': [25, np.nan, 35, 28, np.nan],
    '收入': [8000, 15000, np.nan, 12000, 9500],
    '城市': ['北京', '上海', np.nan, '深圳', '北京'],
})

In [3]:
df

   姓名    年龄       收入   城市
0  张三  25.0   8000.0   北京
1  李四   NaN  15000.0   上海
2  王五  35.0      NaN  NaN
3  赵六  28.0  12000.0   深圳
4  钱七   NaN   9500.0   北京

In [4]:
print(df)

   姓名    年龄       收入   城市
0  张三  25.0   8000.0   北京
1  李四   NaN  15000.0   上海
2  王五  35.0      NaN  NaN
3  赵六  28.0  12000.0   深圳
4  钱七   NaN   9500.0   北京

In [7]:
df.isnull()

      姓名     年龄     收入     城市
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [5]:
df.isnull().sum()

姓名    0
年龄    2
收入    1
城市    1
dtype: int64

In [6]:
print((df.isnull().sum() / len(df) * 100).round(1).astype(str) + '%')

姓名     0.0%
年龄    40.0%
收入    20.0%
城市    20.0%
dtype: object

In [8]:
df.isnull().any()

姓名    False
年龄     True
收入     True
城市     True
dtype: bool

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      5 non-null      object
 1   年龄      3 non-null      float64
 2   收入      4 non-null      float64
 3   城市      4 non-null      object
dtypes: float64(2), object(2)
memory usage: 288.0+ bytes