In [1]:
import pandas as pd
from prompt_toolkit.styles import Priority

In [2]:
file_path = r'index_sort.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    index_col='订单ID'
)

df

      用户ID 商品名称  城市  消费金额
订单ID
1005   202   键盘  上海   899
1001   201   手机  北京  2999
1003   201   卫衣  北京   199
1002   202   耳机  上海   399
1004   203   水杯  广州    59

In [3]:
df_sort_asc = df.sort_index()
df_sort_asc

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [4]:
df_sort_desc = df.sort_index(ascending=False)
df_sort_desc

      用户ID 商品名称  城市  消费金额
订单ID
1005   202   键盘  上海   899
1004   203   水杯  广州    59
1003   201   卫衣  北京   199
1002   202   耳机  上海   399
1001   201   手机  北京  2999

In [5]:
df_multi = df.reset_index().set_index(['用户ID', '订单ID'])
df_multi

          商品名称  城市  消费金额
用户ID 订单ID
202  1005   键盘  上海   899
201  1001   手机  北京  2999
     1003   卫衣  北京   199
202  1002   耳机  上海   399
203  1004   水杯  广州    59

In [6]:
df_multi_sort = df_multi.sort_index(
    level=['用户ID', '订单ID'],
    ascending=[True, False]
)

df_multi_sort

          商品名称  城市  消费金额
用户ID 订单ID
201  1003   卫衣  北京   199
     1001   手机  北京  2999
202  1005   键盘  上海   899
     1002   耳机  上海   399
203  1004   水杯  广州    59

In [16]:
df

      用户ID 商品名称  城市  消费金额
订单ID
1005   202   键盘  上海   899
1001   201   手机  北京  2999
1003   201   卫衣  北京   199
1002   202   耳机  上海   399
1004   203   水杯  广州    59

In [17]:
df_col_sort = df.sort_index(axis=1)
df_col_sort

     商品名称  城市  消费金额  用户ID
订单ID
1005   键盘  上海   899   202
1001   手机  北京  2999   201
1003   卫衣  北京   199   201
1002   耳机  上海   399   202
1004   水杯  广州    59   203

In [12]:
df_sort_asc

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [13]:
df_sort_reset = df_sort_asc.reset_index(drop=False)
df_sort_reset

   订单ID  用户ID 商品名称  城市  消费金额
0  1001   201   手机  北京  2999
1  1002   202   耳机  上海   399
2  1003   201   卫衣  北京   199
3  1004   203   水杯  广州    59
4  1005   202   键盘  上海   899