In [1]:
import pandas as pd

In [2]:
file_path = r'index_rename.csv'

df = pd.read_csv(
    file_path,
    encoding='utf-8',
    index_col='订单ID'
)

df

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [3]:
df.index.name

'订单ID'

In [5]:
print(df.columns.name)

None

In [6]:
df

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [7]:
df.rename_axis('订单编号', inplace=True)

In [8]:
df

      用户ID 商品名称  城市  消费金额
订单编号
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [9]:
df.index.name

'订单编号'

In [12]:
df_multi = df.reset_index().set_index(['用户ID', '订单编号'])
df_multi

          商品名称  城市  消费金额
用户ID 订单编号
201  1001   手机  北京  2999
202  1002   耳机  上海   399
201  1003   卫衣  北京   199
203  1004   水杯  广州    59
202  1005   键盘  上海   899

In [13]:
print(df_multi.index.to_list())

[(201, 1001), (202, 1002), (201, 1003), (203, 1004), (202, 1005)]

In [14]:
df_multi.rename_axis(['用户编号', '订单编号'], axis=0, inplace=True)
df_multi

          商品名称  城市  消费金额
用户编号 订单编号
201  1001   手机  北京  2999
202  1002   耳机  上海   399
201  1003   卫衣  北京   199
203  1004   水杯  广州    59
202  1005   键盘  上海   899

In [15]:
df

      用户ID 商品名称  城市  消费金额
订单编号
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [16]:
print(df.columns.name)

None

In [17]:
df.rename(
    columns={'用户ID': '用户编号', '消费金额': '支付金额'},
    inplace=True
)

df

      用户编号 商品名称  城市  支付金额
订单编号
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [18]:
print(df.columns.name)

None

In [19]:
df.columns.name = '业务字段'
print(df.columns.name)

业务字段

In [22]:
df

业务字段  用户编号 商品名称  城市  支付金额
订单编号
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [25]:
print(df)

业务字段  用户编号 商品名称  城市  支付金额
订单编号
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [23]:
df_reset = df.reset_index()
df_reset

业务字段  订单编号  用户编号 商品名称  城市  支付金额
0     1001   201   手机  北京  2999
1     1002   202   耳机  上海   399
2     1003   201   卫衣  北京   199
3     1004   203   水杯  广州    59
4     1005   202   键盘  上海   899

In [24]:
df_reset.rename(columns={'订单编号': 'ORDER_ID'}, inplace=True)
df_reset

业务字段  ORDER_ID  用户编号 商品名称  城市  支付金额
0         1001   201   手机  北京  2999
1         1002   202   耳机  上海   399
2         1003   201   卫衣  北京   199
3         1004   203   水杯  广州    59
4         1005   202   键盘  上海   899