In [1]:
import pandas as pd

In [2]:
file_path = r'index_data.csv'

df = pd.read_csv(file_path, encoding='utf-8')
df

   用户ID  姓名  城市    消费金额
0   101  张三  北京   899.5
1   102  李四  上海  1299.0
2   103  王五  广州   799.8
3   104  赵六  深圳   999.9
4   105  钱七  北京  1199.7

In [3]:
print(type(df.index))

<class 'pandas.RangeIndex'>

In [4]:
print(df.index.to_list())

[0, 1, 2, 3, 4]

In [5]:
df.head(3)

   用户ID  姓名  城市    消费金额
0   101  张三  北京   899.5
1   102  李四  上海  1299.0
2   103  王五  广州   799.8

In [6]:
df

   用户ID  姓名  城市    消费金额
0   101  张三  北京   899.5
1   102  李四  上海  1299.0
2   103  王五  广州   799.8
3   104  赵六  深圳   999.9
4   105  钱七  北京  1199.7

In [8]:
df_id_index = df.set_index('用户ID')
df_id_index

      姓名  城市    消费金额
用户ID
101   张三  北京   899.5
102   李四  上海  1299.0
103   王五  广州   799.8
104   赵六  深圳   999.9
105   钱七  北京  1199.7

In [9]:
print(type(df_id_index.index))

<class 'pandas.RangeIndex'>

In [10]:
print(df_id_index.index.to_list())

[101, 102, 103, 104, 105]

In [11]:
df_id_index.head(3)

      姓名  城市    消费金额
用户ID
101   张三  北京   899.5
102   李四  上海  1299.0
103   王五  广州   799.8

In [12]:
df_custom_index = df.set_index(['姓名'])
df_custom_index

    用户ID  城市    消费金额
姓名
张三   101  北京   899.5
李四   102  上海  1299.0
王五   103  广州   799.8
赵六   104  深圳   999.9
钱七   105  北京  1199.7

In [13]:
print(type(df_custom_index.index))

<class 'pandas.Index'>

In [14]:
print(df_custom_index.index.to_list())

['张三', '李四', '王五', '赵六', '钱七']

In [15]:
df_custom_index.loc['李四']

用户ID       102
城市          上海
消费金额    1299.0
Name: 李四, dtype: object

In [16]:
df_custom_index.iloc[1]

用户ID       102
城市          上海
消费金额    1299.0
Name: 李四, dtype: object

In [17]:
df_id_index

      姓名  城市    消费金额
用户ID
101   张三  北京   899.5
102   李四  上海  1299.0
103   王五  广州   799.8
104   赵六  深圳   999.9
105   钱七  北京  1199.7

In [18]:
df_reset = df_id_index.reset_index()
df_reset

   用户ID  姓名  城市    消费金额
0   101  张三  北京   899.5
1   102  李四  上海  1299.0
2   103  王五  广州   799.8
3   104  赵六  深圳   999.9
4   105  钱七  北京  1199.7

In [19]:
print(df_reset.index.to_list())

[0, 1, 2, 3, 4]

In [20]:
print(df_reset.columns.tolist())

['用户ID', '姓名', '城市', '消费金额']