In [1]:
import pandas as pd

In [2]:
file_path = r'index_operate.csv'

df = pd.read_csv(file_path, encoding='utf-8')
df

   订单ID  用户ID 商品名称  城市  消费金额
0  1001   201   手机  北京  2999
1  1002   202   耳机  上海   399
2  1003   201   卫衣  北京   199
3  1004   203   水杯  广州    59
4  1005   202   键盘  上海   899

In [3]:
df.head(3)

   订单ID  用户ID 商品名称  城市  消费金额
0  1001   201   手机  北京  2999
1  1002   202   耳机  上海   399
2  1003   201   卫衣  北京   199

In [4]:
df

   订单ID  用户ID 商品名称  城市  消费金额
0  1001   201   手机  北京  2999
1  1002   202   耳机  上海   399
2  1003   201   卫衣  北京   199
3  1004   203   水杯  广州    59
4  1005   202   键盘  上海   899

In [5]:
df_order_index = df.set_index('订单ID')
df_order_index

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [7]:
print(type(df_order_index.index))

<class 'pandas.RangeIndex'>

In [8]:
print(df_order_index.index.to_list())

[1001, 1002, 1003, 1004, 1005]

In [6]:
df_multi_index = df.set_index(['用户ID', '订单ID'])
df_multi_index

          商品名称  城市  消费金额
用户ID 订单ID
201  1001   手机  北京  2999
202  1002   耳机  上海   399
201  1003   卫衣  北京   199
203  1004   水杯  广州    59
202  1005   键盘  上海   899

In [9]:
print(type(df_multi_index.index))

<class 'pandas.MultiIndex'>

In [10]:
print(df_multi_index.index.to_list())

[(201, 1001), (202, 1002), (201, 1003), (203, 1004), (202, 1005)]

In [11]:
df

   订单ID  用户ID 商品名称  城市  消费金额
0  1001   201   手机  北京  2999
1  1002   202   耳机  上海   399
2  1003   201   卫衣  北京   199
3  1004   203   水杯  广州    59
4  1005   202   键盘  上海   899

In [12]:
df_read_index = pd.read_csv(
    file_path,
    encoding='utf-8',
    index_col='订单ID'
)

df_read_index

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [13]:
df_order_index

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [14]:
df_reset1 = df_order_index.reset_index()
df_reset1

   订单ID  用户ID 商品名称  城市  消费金额
0  1001   201   手机  北京  2999
1  1002   202   耳机  上海   399
2  1003   201   卫衣  北京   199
3  1004   203   水杯  广州    59
4  1005   202   键盘  上海   899

In [15]:
df_multi_index

          商品名称  城市  消费金额
用户ID 订单ID
201  1001   手机  北京  2999
202  1002   耳机  上海   399
201  1003   卫衣  北京   199
203  1004   水杯  广州    59
202  1005   键盘  上海   899

In [16]:
print(df_multi_index.index.to_list())

[(201, 1001), (202, 1002), (201, 1003), (203, 1004), (202, 1005)]

In [17]:
df_reset2 = df_multi_index.reset_index()
df_reset2

   用户ID  订单ID 商品名称  城市  消费金额
0   201  1001   手机  北京  2999
1   202  1002   耳机  上海   399
2   201  1003   卫衣  北京   199
3   203  1004   水杯  广州    59
4   202  1005   键盘  上海   899

In [18]:
df_order_index

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [19]:
df_reset_drop = df_order_index.reset_index(drop=True)
df_reset_drop

   用户ID 商品名称  城市  消费金额
0   201   手机  北京  2999
1   202   耳机  上海   399
2   201   卫衣  北京   199
3   203   水杯  广州    59
4   202   键盘  上海   899

In [20]:
df

   订单ID  用户ID 商品名称  城市  消费金额
0  1001   201   手机  北京  2999
1  1002   202   耳机  上海   399
2  1003   201   卫衣  北京   199
3  1004   203   水杯  广州    59
4  1005   202   键盘  上海   899

In [21]:
df_order_index

      用户ID 商品名称  城市  消费金额
订单ID
1001   201   手机  北京  2999
1002   202   耳机  上海   399
1003   201   卫衣  北京   199
1004   203   水杯  广州    59
1005   202   键盘  上海   899

In [24]:
print(df['订单ID'].is_unique)

True