In [12]:
import pandas as pd

In [13]:
file_path = r'data_standardize.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

     id goods_name city  price  num  total_price
0  1001         手机   北京   2999    2         5998
1  1002         耳机   上海    399    5         1995
2  1003         卫衣   广州    199   10         1990
3  1004         水杯   深圳     59   20         1180
4  1005         键盘   北京    899    3         2697

In [14]:
print(df.columns.tolist())

['id', 'goods_name', 'city', 'price', 'num', 'total_price']

In [15]:
col_rename = {'id': '订单ID', 'goods_name': '商品名称', 'city': '城市', 'price': '单价', 'num': '数量',
              'total_price': '总价'}

df.rename(columns=col_rename, inplace=True)

df

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
1  1002   耳机  上海   399   5  1995
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180
4  1005   键盘  北京   899   3  2697

In [16]:
print(df.columns.tolist())

['订单ID', '商品名称', '城市', '单价', '数量', '总价']

In [17]:
df

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
1  1002   耳机  上海   399   5  1995
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180
4  1005   键盘  北京   899   3  2697

In [18]:
df_sort_single = df.sort_values(by='总价', ascending=False)

df_sort_single

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
4  1005   键盘  北京   899   3  2697
1  1002   耳机  上海   399   5  1995
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180

In [19]:
df_sort_multi = df.sort_values(by=['城市', '单价'], ascending=[True, False])
df_sort_multi

   订单ID 商品名称  城市    单价  数量    总价
1  1002   耳机  上海   399   5  1995
0  1001   手机  北京  2999   2  5998
4  1005   键盘  北京   899   3  2697
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180

In [22]:
df

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
1  1002   耳机  上海   399   5  1995
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180
4  1005   键盘  北京   899   3  2697

In [23]:
df_reorder = df[['订单ID', '数量', '总价', '商品名称', '城市', '单价']]
df_reorder

   订单ID  数量    总价 商品名称  城市    单价
0  1001   2  5998   手机  北京  2999
1  1002   5  1995   耳机  上海   399
2  1003  10  1990   卫衣  广州   199
3  1004  20  1180   水杯  深圳    59
4  1005   3  2697   键盘  北京   899

In [24]:
df_sort_single

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
4  1005   键盘  北京   899   3  2697
1  1002   耳机  上海   399   5  1995
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180

In [25]:
df_reset = df_sort_single.reset_index(drop=True)

df_reset

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
1  1005   键盘  北京   899   3  2697
2  1002   耳机  上海   399   5  1995
3  1003   卫衣  广州   199  10  1990
4  1004   水杯  深圳    59  20  1180

In [26]:
df

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
1  1002   耳机  上海   399   5  1995
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180
4  1005   键盘  北京   899   3  2697

In [27]:
df_set_index = df.set_index('订单ID')
df_set_index

     商品名称  城市    单价  数量    总价
订单ID
1001   手机  北京  2999   2  5998
1002   耳机  上海   399   5  1995
1003   卫衣  广州   199  10  1990
1004   水杯  深圳    59  20  1180
1005   键盘  北京   899   3  2697

In [28]:
df['临时列'] = '无用数据'
df

   订单ID 商品名称  城市    单价  数量    总价   临时列
0  1001   手机  北京  2999   2  5998  无用数据
1  1002   耳机  上海   399   5  1995  无用数据
2  1003   卫衣  广州   199  10  1990  无用数据
3  1004   水杯  深圳    59  20  1180  无用数据
4  1005   键盘  北京   899   3  2697  无用数据

In [29]:
df_clean = df.drop(columns=['临时列'])
df_clean

   订单ID 商品名称  城市    单价  数量    总价
0  1001   手机  北京  2999   2  5998
1  1002   耳机  上海   399   5  1995
2  1003   卫衣  广州   199  10  1990
3  1004   水杯  深圳    59  20  1180
4  1005   键盘  北京   899   3  2697