In [1]:
import pandas as pd

In [3]:
file_path = r'time_timezone.csv'

df= pd.read_csv(
    file_path,
    encoding='utf-8',
    parse_dates=['下单时间(UTC)']
)

df

      订单号           下单时间(UTC)  商品     金额 下单地区
0  ORD001 2024-05-01 00:30:00  手机  59980   纽约
1  ORD002 2024-05-01 02:10:00  耳机  19950   伦敦
2  ORD003 2024-05-01 08:00:00  卫衣  15920   北京
3  ORD004 2024-05-01 12:20:00  水杯   5900   东京
4  ORD005 2024-05-01 15:40:00  键盘  26970   悉尼

In [4]:
df['UTC时间'] = df['下单时间(UTC)'].dt.tz_localize('UTC')

df

      订单号           下单时间(UTC)  商品     金额 下单地区                     UTC时间
0  ORD001 2024-05-01 00:30:00  手机  59980   纽约 2024-05-01 00:30:00+00:00
1  ORD002 2024-05-01 02:10:00  耳机  19950   伦敦 2024-05-01 02:10:00+00:00
2  ORD003 2024-05-01 08:00:00  卫衣  15920   北京 2024-05-01 08:00:00+00:00
3  ORD004 2024-05-01 12:20:00  水杯   5900   东京 2024-05-01 12:20:00+00:00
4  ORD005 2024-05-01 15:40:00  键盘  26970   悉尼 2024-05-01 15:40:00+00:00

In [5]:
df['北京时区'] = df['UTC时间'].dt.tz_convert('Asia/Shanghai')

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00

In [6]:
df['纽约时区'] = df['UTC时间'].dt.tz_convert('America/New_York')

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00

In [7]:
df['东京时区'] = df['UTC时间'].dt.tz_convert('Asia/Tokyo')

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00

In [8]:
df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00

In [9]:
df['统一为北京时区'] = df.apply(lambda x: x['UTC时间'].dt.tz_convert('Asia/Shanghai'), axis=1)

df

AttributeError: 'Timestamp' object has no attribute 'dt'

In [10]:
df['统一为北京时区'] = df['UTC时间'].dt.tz_convert('Asia/Shanghai')

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区,统一为北京时区
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00,2024-05-01 08:30:00+08:00
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00,2024-05-01 10:10:00+08:00
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00,2024-05-01 16:00:00+08:00
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00,2024-05-01 20:20:00+08:00
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00,2024-05-01 23:40:00+08:00

In [11]:
df['北京时区_小时'] = df['北京时区'].dt.hour

df['纽约时区_小时'] = df['纽约时区'].dt.hour

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区,统一为北京时区,北京时区_小时,纽约时区_小时
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00,2024-05-01 08:30:00+08:00,8,20
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00,2024-05-01 10:10:00+08:00,10,22
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00,2024-05-01 16:00:00+08:00,16,4
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00,2024-05-01 20:20:00+08:00,20,8
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00,2024-05-01 23:40:00+08:00,23,11

In [12]:
local_time = pd.Series(['2024-05-01 08:00:00', '2024-05-01 09:00:00'])

local_time

0    2024-05-01 08:00:00
1    2024-05-01 09:00:00
dtype: str

In [13]:
local_time_dt = pd.to_datetime(local_time)

local_time_dt

0   2024-05-01 08:00:00
1   2024-05-01 09:00:00
dtype: datetime64[us]

In [14]:
beijing_local = local_time_dt.dt.tz_localize('Asia/Shanghai')

beijing_local

0   2024-05-01 08:00:00+08:00
1   2024-05-01 09:00:00+08:00
dtype: datetime64[us, Asia/Shanghai]

In [15]:
beijing_to_utc = beijing_local.dt.tz_convert('UTC')

beijing_to_utc

0   2024-05-01 00:00:00+00:00
1   2024-05-01 01:00:00+00:00
dtype: datetime64[us, UTC]

In [16]:
df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区,统一为北京时区,北京时区_小时,纽约时区_小时
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00,2024-05-01 08:30:00+08:00,8,20
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00,2024-05-01 10:10:00+08:00,10,22
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00,2024-05-01 16:00:00+08:00,16,4
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00,2024-05-01 20:20:00+08:00,20,8
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00,2024-05-01 23:40:00+08:00,23,11

In [18]:
df['安全时区转换'] = df['下单时间(UTC)'].dt.tz_localize('UTC', ambiguous='NaT').dt.tz_convert('Asia/Shanghai')

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区,统一为北京时区,北京时区_小时,纽约时区_小时,安全时区转换
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00,2024-05-01 08:30:00+08:00,8,20,2024-05-01 08:30:00+08:00
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00,2024-05-01 10:10:00+08:00,10,22,2024-05-01 10:10:00+08:00
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00,2024-05-01 16:00:00+08:00,16,4,2024-05-01 16:00:00+08:00
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00,2024-05-01 20:20:00+08:00,20,8,2024-05-01 20:20:00+08:00
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00,2024-05-01 23:40:00+08:00,23,11,2024-05-01 23:40:00+08:00

In [19]:
df['移除时区'] = df['北京时区'].dt.tz_localize(None)

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区,统一为北京时区,北京时区_小时,纽约时区_小时,安全时区转换,移除时区
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00,2024-05-01 08:30:00+08:00,8,20,2024-05-01 08:30:00+08:00,2024-05-01 08:30:00
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00,2024-05-01 10:10:00+08:00,10,22,2024-05-01 10:10:00+08:00,2024-05-01 10:10:00
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00,2024-05-01 16:00:00+08:00,16,4,2024-05-01 16:00:00+08:00,2024-05-01 16:00:00
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00,2024-05-01 20:20:00+08:00,20,8,2024-05-01 20:20:00+08:00,2024-05-01 20:20:00
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00,2024-05-01 23:40:00+08:00,23,11,2024-05-01 23:40:00+08:00,2024-05-01 23:40:00

In [20]:
df['北京小时'] = df['统一为北京时区'].dt.hour

df

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区,统一为北京时区,北京时区_小时,纽约时区_小时,安全时区转换,移除时区,北京小时
0,ORD001,2024-05-01 00:30:00,手机,59980,纽约,2024-05-01 00:30:00+00:00,2024-05-01 08:30:00+08:00,2024-04-30 20:30:00-04:00,2024-05-01 09:30:00+09:00,2024-05-01 08:30:00+08:00,8,20,2024-05-01 08:30:00+08:00,2024-05-01 08:30:00,8
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00,2024-05-01 10:10:00+08:00,10,22,2024-05-01 10:10:00+08:00,2024-05-01 10:10:00,10
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00,2024-05-01 16:00:00+08:00,16,4,2024-05-01 16:00:00+08:00,2024-05-01 16:00:00,16
3,ORD004,2024-05-01 12:20:00,水杯,5900,东京,2024-05-01 12:20:00+00:00,2024-05-01 20:20:00+08:00,2024-05-01 08:20:00-04:00,2024-05-01 21:20:00+09:00,2024-05-01 20:20:00+08:00,20,8,2024-05-01 20:20:00+08:00,2024-05-01 20:20:00,20
4,ORD005,2024-05-01 15:40:00,键盘,26970,悉尼,2024-05-01 15:40:00+00:00,2024-05-01 23:40:00+08:00,2024-05-01 11:40:00-04:00,2024-05-02 00:40:00+09:00,2024-05-01 23:40:00+08:00,23,11,2024-05-01 23:40:00+08:00,2024-05-01 23:40:00,23

In [21]:
df_work_hour = df[(df['北京小时'] >= 9) & (df['北京小时'] <= 18)]

df_work_hour

,订单号,下单时间(UTC),商品,金额,下单地区,UTC时间,北京时区,纽约时区,东京时区,统一为北京时区,北京时区_小时,纽约时区_小时,安全时区转换,移除时区,北京小时
1,ORD002,2024-05-01 02:10:00,耳机,19950,伦敦,2024-05-01 02:10:00+00:00,2024-05-01 10:10:00+08:00,2024-04-30 22:10:00-04:00,2024-05-01 11:10:00+09:00,2024-05-01 10:10:00+08:00,10,22,2024-05-01 10:10:00+08:00,2024-05-01 10:10:00,10
2,ORD003,2024-05-01 08:00:00,卫衣,15920,北京,2024-05-01 08:00:00+00:00,2024-05-01 16:00:00+08:00,2024-05-01 04:00:00-04:00,2024-05-01 17:00:00+09:00,2024-05-01 16:00:00+08:00,16,4,2024-05-01 16:00:00+08:00,2024-05-01 16:00:00,16