In [1]:
import pandas as pd

In [2]:
file_path = r'data_replace.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称  城市 订单状态    单价  备注
0  1001   手机  北京  已完成  2999   无
1  1002   耳机  上海  待发货   399  缺货
2  1003   卫衣  广州  已完成   199   无
3  1004   水杯  深圳  待发货    59  断货
4  1005   键盘  北京   取消   899  退款

In [3]:
status_map = {'已完成': 'Completed', '待发货': 'Pending', '取消': 'Canceled'}
df['订单状态'] = df['订单状态'].replace(status_map)

df

   订单ID 商品名称  城市       订单状态    单价  备注
0  1001   手机  北京  Completed  2999   无
1  1002   耳机  上海    Pending   399  缺货
2  1003   卫衣  广州  Completed   199   无
3  1004   水杯  深圳    Pending    59  断货
4  1005   键盘  北京   Canceled   899  退款

In [4]:
df['备注'] = df['备注'].replace(['缺货', '断货'], '库存不足')
df

   订单ID 商品名称  城市       订单状态    单价    备注
0  1001   手机  北京  Completed  2999     无
1  1002   耳机  上海    Pending   399  库存不足
2  1003   卫衣  广州  Completed   199     无
3  1004   水杯  深圳    Pending    59  库存不足
4  1005   键盘  北京   Canceled   899    退款

In [6]:
replace_dict = {
    '城市': {'北京': 'BJ', '上海': 'SH', '广州': 'GZ', '深圳': 'SZ'},
    '备注': {'无': '没有了', '库存不足': '没有库存了', '退款': '退款了'}
}

df.replace(replace_dict, inplace=True)
df

   订单ID 商品名称  城市       订单状态    单价     备注
0  1001   手机  BJ  Completed  2999    没有了
1  1002   耳机  SH    Pending   399  没有库存了
2  1003   卫衣  GZ  Completed   199    没有了
3  1004   水杯  SZ    Pending    59  没有库存了
4  1005   键盘  BJ   Canceled   899    退款了

In [9]:
df.replace('没有了', '无', inplace=True)
df

   订单ID 商品名称  城市       订单状态    单价     备注
0  1001   手机  BJ  Completed  2999      无
1  1002   耳机  SH    Pending   399  没有库存了
2  1003   卫衣  GZ  Completed   199      无
3  1004   水杯  SZ    Pending    59  没有库存了
4  1005   键盘  BJ   Canceled   899    退款了