In [1]:
import pandas as pd

In [2]:
file_path = r'data_modify_loc.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   399   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697

In [3]:
df.iloc[1, 2] = 499
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   499   5  上海  1995
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697

In [4]:
df.iloc[1, 5] = df.iloc[1, 3] * df.iloc[1, 2]
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   499   5  上海  2495
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697

In [5]:
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   499   5  上海  2495
2  1003   卫衣   199  10  广州  1990
3  1004   水杯    59  20  深圳  1180
4  1005   键盘   899   3  北京  2697

In [6]:
df.iloc[3] = [1004, '保温杯', 89, 15, '深圳', 1335]
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   499   5  上海  2495
2  1003   卫衣   199  10  广州  1990
3  1004  保温杯    89  15  深圳  1335
4  1005   键盘   899   3  北京  2697

In [7]:
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999   2  北京  5998
1  1002   耳机   499   5  上海  2495
2  1003   卫衣   199  10  广州  1990
3  1004  保温杯    89  15  深圳  1335
4  1005   键盘   899   3  北京  2697

In [8]:
df.iloc[:, 3] = 10
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999  10  北京  5998
1  1002   耳机   499  10  上海  2495
2  1003   卫衣   199  10  广州  1990
3  1004  保温杯    89  10  深圳  1335
4  1005   键盘   899  10  北京  2697

In [9]:
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  2999  10  北京  5998
1  1002   耳机   499  10  上海  2495
2  1003   卫衣   199  10  广州  1990
3  1004  保温杯    89  10  深圳  1335
4  1005   键盘   899  10  北京  2697

In [10]:
df.iloc[0:3, 2:4] = [[3099, 3], [599, 6], [299, 12]]
df

   订单ID 商品名称    单价  数量  城市    总价
0  1001   手机  3099   3  北京  5998
1  1002   耳机   599   6  上海  2495
2  1003   卫衣   299  12  广州  1990
3  1004  保温杯    89  10  深圳  1335
4  1005   键盘   899  10  北京  2697