In [1]:
import pandas as pd

In [7]:
file_path = r'data_modify_cond.csv'

df = pd.read_csv(file_path, encoding='utf-8')

df['总价'] = df['总价'].astype('float64')
df['单价'] = df['单价'].astype('float64')

df

   订单ID 商品名称      单价  数量  城市      总价   折扣
0  1001   手机  2999.0   2  北京  5998.0  0.9
1  1002   耳机   399.0   5  上海  1995.0  1.0
2  1003   卫衣   199.0  10  广州  1990.0  1.0
3  1004   水杯    59.0  20  深圳  1180.0  1.0
4  1005   键盘   899.0   3  北京  2697.0  0.9

In [8]:
df.loc[df['城市'] == '北京', '折扣'] = 0.8
df.loc[df['城市'] == '北京', '总价'] = df['单价'] * df['数量'] * df['折扣']

df

   订单ID 商品名称      单价  数量  城市      总价   折扣
0  1001   手机  2999.0   2  北京  4798.4  0.8
1  1002   耳机   399.0   5  上海  1995.0  1.0
2  1003   卫衣   199.0  10  广州  1990.0  1.0
3  1004   水杯    59.0  20  深圳  1180.0  1.0
4  1005   键盘   899.0   3  北京  2157.6  0.8

In [9]:
cond = (df['城市'] == '上海') & (df['总价'] < 2000)

df.loc[cond, '单价'] = df.loc[cond, '单价'] * 1.1
df.loc[cond, '总价'] = df.loc[cond, '单价'] * df.loc[cond, '数量']

df

   订单ID 商品名称      单价  数量  城市      总价   折扣
0  1001   手机  2999.0   2  北京  4798.4  0.8
1  1002   耳机   438.9   5  上海  2194.5  1.0
2  1003   卫衣   199.0  10  广州  1990.0  1.0
3  1004   水杯    59.0  20  深圳  1180.0  1.0
4  1005   键盘   899.0   3  北京  2157.6  0.8

In [10]:
df['客单等级'] = '低客单'
df

   订单ID 商品名称      单价  数量  城市      总价   折扣 客单等级
0  1001   手机  2999.0   2  北京  4798.4  0.8  低客单
1  1002   耳机   438.9   5  上海  2194.5  1.0  低客单
2  1003   卫衣   199.0  10  广州  1990.0  1.0  低客单
3  1004   水杯    59.0  20  深圳  1180.0  1.0  低客单
4  1005   键盘   899.0   3  北京  2157.6  0.8  低客单

In [11]:
df.loc[df['总价'] > 2000, '客单等级'] = '高客单'
df

   订单ID 商品名称      单价  数量  城市      总价   折扣 客单等级
0  1001   手机  2999.0   2  北京  4798.4  0.8  高客单
1  1002   耳机   438.9   5  上海  2194.5  1.0  高客单
2  1003   卫衣   199.0  10  广州  1990.0  1.0  低客单
3  1004   水杯    59.0  20  深圳  1180.0  1.0  低客单
4  1005   键盘   899.0   3  北京  2157.6  0.8  高客单