In [105]:
import pandas as pd
import numpy as np

In [106]:
student_dict = {
    "姓名": ["张三", "李四", "王五", "赵六"],
    "语文": [88, 95, 79, 92],
    "数学": [92, 87, 90, 85],
    "英语": [78, 90, 86, 94]
}

In [107]:
student_df = pd.DataFrame(student_dict)

In [108]:
student_df

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90
2  王五  79  90  86
3  赵六  92  85  94

In [109]:
print(student_df)

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90
2  王五  79  90  86
3  赵六  92  85  94

In [110]:
score_list = [
    ["张三", 88, 92, 78],
    ["李四", 95, 87, 90],
    ["王五", 79, 90, 86],
    ["赵六", 92, 85, 94]
]

In [111]:
columns = ["姓名", "语文", "数学", "英语"]
student_df2 = pd.DataFrame(score_list, columns=columns)
student_df2

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90
2  王五  79  90  86
3  赵六  92  85  94

In [112]:
math_series = pd.Series([92, 87, 90, 85], index=["张三", "李四", "王五", "赵六"], name="数学")

In [113]:
math_series

张三    92
李四    87
王五    90
赵六    85
Name: 数学, dtype: int64

In [114]:
student_df

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90
2  王五  79  90  86
3  赵六  92  85  94

In [115]:
student_df.to_csv("学生成绩表.csv", encoding='utf-8', index=False)

In [116]:
student_df.to_excel("学生成绩表.xlsx", sheet_name="成绩表", engine='openpyxl', index=False)

In [117]:
df_csv = pd.read_csv("学生成绩表.csv", encoding='utf-8')
df_csv

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90
2  王五  79  90  86
3  赵六  92  85  94

In [118]:
df_excel = pd.read_excel("学生成绩表.xlsx", sheet_name="成绩表", engine='openpyxl')
df_excel

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90
2  王五  79  90  86
3  赵六  92  85  94

In [119]:
student_df.shape

(4, 4)

In [120]:
student_df.head(2)

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90

In [121]:
student_df.head()

   姓名  语文  数学  英语
0  张三  88  92  78
1  李四  95  87  90
2  王五  79  90  86
3  赵六  92  85  94

In [122]:
student_df.tail(2)

   姓名  语文  数学  英语
2  王五  79  90  86
3  赵六  92  85  94

In [123]:
student_df.columns.to_list()

['姓名', '语文', '数学', '英语']

In [124]:
student_df.dtypes

姓名    object
语文     int64
数学     int64
英语     int64
dtype: object

In [125]:
student_df.describe()

              语文         数学         英语
count   4.000000   4.000000   4.000000
mean   88.500000  88.500000  87.000000
std     6.952218   3.109126   6.831301
min    79.000000  85.000000  78.000000
25%    85.750000  86.500000  84.000000
50%    90.000000  88.500000  88.000000
75%    92.750000  90.500000  91.000000
max    95.000000  92.000000  94.000000

In [126]:
student_df.isnull().sum()

姓名    0
语文    0
数学    0
英语    0
dtype: int64

In [127]:
chinese_col = student_df["语文"]

In [128]:
chinese_col

0    88
1    95
2    79
3    92
Name: 语文, dtype: int64

In [129]:
score_cols = student_df[["语文", "数学", "英语"]]
score_cols

   语文  数学  英语
0  88  92  78
1  95  87  90
2  79  90  86
3  92  85  94

##### pandas 中 loc 与 iloc 的核心区别

✅ loc 是「标签索引」，基于行 / 列的「标签名（label）」取值

✅ iloc 是「位置索引」，基于行 / 列的「数字位置（index position）」取值（从 0 开始）

In [130]:
df = pd.DataFrame(
    data=np.arange(20).reshape(5, 4),
    index=[10, 20, 30, 40, 50],
    columns=['A', 'B', 'C', 'D']
)
df

     A   B   C   D
10   0   1   2   3
20   4   5   6   7
30   8   9  10  11
40  12  13  14  15
50  16  17  18  19

In [131]:
df.loc[30, 'B']

9

In [132]:
df.iloc[2, 1]

9

In [133]:
df.iloc[2, :]

A     8
B     9
C    10
D    11
Name: 30, dtype: int32

In [134]:
df.loc[20:40, 'B':'D']

     B   C   D
20   5   6   7
30   9  10  11
40  13  14  15

In [135]:
df.iloc[1:3, 1:3]

    B   C
20  5   6
30  9  10

In [136]:
df.loc[[10, 30, 50], ['A', 'C']]

     A   C
10   0   2
30   8  10
50  16  18

In [137]:
df.iloc[[0, 2, 4], [0, 2]]

     A   C
10   0   2
30   8  10
50  16  18

In [138]:
df.loc[(df['A'] > 5) & (df['B'] < 15), ['B', 'D']]

     B   D
30   9  11
40  13  15

In [139]:
student_df.iloc[0]

姓名    张三
语文    88
数学    92
英语    78
Name: 0, dtype: object

In [140]:
student_df.iloc[1: 3]

   姓名  语文  数学  英语
1  李四  95  87  90
2  王五  79  90  86

In [141]:
student_df[student_df['语文'] >= 90]

   姓名  语文  数学  英语
1  李四  95  87  90
3  赵六  92  85  94

In [142]:
student_df[(student_df["数学"] >= 90) & (student_df["英语"] >= 85)]

   姓名  语文  数学  英语
2  王五  79  90  86

In [143]:
test_df = pd.DataFrame(
    {"姓名": ["张三", "李四", "李四", "王五", None],
     "语文": [88, 95, None, 79, 92],
     "数学": [92, 87, 87, 90, 85],
     "英语": [78, 90, 90, None, 94]
     }
)
test_df

     姓名    语文  数学    英语
0    张三  88.0  92  78.0
1    李四  95.0  87  90.0
2    李四   NaN  87  90.0
3    王五  79.0  90   NaN
4  None  92.0  85  94.0

In [144]:
test_df_drop_dup = test_df.drop_duplicates()
test_df_drop_dup

     姓名    语文  数学    英语
0    张三  88.0  92  78.0
1    李四  95.0  87  90.0
2    李四   NaN  87  90.0
3    王五  79.0  90   NaN
4  None  92.0  85  94.0

In [145]:
test_df_drop_null = test_df_drop_dup.dropna()
test_df_drop_null

   姓名    语文  数学    英语
0  张三  88.0  92  78.0
1  李四  95.0  87  90.0

In [147]:
test_df_fill_null = test_df_drop_dup.fillna(
    {
        "语文": test_df_drop_dup["语文"].mean(),
        "英语": 0,
        "姓名": "未知"
    }
)
test_df_fill_null

   姓名    语文  数学    英语
0  张三  88.0  92  78.0
1  李四  95.0  87  90.0
2  李四  88.5  87  90.0
3  王五  79.0  90   0.0
4  未知  92.0  85  94.0

In [148]:
total_score = student_df[["语文", "数学", "英语"]].sum()
total_score

语文    354
数学    354
英语    348
dtype: int64

In [150]:
avg_score = student_df[["语文", "数学", "英语"]].mean()
avg_score

语文    88.5
数学    88.5
英语    87.0
dtype: float64

In [151]:
max_score = student_df[["语文", "数学", "英语"]].max()
min_score = student_df[["语文", "数学", "英语"]].min()

In [153]:
max_score

语文    95
数学    92
英语    94
dtype: int64

In [154]:
min_score

语文    79
数学    85
英语    78
dtype: int64

In [155]:
avg_score.round(2)

语文    88.5
数学    88.5
英语    87.0
dtype: float64

In [156]:
student_df["总分"] = student_df[["语文", "数学", "英语"]].sum(axis=1)

In [157]:
student_df

   姓名  语文  数学  英语   总分
0  张三  88  92  78  258
1  李四  95  87  90  272
2  王五  79  90  86  255
3  赵六  92  85  94  271

In [158]:
sorted_df = student_df.sort_values(by="总分", ascending=False)

In [159]:
sorted_df

   姓名  语文  数学  英语   总分
1  李四  95  87  90  272
3  赵六  92  85  94  271
0  张三  88  92  78  258
2  王五  79  90  86  255