In [1]:
import numpy as np
import pandas as pd

In [4]:
dict_data = {
    '姓名': ['张三', '李四', '王五'],
    '年龄': [20, 25, 30],
    '城市': ['北京', '上海', '广州']
}

df1 = pd.DataFrame(dict_data)
print(df1)

   姓名  年龄  城市
0  张三  20  北京
1  李四  25  上海
2  王五  30  广州

In [6]:
df1

   姓名  年龄  城市
0  张三  20  北京
1  李四  25  上海
2  王五  30  广州

In [7]:
df1_custom = pd.DataFrame(dict_data, index=['A', 'B', 'C'])
print(df1_custom)

   姓名  年龄  城市
A  张三  20  北京
B  李四  25  上海
C  王五  30  广州

In [8]:
df1_custom

   姓名  年龄  城市
A  张三  20  北京
B  李四  25  上海
C  王五  30  广州

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [10]:
df2 = pd.DataFrame(arr,
                   columns=['列1', '列2', '列3'],
                   index=['行1', '行2', '行3'])
print(df2)

    列1  列2  列3
行1   1   2   3
行2   4   5   6
行3   7   8   9

In [11]:
df2

    列1  列2  列3
行1   1   2   3
行2   4   5   6
行3   7   8   9

In [12]:
s1 = pd.Series([100, 200, 300], index=['A', 'B', 'C'], name='销售额')
print(s1)

A    100
B    200
C    300
Name: 销售额, dtype: int64

In [13]:
s1

A    100
B    200
C    300
Name: 销售额, dtype: int64

In [14]:
s2 = pd.Series([50, 60, 70], index=['A', 'B', 'C'], name='成本')
print(s2)

A    50
B    60
C    70
Name: 成本, dtype: int64

In [15]:
s2

A    50
B    60
C    70
Name: 成本, dtype: int64

In [16]:
df3 = pd.DataFrame({'销售额': s1, '成本': s2})
print(df3)

   销售额  成本
A  100  50
B  200  60
C  300  70

In [17]:
df3

   销售额  成本
A  100  50
B  200  60
C  300  70

In [18]:
df4 = pd.DataFrame()
print(df4)

Empty DataFrame
Columns: []
Index: []

In [19]:
df4

Empty DataFrame
Columns: []
Index: []

In [22]:
df5 = pd.DataFrame({
    '数值列': [1, 2, 3],
    '文本列': ['a', 'b', 'c']
})

print(df5)

   数值列 文本列
0    1   a
1    2   b
2    3   c

In [23]:
# 2. 为不同列分别指定数据类型
df5['数值列'] = df5['数值列'].astype('int32')
df5['文本列'] = df5['文本列'].astype('object')

In [24]:
print(df5.dtypes)

数值列     int32
文本列    object
dtype: object