In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(
    {
        '姓名': [f'学生{i}' for i in range(1, 11)],
        '语文': np.random.randint(60, 100, 10),
        '数学': np.random.randint(50, 100, 10),
        '英语': np.random.randint(65, 100, 10)
    }
)

print(df)

     姓名  语文  数学  英语
0   学生1  78  68  70
1   学生2  97  61  96
2   学生3  85  90  88
3   学生4  74  99  83
4   学生5  73  75  66
5   学生6  97  74  78
6   学生7  73  78  73
7   学生8  89  51  81
8   学生9  61  80  86
9  学生10  63  73  73

In [3]:
df

     姓名  语文  数学  英语
0   学生1  78  68  70
1   学生2  97  61  96
2   学生3  85  90  88
3   学生4  74  99  83
4   学生5  73  75  66
5   学生6  97  74  78
6   学生7  73  78  73
7   学生8  89  51  81
8   学生9  61  80  86
9  学生10  63  73  73

In [4]:
df.head()

    姓名  语文  数学  英语
0  学生1  78  68  70
1  学生2  97  61  96
2  学生3  85  90  88
3  学生4  74  99  83
4  学生5  73  75  66

In [5]:
df.head(3)

    姓名  语文  数学  英语
0  学生1  78  68  70
1  学生2  97  61  96
2  学生3  85  90  88

In [6]:
df.tail()

     姓名  语文  数学  英语
5   学生6  97  74  78
6   学生7  73  78  73
7   学生8  89  51  81
8   学生9  61  80  86
9  学生10  63  73  73

In [7]:
df.tail(3)

     姓名  语文  数学  英语
7   学生8  89  51  81
8   学生9  61  80  86
9  学生10  63  73  73

In [8]:
df.sample(3)

     姓名  语文  数学  英语
9  学生10  63  73  73
4   学生5  73  75  66
0   学生1  78  68  70

In [9]:
df.sample()

    姓名  语文  数学  英语
6  学生7  73  78  73

In [10]:
df.sample()

    姓名  语文  数学  英语
2  学生3  85  90  88

In [13]:
df.sample(frac=0.2)

    姓名  语文  数学  英语
6  学生7  73  78  73
1  学生2  97  61  96

In [14]:
df.数学

0    68
1    61
2    90
3    99
4    75
5    74
6    78
7    51
8    80
9    73
Name: 数学, dtype: int32

In [15]:
df['数学']

0    68
1    61
2    90
3    99
4    75
5    74
6    78
7    51
8    80
9    73
Name: 数学, dtype: int32

In [17]:
df[['语文', '英语']]

   语文  英语
0  78  70
1  97  96
2  85  88
3  74  83
4  73  66
5  97  78
6  73  73
7  89  81
8  61  86
9  63  73

In [18]:
df.语文

0    78
1    97
2    85
3    74
4    73
5    97
6    73
7    89
8    61
9    63
Name: 语文, dtype: int32

In [19]:
df

     姓名  语文  数学  英语
0   学生1  78  68  70
1   学生2  97  61  96
2   学生3  85  90  88
3   学生4  74  99  83
4   学生5  73  75  66
5   学生6  97  74  78
6   学生7  73  78  73
7   学生8  89  51  81
8   学生9  61  80  86
9  学生10  63  73  73

In [20]:
print(df.describe())

             语文         数学         英语
count  10.00000  10.000000  10.000000
mean   79.00000  74.900000  79.400000
std    12.74537  13.584714   9.191784
min    61.00000  51.000000  66.000000
25%    73.00000  69.250000  73.000000
50%    76.00000  74.500000  79.500000
75%    88.00000  79.500000  85.250000
max    97.00000  99.000000  96.000000

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      10 non-null     str
 1   语文      10 non-null     int32
 2   数学      10 non-null     int32
 3   英语      10 non-null     int32
dtypes: int32(3), str(1)
memory usage: 332.0 bytes

In [22]:
df.iloc[4]

姓名    学生5
语文     73
数学     75
英语     66
Name: 4, dtype: object

In [24]:
df.loc[8]

姓名    学生9
语文     61
数学     80
英语     86
Name: 8, dtype: object

In [25]:
df.head(100)

     姓名  语文  数学  英语
0   学生1  78  68  70
1   学生2  97  61  96
2   学生3  85  90  88
3   学生4  74  99  83
4   学生5  73  75  66
5   学生6  97  74  78
6   学生7  73  78  73
7   学生8  89  51  81
8   学生9  61  80  86
9  学生10  63  73  73